### ISSUE TITLE
Implement CSS polyfill service endpoint

### ISSUE THREAD

**Issue by samgiles** [polyfillpolyfill/polyfill-service#1]
When the file extension is `.css` the CSS polyfills should be looked up and returned.

This is based on the data in: https://github.com/jonathantneal/polyfill/blob/master/agent.css.json and https://github.com/jonathantneal/polyfill/blob/master/normalize.json

These should additionally be assigned equivalent Modernizr aliases where appropriate.

**Comment by triblondon** [comment]
Maybe the service will one day support CSS.  I don't think we need an issue for it.
