### ISSUE TITLE
Contributing.md link in readme is broken.

### ISSUE THREAD

**Issue by AdriVanHoudt** [polyfillpolyfill/polyfill-service#1014]
See https://github.com/Financial-Times/polyfill-service/blob/master/README.md#license

It should at least have a link to/or have in it the CLA. (Which I think is unnecessary given the license and is some legal text which makes it harder to contribute imo)

**Comment by JakeChampion** [comment]
The licensing side of this project is one I am not 100% sure of, we will have to ask @triblondon about that.

**Comment by triblondon** [comment]
Raised PR for the fix, thanks for spotting this.

The CLA for this project is actually extremely short compared to other OSS projects, and CLAs are needed for good governance - they give users confidence that we have the legal right to offer this software for use by anyone that wants to enjoy it.  If we accept a contribution from someone who has not signed a CLA, they might in theory be able to reserve copyright over their portion of the code in future, and extract financial redress from anyone who has used it.  We're happy that our CLA offers a good balance of brevity and security of ownership.

**Comment by AdriVanHoudt** [comment]
Not the legal expert here but does contributing to an MIT project already provide that legal right?
Or in other words by contributing to the MIT project you inherently agree with the license which allows anyone, including the FT, to use the code as they please?

**Comment by triblondon** [comment]
I am also not a legal expert but the person who advised us on our contribution rules is.

**Comment by AdriVanHoudt** [comment]
@triblondon ok, if you get to speak to him/her again could pass along my question? Not trying to be annoying just being curious btw!
