### ISSUE TITLE
Where to put the <template> tag?

### ISSUE THREAD

**Issue by fatso83** [polyfillpolyfill/polyfill-service#1015]
Hi, I'd like to add [jeffcarp/template-polyfill](https://github.com/jeffcarp/template-polyfill/blob/master/index.js), but I am not totally sure where to put the code. `~html5-elements` does not seem appropriate, even though `template` is a HTML5 tag.

Would it be OK to reserve `polyfills/html-template` for this?

**Comment by triblondon** [comment]
`HTMLTemplateElement` would be the correct name, but looking at that polyfill, it does not create `window.HTMLTemplateElement` so detecting that the polyfill has been applied is quite difficult.

**Comment by fatso83** [comment]
Ah, good catch! I'll try and address that before submitting. Thanks!
