### ISSUE TITLE
IOS 10.2 Safari 10 fails on `Array.prototype.iterator` with `is not a function`

### ISSUE THREAD

**Issue by asilvas** [polyfillpolyfill/polyfill-service#1019]
Safari 10 fails on `[][Symbol.iterator]()` with `is not a function` when `es6` feature is included.

Effectively ES6 `for (var key in [])` transpiles to use array iterators. But if you include `es6` feature, it breaks the native implementation (that worked before the polyfill). `[][Symbol.iterator]()` works without the polyfill, natively. If I do not import `es6`, which overwrites `Symbol`, it works.

**Comment by JakeChampion** [comment]
Could you post the polyfill.io url you are using please?

**Comment by asilvas** [comment]
Wanted to use:

https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es6

But had to work around the problem by using:

https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Promise,Function.name,Array.prototype.@@iterator,String.prototype.repeat,Array.prototype.find,Array.prototype.findIndex

**Comment by JakeChampion** [comment]
Thanks!

Just so I am 100% certain on the issue, could you confirm whether this is correct please:
When polyfilling `Array.prototype.@@iterator` (`[][Symbol.iterator]`) alongside polyfilling `Symbol` and using Safari 10, an error is thrown when it shouldn't be.

I checked what polyfills are returned from your first polyfill.io url for safari 10 and we don't polyfill `Symbol` or `Array.prototype.@@iterator` for that browser. Can you create a reduced test case for this issue at all? You can see what we served a browser by removing the `.min` from the url.

These are what we serve to Safari 10 for `default,es6`:
```
/* Polyfill service v3.15.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: safari/10.0.0
 * Features requested: default,es6
 * 
 * - URL, License: CC0 (required by "default")
 * - Math.clz32, License: CC0 (required by "es6")
 * - Math.sign, License: CC0 (required by "es6")
 * - Object.is, License: CC0 (required by "es6")
 * - String.prototype.repeat, License: CC0 (required by "es6") */
```

**Comment by asilvas** [comment]
On vaca for a couple weeks, it'll have to wait til I get back.

**Comment by bkniffler** [comment]
Another similar problem is, when you use some compatible browser like chrome and use the simulator to simulate an IOS device, your code will break with something like `Uncaught TypeError: t[Symbol.iterator] is not a function` since the user-agent will report there is features missing that are actually available. Would it be feasible to build in a check inside the code to make sure Symbol.iterator isn't defined?

**Comment by JakeChampion** [comment]
@bkniffler we already have that feature, it is listed on our [api page](https://polyfill.io/v2/docs/api). adding `&flags=gated` to the end of the polyfill.io url you are using will apply the gated flag to all features requested in the features parameter. `gated` adds a feature detect around every polyfill, meaning the polyfills will only execute if the feature detect decides the browser does not have that feature natively.

**Comment by bkniffler** [comment]
Brilliant, didn't see that one. Thanks a ton!

**Comment by triblondon** [comment]
@asilvas hope the vacation was good :-)  Are you able to follow up on this?

**Comment by asilvas** [comment]
Hmm I'm no longer able to repro. No sure what changed. Will close for now, thanks.

**Comment by asilvas** [comment]
I remember why the confusion now... This was specifically on IOS 10.2 Safari 10. I updated the title accordingly.

Here is the dump for `default,es6`:

```
/* Polyfill service v3.16.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: ios_saf/10.0.0
 * Features requested: default,es6
 * 
 * - URL, License: CC0 (required by "default")
 * - Math.clz32, License: CC0 (required by "es6")
 * - Math.sign, License: CC0 (required by "es6")
 * - Object.is, License: CC0 (required by "es6")
 * - String.prototype.repeat, License: CC0 (required by "es6")
 * - Symbol, License: MIT (required by "es6", "Symbol.hasInstance", "Symbol.isConcatSpreadable", "Symbol.iterator", "Symbol.match", "Symbol.replace", "Symbol.search", "Symbol.species", "Symbol.split", "Symbol.toPrimitive", "Symbol.toStringTag", "Symbol.unscopables")
 * - Symbol.hasInstance, License: MIT (required by "es6")
 * - Symbol.isConcatSpreadable, License: MIT (required by "es6")
 * - Symbol.iterator, License: MIT (required by "es6")
 * - Symbol.match, License: MIT (required by "es6")
 * - Symbol.replace, License: MIT (required by "es6")
 * - Symbol.search, License: MIT (required by "es6")
 * - Symbol.species, License: MIT (required by "es6")
 * - Symbol.split, License: MIT (required by "es6")
 * - Symbol.toPrimitive, License: MIT (required by "es6")
 * - Symbol.toStringTag, License: MIT (required by "es6")
 * - Symbol.unscopables, License: MIT (required by "es6") */

(function(undefined) {

// URL
// URL Polyfill
// Draft specification: https://url.spec.whatwg.org

// Notes:
// - Primarily useful for parsing URLs and modifying query parameters
// - Should work in IE8+ and everything more modern
```

**Comment by asilvas** [comment]
Possibly related to https://github.com/Financial-Times/polyfill-service/issues/1034

**Comment by jonashaag** [comment]
This is still an issue. To reproduce:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Symbol,Symbol.iterator,Array.prototype.@@iterator"></script>
<script>
const a = [1,2,3]
const it = a[Symbol.iterator]()
let x
while((x = it.next(), !x.done)) {
  document.write("<div>" + x.value + "</div>")
}
</script>
```
