### ISSUE TITLE
`Object [object Performance] has no method 'now'` errors in different 4.x.x Android browsers

### ISSUE THREAD

**Issue by avocadowastaken** [polyfillpolyfill/polyfill-service#1020]
I know that in [this](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) docs said that `performance.now` is supported by v4 android browsers but I still got errors from some of them:

* Device: Prestigio PAP4322DUO
* OS: Android 4.1.1
```
Mozilla/5.0 (Linux; U; Android 4.1.1; en-us; PAP4322DUO Build/PrestigioPAP4322DUO) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

* Device: HUAWEI G750-U10
* OS: Android 4.2.2
```
Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; HUAWEI G750-U10 Build/HuaweiG750-U10) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 ACHEETAHI/1
```

* Device: Q10
* OS: Android 4.3
```
Mozilla/5.0 (Linux; U; Android 4.3; en-; Q10 Build/10.3.2.348) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

* Device: HTC Desire 500 dual sim
* OS: Android 4.1.2
```
Mozilla/5.0 (Linux; U; Android 4.1.2; en-in; HTC_Desire_500_dual_sim Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

* Device: Sony ST26i
* OS: Android 4.1.2
```
Mozilla/5.0 (Linux; U; Android 4.1.2; en-us; SonyST26i Build/11.2.A.0.33) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

* Device: Lenovo A706_ROW
* OS: Android 4.1.2
```
Mozilla/5.0 (Linux; U; Android 4.1.2; en-us; Lenovo A706_ROW Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 ACHEETAHI/1
```

* Device: Micromax A116
* OS: Android 4.1.2
```
Mozilla/5.0 (Linux; U; Android 4.1.2; en-in; Micromax A116 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

* Device: Asus ME301T
* OS: Android 4.1.1
```
Mozilla/5.0 (Linux; U; Android 4.1.1; en-us; ME301T Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
```

**Comment by klaemo** [comment]
I can confirm this error.

```
Object [object Performance] has no method 'now'
/v2/polyfill.min.js in n.requestAnimationFrame at line 52:6977
```

 Here are some more UA strings ;)

- One X
- Android 4.2.2
```
Mozilla/5.0 (Linux; U; Android 4.2.2; de-de; HTC_One_X/4.17.161.3 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

- Z30
- Android 4.3
```
Mozilla/5.0 (Linux; U; Android 4.3; de-de; Z30 Build/10.3.2.348) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

Here are the affected Android versions according to our error tracking system:
<img width="653" alt="bildschirmfoto 2016-12-22 um 15 20 35" src="https://cloud.githubusercontent.com/assets/778624/21428427/4bdfac68-c85a-11e6-8770-25e2d79f9ee2.png">

**Comment by JakeChampion** [comment]
Yup, our compat.json shows that it fails until 4.4 --> https://github.com/Financial-Times/polyfill-service/blob/master/docs/assets/compat.json#L4764

Happy to accept a PR for this, the instructions for this are --> https://qa.polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by avocadowastaken** [comment]
I guess here problem with not Android itself but `AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

**Comment by JakeChampion** [comment]
@umidbekkarimov I'm not sure I understand, the string you posted identifies as safari 4, this issue is for Android 4.

**Comment by avocadowastaken** [comment]
All these https://github.com/Financial-Times/polyfill-service/issues/1020#issue-195645589 and these https://github.com/Financial-Times/polyfill-service/issues/1020#issuecomment-268809066 android devices use `AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30` browser a.k.a. `WebKit v534`

Here more [examples](https://www.whatismybrowser.com/developers/tools/user-agent-parser/browse/browser-name/android-browser-user-agents) with this browser.

> Yup, our compat.json shows that it fails until 4.4 

Actually this is right cause from 4.4 android jumped to `WebKit v537.36` (http://jimbergman.net/webkit-version-in-android-version/) and I never had a problem with this version.

~~I guess problem should be here https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Intl/config.json#L3 no ?~~ overlooked it, too many opened tabs 😓 

`"android": "<=4.3"` (from https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Intl/config.json#L3) said that it should be polyfilled on Android Browsers lower or equal to 4.3 right ?

So for this UA

```
Mozilla/5.0 (Linux; U; Android 4.1.1; en-us; PAP4322DUO Build/PrestigioPAP4322DUO) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

http://www.whatsmyua.com shows [Android Browser 4.0](https://goo.gl/dVOQ4l) (open in Chrome, safari breaks the link)

But [polyfill](https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Linux;%20U;%20Android%204.1.1;%20en-us;%20PAP4322DUO%20Build/PrestigioPAP4322DUO)%20AppleWebKit/534.30%20(KHTML,%20like%20Gecko)%20Version/4.0%20Mobile%20Safari/534.30) has no `performance.now`  

___

So we need to add 4.0 version to [compat.json](https://github.com/Financial-Times/polyfill-service/blob/master/docs/assets/compat.json#L4764) ?

**Comment by JakeChampion** [comment]
If wanting to change the range of Android versions we target the `performance.now` polyfill at, you will need to modify the contents of `polyfills/performance/now/config.json`. We have instructions for this on our website to help new contributors, would you be able to give them a read and see if you can do the change? The instructions can be found here -- https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

If you have any questions at all, feel free to post them in here and I will do my best to help, we're trying to make contributing to this project as simple as possible :-)

**Comment by kdzwinel** [comment]
We are observing same issues. I've opened a PR to fix this.

<img width="424" alt="screen shot 2017-01-09 at 11 44 56" src="https://cloud.githubusercontent.com/assets/985504/21763990/18f27afa-d661-11e6-824d-ee57a4220e1e.png">
