### ISSUE TITLE
for... of issue when requesting es6 feature (mobile safari vs IE)

### ISSUE THREAD

**Issue by davidkrijgsman** [polyfillpolyfill/polyfill-service#1029]
Hi guys,

I'm having some problems with using for.. of on mobile safari. I've setup a simple test scenario. My Javascript is a babelified version of:

```
var arr = [1,2,3];
for (var item of arr)
{
    console.log(item);
}
```

resulting in:

```
var arr = [1, 2, 3];
var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
	for (var _iterator = arr[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
		var item = _step.value;

		console.log(item);
	}
} catch (err) {
	_didIteratorError = true;
	_iteratorError = err;
} finally {
	try {
		if (!_iteratorNormalCompletion && _iterator.return) {
			_iterator.return();
		}
	} finally {
		if (_didIteratorError) {
			throw _iteratorError;
		}
	}
}
```

Using the polyfill service without requesting specific features, this works great in modern browsers, including mobile safari. 

Not so much in Internet Explorer 11 where the error 'Object expected' is the result. I've read about this in this issue: https://github.com/Financial-Times/polyfill-service/issues/792

When requesting the es6 feature-set (https://cdn.polyfill.io/v2/polyfill.js?features=es6), IE11 works as expected. However this causes problems in mobile safari, resulting in the following error:

```
[Error] TypeError: arr[Symbol.iterator] is not a function. (In 'arr[Symbol.iterator]()', 'arr[Symbol.iterator]' is undefined)
```

When I only request Array.prototype.@@iterator (https://cdn.polyfill.io/v2/polyfill.js?features=Array.prototype.@@iterator) both IE11 and mobile safari seem to be happy.

Is this as intended? I've also tried requesting both the es6 feature-set and Array.prototype.@@iterator. IE11 is still happy, mobile safari is not.

Also, I wasn't able to for.. of loop over a Nodelist in either browser, not by requesting the es6 feature-set nor by requesting Nodelist.prototype.@@iterator.

None of these problems occured when using the Babel polyfill (https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.20.0/polyfill.min.js). But that's quite a chunk of code without the intelligence of serving just what the browser needs, so I'd rather use polyfill.io.

Can someone please point me in the right direction? Any help is much appreciated.

Thanks!

**Comment by JakeChampion** [comment]
Getting `for..of` working requires compiling your code. I see you're using Babel to compile your code, Babel is can compile in many different ways, could you paste your babel configuration into this issue please?

One issue I've seen with Babel is that it sometimes outputs code which is tied to the core-js Symbol polyfill. If this is the issue, you can use `babel-preset-env` plugin and specify an exclude for `es6.symbol`. Another solution is to use https://github.com/Financial-Times/babel-polyfill-silencer.

About NodeList iterator support, we have a polyfill for this, you can see the browsers it is sent to in the config file -- https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/NodeList/prototype/%40%40iterator/config.json

If you are still finding issues, please post a reduced test case for us to help debug this with you. A reduced test case could be a jsbin.com link or a github repo made which only contains code to show the issue you are having.

**Comment by davidkrijgsman** [comment]
Thanks for getting back to me. I use gulp-babel to compile my code with the es2015 preset: 
```
.pipe(gulpif(['*.es6.js'], babel({
     presets: ['babel-preset-es2015'].map(require.resolve)
})))
```
Which yields the same result as the online babel compiler: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=var%20arr%20%3D%20%5B1%2C2%2C3%5D%3B%0D%0Afor%20(var%20item%20of%20arr)%0D%0A%7B%0D%0A%20%20%20%20console.log(item)%3B%0D%0A%7D

The jsbin can be found here: http://jsbin.com/yuyodi/2/edit?html,js,console where I'm loading the es6 feature set. Works fine in modern browsers and IE11, however safari on iphone reports: 
```
"TypeError: arr[Symbol.iterator] is not a function. (In 'arr[Symbol.iterator]()', 'arr[Symbol.iterator]' is undefined)".
```

When requesting only Array.prototype.@@iterator (http://jsbin.com/kewijoh/edit?html,js,console), it does work.

I think it's related to this issue: https://github.com/Financial-Times/polyfill-service/issues/1019


I see the NodeList iterator does work on both IE11 and mobile safari when specifically requested, but it's not included in the es6 feature-set.

I'll look into `babel-preset-env`. Thanks for your help!

**Comment by davidkrijgsman** [comment]
Hi @JakeChampion,

Any chance you can help any further with this? Specifically this error:

```
[Error] TypeError: arr[Symbol.iterator] is not a function. (In 'arr[Symbol.iterator]()', 'arr[Symbol.iterator]' is undefined)
```

which I'm getting on mobile Safari (iOS 9.3.2). I've provided some jsbin examples in my previous post.

I've tried using `babel-preset-env` and excluding `es6.symbol`, but it yields the exact same output.

Thanks again for your help!

**Comment by JakeChampion** [comment]
This looks like it has been fixed but forgot to close the issue
