### ISSUE TITLE
Symbol Polyfill throws error in mobile safari v10 (iOS 10.2)

### ISSUE THREAD

**Issue by avocadowastaken** [polyfillpolyfill/polyfill-service#1034]
Polyfill url:

https://cdn.polyfill.io/v2/polyfill.js?unknown=polyfill&features=es6,default,performance.now|always"

UA:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1
```

Error Message:

```
undefined is not an object (near '...his[internalSymbol]['@@' + uid]...')
```

Line:

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/polyfill.js#L84

**Comment by JakeChampion** [comment]
ios 10 doesn't need Symbol, will update our configuration so we don't send it the polyfill
