### ISSUE TITLE
Object.create

### ISSUE THREAD

**Issue by abozhilov** [polyfillpolyfill/polyfill-service#104]
Object.create(null); //TypeError: Object prototype may only be an Object or null

`if (prototype !== Object(prototype))` Object constructor with primitive types returns new object. So it will not work as expected with `null`. 

Don't know why you are using Function constructor in this polyfill. Function expression would do the same thing and I think it would be definitely faster.

**Comment by triblondon** [comment]
@abozhilov would you consider helping us fix this?

**Comment by JakeChampion** [comment]
I can not reproduce this bug using the current `Object.create` polyfill within this project. 

Closing the ticket, feel free to reopen if you like.
