### ISSUE TITLE
Element polyfill - DOMException in Opera Mini, Samsung Browser and Amazon Silk

### ISSUE THREAD

**Issue by kdzwinel** [polyfillpolyfill/polyfill-service#1043]
We observed that Element polyfill (which is not a third-party code) throws errors in these browsers:

 - Opera Mini (4.2-4.5) - `Uncaught exception: DOMException: HIERARCHY_REQUEST_ERR` (e.g. ua: `Opera/9.80 (J2ME/MIDP; Opera Mini/4.1.13572/37.9224; U; en) Presto/2.12.423 Version/12.16`)
- Samsung Internet (2.0-3.5) - `Failed to execute 'appendChild' on 'Node': Nodes of type 'BODY' may not be inserted inside nodes of type '#document'.` (e.g. ua: `Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG SM-J100ML Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.0 Chrome/34.0.1847.76 Mobile Safari/537.36`)
- Amazon Silk (46-55) - `Failed to execute 'appendChild' on 'Node': Only one element on document allowed.` (e.g. ua: `Mozilla/5.0 (Linux; Android 4.0.3; KFTT Build/IML74K) AppleWebKit/537.36 (KHTML, like Gecko) Silk/54.4.4 like Chrome/54.0.2840.85 Safari/537.36`)

This was caught by our error tracking solution, please let me know if you need more details.

**Comment by triblondon** [comment]
@kdzwinel can you provide some trigger code?  Or are you saying that these errors are thrown on pageload simply by including the polyfill.io script tag in an otherwise empty pagE?

**Comment by kdzwinel** [comment]
Yes, simply including the polyfill.io script causes Element polyfill to execute which triggers the error.  

I should also mention that we are using `unknown=polyfill` because these browsers (AFAIK) are not supported by polyfill.io (I've added UAs to the report above). Maybe this polyfill is only meant for specific browsers that allow `document.appendChild(document.createElement('body'))` (this code is not valid in any modern browser) ? Should it be? IMO polyfills should execute correctly in all browsers. But maybe it's just a matter of checking if polyfill is needed before executing it? I imagine this increases the size of the polyfill, so maybe such checks should be only appended when `unknown=polyfill` is active and browser is not recognized?

**Comment by JakeChampion** [comment]
@kdzwinel You can add feature detects using `&flags=gated` to the polyfill.io url you are using. This will check if a polyfill is needed before executing it.

**Comment by kdzwinel** [comment]
@JakeChampion thanks, I forgot about it! The only issue with `gated` is that detects will be included for all polyfills, I'd be perfect to include them only for unknown browsers. How about creating `unknown=gated`?

Not sure if this resolves the original issue though? `Elements` polyfill contains invalid code (according to most of the browsers).

**Comment by triblondon** [comment]
I think there's an argument for forcing gated to be on whenever unknown=polyfill and the request is coming from an unknown browser.  This is highly likely to produce a net reduction in issues experienced in the wild, though of course it's technically a breaking change so could cause some issues too.  To be safe, yes we could add a new option value for the `unknown` param, but I think trying to explain the options in docs would be quite hard

**Comment by JakeChampion** [comment]
@triblondon I think that is a great idea, one for the list of desirable breaking changes - https://github.com/Financial-Times/polyfill-service/issues/892

**Comment by decompil3d** [comment]
I'm seeing this happen fairly frequently when loading from China. Repros in other browsers like Safari and Firefox. And I already do have `flags=gated`, so that does not seem to fix the issue.

Also noticed that the issue doesn't seem to repro when caching is disabled. So may be a race condition on slower networks?

**Comment by decompil3d** [comment]
Update on above: turns out it was an improperly configured private CDN cache on my end. Even though my app was passing `flags=gated`, other apps calling through the cache were not, so I'd see this error.

**Comment by JakeChampion** [comment]
In version 3 of https://polyfill.io the browsers mentioned in this issue would now fall under the unsupported browser list and get the polyfills served with feature detects and no longer execute the polyfills which were causing the errors 🎉
