### ISSUE TITLE
HTMLCanvasElement polyfill typo? (protoype)

### ISSUE THREAD

**Issue by eXtreme** [polyfillpolyfill/polyfill-service#1045]
Is there a specific reason why `HTMLCanvasElement.toBlob` polyfill is spelled with `protoype`? Is this a typo? 

https://polyfill.io/v2/docs/features/#HTMLCanvasElement_protoype_toBlob
https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/HTMLCanvasElement/protoype/toBlob

**Comment by JakeChampion** [comment]
Will be fixed by #1149
