### ISSUE TITLE
Array.prototype.@@iterator on IOS9-10

### ISSUE THREAD

**Issue by olanod** [polyfillpolyfill/polyfill-service#1048]
IOS 9 and 10 are supposed to support `Array.prototype[Symbol.iterator]` but the devices I tested it with didn't support it.

**Comment by JakeChampion** [comment]
When we ran our tests, we saw ios 9 come back as reporting it is [natively supported](https://github.com/Financial-Times/polyfill-service/blob/master/docs/assets/compat.json#L55).

[Kangax Compat Table](https://kangax.github.io/compat-table/es6/#test-Array.prototype_methods_Array.prototype[Symbol.iterator]) also reports ios 9 as supporting `Array.prototype[Symbol.iterator]`.

Would you be able to write a test which shows it isn't supported on ios 9?

**Comment by olanod** [comment]
I raised the issue for them as well, it's weird because I imagine you have that as an automated test. But we were getting errors from customers and managed to reproduce it in a live device in browserstack

**Comment by triblondon** [comment]
Closing this as our tests and public compat tables say it's native.  Please do reopen with a test case if you can show it is not.
