### ISSUE TITLE
Function.name polyfill crashes on Android 4.4

### ISSUE THREAD

**Issue by ruiaraujo** [polyfillpolyfill/polyfill-service#1052]
Since it was included in the es6 alias it broke my website in .

The user agent includes Chrome 30 which causes it to be parsed as Chrome.

**Comment by p0wl** [comment]
we have the same problem:

![image](https://cloud.githubusercontent.com/assets/596578/23758788/12605a14-04eb-11e7-984d-f21a6c2196d7.png)

as chrome 30 does not need the polyfills for `array.prototype.find`, ... our app breaks.

It seems to be the same issue as described here: https://github.com/Financial-Times/polyfill-service/issues/793, but I don't understand what the proposed solution is. For me, it sounds like `chrome mobile` should be a browser family of its own.

**Comment by triblondon** [comment]
So you're saying here that Android 4.4 is being misidentified as Chrome?  Please post the UA string so we can take a look at the parsing.

**Comment by triblondon** [comment]
Hi @ruiaraujo are you able to provide the info to help us unblock this?

**Comment by p0wl** [comment]
The useragent (in webview) is: 
```Mozilla/5.0 (Linux; Android 4.4.2; Android SDK built for x86 Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36```

**Comment by ruiaraujo** [comment]
@triblondon I can confirm @p0wl UAs

**Comment by kikemx78** [comment]
Similar issue here for same UA
 `Cannot redefine property: name ` `polyfill.js?features=es6:477`

**Comment by gtournie** [comment]
Same too. The user agent is correctly identified in my case.

Console: Uncaught TypeError: Cannot redefine property: name https://polyfill.io/v2/polyfill.js?features=es5,es6:477

User Agent: Dalvik/1.6.0%20(Linux;%20U;%20Android%204.4.4;%20XT1080%20Build/SU6-7.3)

=> https://polyfill.io/v2/polyfill.js?features=es5,es6&ua=Dalvik/1.6.0%20(Linux;%20U;%20Android%204.4.4;%20XT1080%20Build/SU6-7.3)
