### ISSUE TITLE
Feature detects are not minified

### ISSUE THREAD

**Issue by kdzwinel** [polyfillpolyfill/polyfill-service#1054]
https://cdn.polyfill.io/v2/polyfill.min.js?features=default|gated&unknown=polyfill&ua=test .

<img width="534" alt="screen shot 2017-01-12 at 13 46 00" src="https://cloud.githubusercontent.com/assets/985504/21890313/7e5ad716-d8cd-11e6-8372-732391891100.png">

Feature detects are not getting minified even though polyfills are.

**Comment by triblondon** [comment]
This is a known... situation :-)  I hesitate to call it a bug because detects are so small that minifying them makes virtually no difference to the size of the bundle.  Just neatness?

**Comment by kdzwinel** [comment]
Gotcha, didn't know you are aware of that. The impact is small, but it's still a bug IMO :) I can imagine this has a low priority, but maybe can be fixed in the future? Anyway, I'd leave this issue open for reference.

**Comment by triblondon** [comment]
Fair enough.  It would slow down the build to write a minified file for every detect.js, but not significantly.  Basically it's a relatively insignificant cost for a relatively insignificant gain :-)

**Comment by kdzwinel** [comment]
Sounds like a perfect task for an intern 😉

**Comment by triblondon** [comment]
Or a contributor!  I don't think this is going to be a priority for us - but if it is an annoyance to you, please go for it and we'd certainly accept the change in principle.  You'd mostly want to take a look at https://github.com/Financial-Times/polyfill-service/blob/master/tasks/node/buildsources.js
