### ISSUE TITLE
IE11 mobile is missing Element.prototype.matches

### ISSUE THREAD

**Issue by CheloXL** [polyfillpolyfill/polyfill-service#1065]
IE11 mobile needs (just like IE11 desktop) Element.prototype.matches.
Running the following query correctly detects the browser, but the matches polyfill is not included...

`https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Mobile;%20Windows%20Phone%208.1;%20Android%204.0;%20ARM;%20Trident/7.0;%20Touch;%20rv:11.0;%20IEMobile/11.0;%20Microsoft;%20Lumia%20535)%20like%20iPhone%20OS%207_0_3%20Mac%20OS%20X%20AppleWebKit/537%20(KHTML,%20like%20Gecko)%20Mobile%20Safari/537`

**Comment by triblondon** [comment]
We don't target this polyfill to IE mobile at all.  If you can test it and see that it works, feel free to add that browser family here:

https://github.com/Financial-Times/polyfill-service/blob/v3.16.0/polyfills/Element/prototype/matches/config.json#L11-L23

See here for instructions:

https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by CheloXL** [comment]
Ah!, Didn't know... since the service correctly detected ie mobile, I supposed it was supported. Will check your instructions, as ie11 mobile is exactly the same as ie11 desktop.

Thanks!

**Comment by CheloXL** [comment]
@triblondon Can I ask for some help on this?
I'm trying to run the tests on windows. After running the npm install, I'm getting several errors on the npm run build because the command "rm" doesn't exists on windows (even under powershell).

Since build doesn't run, neither run dev.

Also, I'm trying to understand why running the page at https://polyfill.io/v2/docs/features/ and selecting the "live test" on my mobile shows matches as "supported with Polyfill service" (that ok, as I noted above ie11mob is the same as ie11), but then, the test at https://polyfill.io/test/tests?feature=Element.prototype.matches&mode=all also passes on my mobile and I expected it to not pass.

**Comment by triblondon** [comment]
@CheloXL we may have broken the build process on Windows.  I'm very sorry about that, the core team are all OSX and Linux and we don't regularly need to build on Windows.  But we'd be very grateful for any fixes you can contribute - eg by replacing the offending shell exec with a cross platform npm module?

Regarding your second question, you're seeing the result of testing, not targeting.  They *should* be the same, but sometimes if the targeting is wrong (or the tests are not able to identify an issue for which we've intentionally tweaked the targeting) they may differ.

It would actually be pretty cool to augment the live test feature to report not just whether we're able to make the feature work in your browser but whether it is currently targeted too.  See https://github.com/Financial-Times/polyfill-service/issues/1042#issuecomment-276549454 for more details.

If you want to pursue the Windows build issue, could you raise that separately, and we'll keep this thread for the IE11 / matches targeting issue.

**Comment by CheloXL** [comment]
@triblondon Thanks for the answer. As you can see from my pull requests, I already got the system working on windows. I just had to install the [GNU coreutils for windows](http://gnuwin32.sourceforge.net/packages/coreutils.htm), That solved my build problems (maybe that's something that could be added to the documentation?).

As for the second question, yes, browsing the code led me to that conclusion too. Again, thanks for your help!

**Comment by triblondon** [comment]
Ok, great!
