### ISSUE TITLE
Map polyfill throws on Function.prototype.apply on IE11

### ISSUE THREAD

**Issue by CheloXL** [polyfillpolyfill/polyfill-service#1068]
I'm not quite sure why this is happening, as the test on https://polyfill.io/test/tests?feature=Map (running on IE11) says that all tests pass.

But using the polyfill with the following query `https://polyfill.io/v2/polyfill.js?features=default,AudioContext,WeakMap,WeakSet,Symbol,Symbol.iterator&ua=Mozilla/5.0%20(Windows%20NT%206.1;%20Trident/7.0;%20SLCC2;%20.NET%20CLR%202.0.50727;%20.NET%20CLR%203.5.30729;%20.NET%20CLR%203.0.30729;%20Media%20Center%20PC%206.0;%20Tablet%20PC%202.0;%20rv:11.0)%20like%20Gecko` and trying to do a new Map(anotherMap) throws "Function.prototype.apply: argument is not an Object".

Checking the tests I only see ctor tests for () and ([,]), but not for (map). Maybe that's not supported in the current polyfill? (browsers support that as this is throwing only in IE11).

**Comment by triblondon** [comment]
@CheloXL yes, it does seem likely that the polyfills fails to support creating a map from another map.  It looks like in this situation we should clone the map.
