### ISSUE TITLE
Self-learning configs

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#107]
@jonathantneal suggested that our CI test suite on Sauce Labs could be used to determine which browsers lack support for features, and in which subset of those the polyfill works, and then update our polyfill configs automatically.

**Comment by maxnordlund** [comment]
This could (should?) be combined with live data from users of the service. This means it would adapt as new browser versions come out.

**Comment by triblondon** [comment]
The idea of beaconing RUM results back to the service was raised as part of https://github.com/Financial-Times/polyfill-service/issues/366 and concerns were raised about security.  I think initially we could simply add to the compatgen grunt task to get it to output a list of inconsistencies between the compat test results and the current targeting.

**Comment by triblondon** [comment]
Prompted by a discussion on #731 and the increasing prevalence of "X isn't served on Y" type issues, and the general reluctance of those reporting those issues to write the one line of JSON required to fix them (whoa, passive aggressive mode enabled by accident, sorry. OK, carry on), I think it is worth resurrecting the idea of self-learning target config via RUM.  Here's an idea:
1. New query param `beacon=1` will activate beacon functionality
2. When loading a polyfill from disk, we initialise an empty `beaconData` property, which is a data tree organised as `.beaconData.<uaFamily>.<uaVersion>.passCount` and `.beaconData.<uaFamily>.<uaVersion>.failCount`
3. When serving a request that includes `beacon=1`, we choose up to `n` polyfills at random from those in the produced bundle, and _prefix_ the bundle with all the detects for those polyfills.  This creates a pass/fail for each polyfill against the browser's native capabilities.  Schedule a beacon using a legacy-compatible `new Image` technique
4. New API endpoint `/v2/reportBeaconData` which takes a query param for each feature.  It then updates the pass and fail counts for that feature in the browser that made the request, and responds with a lovely 1x1px gif.

Risks and complications:
- **Idiots**: We might need to do something to prevent people from just firing millions of fake beacon requests at the service to intentionally pollute the data.  The only thing I can think of is recording the IP address of the beacon source, and requiring a decent variety of IP sources (maybe 1000 unique IPs) before we trust the data.
- **Caching**: The `beacon=1` responses will be cached by Fastly meaning that the selection of polyfills that we test doesn't change as often as we might like.  Given variation of requesting user agents and different bundle sets, this is probably not a huge issue, but maybe beacon-enabled bundles could be cached for a shorter period (eg 1 hour).  This is mostly a load issue, since we already have stale-while-revalidate
- **Existing polyfills**: If a site loads other polyfills before ours, then we'll get skewed results because we're testing a polyfilled environment, not a native one.  If that site is the only one using the polyfill service to serve a super niche browser, then all our results for that browser will consistently misreport that polyfill's data.

Rollout plan:

**Phase 1**: As above and add an additional endpoint to export collected data as a diff against the current target config.  This can then be committed so we have better targeting for the following release. Real time, beacon data does not have any impact on targeting.

**Phase 2**: Scrap targeting data (but keep some hard coded 'minimums').  On startup, serve all polyfills that meet the minimum version requirement (gated) and gradually reduce this set if beacons are showing that detects pass.

**Phase 3**: Expand the feature to include testing post-polyfill to see if the polyfill worked. This is tough, we can't exactly run our entire test suite in RUM, and a detect might well pass even if the polyfill doesn't work.  So I'm not sure how this would work.

**Comment by wheresrhys** [comment]
I'm not sure I like the idea of choosing n detects. As you say, it would need cycling, with caching implications. Why not wrap the entire bundle in an uber-closure and judge each feature in situ?

```
(function () {
  var features = {X: false, Y: false}
  if (detectX) {
       features.X = true; 
    //polyfill X
  } 
  beacon(features)
});
```

_Phase3 idea_
Wrap the polyfill in a try/catch. In the catch beacon the ua and polyfill name and (mayeb) some error information (or, minimally, just the fact it's errored), then rethrow the error. It's not quite the same as 'was it polyfilled perfectly?', but is a strong proxy for 'was it polyfilled _satisfactoriily_?'. Caveat - would only work for mainly synchronous polyfills. 

Would it be worth considering a lightweight data store such as redis from the start so that data persists across restarts

**Comment by triblondon** [comment]
- OK, let's just test the things that are in the bundle.
- Don't want to consider a data store in phase 1, so we can get something done quickly.
- I thought of the try..catch wrapper but it seems to me to be a bit too lame to lean on. Too many caveats.

Any suggestions to mitigate the security / data pollution risks?  Not too much of an issue in phase 1 since we're just reporting.

I'll put something together.

**Comment by triblondon** [comment]
This is now deployed and working, and persists data using a database backend.  Reports can be viewed here:

https://polyfill.io/v2/getRumCompatData?header=1

Automatic configuration is still to-do but is pretty low priority right now.
