### ISSUE TITLE
Add support for Object.values()

### ISSUE THREAD

**Issue by JosefJezek** [polyfillpolyfill/polyfill-service#1076]
Could you add support for Object.values()?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

## Object.values shim

`Object.values = Object.values || (obj => Object.keys(obj).map(key => obj[key]));`

Source: http://stackoverflow.com/a/16643074/1614237

**Comment by triblondon** [comment]
https://github.com/Financial-Times/polyfill-service/pull/1082

**Comment by triblondon** [comment]
Closing issue since we now have PR.
