### ISSUE TITLE
Polyfill Intl is not served on UCBrowser for Android v11

### ISSUE THREAD

**Issue by MikaFima** [polyfillpolyfill/polyfill-service#1079]
Hello polyfill.io,

As declared by http://caniuse.com/#search=Intl, the last version of UCBrowser for Android, do not implements Intl at all.
According to their usage percentage, we have to make it work for our projects.

For now I have this response :
```
/* Polyfill service v3.16.0
* For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
*
* UA detected: other/0.0.0 (unknown/unsupported; using policy `unknown=ignore`)
* Features requested: Intl.~locale.en,Intl.~locale.fr
*  */

/* No polyfills found for current settings */
```

I've found something here: https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/lib/UA.js#L76, but we are now on 11.2.0.

Adding v10 would be a plus.

Thank you.

**Comment by JakeChampion** [comment]
@MikaFima Have you tried adding `&unknown=polyfill` to the end of your polyfill.io script url?

I don't know much about UC browser, we are aliasing UC 9.9.* to IE 10 as they are similar. Do you know if UC browser 10 and 11 are similar to other IE versions?

**Comment by MikaFima** [comment]
Hi, thank you for your reply.
I didn't try that yet, but I will do it quickly.

For Intl implementation, at least, it stay at the same point since v9.9.

**Comment by MikaFima** [comment]
Right, this is enough FTM.
You can close this issue, unless you want to make some investigation and officially support it ;).
If I find time for this, i'll came back to you.

Thank you
