### ISSUE TITLE
JS Syntax error on line 15 when calling Intl.js (non-minified) on IE

### ISSUE THREAD

**Issue by phil-cap** [polyfillpolyfill/polyfill-service#1080]
I am getting a Javascript syntax error when using the `Intl` feature by fetching

> https://cdn.polyfill.io/v2/polyfill.js?features=Intl

This is **not** the case when fetching the minified version (`https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl`).

This was observed when running IE Edge in Document Mode 10 (emulating IE 10).

**Comment by triblondon** [comment]
OK, this is because of a comment:

```
//# sourceMappingURL=Intl.min.js.map})
.call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});
```

We've previously added newlines before the start of a polyfill to avoid concatenating code onto the end of a comment, and we obviously need to do that again with the boilerplate code and outer closure.

**Comment by triblondon** [comment]
Scheduled for 3.17 release, follow polyfillio on twitter for release notification.
