### ISSUE TITLE
Array.prototype.values not polyfilled in FF

### ISSUE THREAD

**Issue by PascalAOMS** [polyfillpolyfill/polyfill-service#1081]
`Array.prototype.values` is only supported in the Nightly Firefox build and should be polyfilled which is not happening right now.

See also [ES6 compat table](http://kangax.github.io/compat-table/es6/#test-Array.prototype_methods_Array.prototype.values)

**Comment by triblondon** [comment]
Thanks, we'd gladly accept a contribution to fix the appropriate browser targets:

https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by triblondon** [comment]
Currently awaiting edits in the PR

**Comment by triblondon** [comment]
See PR #1103.
