### ISSUE TITLE
Intl not served to Sogou Explorer 1.0

### ISSUE THREAD

**Issue by tschaub** [polyfillpolyfill/polyfill-service#1084]
We're seeing errors from users who are not getting the `Intl` polyfill in Sogou Explorer 1.0.  Sentry reports this for the User-Agent:
```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.22 Safari/537.36 SE 2.X MetaSr 1.0
```

I'll happily put together a pull request, but I'm uncertain how this browser name might appear in [the `config.json`](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Intl/config.json).

**Comment by triblondon** [comment]
To see how we parse the UA for a browser, you can use the `ua` param:

https://polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20WOW64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/49.0.2623.22%20Safari/537.36%20SE%202.X%20MetaSr%201.0

![image](https://cloud.githubusercontent.com/assets/1735391/22799265/3279d24a-eed3-11e6-861e-b21bc58a0ddd.png)

This means that currently we recognise this browser as its own family - `sogou explorer`, and we have no polyfills for it.  The easiest solution is to create an alias to an existing browser family, but I don't think there's a version-compatible mapping to another browser.  Do you know anyone from Sogou who might be able to help here?

**Comment by triblondon** [comment]
OK, in the absence of interest from Sougou, the only thing we can suggest is to use the `unknown` attribute to change the policy you want to apply to unknown browsers.  `unknown=polyfill` will serve all the polyfills to the unknown browser.
