### ISSUE TITLE
IE 11 - Array.prototype.find / Array.prototype.findIndex

### ISSUE THREAD

**Issue by nekman** [polyfillpolyfill/polyfill-service#1087]
Don't know if this is a bug, but I currently missing the `Array.prototype.findIndex` / `Array.prototype.find` when running IE 11 on Windows 8.1.

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<script>[1, 2, 3].find(item => item === 2); //will not work</script>
```

Here is the unminified version of the polyfill response: https://gist.github.com/nekman/297ebda63d6b00380058cbb0114296aa

**Comment by JakeChampion** [comment]
They are not in the default set of polyfills, if you would like to include these in your polyfill bundle you will need to use this url.
`https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.find,Array.prototype.findIndex`

We have a section in the documentation about the default sets -- https://polyfill.io/v2/docs/features/#default-sets

A quick way to see if a feature is in the latest default set is by looking at the feature list, if the feature has a black star next to it, it is in the default set -- https://polyfill.io/v2/docs/features/#feature-list

**Comment by nekman** [comment]
Thank you @JakeChampion. I should have looked closer on the documentation. Sorry!
