### ISSUE TITLE
Service Worker Support

### ISSUE THREAD

**Issue by c-h-** [polyfillpolyfill/polyfill-service#1088]
Hello, would love to use Polyfill.io, however my app uses a Service Worker for offline support. To my best understanding, service workers can't cache resources from third-party origins like polyfill.io.

Is there any way to use polyfill.io with a service worker? Or would it be required to run a custom polyfill service on a first-party hostname?

Thanks.

**Comment by triblondon** [comment]
Service workers can load URLs from foreign origins like polyfill.io, but the response will be 'opaque'.  For most purposes this is fine.  I suggest you experiment with that, and if it doesn't meet your needs, you can always run the service yourself.
