### ISSUE TITLE
Fetch API Polyfill

### ISSUE THREAD

**Issue by matthew-andrews** [polyfillpolyfill/polyfill-service#109]
It would be great if this service was able to serve a polyfill for the [Fetch API](https://fetch.spec.whatwg.org/) (XHR with Promise interface).

Unfortunately I highly suspect one doesn't yet exist.  Am I wrong, does one already exist?  (Maybe @annevk could confirm?)

If not, then I'm not sure how to proceed...

**Comment by triblondon** [comment]
See https://github.com/Financial-Times/polyfill-service/pull/246
