### ISSUE TITLE
Document usage with Babel?

### ISSUE THREAD

**Issue by slorber** [polyfillpolyfill/polyfill-service#1099]
Hi,

I've seen this discussed in some issues, but I think it would be nice to have a clear guide on how to use the polyfill service for those already using Babel. As of now, I'm not totally sure if I can remove babel polyfill completly when using the polyfill service.

My app loads at startup some polyfills:

```javascript
import "babel-polyfill";
import "intl";
import "intl/locale-data/jsonp/en.js";
import "intl/locale-data/jsonp/fr.js";
```

Can all this be replaced entirely and safely by using polyfill service (v2) or are there cases where it might be a problem? As far as I understand this could work fine but I didn't really find any crystal clear answer in issues and neither in documentation.

**Comment by TheUltDev** [comment]
The main thing `babel-polyfill` does is:

```javascript
import "core-js/shim";
import "regenerator-runtime/runtime";
```

You'll be fine to remove `core-js/shim` and just import `regenerator-runtime/runtime` if you use generators.

Keep in mind by default polyfill doesn't include everything `core-js/shim` does. I suggest running your app and seeing what breaks and adding the specific features to the polyfill url.

The only feature I've found that the polyfill service doesn't have is TypedArrays (for IE9 support). The `core-js/shim` does have this, you could import it from core-js directly if you need it.

Here's some code that might make your life easier:

```javascript
const polyfillFeatures = [
  'default', // https://polyfill.io/v2/docs/features/#default-sets
  'fetch',
  'performance.now',
  'Symbol',
  'Array.prototype.find',
  'Array.prototype.findIndex',
  'Array.prototype.includes',
];

const Polyfill = ({ path }) => (
  <script src={`${path}?features=${polyfillFeatures.join()}&unknown=polyfill&flags=gated`} />
);

Polyfill.propTypes = {
  path: React.PropTypes.string.isRequired,
};
```
```javascript
<Polyfill path={`https://cdn.polyfill.io/v2/polyfill${isProduction ? '.min' : ''}.js`} />
```

**Comment by slorber** [comment]
Thanks for these infos, it'll certainly be useful to more people than just me ;)

**Comment by triblondon** [comment]
I think we'd be very happy to see someone provide this information, but I'm not confident that we could keep it up to date if we made it part of our official docs, and of course there are many other libraries that would then make sense to document integration with as well.

Closing this because it's unlikely any of the core team would do this, and if a third party wants to provide it we'd probably prefer they maintain it outside of the project (but we'd be very happy to link to it)

**Comment by triblondon** [comment]
https://github.com/Financial-Times/babel-polyfill-silencer may also be helpful here.
