### ISSUE TITLE
I want to start the HTTPS

### ISSUE THREAD

**Issue by 94cstyles** [polyfillpolyfill/polyfill-service#1105]
I want to start the HTTPS ~ What do I need to configure？

**Comment by JakeChampion** [comment]
@TOP-Chao What do you mean? Could you add some more detail please? If you want to use HTTPS for https://polyfill.io, we already redirect users from HTTP to HTTPS and set a HSTS header to ensure that subsequent requests hit HTTPS directly.

**Comment by matthew-andrews** [comment]
你好 @TOP-Chao, 我们这里能看得懂一点点中文，所以如果你想用说明你的问题，也许我们可以试试帮助你。

**Comment by 94cstyles** [comment]
@matthew-andrews 噢！你们能懂中文这太棒了。
问题:

1. 使用官网提供的cdn地址，我测试了下访问速度，发现大约有1/8的中国的网络节点访问不到或者访问速度不太理想。我想自己架设polyfill-service的服务，我需要支持https访问，我应该怎么去设置或者我需要修改什么代码?

2. 不知道polyfill-service对移动设备的支持怎么样? 因为中国有很多手机厂商，喜欢自定义浏览器，我担心polyfill-service对这类浏览器的判别不正确，所以我准备扩展polyfill-service，可以对某些品牌的手机浏览器响应所有的polyfill。

**Comment by matthew-andrews** [comment]
谢谢你的回复，我理解你的问题。（我先要说我的中文比较差所以我下面的回复可能有很多错误，如果不清楚的话就告诉我然后我能阐明）

1. polyfill.io的https是被我们的CDN [(Fastly)](https://docs.fastly.com/guides/securing-communications/)提供了，所以我觉得这个repo没有https有关系的code。这个service是一个标准的nodejs (express) app，你以前架设过一个https+nodejs app吗？平时怎么架设？

2. 你看到API [`?unknown=polyfill` property](https://polyfill.io/v2/docs/api)了么？如果用这个property的话polyfill.io不认识浏览器时会跟所有polyfills回答。而且如果你愿意帮助我们，我们可以一起慢慢地进步polyfill.io中国流行的浏览器支持。我们想提高我们的中国浏览器支持。

**Comment by 94cstyles** [comment]
我用过express 我知道怎么添加https了 ~ 非常谢谢！ 
polyfill-service 是个伟大的项目 我很乐意为该项目贡献代码。

**Comment by matthew-andrews** [comment]
不客气，如果碰到问题请再跟我们聊天！

**Comment by 94cstyles** [comment]
我现在遇到一个非常诡异的问题 polyfill无法注入。
```javascript
var features = [];

//Symbol
('Symbol' in this && 'iterator' in this.Symbol) || features.push('Symbol.iterator');

//Promise
('Promise' in this) || features.push('Promise');

//IntersectionObserver
("IntersectionObserver" in this) || features.push('IntersectionObserver');

//Array
'from' in Array && (function () {
    try {
        Array.from({length: -Infinity});

        return true;
    } catch (e) {
        return false;
    }
})() || features.push('Array.from');
('isArray' in Array) || features.push('Array.isArray');
('of' in Array) || features.push('Array.of');
('Symbol' in this && 'iterator' in this.Symbol && !!Array.prototype.entries) || features.push('Array.prototype.entries');

//Object
('assign' in Object) || features.push('Object.assign');
('defineProperty' in Object) || features.push('Object.defineProperty');

if (features.length > 0) {
    var el = document.createElement('script');
    el.src = location.protocol + '//polyfill.io/v2/polyfill.js?features=' + features.join(',') + '&flags=gated,always&rum=1&callback=main';
    el.async = true;
    document.head.appendChild(el);


    window.main = function () {
        console.log('file content:', el.textContent || el.innerText || el.innerHTML);
        console.log(JSON.stringify(features, null, 4));
        console.log('Object.assign:' + Object.assign);
    };
}
```

![ua](http://yppstatic.oss-cn-shanghai.aliyuncs.com/FEtest/BFEA06E29DA112842DFDF18B582376C3.jpg)

![console](http://yppstatic.oss-cn-shanghai.aliyuncs.com/FEtest/CD4EBB86DA70D770685DC8B13FA82B7E.jpg)

**Comment by 94cstyles** [comment]
已解决 加上`unknown=polyfill`就可以~ 
中国好多webview都无法识别~ 

----
@matthew-andrews' translation:
Already solved it — added `unknown=polyfill` and it was fine~
China has so many webview[s] that can’t be identified

**Comment by matthew-andrews** [comment]
我们很开心你会解决了你的问题。如何有其它问题，请随时再跟我们联系。

We're very happy that you were able to solve your problem.  If you have any other questions, please don't hesitate to contact us.
