### ISSUE TITLE
Event polyfill fails in a worker

### ISSUE THREAD

**Issue by tschaub** [polyfillpolyfill/polyfill-service#1110]
The `Event` polyfill assumes that [`window` is defined](https://github.com/Financial-Times/polyfill-service/blob/5f374f29fdb7e1ca26bb4f043cedcb7a29b1730c/polyfills/Event/polyfill.js#L35), so it does not work in a worker.

In case it is useful for others searching for the same, this means that the `Promise` polyfill (and anything else that depends on `Event`) does not work in a worker.

**Comment by triblondon** [comment]
This polyfill was originally written by @jonathantneal.  Jonathan, are you able to confirm whether you think it's OK to replace instances of `window` in your polyfill with `this`, which is our safe reference to the global scope (works across node, workers and browsers)

**Comment by triblondon** [comment]
Polyfill source is at https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Event/polyfill.js

**Comment by jonathantneal** [comment]
Yes, as long as you are okay with `Event` being assigned to that global space. Also, note that `Window` is a presumed object. That may need to be adjusted as well.

**Comment by triblondon** [comment]
Hmm, actually we're defining properties of `window`, `Window`, `Element` and `document`.  We serve this polyfill to some surprisingly recent browsers - I think in IE's case this is because the `Event` constructor is not instantiable and the polyfill fixes that (see https://github.com/Financial-Times/polyfill-service/issues/705).

I have never used web workers, but docs suggest that neither `window` nor `document` is available.  We could therefore define `Event` but can't define event related prototype methods of window and document like `addEventListener`.

**Comment by triblondon** [comment]
In fact, even our implementation of the `Event` constructor depends on `document.createEventObject` so I think all we can do here is probably to prevent this polyfill running in workers.

**Comment by triblondon** [comment]
@tschaub does the Promise polyfill work in the worker if you specifically exclude the Event polyfill from being loaded using our `exclude` parameter? ([Docs](https://polyfill.io/v2/docs/api))

**Comment by tschaub** [comment]
@triblondon - I'll give it a try (we're bundling in [`promise-polyfill`](https://www.npmjs.com/package/promise-polyfill) for now).

Would it make sense to accept something like `context=worker` so special `exclude`s like this could be handled by the service?

**Comment by triblondon** [comment]
Perhaps, but since I don't think Jake or I make much use of workers, it would be tough to maintain, unless someone else steps up to help us with that.  Thanks for trying it, let me know if it works without the Event polyfill

**Comment by JakeChampion** [comment]
Hi @tschaub, this is now available for testing on https://qa.polyfill.io/ 👍
