### ISSUE TITLE
Add Document.registerElement() polyfill

### ISSUE THREAD

**Issue by slawiko** [polyfillpolyfill/polyfill-service#1113]
- [ ] Polyfill X is not served in browser Y (and it should be)
- [ ] Polyfill X is served in browser Y (and it shouldn't be)
- [ ] My browser is not recognised correctly
- [x] Please add polyfill X
- [ ] Please update polyfill X from the upstream repo
- [ ] Polyfill X doesn't work properly

[Document.registerElement()](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement) polyfill.

Maybe we can use https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.max.amd.js or something like that.

**Comment by triblondon** [comment]
Duplicate of https://github.com/Financial-Times/polyfill-service/pull/1101?

**Comment by alexlafroscia** [comment]
Per [MDN's docs on `registerElement`](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement):

> document.registerElement() is deprecated in favor of customElements.define().

`customElements.define()` will be polyfilled by the PR I'm working on, which @triblondon linked to above.  So it's not really a duplicate, but I'm not sure if you'd want to add a polyfill not for behavior that is already deprecated.

**Comment by slawiko** [comment]
@alexlafroscia yes, you're right, I wouldn't. So let's close this issue.
