### ISSUE TITLE
Add reflect metadata polyfill

### ISSUE THREAD

**Issue by slawiko** [polyfillpolyfill/polyfill-service#1114]
- [ ] Polyfill X is not served in browser Y (and it should be)
- [ ] Polyfill X is served in browser Y (and it shouldn't be)
- [ ] My browser is not recognised correctly
- [x] Please add polyfill X
- [ ] Please update polyfill X from the upstream repo
- [ ] Polyfill X doesn't work properly

[Reflect metadata](https://rbuckton.github.io/reflect-metadata/) polyfill.  Maybe we can use that https://www.npmjs.com/package/reflect-metadata .

**Comment by JakeChampion** [comment]
I would be hesitant adding this as a polyfill in our service because it currently not does not have a champion in TC39 and is not being actively proposed (assumption made on looking at the proposals document -- https://github.com/tc39/proposals).

**Comment by JakeChampion** [comment]
We are looking to follow the advice that the W3C TAG has written about polyfills. https://w3ctag.github.io/polyfills/#feature-life-cycle-and-the-role-of-polyfills

**Comment by slawiko** [comment]
Ok, let's close this issue
