### ISSUE TITLE
Array.from not served to chrome 45

### ISSUE THREAD

**Issue by CheloXL** [polyfillpolyfill/polyfill-service#1122]
As the title says, Array.from should be served to Chrome <= 45.
Test url: https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Windows%20NT%206.1)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/45.0.2423.0%20Safari/537.36

**Comment by JakeChampion** [comment]
Chrome 45 has basic support for `Array.from`, have you got a reproducible example of their native implementation failing to work correctly?

**Comment by CheloXL** [comment]
I'm getting errors reports like "Uncaught TypeError: Array.from is not a function in xxx" in Chrome 45 (Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2423.0 Safari/537.36).
I'm passing a Set to Array.from, but by the error it seems that it is not supported at all (is not a function), not some type error in the arguments...

**Comment by JakeChampion** [comment]
@CheloXL Could you create a small reproducible test case for this? https://jsbin.com is a good place to store such a test case.

**Comment by CheloXL** [comment]
@JakeChampion I suppose I can, it should be a couple of lines, but I don't have Chrome 45 to test against... Do you have any kind of test service that can handle that?

**Comment by JakeChampion** [comment]
I use Browserstack for testing, Browserstack has Chrome 45.

**Comment by CheloXL** [comment]
@JakeChampion Done, it should work (or not :) )
https://jsbin.com/zayihiwevo/edit?html,js,output

**Comment by JakeChampion** [comment]
@CheloXL It works on chrome 45 on windows. 
<img width="1440" alt="screen shot 2017-03-16 at 14 22 39" src="https://cloud.githubusercontent.com/assets/1569131/24000766/1ad63eca-0a54-11e7-9843-bd781103d8f0.png">

**Comment by CheloXL** [comment]
@JakeChampion mmm... strange. Can you tell me which version of windows is running Chrome on?

**Comment by JakeChampion** [comment]
Windows 10 @CheloXL

**Comment by JakeChampion** [comment]
I've also tested on windows 8/7 and XP and it works as expected

**Comment by CheloXL** [comment]
@JakeChampion Ok. Closing as it seems to be non-reproducible. If I get more data or I'm able to reproduce locally, will open a new issue. Thanks for your time!
