### ISSUE TITLE
Polyfill Intl breaking test

### ISSUE THREAD

**Issue by aleics** [polyfillpolyfill/polyfill-service#1125]
Hello,

We are experiencing some problems with the `Intl` feature. When adding the following polyfill https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en,Intl.~locale.de on our karma configuration file for the unit tests, we receive the following error:

````
PhantomJS 2.1.1 ERROR
  TypeError: undefined is not an object (evaluating 'Intl.Collator.supportedLocalesOf')
  at https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en,Intl.~locale.de,Element.prototype.classList&flags=gated:6
````
When removing the `Intl` feature, all the tests pass properly.

Is this some problem that you've already experienced?

Thanks!

**Comment by renehamburger** [comment]
The same happens in IE10: 'Intl.Collator' is undefined.

**Comment by JakeChampion** [comment]
This should solve the issue -- https://github.com/Financial-Times/polyfill-service/pull/1126

**Comment by renehamburger** [comment]
@JakeChampion, thanks for the quick fix!

**Comment by MikaFima** [comment]
Hi @JakeChampion, can we hope a CDN update including this fix soon ?

**Comment by JakeChampion** [comment]
Yes, I'm working on creating the next release. We have a bit of an issue with generating our compatibility data which is used on https://polyfill.io/v2/docs/features/. Once I have resolved that issue a release will make it's way to https://qa.polyfill.io and then onto https://polyfill.io if no issues are found during the QA period.
