### ISSUE TITLE
Discussion: Policy around aliases for ecmascript-262

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#1135]
>We currently have a lot of polyfills aliased to es6, but not many attached to the year-based names and none attached to es7 or es8. We might need some policy here, @JakeChampion - thoughts?
_- https://github.com/Financial-Times/polyfill-service/pull/1082#discussion_r106840705_

**Comment by JakeChampion** [comment]
My thoughts would be to follow ecmascript-262 and use the year-based names. We should go back and alias all `es6` features to `es2015`, keeping the `es6` alias for backwards compatibility.

**Comment by triblondon** [comment]
Sounds like a good plane job.  I'll do this, and also write up the policy in docs.
