### ISSUE TITLE
How can I drop IE8 specific code?

### ISSUE THREAD

**Issue by hbrls** [polyfillpolyfill/polyfill-service#1142]
Like [this](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Element/polyfill.js#L3)

    // IE8
    if (window.Element && !window.HTMLElement) {
        window.HTMLElement = window.Element;
        return;
    }

**Comment by triblondon** [comment]
Hi @hbrls.  One of the reasons for using our service is that we only serve content to browsers that need it, so most code designed for IE8 will only appear if requested from IE8.  In odd cases we do have tiny fragments of code for old browsers that are embedded in polyfills that we target at more recent browsers.  The fragment you've extracted is from our Element polyfill, which we only serve to IE 6-8.

https://github.com/Financial-Times/polyfill-service/blob/70fc44727ed08f14f150eaa0205d4ec4b08313e0/polyfills/Element/config.json

**Comment by hbrls** [comment]
Hi, @triblondon. I came from `Promise -> Event -> Element`. And most likely I will use the `always` flag instead of detecting.

Actually I'm looking for a more general solution for apps not serving IE8. I was thinking of something similar to the wildly accepted practice `if (process.env.NODE_ENV === 'development')` that could be eliminated by uglifyjs.

I've searched and read the issues and quite appreciate your consideration to compatibility. Although the IE6-8 only `Element` example is not typical enough, would you open the issue again if my general expectation was on the right track?

**Comment by triblondon** [comment]
I don't think what you're suggesting is applicable to our service because we already only serve code that is needed by the browser.  If you choose to use `always`, then you transfer the code bloat issue onto yourself, but since we already provide a solution I don't think we're interested in providing another one.

**Comment by hbrls** [comment]
Do you mean that the detecting service can skip `Element` on some browser has `Element` but not `Promise`? I can work with that. Am I missing some docs?

**Comment by JakeChampion** [comment]
We do that by default, you are overriding that functionality by using the `always` flag.

>always
>Polyfill should be included regardless of whether it is required by the user-agent making the request. If there are multiple browser-specific variants of the polyfill, the default one will be used for browser that doesn't actually require the polyfill. In some cases where the only way of implementing a polyfill is to use browser-specific proprietary technology, the default variant may be empty.
>https://polyfill.io/v2/docs/api

What is the reason for using the `always` flag?

**Comment by hbrls** [comment]
@JakeChampion I want to inline the script.

**Comment by hbrls** [comment]
Dear all, I kind of misunderstood the service. I tried with Chrome for the following 2 cases and would like to share the result.

1. Chrome with [Win7/IE8 useragent](https://blogs.msdn.microsoft.com/ie/2009/01/09/the-internet-explorer-8-user-agent-string-updated-edition/)

```
https://cdn.polyfill.io/v2/polyfill.js?features=Element&ua=Mozilla%2F4.0%20(compatible%3B%20MSIE%208.0%3B%20Windows%20NT%206.1%3B%20Trident%2F4.0)

    /* Polyfill service v3.17.0
    * For detailed credits and licence information see https://github.com/financial-times/polyfill-
    service.
    * 
    * UA detected: ie/8.0.0
    * Features requested: Element
    * 
    * - Document, License: CC0 (required by "Element")
    * - Element, License: CC0 */
```

2. Chrome

```
https://cdn.polyfill.io/v2/polyfill.js?features=Element

    /* Polyfill service v3.17.0
    * For detailed credits and licence information see https://github.com/financial-times/polyfill 
    service.
    * 
    * UA detected: chrome/56.0.0
    * Features requested: Element
    *  */

    /* No polyfills found for current settings */ 
```

The result is clear how the service skip unnecessary deps.

And my decision is `https://cdn.polyfill.io/v2/polyfill.js?features=Promise,fetch&excludes=Window,Document,Element,Event,XMLHttpRequest,Object.defineProperty,Object.getOwnPropertyNames,Array.isArray,Array.prototype.forEach&flags=always,gated`.

Thanks for all your help.
