### ISSUE TITLE
IntersectionObserver is not defined

### ISSUE THREAD

**Issue by shtse8** [polyfillpolyfill/polyfill-service#1154]
We have received lots of error reports from users.

Url:
```
https://cdn.polyfill.io/v2/polyfill.min.js?features=IntersectionObserver,requestAnimationFrame&flags=gated&unknown=polyfill
```

Error:
```
IntersectionObserver is not defined
```

User-agents:
```
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
```
```
Mozilla/5.0 (Linux; Android 5.1.1; F1f Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Mobile Safari/537.36 OPR/34.0.2044.99135
```
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2683.0 Safari/537.36
```
```
Mozilla/5.0 (Windows NT 6.1; rv:53.0) Gecko/20100101 Firefox/53.0
```
```
Mozilla/5.0 (Linux; Android 5.1; CPH1605 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Mobile Safari/537.36 OPR/37.0.2192.112031
```

**Comment by shtse8** [comment]
Error:
```
ReferenceError: Can't find variable: IntersectionObserver
```

User Agnets:
```
Mozilla/5.0 (iPad; CPU OS 5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Mobile/9B206 [FBAN/FBIOS;FBAV/6.5.1;FBBV/377040;FBDV/iPad1,1;FBMD/iPad;FBSN/iPhone OS;FBSV/5.1.1;FBSS/1; FBCR/;FBID/tablet;FBLC/zh_CN;FBOP/1]
```

```
Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Mobile/10B329 [FBAN/FBIOS;FBAV/8.0.0.28.18;FBBV/1665515;FBDV/iPad3,1;FBMD/iPad;FBSN/iPhone OS;FBSV/6.1.3;FBSS/2; FBCR/;FBID/tablet;FBLC/zh_TW;FBOP/1]
```

**Comment by shtse8** [comment]
Error:
```
Uncaught ReferenceError: IntersectionObserver is not defined
```

User Agents:
```
Mozilla/5.0 (Linux; U; Android 4.1.2; en-gb; GT-P3100 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
```

```
Mozilla/5.0 (Linux; U; Android 4.1.1; zh-tw; GT-P3100 Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
```

**Comment by JakeChampion** [comment]
The firefox user agents will be fixed in the next release -- https://github.com/Financial-Times/polyfill-service/pull/1120/files

**Comment by shtse8** [comment]
But it seems not only firefox, will they be fixed in the next release? I have turned on `flags=always` to temporarily resolve this issue

**Comment by JakeChampion** [comment]
`Mozilla/5.0 (Linux; U; Android 4.1.1; zh-tw; GT-P3100 Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30` is Android 4.1, the polyfill targets Android 4.4 and higher.

`Mozilla/5.0 (Linux; U; Android 4.1.2; en-gb; GT-P3100 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30` is Android 4.1, the polyfill targets Android 4.4 and higher.

`Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Mobile/10B329 [FBAN/FBIOS;FBAV/8.0.0.28.18;FBBV/1665515;FBDV/iPad3,1;FBMD/iPad;FBSN/iPhone OS;FBSV/6.1.3;FBSS/2; FBCR/;FBID/tablet;FBLC/zh_TW;FBOP/1]` is iOS Safari 6.1, the polyfill targets iOS Safari 7 and higher.

`Mozilla/5.0 (iPad; CPU OS 5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Mobile/9B206 [FBAN/FBIOS;FBAV/6.5.1;FBBV/377040;FBDV/iPad1,1;FBMD/iPad;FBSN/iPhone OS;FBSV/5.1.1;FBSS/1; FBCR/;FBID/tablet;FBLC/zh_CN;FBOP/1]` is iOS Safari 5.1, the polyfill targets iOS Safari 7 and higher.

`Mozilla/5.0 (Linux; Android 5.1; CPH1605 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Mobile Safari/537.36 OPR/37.0.2192.112031` is Opera Mobile, the polyfill does not target Opera Mobile at all.

`Mozilla/5.0 (Linux; Android 5.1.1; F1f Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Mobile Safari/537.36 OPR/34.0.2044.99135` is Opera Mobile, the polyfill does not target Opera Mobile at all.

`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2683.0 Safari/537.36` is Chrome 51, the polyfill targets Chrome up to version 50.

You can see what the polyfill supports here - https://github.com/WICG/IntersectionObserver/tree/gh-pages/polyfill#browser-support
You can see what we target the polyfill at here - https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/IntersectionObserver/config.json

**Comment by shtse8** [comment]
Unterstand. That means many users are using old browser. and it is hard to make a polyfill.
So it doesn't support the polyfill but not user-agent detecting issue. is it right?

**Comment by triblondon** [comment]
Our targeting of IntersectionObserver correctly matches the declared support range of the polyfill.  If you can do further testing to show that it works on earlier browsers, you can submit a PR to expand the range, but in that case it is also highly desirable to also get the polyfill authors to update the range of browsers they support so that future releases of the polyfill do not regress that support.

For the moment, no action for us since our support range matches the advertised support range on the polyfill.

**Comment by triblondon** [comment]
@philipwalton for info ☝️

**Comment by triblondon** [comment]
Also see https://github.com/WICG/IntersectionObserver/pull/209
