### ISSUE TITLE
MutationObserver documentation issue

### ISSUE THREAD

**Issue by ctjhoa** [polyfillpolyfill/polyfill-service#1155]
Hi,

I would like to raise a documentation error for the mutationObserver feature.
![2017-03-29-235602_1682x1022_scrot](https://cloud.githubusercontent.com/assets/1716173/24491255/4adee04a-14db-11e7-8f2e-8b136f7c2444.png)

This feature cannot be supported natively everywhere obviously and values should be https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/MutationObserver/config.json

**Comment by triblondon** [comment]
See #1179
