### ISSUE TITLE
iOS 10.2 Safari 10 fails on `Array.prototype.iterator` with `is not a function`

### ISSUE THREAD

**Issue by jonashaag** [polyfillpolyfill/polyfill-service#1159]
As a means of re-opening #1019:

This is still an issue. To reproduce:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Symbol,Symbol.iterator,Array.prototype.@@iterator"></script>
<script>
const a = [1,2,3]
const it = a[Symbol.iterator]()
let x
while((x = it.next(), !x.done)) {
  document.write("<div>" + x.value + "</div>")
}
</script>
```

**Comment by JakeChampion** [comment]
From the features you have requested, ios safari 10.2 only gets served the URL polyfill. Should we be serving other polyfills to it from your list?

https://cdn.polyfill.io/v2/polyfill.js?features=default,Symbol,Symbol.iterator,Array.prototype.@@iterator&ua=ios_saf/10.2

```
/* Polyfill service v3.17.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: ios_saf/10.2.0
 * Features requested: Array.prototype.@@iterator,Symbol,Symbol.iterator,default
 * 
 * - URL, License: CC0 (required by "default") */
```

**Comment by triblondon** [comment]
@jonashaag Our `Array.prototype.@@iterator` tests are passing in iOS 10.2 with no polyfill.  I also copied your repo code into a JSBin:

http://jsbin.com/binuzotehe/

This runs without error in desktop and iOS safari 10.  Feel free to reopen if you can provide a JSBin with a reproducible test case.
