### ISSUE TITLE
Set polyfill doesn't work with Array.from in IE11

### ISSUE THREAD

**Issue by zslabs** [polyfillpolyfill/polyfill-service#1161]
Hi all,
Using the included [Set polyfill](https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/Set), I have the following:

`const testSet = [...new Set([1, 2, 1])];`

In Chrome and Edge (for example), the output is what I expect it to be:

<img width="158" alt="screen shot 2017-04-04 at 1 38 10 pm" src="https://cloud.githubusercontent.com/assets/1018402/24670429/f7e94faa-193b-11e7-82e2-ccce6fffae11.png">

But in IE11 (where the polyfill kicks-in), this is what I'm shown:

<img width="313" alt="screen shot 2017-04-04 at 1 38 53 pm" src="https://cloud.githubusercontent.com/assets/1018402/24670454/11317d3e-193c-11e7-8cae-0f1b4537798c.png">

It looks like it's creating an object within the array. I've run the code directly from your source as well and am getting the same results. Any idea what's going on?

**Comment by JakeChampion** [comment]
It looks like you are also compiling the code as IE11 does not support the spread operator, can you show us how you are compiling the code please? I'm interested in seeing if it is pulling in the babel-polyfills or similar.

**Comment by zslabs** [comment]
Hey @JakeChampion I was using CodePen for this example with the babel option turned on, but the portion is used inside a larger React-app. What's odd is I have to use `babel-polyfill` inside of `.babelrc` for this to work with the polyfill option turned on which loads https://github.com/babel/babel/blob/master/packages/babel-polyfill/src/index.js but I'm not seeing anything in there that polyfill.io shouldn't also be taking care of already which is the confusing part.

**Comment by zslabs** [comment]
@JakeChampion On https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array/from/polyfill.js#L79 `arraylike.constructor.name` is coming up as `undefined` in IE http://stackoverflow.com/questions/25140723/constructor-name-is-undefined-in-internet-explorer

**Comment by zslabs** [comment]
Any other info I could provide? We are attempting to use polyfill.io within a React environment; `.babelrc` file has the following:

```
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    "transform-strict-mode",
    "transform-class-properties"
  ],
  "env": {
    "production": {
      "presets": ["react-optimize"]
    }
  }
}
```

and the app only works if I include the following (which seems like they'd be covered already by this service):

```
if (typeof Promise === 'undefined') {
  // Rejection tracking prevents a common issue where React gets into an
  // inconsistent state due to an error, but it gets swallowed by a Promise,
  // and the user has no idea what causes React's erratic future behavior.
  require('promise/lib/rejection-tracking').enable();
  window.Promise = require('promise/lib/es6-extensions.js');
}

// Object.assign() is commonly used with React.
// It will use the native implementation if it's present and isn't buggy.
Object.assign = require('object-assign');

require('babel-polyfill');
```

I have also added `regenerator-runtime` (since that is required in the app).

**Comment by JakeChampion** [comment]
You have lots of parts here, babel polyfills (which can conflict with our polyfills), compiling spread operator to the es5 equivalent (is that be replaced by Array.from or is babel doing something else?) and multiple babel presets. I'm not sure if any in particular are the surfacing the issue.

A minimal code example which reproduces the bug and the polyfill.io url you are using to get your polyfill bundle would be really helpful.

Our Set polyfill tests pass in IE11, perhaps you can look at the tests and see if you can add one which replicates what you are seeing?

**Comment by JakeChampion** [comment]
Our Set polyfill tests pass in IE11, perhaps you can look at the tests and see if you can add one which replicates what you are seeing?

**Comment by zslabs** [comment]
Hey @JakeChampion,
Sure - a quick example is available at http://codepen.io/zslabs/pen/a56d6c9eae0e692bc019cae6f1f1e787?editors=1111

If I `console.log()` that Set I get `[1, 2, 3, 4]` in Chrome, but `[]` in IE11, no babel enabled.

**Comment by JakeChampion** [comment]
@zslabs Where is the call to the polyfill service in that codepen example? Could you please tell me the polyfill.io url you are using to get your polyfill bundle.

**Comment by zslabs** [comment]
If you click on the settings cog in the JS window, you'll see it included in there. Just using `https://cdn.polyfill.io/v2/polyfill.min.js`

**Comment by zslabs** [comment]
You can also view the debug mode to see the plain generated HTML page http://s.codepen.io/zslabs/debug/a56d6c9eae0e692bc019cae6f1f1e787

**Comment by triblondon** [comment]
OK, the problem here is that `Array.from()` doesn't work on our polyfilled sets in IE.

```javascript
> var s = new Set([1,2,3,4]);
> console.log(Array.from(s));
< []
```

**Comment by triblondon** [comment]
See #1161

**Comment by zslabs** [comment]
Thanks @triblondon ! It looks like the releases may not necessarily be on a defined schedule -- any idea when something like that may land in the wild?

**Comment by triblondon** [comment]
When a PR is merged, it's assigned to a release, and then we release periodically. You'll get at least 7 days notice because we push to qa.polyfill.io a week ahead of cdn.polyfill.io, and announce on twitter.
