### ISSUE TITLE
Promise polyfill not working in UC Browser for Android

### ISSUE THREAD

**Issue by matthewsuan** [polyfillpolyfill/polyfill-service#1162]
Polyfills are not loading on UC Browser for Android.

Any ideas would be greatly appreciated.

Thanks!

**Comment by matthewsuan** [comment]
I just wanted to add that when I load the polyfill using UC, it says

`unknown/unsupported`
 &
`No polyfills found for current settings`

**Comment by JakeChampion** [comment]
@matthewsuan Please add to your URL `&unknown=polyfill` to serve polyfills to browsers which we do not support.

**Comment by matthewsuan** [comment]
Gotcha.

Thanks.
