### ISSUE TITLE
Multiple arguments for classList.add & classList.remove

### ISSUE THREAD

**Issue by JoyceBabu** [polyfillpolyfill/polyfill-service#1167]
I would like to include a polyfill to add support for multiple arguments in `classList.add` and `classList.remove` on IE 10/11, Firefox < 26 and Chrome < 27.

There is already a polyfill adding support for the second argument in `classList.toggle`. But the there is a mismatch in the browser support for `classList.toggle` and `classList.add` / `classList.remove`.

Where should I add the new polyfill? 

- Should I update the existing polyfill for `classList.toggle` with and conditional check to prevent the polyfill for `classList.toggle` from being applied to IE 11 / Firefox 24/24. 
- Or should I create a new polyfill independent of the above polyfill

**Comment by triblondon** [comment]
@JoyceBabu Our preferred option would be to update the existing polyfill and extend the targeting if appropriate.

**Comment by JakeChampion** [comment]
This will be resolved via https://github.com/Financial-Times/polyfill-service/pull/1347
