### ISSUE TITLE
Better document the need for specifying features if not getting expected polyfills

### ISSUE THREAD

**Issue by msteitle** [polyfillpolyfill/polyfill-service#1168]
In my humble opinion, the documentation needs to place more emphasis on specifying feature sets (none/default, es5, es6, es7, etc). I needed `Array.protoype.includes` for IE, but couldn't understand why it wasn't being loaded. I looked at the `config.json` file for it and saw that ie definition specified `*`, so it should be included. After an hour of digging in the code and walking through the request, I discovered that there was a default set of features loading and `Array.protoype.includes` wasn't in that set. This led me to locate the different defined sets, which led me to look for documentation on sets and finally realize the issue.

It would have saved me a lot of time if this was more prominent (mentioning the default set, perhaps) in the about/getting-started notes, or in a troubleshooting/faq section, and not just hiding in the API documentation. It would also helped make the mental connection if the browser/feature table specified which features were included in each feature set.

If we are in agreement, I'll be happy to add a documentation PR for it.

**Comment by triblondon** [comment]
@msteitle Thanks for raising this, though I do think we make this reasonably clear already. Regardless of how obvious you make something there will be a proportion of people who miss it, through no fault of their own, but it does say it right here in the center of the homepage:

![image](https://cloud.githubusercontent.com/assets/1735391/25317163/0bfbc220-2828-11e7-9c05-990e063ab743.png)

I suppose we could reverse the order of those two sentences.  Would that help?

**Comment by msteitle** [comment]
I don't disagree about your philosophy on documentation. Finding the relevant documentation in retrospect is obvious, but it would have helped to have a faq or troubleshooting section for why expected polyfills aren't being loaded. ES6 is so prevalent these days, I made the assumption that it would be part of the default before I later found that relevant documentation. Map and Set, for instance, are es6 additions, but are included by default.

**Comment by triblondon** [comment]
@msteitle Maybe just make a PR to throw some more stuff into the default set.  We don't have a defined methodology for it, and are happy to move more stuff in as browsers evolve beyond the need for many of them.

Will close this as I think we will probably not update docs, but I'd encourage the update to the default set as a fresh PR.
