### ISSUE TITLE
Can't get Object.values polyfill to be included

### ISSUE THREAD

**Issue by msteitle** [polyfillpolyfill/polyfill-service#1169]
[The MDN compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values) confirms that `Object.value` is an es2017 feature and [the polyfill config file](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/values/config.json) agrees. But even requesting the polyfill script via `https://cdn.polyfill.io/v2/polyfill.js?features=es2017|always` doesn't include it.

**Comment by JakeChampion** [comment]
It has not yet been released into production. You can see what features are
in production by visiting https://polyfill.io/v2/docs/features/

It will be included in the next release :-)

**Comment by msteitle** [comment]
Aah, yes. That would explain it. Thanks!
