### ISSUE TITLE
Polyfill throws ´Permission denied to access property "target"´

### ISSUE THREAD

**Issue by CheloXL** [polyfillpolyfill/polyfill-service#1171]
This seems to be happening on firefox >= 50. This is happening on a system I maintain and the errors are logged into a logging system (I can't reproduce this error on the machines I have access to).

Polyfill served to the browser: https://cdn.polyfill.io/v2/polyfill.js?features=default,MutationObserver,AudioContext,WeakMap,WeakSet,Symbol,Symbol.iterator&ua=Mozilla/5.0%20(X11;%20Ubuntu;%20Linux%20i686;%20rv:50.0)%20Gecko/20100101%20Firefox/50.0

The served file only contains a couple of lines, so I suppose the error is related to the events focusin/focusout.

Not sure what else I can provide on this...

**Comment by triblondon** [comment]
https://github.com/Financial-Times/polyfill-service/issues/213 describes some earlier issues that we had with focusin in FF.  My theory was that the behaviour depended on the stage at which the event got called.  It seemed like if it happened during the page load, you could not `dispatchEvent` on target.

I'm not sure I got to the bottom of what `target` is when this error occurs.  Do you have a record of that?  Or can you log it?

**Comment by CheloXL** [comment]
Well... I would need to serve a custom polyfill version for that, as I would need to trap the error and log additional information. Now, even with that, I'm not quite sure I would be able to know what target holds, as I don't think I will be able to read it (same error).

My research on that error sent me to this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied, but my application doesn't use iframes, nor I let my application run inside an iframe (it should fail even before the browser tries to load the polyfill), so I really don't know what could be happening here...

**Comment by JakeChampion** [comment]
@CheloXL Can you create a reproducible test case for this on jsbin? If not, I'm not sure how we can progress with fixing the issue.

**Comment by CheloXL** [comment]
@JakeChampion unfortunately, no. I'm getting this error on the logs, but I were never able to reproduce on my side. Feel free to close the issue. If at any point I'm able to reproduce it, I will open a new one.

**Comment by JakeChampion** [comment]
We now only serve the focusin polyfill to firefox versions older than version 52, hopefully that would fix the issue you saw before.

https://github.com/Financial-Times/polyfill-service/pull/1383
