### ISSUE TITLE
Map / Set polyfills fail on UC Browser

### ISSUE THREAD

**Issue by JoyceBabu** [polyfillpolyfill/polyfill-service#1172]
Map / Set polyfills fail in UC Browser on Android (tested with version 11.2.0)  with messages

> TypeError: Cannot set property 'Map' of undefined

and

> TypeError: Cannot set property 'Set' of undefined respectively.

**Comment by triblondon** [comment]
Moved to https://github.com/Financial-Times/polyfill-service/pull/1173
