### ISSUE TITLE
Promise polyfill is not working in UC Browser

### ISSUE THREAD

**Issue by JoyceBabu** [polyfillpolyfill/polyfill-service#1174]
The included version of `Promise` polyfill is not working in UC Browser. The issue has been fixed in latest upstream release `v0.17.12`

https://github.com/ysmood/yaku/issues/45

**Comment by JakeChampion** [comment]
Thanks, will get this updated 👍

**Comment by JoyceBabu** [comment]
I was about send a PR. Should I continue?

**Comment by difelice** [comment]
@JoyceBabu Promise is not working for me on **UC Browser 11.3.5.972** and **polyfill.io 3.19.0**. Can you please confirm?

**Comment by JoyceBabu** [comment]
It is working for me on the same version of UC Browser. Are you depending on `polyfill.io`'s user agent based feature detection? I am using JS based feature detection.

http://www.joycebabu.com/test/uc-promise/demo.html

**Comment by JoyceBabu** [comment]
I think UC browser is not supported by the user agent detection service, so it won't get a polyfill unless you append `&unknown=polyfill`  to the end of the polyfill script url.

**Comment by difelice** [comment]
That might solve the problem. I'll try it. 

Thank you so much!
