### ISSUE TITLE
Gated locales will crash in IE 9 because Intl.Collator is undefined

### ISSUE THREAD

**Issue by nerdgore** [polyfillpolyfill/polyfill-service#1180]
Implementing the polyfill for Intl in IE 9 will load the correct polyfills but will crash the browser when checking for supported locales.

**Expected behaviour:**
GIVEN I load the polyfilled page
WHEN the polyfill is loaded
THEN the Intl API is available

**Actual Behaviour:**
GIVEN I load the polyfilled page
WHEN the polyfill is loaded
THEN the browser displays an error:
> Unable to get value of the property 'supportedLocalesOf': object is null or undefined

Checking in the console, the culprit seems to be the statement checking `Intl.Collator` which is undefined. `Intl.DateTimeFormat` and `Intl.NumberFormat` are defined.

Removing `flags=gated` removes the error message, however `Intl.Collator` is never defined.

Polyfill used: `https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Intl.~locale.de-DE&flags=gated`

**Comment by hannesj** [comment]
This was fixed in https://github.com/Financial-Times/polyfill-service/commit/a4ba0f20c24ba7292066193295109aed20496ac9, but is not released yet. 

@JakeChampion Do you have any estimate for the next release?

**Comment by JakeChampion** [comment]
Think I fixed the issues blocking a release, building the release now :-)
