### ISSUE TITLE
`cloneNode` detection is failing on Firefox 53

### ISSUE THREAD

**Issue by JoyceBabu** [polyfillpolyfill/polyfill-service#1183]
`cloneNode` detection is failing on Firefox 52/53. Tested on Mac and Window.

**Comment by JakeChampion** [comment]
What is the full polyfill url you are using? Do you know of a way to detect `cloneNode` that works in those browsers?

**Comment by JoyceBabu** [comment]
I think the detection script is working fine, but Firefox is not compliant.

Following code returns false on Chrome, but true on Firefox

```
!('document' in this && "cloneNode" in document.documentElement && (function() {
	var test = document.createElement('input');
	test.checked = true;
	var result = test.cloneNode(true);
	return !!result.checked;
})())
```

**Comment by JoyceBabu** [comment]
Sorry, the issue is that `checked` is not applicable for `input[type=text]`. If you change the type to `radio`, or use `value` instead of `checked` it works as expected.


```
!('document' in this && "cloneNode" in document.documentElement && (function() {
	var test = document.createElement('input');
	test.checked = true;
        test.type = "radio";
	var result = test.cloneNode(true);
	return !!result.checked;
})())
```

and

```
!('document' in this && "cloneNode" in document.documentElement && (function() {
	var test = document.createElement('input');
	test.value = "1";
	var result = test.cloneNode(true);
	return !!result.value === "1"
})())
```

works correctly

**Comment by JoyceBabu** [comment]
!('document' in this && "cloneNode" in document.documentElement && (function() {
	var test = document.createElement('input');
	test.checked = true;
        test.type = "radio";
	var result = test.cloneNode(true);
	return !!result.checked;
})())

and

!('document' in this && "cloneNode" in document.documentElement && (function() {
	var test = document.createElement('input');
	test.checked = true;
        test.type = "radio";
	var result = test.cloneNode(true);
	return !!result.checked;
})())

or 

!('document' in this && "cloneNode" in document.documentElement && (function() {
	var test = document.createElement('input');
	test.value = 1;
	test.type = "radio";
	var result = test.cloneNode(true);
	return !!result.value == 1
})())

works correctly

**Comment by JakeChampion** [comment]
Will you be submitting a PR for this @JoyceBabu?
