### ISSUE TITLE
3.18 Release

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#1185]
We've pushed version 3.18.0-0 to [QA](https://qa.polyfill.io) and it has been published to NPM under the `next` label.

To install this package from NPM you can run `npm i polyfill-service@next`.

[Click here for the full changelog.](https://github.com/Financial-Times/polyfill-service/milestone/34?closed=1)

New polyfills:
- Added `String.prototype.@@iterator` #1165 by @JakeChampion
- Added `String.fromCodePoint` #1152 by @JakeChampion
- Added `String.prototype.padStart` and `String.prototype.padEnd` #1117 by @regiskuckaertz
- Added `EventSource` #1073 by @CheloXL 
- Added `Object.values` #1082 by @JounQin 

Notable changes:
- Cache content on CDN for a year, soft purge from CDN when deploying #1145 by @JakeChampion
- Fix UA detection for wkwebview  #1124 by @lepture 
- Update Opera configurations for ES6 requirements #1100 by @dlebech  
- Include subdomains in HSTS and enable polyfill.io to be on preload list #1118 by @JakeChampion

No changes to the default set, so we have not introduced a new immutable default set label.

As usual, we'll hold this on QA for a week for testing. Please post any concerns here.

**Comment by JoyceBabu** [comment]
Can you please include the fix for https://github.com/Financial-Times/polyfill-service/issues/1183 also in to the release?

**Comment by JakeChampion** [comment]
This is live on https://polyfill.io -- https://github.com/Financial-Times/polyfill-service/releases/tag/v3.18.0
