### ISSUE TITLE
Element.matches not working on Edge 13 + 14

### ISSUE THREAD

**Issue by coreybruyere** [polyfillpolyfill/polyfill-service#1187]
Just added polyfil.io and saw the Element.matches isn't working in Edge 13 + 14 when testing in Browserstack. IE 11 and Edge 15 work fine though.

**Comment by JakeChampion** [comment]
Hi, thanks for reporting the issue. Could you please create a test case using an online tool like <a href="https://jsbin.com">JSBin</a>, which loads <strong>only</strong> the polyfill service script, and then includes inline any code required to trigger the problem (which should be no more than a few lines).

**Comment by CheloXL** [comment]
Probably related to #1065. I fixed that for IE11, as I didn't get any reports from Edge missing it.
Are you sure it's from Edge "destktop"? As noted in mi pull request (#1071) I wasn't able to test it on Edge mobile. Maybe there is where it is needed?

**Comment by coreybruyere** [comment]
Sorry for the late response. I'm just testing in Edge 14 now and am not seeing the issue. Edge 13 isn't on Browserstack anymore. I'll close this issue.
