### ISSUE TITLE
Dropped support for TLS below 1.2

### ISSUE THREAD

**Issue by davidfischer** [polyfillpolyfill/polyfill-service#1192]
It isn't entirely clear to me whether this was a decision you guys made or a decision by fastly or something inadvertent, but the latest release to cdn.polyfill.io dropped support for TLS versions below 1.2.

While I can't expect you to serve older browsers or OSs forever, I just wanted to make sure that you were clear on what you are dropping support for (IE before 11 without tweaks, Chrome before 30, Android before 4.4, etc.) with this release.

* While you have an [A+ with SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=cdn.polyfill.io&s=151.101.128.207&latest) you can also see all the browsers and OSs with no support
* http://caniuse.com/#feat=tls1-2

**Comment by JakeChampion** [comment]
Thanks for reporting the issue!

Yes, Fastly dropped support for TLS 1.0 and TLS 1.1 on their general set-up. I have requested that polyfill.io Fastly services use the set-up which still supports TLS 1.0 and TLS 1.1.

I've tested this in IE 9 and it looks to be working. Would you be able to confirm on your side of things that it is working as you expect?

**Comment by rupesh1** [comment]
Our IE9 VM that was unable to connect yesterday (without manual intervention) is connecting as expected today. Thanks all.

And verified by a colleague on a real laptop still running IE9 on Windows 7.

**Comment by JakeChampion** [comment]
@rupesh1 Thank you for the confirmation, I will be closing this issue now as it looks like the work has been completed by Fastly :-)

**Comment by davidfischer** [comment]
Thank you for the change and I can confirm support for some old browsers and OSs are restored.

**Comment by davidfischer** [comment]
Also, I'm a big fan of the FT. Keep up the good work!
