### ISSUE TITLE
Array.prototype.@@iterator not served to Android 5.0

### ISSUE THREAD

**Issue by jonashaag** [polyfillpolyfill/polyfill-service#1196]
https://cdn.polyfill.io/v2/polyfill.js?features=Symbol.iterator,Array.prototype.@@iterator&ua=Mozilla/5.0%20(Linux;%20Android%205.0;%20SAMSUNG%20SM-N9005%20Build/LRX21V)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20SamsungBrowser/2.1%20Chrome/34.0.1847.76%20Mobile%20Safari/537.36

According to https://kangax.github.io/compat-table/es6/ `Array.prototype.@@iterator` is not supported on Android 5.0 stock browser, so it should be polyfilled.

Edit: Actually I'm not sure if this is stock browser but we it showed up in our JS error logs with that UA.

**Comment by JakeChampion** [comment]
Hi @jonashaag, the user-agent string you have in the polyfill.io url is detected as samsung_mob/2.1.0, which is a version of the samsung browser we do not support.

If you add `&unknown=polyfill` to the end of the polyfill.io url, we will serve all the polyfills requested when we do not support the browser that the request has come from.
