### ISSUE TITLE
Feature list not loading in docs

### ISSUE THREAD

**Issue by frederikcreemers** [polyfillpolyfill/polyfill-service#1197]
I went to look at [the feature list in the docs](https://polyfill.io/v2/docs/features/), but there are no features listed. I tried entering "Array.prototype" in the filter box, to see if it'd show only filtered items, but still nothing. This is the case both in Chrome and Safari.

**Comment by JakeChampion** [comment]
That should be back now :-)

**Comment by frederikcreemers** [comment]
It's working when I look in incognito mode, but not without, so there's probably some broken content still in my cache. If the expiration time isn't too long, this is probably not an issue, but if there's any cache busting you can do, that'd fix it for users who ahve visited the page while it was broken.

**Comment by JakeChampion** [comment]
I purged the cache at edge (Fastly). I will close this issue as it looks to be working correctly. Thanks for reporting the issue!
