### ISSUE TITLE
can't browse the webpage using Midori

### ISSUE THREAD

**Issue by drzraf** [polyfillpolyfill/polyfill-service#1199]
* Please fix the website

This webpage https://polyfill.io/v2/docs/features/
* the menu button corresponding to each polyfill) is not usable under Midori 0.5.11 although it could even without a need for Javascript
* filter does not work
* ...

**Comment by triblondon** [comment]
Thanks for the report.  None of the core contributors to polyfill.io use Midori, but if you would like to submit a pull request to fix the experience for Midori users, we would be happy to accept it.
