### ISSUE TITLE
Condition for adding a polyfill to default set

### ISSUE THREAD

**Issue by JoyceBabu** [polyfillpolyfill/polyfill-service#1203]
- On what basis are the polyfills included in the default alias selected?
I just noticed that the `Element.prototype.dataset` polyfill is not included in the default set, whereas more modern features like `Map` and `Set` are included.
- Does it make sense to include `Element.prototype.dataset` with `default-3.7`?

**Comment by triblondon** [comment]
Including stuff in the default set is based on:

* Demand (should be high)
* Polyfill size (should be small)
* Number of browsers with native support (should be at least 2)

In the case of dataset I think it meets those criteria, but if we issue an updated default set I think it would make sense to run through the list and consider adding several more.  If you want to do that and propose a change to the default set in a PR, we'd be happy to consider merging that for the next release.
