### ISSUE TITLE
FormData Polyfill missing

### ISSUE THREAD

**Issue by MartinMuzatko** [polyfillpolyfill/polyfill-service#1205]
I don't have the time for a PR right now. But I want to report that FormData is missing.
I believe the polyfill here works, but I didn't have time to give it a try: https://www.npmjs.com/package/formdata-polyfill

> If so please visit https://polyfill.io/v2/docs/contributing/common-scenarios for help putting together all the information you need for your issue.  Running through the appropriate checklist need not take much time and will make it much more likely that we can deal with the issue quickly.

**Comment by triblondon** [comment]
Hi @MartinMuzatko, indeed we don't currently have a formdata polyfill.  Adding new polyfills to the service is a great activity for new contributors and we'd encourage you to give it a try, using the process that you found in our contributors guide.  We don't keep feature request issues open if they're not actively being worked on but we'd welcome and provide support to help merge a pull request.
