### ISSUE TITLE
Where is the polyfill bundle for each browser

### ISSUE THREAD

**Issue by drnkwati** [polyfillpolyfill/polyfill-service#1210]
Where is the compiled distribution for each browser?
At least we should have a compiled dist to choose from

**Comment by JakeChampion** [comment]
It is compiled on the fly based upon the polyfills you are requesting and which ones the users' browser actually require.

There is not way we can compile a list for this, as there are too many combinations to go through.

**Comment by drnkwati** [comment]
I was expecting atleast those listed on the table here
https://polyfill.io/v2/docs/features/
Bundle sizes have been stated. 
We need those compiled atleast most developers polyfill due to ie issues
Thanks

**Comment by JakeChampion** [comment]
We could calculate the size of the default bundle for the browsers listed on the features page, that is a nice idea :-)

**Comment by triblondon** [comment]
We do that already in the bundle sizes section

**Comment by drnkwati** [comment]
So were is the build. I don't see download link to any of the minified or zipped files

**Comment by JakeChampion** [comment]
What do you mean @drnkwati, I don't understand.

Here is the minified default bundle for IE 10 -- https://cdn.polyfill.io/v2/polyfill.min.js?ua=ie/10

**Comment by drnkwati** [comment]
Were are the links to those files. Or should we be searching on cdn. 
Please just bundle a build or dist and place those links in this repository for easy accessibility.

**Comment by JakeChampion** [comment]
I don't quite understand what you are wanting to achieve, could you please elaborate?

**Comment by drnkwati** [comment]
I don't want to depend on the cdn. I want an ie8 minified to bundle with my project
I want the app to be self contained with all required files.

**Comment by triblondon** [comment]
@drnkwati it sounds like you should probably find a different solution.  Good luck!

**Comment by skitterm** [comment]
Not sure if this is exactly what @drnkwati was wanting, but I'd love to have a downloadable, minified JS file with just the polyfills I need. This would assume I have a static list of polyfills I want, maybe the UI on the site would literally be a series of checkboxes for each of the polyfillable features (like Array.prototype.map) and clicking "download" would generate a .js file with just the checked polyfills (and each polyfill's license!) that I could self-host. Much like what jQuery UI does: http://jqueryui.com/download/

 This would be excellent in settings where pinging an external CDN isn't possible (offline or intranet situations).

Realize that that only works for a static list of polyfills that are known ahead of time, but I'd find that useful.

**Comment by drnkwati** [comment]
That will be cool.

**Comment by RiZKiT** [comment]
You mean this? https://polyfill.io/v3/url-builder/

Creating it in a build process can be achived with: https://github.com/Financial-Times/polyfill-library

**Comment by drnkwati** [comment]
thank you very very much.
