### ISSUE TITLE
Fetch polyfill is served to Safari 10.1

### ISSUE THREAD

**Issue by gmishkin** [polyfillpolyfill/polyfill-service#1216]
According to http://caniuse.com/#feat=fetch Fetch is built in to Safari 10.1 with no known issues. Can the service be updated so that it is not served to Safari versions 10.1 and higher? This version is currently only on macOS, not iOS from what I can tell. But maybe if iOS 11 betas start coming out soon it will be there too.

`https://cdn.polyfill.io/v2/polyfill.js?features=default-3.6%2Cdocument.head%2Cfetch%2CArray.prototype.find&unknown=polyfill`
* UA detected: safari/10.1.0
* Features requested: Array.prototype.find,default-3.6,document.head,fetch

The polyfill works but because of how it uses blobs it makes debugging a little harder than it would be otherwise (the way the requests show up in web inspector).

It looks like there is a feature detect for this
```javascript
'fetch' in this
```
But I'm not sure why that wouldn't prevent the polyfill from being applied, probably misunderstanding something.

**Comment by pieterbeulque** [comment]
This appears to have been updated in #1214 .

**Comment by JakeChampion** [comment]
Hi, this is now available for testing on https://qa.polyfill.io/ 👍

**Comment by caub** [comment]
I don't have Safari, but my coworker has Safari Version 10.0.1 (12602.2.14.0.7)

and https://jsfiddle.net/aj4htd7r/4/ returns false, so there's an issue

He gave me his userAgent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14` so it can be tested at: https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_12_1)%20AppleWebKit/602.2.14%20(KHTML,%20like%20Gecko)%20Version/10.0.1%20Safari/602.2.14 

and indeed no fetch available, should I open a new issue?

**Comment by JakeChampion** [comment]
It is only on qa.polyfill.io right now. Will be on the production site this
week.

**Comment by caub** [comment]
Yes, but the bug (fetch not provided for safari 10.0.1) is happening in the production site

**Comment by JakeChampion** [comment]
@caub Try using qa.polyfill.io, if that works then we know when we promote to the production site (cdn.polyfill.io) that the issue will be fixed.

**Comment by caub** [comment]
It's the same with qa.polyfill.io?ua=..., fetch is missing too

**Comment by JakeChampion** [comment]
@caub Ah yes, that is because `fetch` is not in the default set of polyfills which is what you are requesting. If you want `fetch` alongside the default set you can make a request like this https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch
