### ISSUE TITLE
classList support

### ISSUE THREAD

**Issue by Ollie-w** [polyfillpolyfill/polyfill-service#1222]
From your website it shows that you don't support classList for IE 10 and 11 but do support it in earlier browser? This is pretty confusing. Is that the case or is the website wrong? It seems like an easy thing to polyfill.
From my own testing classList .contains did not work. in IE9.

**Comment by JakeChampion** [comment]
I think you are describing two issues. 

Polyfilling classList for IE10/11:
classList exists in IE10 and IE11, it however does not support multiple parameters to add and remove methods. The polyfill we use also does not support multiple add or remove. If we add support for mulitple parameters to add and remove methods, we would include IE10/11 in the polyfill targeting.

classList polyfill not working in IE9:
You haven't given us much information to go on. Could you please provide the minimum amount of code required to show the issue you are seeing, preferably in a jsbin or codepen page. With a reproducible test, we should be able to help diagnose if there is an issue and whether it can be resolved.

**Comment by Ollie-w** [comment]
Hi Jake. Here's a bin. 
http://jsbin.com/puvikinotu/2/edit?html,js,output
Console error message: error Unable to get property 'contains' of undefined or null reference (line 3)

**Comment by JakeChampion** [comment]
This should be fixed by https://github.com/Financial-Times/polyfill-service/pull/1347
