### ISSUE TITLE
setImmediate dependancy for Promise

### ISSUE THREAD

**Issue by JoyceBabu** [polyfillpolyfill/polyfill-service#1229]
`setImmediate` is listed as a dependency for the `Promise` polyfill. But the current Promise polyfill does not use `setImmediate`.

https://github.com/ysmood/yaku/blob/b5187ec39a90befed234ad27c980d7a36744ef49/src/yaku.core.js#L40-L42

Is it okay to remove the dependancy?

**Comment by JakeChampion** [comment]
@JoyceBabu Good spot! If you could submit a PR which removes it that would be fantastic!

**Comment by JoyceBabu** [comment]
Done https://github.com/Financial-Times/polyfill-service/pull/1230
