### ISSUE TITLE
IntersectionObserver polyfill throws an error in IE11 (Windows 7)

### ISSUE THREAD

**Issue by Konrud** [polyfillpolyfill/polyfill-service#1236]
Trying to add polyfill for IntersectionObserver  in IE11 (using Windows 7)
 I get an error:
 ` window is undefined` in line 252.

![polyfillerror](https://user-images.githubusercontent.com/7681999/27908634-87995304-6255-11e7-8644-2da43ee7a42e.jpg)

**Comment by JakeChampion** [comment]
Hi @Konrud,

If you could post a small reproducible test case for this that would be really helpful. Until then, I will close this issue as we run our tests in IE11 and they are passing.

**Comment by Konrud** [comment]
@JakeChampion  are you run in on Linux or Windows?

**Comment by JakeChampion** [comment]
Windows when we test IE

**Comment by Konrud** [comment]
I've tried it today on Windows 7 IE11 - it gives me: "**SCRIPT5009: 'IntersectionObserver' is undefined**"
