### ISSUE TITLE
Add browserslist support 💪

### ISSUE THREAD

**Issue by retyui** [polyfillpolyfill/polyfill-service#1237]
It will be great if there is an opportunity to create custom build polyfill based on [browserslist](https://github.com/ai/browserslist) 💪

**Comment by JakeChampion** [comment]
Hi @retyui, we don't keep feature request issues open if they're not actively being worked on but we'd welcome and provide support to help merge a pull request.

**Comment by ahmadnassri** [comment]
@JakeChampion this is something I'd wanna work on, where do you suggest I can start?

**Comment by JakeChampion** [comment]
I'm not sure how it would work as we serve a different polyfill bundle to each user-agent.

@triblondon, do you think this feature is possible and if so, something we should add?

**Comment by triblondon** [comment]
I'm also not sure how this would work.  I think the OP would need to outline how they imagine it to work for polyfill.io and then someone might like to work on it.

**Comment by brad-jones** [comment]
Something I knocked up, very rough and dirty but with some polish might be useful.
https://gist.github.com/brad-jones/2f9b9bf0d230ce916960eac933f9da36

Basically the idea would be to generate a polyfill.io URL based on a supplied browserslist config.
