### ISSUE TITLE
ReferenceError: Can't find variable: Window 

### ISSUE THREAD

**Issue by Merri** [polyfillpolyfill/polyfill-service#1243]
Using `https://cdn.polyfill.io/v2/polyfill.min.js?features=default-3.6&unknown=ignore&callback=window._POLY`

TrackJS that we use is reporting this issue on at least these browsers:

- Chrome 43.0.2357
- Chrome 44.0.2403
- Chrome 45.0.2454
- Chrome 46.0.2490
- IE 9.0

Operating systems with errors include Mac OS X, Windows and Linux.

This issue was first seen on 18th of July and seemed to be corrected after that, but started again this Monday and has continued today (Tuesday).

TrackJS is unable to get stacktrace so finding the issue probably requires someone to test in some of the troublesome browser versions to see what the problem is.

**Comment by JakeChampion** [comment]
Hi, if you change your script tag to include the crossorigin attribute set to anonymous then you will start to see stack traces from errors inside of polyfills.

`<script crossorigin="anonymous" src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default-3.6&unknown=ignore&callback=window._POLY"></script>`

I'm not sure what is causing the error, hopefully when a stack trace is caught alongside the error that would help both of us investigate the issue.

**Comment by JakeChampion** [comment]
Hi @Merri, I've tried to replicate this on IE9 but I can not, here is the small test case I made -- http://jsbin.com/?console#/xedaqetizi/1/edit

I will close this issue for now as I can not replicate. If you can put together a small reproducible test case, we can re-open the issue and look at how to fix it.
