### ISSUE TITLE
IE11 Array.prototype.find anonymous function is not a function TypeError

### ISSUE THREAD

**Issue by smdern** [polyfillpolyfill/polyfill-service#1245]
In IE11 we're seeing a type error `function(t) { return t.cardId === other.id } is not a function` when trying to call `[].find()`. But in the console `function(t) { return... } instanceof Function` is true. I'm not sure what's going on and why it would work in one place but not the other in IE11. This is an issue on all Array.prototype functions that take a callback and do a type check. 

I believe the simple solution would be to use a `typeof callback === 'function'` check instead of `instanceof Function` check.

**Comment by aaronjensen** [comment]
How about doing it manually? Also, include it in vendor rather than each package:

```js
// https://tc39.github.io/ecma262/#sec-array.prototype.find
if (!Array.prototype.find) {
  Object.defineProperty(Array.prototype, 'find', {
    value: function(predicate) {
     // 1. Let O be ? ToObject(this value).
      if (this == null) {
        throw new TypeError('"this" is null or not defined');
      }

      var o = Object(this);

      // 2. Let len be ? ToLength(? Get(O, "length")).
      var len = o.length >>> 0;

      // 3. If IsCallable(predicate) is false, throw a TypeError exception.
      if (typeof predicate !== 'function') {
        throw new TypeError('predicate must be a function');
      }

      // 4. If thisArg was supplied, let T be thisArg; else let T be undefined.
      var thisArg = arguments[1];

      // 5. Let k be 0.
      var k = 0;

      // 6. Repeat, while k < len
      while (k < len) {
        // a. Let Pk be ! ToString(k).
        // b. Let kValue be ? Get(O, Pk).
        // c. Let testResult be ToBoolean(? Call(predicate, T, « kValue, k, O »)).
        // d. If testResult is true, return kValue.
        var kValue = o[k];
        if (predicate.call(thisArg, kValue, k, o)) {
          return kValue;
        }
        // e. Increase k by 1.
        k++;
      }

      // 7. Return undefined.
      return undefined;
    }
  });
}
```

via https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by JakeChampion** [comment]
Hi @smdern, we are happy to accept a PR which uses `typeof` instead of `instanceof`.

**Comment by aaronjensen** [comment]
@JakeChampion https://github.com/Financial-Times/polyfill-service/pull/1253
