### ISSUE TITLE
requestAnimationFrame sometimes not available in Android 4.4.4

### ISSUE THREAD

**Issue by christophehurpeau** [polyfillpolyfill/polyfill-service#1247]
Hello,

We have several reports thanks to [sentry](https://sentry.io/) that `requestAnimationFrame` is sometimes not available on Android 4.4.4, but [is not included](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/requestAnimationFrame/config.json#L12) by the polyfill.
 
Here are examples of user agents:
- `Mozilla/5.0 (Linux; U; Android 4.4.4; fr-fr; GT-I9305 Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`
- `Mozilla/5.0 (Linux; U; Android 4.4.4; fr-fr; SAMSUNG SM-G357FZ/G357FZXXU1AOJ1 Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

I tested with an emulator and that version had `requestAnimationFrame`:

- `Mozilla/5.0 (Linux; Android 4.4.2; Android SDK built for x86 Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36`

Maybe the difference is in `Chrome/30.0.0.0` ?

**Comment by JakeChampion** [comment]
Hmm, the first user agent string you posted is [identified as Android 4.4](https://polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Linux;%20U;%20Android%204.4.4;%20fr-fr;%20GT-I9305%20Build/KTU84P)%20AppleWebKit/534.30%20(KHTML,%20like%20Gecko)%20Version/4.0%20Mobile%20Safari/534.30) and won't get served the polyfill.

The last user agent string you posted is [identified as Chrome 30](https://polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Linux;%20Android%204.4.2;%20Android%20SDK%20built%20for%20x86%20Build/KK)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Version/4.0%20Chrome/30.0.0.0%20Mobile%20Safari/537.36) which also does not get served the polyfill.

The MDN support table states that [Android 4.4 supports requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#compat-mobile).

Do you think we should bump the range for Android to `<5`?

**Comment by christophehurpeau** [comment]
Since Android 4.4 google no longer had a browser bundled into it, so that Chrome could be installed as an application and be updated without depending on the system.
However some manufacturers kept distributing some Android with a browser bundled into it with an older version of the renderer.

So I think we can safely asume that when [Chome/xxx is not in the user agent](https://developer.chrome.com/multidevice/user-agent) in Android 4.4 then the browser is probably an older one ? Or is it possible to use `AppleWebKit/XXX.XX` / `Safari/XXX.XX` to guess it's equivalent chrome version when the browser is `Android` ?

According to [whatismybrowser.com](https://www.whatismybrowser.com/developers/tools/user-agent-parser/browse/operating-system-name/android-user-agents), for browsers in Android 4 without `chrome/` it's `Android Browser 4`, and they all have `AppleWebKit/534.30`

So I guess we could say `"android": "*"` ?
