### ISSUE TITLE
Array.from does not try to use iterator protocol

### ISSUE THREAD

**Issue by magnushiie** [polyfillpolyfill/polyfill-service#1251]
In Chrome (without Polyfill), the following snippet produces the expected result:
```js
var o = {};
o[Symbol.iterator] = function() {
  let i = 0;
  return ({
    next: function() {
      i++;
      return { done: i > 5, value: i};
    }
  });
};
Array.from(o);
```

```js
(5) [1, 2, 3, 4, 5]
```

The same in IE11 with https://cdn.polyfill.io/v2/polyfill.min.js?features=es6 loaded returns an empty array:
```
[object Array]   []
   length        0
```

I discovered this actually with MobX observables, for which Array.from also produces an empty array.

**Comment by fooloomanzoo** [comment]
same for me
