### ISSUE TITLE
Add polyfill for `<details>` and `<summary>` elements

### ISSUE THREAD

**Issue by onishiweb** [polyfillpolyfill/polyfill-service#1252]
Would it be feasible to support the polyfill for the `<details>` and `<summary>` elements? 

MDN:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
https://developer.mozilla.org/en/docs/Web/HTML/Element/summary

There's already a couple of Polyfills, https://github.com/javan/details-element-polyfill which looks fairly substantial and another https://gist.github.com/remy/370590 which I'm guessing might need to be implemented in here directly with the relevant tests etc. 

If this sounds like a good idea I'd be happy to take a crack at it.

**Comment by JakeChampion** [comment]
Sounds great! Thanks for offering to do the work, that would be really helpful. If you get stuck or the documentation isn't helpful feel free to tag me in any PR or issue :-)

**Comment by JakeChampion** [comment]
Hi @onishiweb, we don't keep feature request issues open if they're not actively being worked on but we'd welcome and provide support to help merge a pull request.
