### ISSUE TITLE
Problems with IE 11 in compatibility mode

### ISSUE THREAD

**Issue by JCofman** [polyfillpolyfill/polyfill-service#1255]
Hi everyone first thanks a lot for the service. 

I am currently facing an issue which I cannot resolve properly. I want to add the Intl. polyfill when a browser needs it for example IE 10. Since IE 11 doesn't need a polyfill its alright that it doesnt get send down the wire while using IE 11 but now I want to make sure that the polyfill will get send also when a user switches from IE 11 to IE 10 e.g. inside the devtools or is using IE 11 in compatability mod. .

So what I tried to do is to send down the polyfill always but only for IE 11 users -> 
```
https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en-US|always&ua=Mozilla%2F5.0%20(Windows%20NT%206.1%3B%20Trident%2F7.0%3B%20rv%3A11.0)%20like%20Gecko
```
Is that possible I think I dont understand the API correctly.

Thanks a lot in advance. :)

**Comment by JakeChampion** [comment]
Hi @Ixl123, IE11 compatability mode is recognised as IE/7. The Intl polyfill [supports IE 9 - 10](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Intl/config.json#L4).

Regarding the polyfill URL you have mentioned, the `ua` parameter is used to tell the polyfill-service what browser to target the polyfills for. If you send us the IE/11 user-agent string, we will service polyfills for IE/11 to all your users, including those on Chrome, Safari etc. This is not recommended.

What you can do is force the Intl.~locale.en-US polyfill to always be downloaded but only use it if the feature is not detected as natively supported. The way to do this is to include `|always|gated` after the specific polyfill. E.G. `https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en-US|always|gated`. This will mean that modern browser which support Intl will always download the polyfill but they wont ever use the polyfill.

**Comment by JakeChampion** [comment]
This can not be solved by the polyfill-service until https://github.com/andyearnshaw/Intl.js/issues/189 is resolved upstream. Please follow that issue if you would like to know when a fix for this is released.

**Comment by JCofman** [comment]
@JakeChampion thanks a lot for your response 👍
