### ISSUE TITLE
Array.from polyfill still does not work correctly when passed a set in IE11

### ISSUE THREAD

**Issue by mcshaz** [polyfillpolyfill/polyfill-service#1259]
this is a continuation on from issue #1161. 

The tests and fix provided in the fix for issue #1161 check the map or set for the 'entries' or 'values' methods respectively on the prototypes, but IE11 does not have these methods on the map and set prototypes. Similarly, it does not seem in my testing that these methods are being polyfilled in IE11.

The test passes in IE11 only because the test is bypassed - the  existence of the 'entries' and 'values' methods are checked before running the test and bypassed if not present. 

2 potential options I can see:

- check for the forEach method on the prototypes of map and set, and then build the array using this rather than looking for an iterator.
- polyfill in the entries and values methods to map and set prototypes prior to running Array.from

I can submit a pull request for failing tests to look at the issue more closely.

Thanks

**Comment by mcshaz** [comment]
some approaches to testing and a simple fix are here https://github.com/Financial-Times/polyfill-service/compare/master...mcshaz:master. 2 commits - the first with the tests that fail in IE11 and the second with the code changed to use forEach rather than entries/values for map & set instances.

**Comment by mcshaz** [comment]
I think this issue should probably be merged with #1209  although I don't believe the Set polyfill is used because IE11 has a Set constructor, but the object produced doesn't adhere to the iterable pattern - the code in the pull request related to this solution is a workaround using IE11s native set which does have a foreach method which does iterate through undefined values.

**Comment by JakeChampion** [comment]
@mcshaz As the PR related to this issue ( #1260 ) has been merged, can we close this issue?
