### ISSUE TITLE
Promise polyfill is not a promise polyfill

### ISSUE THREAD

**Issue by juandopazo** [polyfillpolyfill/polyfill-service#126]
Returning `this` from `then` is not a valid behavior for a promise polyfill. It´s also lacking `Promise.race`, `Promise.resolve` and `Promise.reject`. I suggest using https://github.com/jakearchibald/es6-promise.

**Comment by monolithed** [comment]
#### jonathantneal's:

Promises/A+ 266 passing / 593 failing

#### Octane's

https://github.com/Octane/Promise
Promises/A+ 872 passing + 55 own tests

 I suggest using Octane's polyfill

**Comment by jonathantneal** [comment]
I’m game with that, but your numbers don’t add up: 266 + 593 = 859 ... vs 872? + 55 own tests?

Would you setup something like you’ve done with https://octane.github.io/promise/ to show us the 859 to 872 plus 55 tests? Depending on the severity difference (like, if all your failing tests hang on one feature) we can fix ours or adopt yours.

**Comment by Octane** [comment]
Hello.
The [Promise polyfill](https://github.com/Octane/Promise) is passing 872 tests of the [Promises/A+ compliance test suite](https://github.com/promises-aplus/promises-tests) [![Build Status](https://travis-ci.org/Octane/Promise.svg?branch=master)](https://travis-ci.org/Octane/Promise)

![passing 872 tests](https://dl.dropboxusercontent.com/u/8763532/screenshots/promise872tests.png)
try it

```
$ git clone https://github.com/Octane/Promise.git
$ cd Promise
$ npm install
$ npm test
```

I wasn't trying to run mocha-based Promise/A+ tests in a browser, but I have [55 browser-based tests](https://octane.github.io/promise/tests/browser.html)  in which there are tests for `Promise.all` and `Promise.race` (missing in the test suite).

Supports IE8+

––––––––––––––––––––––––––––––
UPD: I replaced my polyfil to your ([modified for tests](https://dl.dropboxusercontent.com/u/8763532/promise.js)) and got the result:
![your polyfill results](https://dl.dropboxusercontent.com/u/8763532/screenshots/promise593failing.png)

**Comment by jonathantneal** [comment]
That’s awesome. I’m sure Juan or someone will setup some tests so we can take a look. Great work, both of you.

**Comment by juandopazo** [comment]
Octane's promise looks pretty good. The implementation is straightforward and readable. Its approach is similar to my own version, so I obviously like it! :wink: 

My only gripe with it is that it relies on `setImmediate` as a global API. `setImmediate` will not be supported by any browsers other than IE and its semantics are different from what promises really do under the hood (google "promises microtasks vs macrotasks"). @Octane will you be willing to use https://github.com/kriskowal/asap instead? It uses the fastest implementation possible instead of trying to mimic `setImmediate`.

**Comment by jonathantneal** [comment]
I’m with you, @juandopazo. Having looked over [the code](https://github.com/Octane/Promise/blob/master/promise.js), this is probably the most readable Promise polyfill I have seen. We’ll all have our biases (I think it could be shorter and more streamlined), but if the tests are true, then this is fantastic, and I would be very open and eager to adopting this polyfill.

I’m still not comfortable with asap, @juandopazo =) but I think @Octane’s work is cleanly compatible with many deferred solutions, even our current one.

**Comment by matthew-andrews** [comment]
I've run into a bug today when using the polyfill service's Promise polyfill with [fetch](http://github.com/github/fetch)…

``` js
Promise.resolve().then(function() {
  return Promise.resolve('["i output therefore i am"]').then(JSON.parse);
}).then(function(a) { console.log(a[0]); });
// Should output “i output therefore i am”
```

Native Promise (Chrome)
![screen shot 2015-01-24 at 17 55 13](https://cloud.githubusercontent.com/assets/825088/5888325/6d42ebec-a3f2-11e4-88b3-4f824a8a8282.png)

ES6-Promise in Node
![screen shot 2015-01-24 at 17 58 07](https://cloud.githubusercontent.com/assets/825088/5888329/9c620e6c-a3f2-11e4-8315-b18d016dea2b.png)

ES6-Promise in IE9
![screen shot 2015-01-24 at 18 00 48](https://cloud.githubusercontent.com/assets/825088/5888344/f5203268-a3f2-11e4-9cc7-b852f5066316.png)

Polyfilled Promise in IE9
![screen shot 2015-01-24 at 17 55 36](https://cloud.githubusercontent.com/assets/825088/5888327/7a0e53b6-a3f2-11e4-90b8-9047dd1c0aa3.png)

This is affecting FT stuff…

Thanks!

**Comment by juandopazo** [comment]
It's basically failing to resolve the promise inside `then`. It's covered by the A+ test suite, so any implementation that fully passes the test suite should not fail you. Any of [ypromise](http://github.com/yahoo/ypromise), [es6-promise](https://github.com/jakearchibald/es6-promise) or [Octane's](https://github.com/Octane/Promise) should be fine.

**Comment by triblondon** [comment]
See #255 and #257
