### ISSUE TITLE
Proposal: publish service and library seperately

### ISSUE THREAD

**Issue by marionebl** [polyfillpolyfill/polyfill-service#1265]
I am currently working on adding the library part of polyfill-service on a project and running into some difficulties with deploying my work due to compilation issues around `node-zopfli` - although my code and the polyfill-service code I want to use do not actually need it.

```bash
project@1.0.0 ~/project
└─┬ polyfill-service@3.20.2
  └─┬ shrink-ray@0.1.3 # imported at service/index.js#7
    └── node-zopfli@1.4.0 
```

Diving into the source I noticed dependencies for both the polyfill.io service and the underlying are managed in one manifest file. Also, both parts are published via the same npm package.

I propose splitting service and library into distinct packages like this to avoid installing the sum of all dependencies of all sub projects at every dependent.

```bash
packages
├── polyfill-service # publishes to polyfill-service
└── polyfill-library # publishes to polyfill-library
```

`polyfill-service` would depend on `polyfill-library` and expose it to maintain backward compat for the time being. Interested consumers could install `polyfill-library` and avoid the dependencies of `polyfill-service` this way. Also this would lend itself to new interfaces to the logic of `polyfill-library` - think `polyfill-cli`.

The entire thing could be managed via `lerna`. I'be happy to lend a hand. Thoughts?

**Comment by JakeChampion** [comment]
I completely agree that they should be separate packages, I have been thinking about doing this for quite some time. I've never used `lerna`, do you think a solution is possible without involving it? If you have the time and capacity to lend a hand, that is great! I'm happy to explain the codebase or answer any questions you may have.

**Comment by marionebl** [comment]
Doing this without lerna is perfectly possible - doing the publishing and dep management by hand won't be hard as long as only two packages are involved. I'll submit a PR showcasing this later today

**Comment by SebastianS90** [comment]
As owner of [`SebastianS90/webpack-polyfill-injector`](https://github.com/SebastianS90/webpack-polyfill-injector/) which uses polyfills from this amazing project here, I also want to advocate for splitting the package into two parts where one only contains the polyfills and the other all code and dependencies that are required to run the polyfill-service webserver.

**Comment by marionebl** [comment]
@SebastianS90 This already underway via https://github.com/Financial-Times/polyfill-service/pull/1267

**Comment by JakeChampion** [comment]
This has been done. The library is at https://github.com/Financial-Times/polyfill-library and the service is at https://github.com/Financial-Times/polyfill-service
