### ISSUE TITLE
Proposal: 'always' flag for callback 

### ISSUE THREAD

**Issue by tamb** [polyfillpolyfill/polyfill-service#1268]
In the case that we need to handle the failure of polyfill.io script retrieval, the callback function should always be fired.  This way if x amount of time has gone by without function firing we can inform the user/handle accordingly.

**Comment by JakeChampion** [comment]
I am not sure that can be achieved by us (polyfill.io). You can ensure the callback is fired by adding an `onerror` event listener to the script tag, [MDN has some advice about how to do this](https://developer.mozilla.org/en/docs/Web/API/HTMLScriptElement#Dynamically_importing_scripts).
