### ISSUE TITLE
Polyfill Object.assign is not served in Opera

### ISSUE THREAD

**Issue by kaelig** [polyfillpolyfill/polyfill-service#1273]
According to my bugsnag logs on polaris.shopify.com, this happened in two instances:

```
TypeError · Object doesn't support property or method 'assign'
```

## Win 7 / Opera 46 (Edition Yx)

browserName: Opera
browserVersion: 46.0.2597
locale:ru
osName:Windows 7
userAgent: `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 OPR/46.0.2597.57 (Edition Yx)`

https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Windows%20NT%206.1;%20WOW64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/59.0.3071.115%20Safari/537.36%20OPR/46.0.2597.57%20(Edition%20Yx)

----

## Win 10 / Opera 46

browserName: Opera
browserVersion: 46.0.2597
locale: ru
osName: Windows 10
userAgent: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 OPR/46.0.2597.57`

https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20WOW64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/59.0.3071.115%20Safari/537.36%20OPR/46.0.2597.57

Let me know if you'd like additional information.

**Comment by kaelig** [comment]
Note that Opera 47 may also need the polyfill as I can see the same type of errors in my logs for it.

**Comment by JakeChampion** [comment]
@kaelig We don't have Opera available in our testing environment. Would you be able to contribute this fix? We have a guide that you can follow -- https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by kaelig** [comment]
Unfortunately neither do I! It’s been showing up in my logs but I haven’t tried to reproduce it.

**Comment by christophehurpeau** [comment]
Opera 46 is based on chrome 59 so it has Object.assign

**Comment by JakeChampion** [comment]
@kaelig We have no tests for our `Object.assign` polyfill 🙀. I have a PR which adds them (#1284). Once that is out, we can confirm whether Opera 46 requires the polyfill, I assume not based on @christophehurpeau's comment above ☝️.
