### ISSUE TITLE
Polyfill Array.find is not served in IE11

### ISSUE THREAD

**Issue by LeoIannacone** [polyfillpolyfill/polyfill-service#1275]
As per title.
Thanks

**Comment by christophehurpeau** [comment]
https://cdn.polyfill.io/v2/polyfill.js?features=default,es6&ua=Mozilla/5.0%20(Windows%20NT%206.3;%20Trident/7.0;%20rv:11.0)%20like%20Gecko

it is, did you required it ?

**Comment by LeoIannacone** [comment]
I'm using defaults TBH

**Comment by JakeChampion** [comment]
Array.prototype.find is not in the default set, if you require it, please add it to the features list in your polyfill.io script call

**Comment by LeoIannacone** [comment]
Thanks!

How can I add all the polyfill in one require ?

**Comment by JakeChampion** [comment]
Like so: https://polyfill.io/v2/polyfill.js?features=default,Array.prototype.find

**Comment by mikemclin** [comment]
@JakeChampion He was asking how to get the "kitchen sink" of polyfills for a browser.  It too am looking for that.

**Comment by triblondon** [comment]
See https://polyfill.io/v2/docs/api:

> Setting the value "all" will select every feature in the library (this is an extremely bad idea and will be removed in a future version)

Please don't use 'all'.  Today that will deliver a bundle of up to 25MB in size, and you should assume that in future it might deliver new features in WASM modules which might be even larger.  Basically if you set 'all' today and forget about it, you should assume that the file will grow to 1GB+ in future.
