### ISSUE TITLE
Polyfill always fetched from source with 'age' header value higher than 'max-age' header value.

### ISSUE THREAD

**Issue by romainmenke** [polyfillpolyfill/polyfill-service#1276]
When requesting `https://cdn.polyfill.io/v2/polyfill.min.js?features=es5,es6,es7,default-3.6,Object.values&flags=gated&version=latest&unknown=ignore` I see the following response headers:

```
accept-ranges:bytes
access-control-allow-origin:*
age:1099341
cache-control:public, s-maxage=31536000, max-age=604800, stale-while-revalidate=604800, stale-if-error=604800
content-encoding:br
content-length:978
content-type:application/javascript;charset=utf-8
date:Fri, 25 Aug 2017 15:37:54 GMT
server:Cowboy
status:200
strict-transport-security:max-age=31536000; includeSubdomains; preload
timing-allow-origin:*
vary:User-Agent
vary:Accept-Encoding
via:1.1 vegur
via:1.1 varnish
x-cache:HIT
x-cache-hits:1
x-content-type-options:nosniff
x-frame-options:sameorigin
x-served-by:cache-ams4135-AMS
x-timer:S1503675475.984820,VS0,VE0
x-xss-protection:1; mode=block
```

Because the `age` value is higher than the `max-age` value the response is never stored in browser cache and always fetched from the CDN.

Would it be possible to omit the `age` header?

---

update

Have done some more research on this. The 'age' header seems to be set by fastly. This seems an incorrect configuration to me as the current cache mechanic for polyfill.io is to store indefinitely in CDN and purge on update. Serving "stale", as indicated by the response headers can't be intentional.

**Comment by romainmenke** [comment]
Any news on this? If this is not the right channel to report issues with `polyfill.io` then please tell how to get in touch with someone who can help me resolve this.

**Comment by JakeChampion** [comment]
This is the correct channel however, I will look into this next week 👍

**Comment by JakeChampion** [comment]
@romainmenke PR for this -- https://github.com/Financial-Times/polyfill-service/pull/1282

**Comment by romainmenke** [comment]
Thank you for resolving this quickly!

Probably being inpatient ( :-) ) but does this require cache purging before it will take effect or just waiting to be deployed?

Will update if we see this taking effect.

**Comment by JakeChampion** [comment]
The release which has this fix will go out on Thursday 👍
