### ISSUE TITLE
IntersectionObserver polyfill doesn't work in IE11 (Windows 7)

### ISSUE THREAD

**Issue by Konrud** [polyfillpolyfill/polyfill-service#1288]
Trying to add polyfill for IntersectionObserver in IE11 (using Windows 7)
doesn't work (**SCRIPT5009: 'IntersectionObserver' is undefined**). 

Please see test case below (Note this code has been tested on IE11 Windows 7)

[test case](https://jsfiddle.net/p44j37f5/)

**Comment by JakeChampion** [comment]
@Konrud When I rewrite the test case to not use dynamic script loading and instead to do a blocking script call it work -- https://jsfiddle.net/p44j37f5/1/

I assume that you want to run your code after the polyfills load? If that is correct, you should ideally use our callback parameter. The callback parameter takes the name of the global function you want to run after the polyfills have loaded. E.G. `https://polyfill.io/v2/polyfill.js?features=IntersectionObserver,Array.from&callback=startApplication`.

<img width="1440" alt="screen shot 2017-09-07 at 10 03 07" src="https://user-images.githubusercontent.com/1569131/30155771-9aff01aa-93b5-11e7-8ed3-5a16ce35c920.png">

**Comment by Konrud** [comment]
@JakeChampion still doesn't work.
[https://jsfiddle.net/p44j37f5/3/](https://jsfiddle.net/p44j37f5/3/)

**Comment by JakeChampion** [comment]
@Konrud You can't use `const` and the function needs to be on the `window` object. Here is your code after I applied those fixes -- https://jsfiddle.net/p44j37f5/5/ -- it works.

**Comment by Samanoova** [comment]
Hi @JakeChampion 
i have the same issue can you please help me the links wont open.


here is my code 

`$(function () {
    const targets = document.querySelectorAll('.background-cover');
    const lazyLoad = function (target) {
        const io = new IntersectionObserver(function (entries, observer) {
            console.log("musab");
            console.log(entries);
            for (var i = 0; i < entries.length; i++) {
                if (entries[i].isIntersecting) {
                    const img = entries[i].target;
                    const src = img.getAttribute('data-lazy');
                    img.style.backgroundImage = "url(" + src + ")";
                    observer.disconnect();
                }
            }
        });
        io.observe(target)
    };
    for (var i = 0; i < targets.length; i++) {
        lazyLoad(targets[i]);
    }
})`


how can i make it work with internet explorer ?
