### ISSUE TITLE
How can Symbol.hasInstance be polyfilled?

### ISSUE THREAD

**Issue by trusktr** [polyfillpolyfill/polyfill-service#1291]
I see the polyfill [here](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/hasInstance/polyfill.js), but how can this actually work? 

I mean, even if you put some `hasInstance` property on a `Symbol` global, how can we actually modify `instanceof` to use the method that will be assigned with it.

For example,

```js

class Foo {}

Foo[Symbol.hasInstance] = function(other) {
  console.log('instanceof check')
}

const f = new Foo

f instanceof Foo // logs "instanceof check"

```

How can this actually work?

Wouldn't the `instanceof` checks need to be transpiled to something else that uses the fake Symbol?

**Comment by JakeChampion** [comment]
That's correct, we can't do anything here for that. It requires a compilation step with our specific polyfill implementations in-mind, I don't think anything like that currently exists.

**Comment by trusktr** [comment]
To that end, is it worth having this polyfilled if it doesn't do anything besides possibly introduce unexpected errors when instanceof checks don't work as expected?

If it weren't polyfilled, then initializtion code using Symbol.hasInstance would fail sooner and in the right place, as a stronger indication that the environment running the code cannot work properly with the given code.

**Comment by trusktr** [comment]
For my own use case, I'm using Rollup + Bublé.

Bublé doesn't polyfill anything, it only transpiles language features. So Bublé leaves stuff like `instanceof` in the code and does not add a `Symbol` variable to global.

So, what I'll do in [my project](https://github.com/trusktr/infamous) is [replace `instanceof` occurrences with a custom function that uses `Symbol.hasInstance`](https://github.com/trusktr/infamous/issues/130).

**Comment by JakeChampion** [comment]
That's correct, if wanting to support older environments whilst wanting to overload the `instanceof` keyword you need to compile `instanceof` into an abstraction over the native `instanceof` and `Symbol.hasInstance`. The alternative is to do what you suggest and avoid the compilation and always use the abstraction.

With regards to providing a polyfill, as `Symbol.hasInstance` is a specific symbol that is shipped in browsers, we should provide a polyfill for it. There are many places where Symbols are used indirectly via syntax, such as `for..of` loops using `Symbol.iterator`. These Symbols can be used without the special syntax, which is why we provide them.

**Comment by trusktr** [comment]
> always use the abstraction

Cool, yep, that's what I'll do.

> These Symbols can be used without the special syntax

In what way can `Symbol.hasInstance` be used without the special syntax, for example? In cases like mine where I'll use the abstraction instead of the literal?

**Comment by JakeChampion** [comment]
This is how I would write your example without using `instanceof`:
```js
    class Foo {
        static [Symbol.hasInstance](other) {
            console.log('instanceof check');
        }
    }
    var f = new Foo;

    return Foo[Symbol.hasInstance](f);
```

**Comment by trusktr** [comment]
👍 Good idea! It works well if the RHS is constant, and in my cases it is. I might just make an `instanceOf(LHS, RHS)` helper function for readability.

**Comment by JakeChampion** [comment]
Good idea! I'm going to close the issue as we agree that having these as polyfills is still useful.
