### ISSUE TITLE
loading within webworker

### ISSUE THREAD

**Issue by fooloomanzoo** [polyfillpolyfill/polyfill-service#1292]
`Document`-Polyfill fails if try to load polyfills with-in webworker. If using a webworker it might be useful, also to use `Promise`-Polyfill or other polyfills. It's not a problem that the service sends then those polyfills, because it is eventually not so easy to detect if an requests comes within the `WorkerScope`, but it shouldn't throw an error. 

* in browser Opera (>47), IE11, ...

Also it shouldn't happen, because Opera is build on chromium.

```javascript
importScripts('https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es5,es6');
```
![image](https://user-images.githubusercontent.com/9318952/30181331-2c08084c-9413-11e7-969c-bd1133cb8c64.png)

![image](https://user-images.githubusercontent.com/9318952/30181372-4edc7dc6-9413-11e7-8f68-84859cbf6ad8.png)

**Comment by JakeChampion** [comment]
@fooloomanzoo Can you please post the User-Agent string of the browser you saw this on? Also, this will happen as these feature are not available in a Worker context, I think you can resolve this by asking for each feature to be wrapped in a feature detect like so: `https://cdn.polyfill.io/v2/polyfill.min.js?features=default,es5,es6&flags=gated`.

**Comment by fooloomanzoo** [comment]
@JakeChampion 
UserAgent: `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36 OPR/47.0.2631.71`

`flags=gated` does not change it. There seems to be something missing in missing-feature-detection, at least for `Document`, because it looks for a property in prototype. Such errors can stop executing scripts and the polyfill replacement too.

![image](https://user-images.githubusercontent.com/9318952/30188138-2b3d3b16-942d-11e7-87b4-a6aff0fdddda.png)

**Comment by fooloomanzoo** [comment]
@JakeChampion 
The polyfill for `Element.prototype.after` also includes the line:

```javascript
Document.prototype.after = Element.prototype.after = ...
```

Although in its dependencies there is the entry for `Document`, it is as you can see, not loaded before. 
Nevertheless it also would **not be neccessary** to load it for Opera because in the document-scope it is available (because Opera 47 is using `chromium 60`. The specifications are partly wrong or incomplete) :

![image](https://user-images.githubusercontent.com/9318952/30211348-ed2d09ea-94a0-11e7-9fb9-48872be4feda.png)

On the other hand it might be senseful to specify for a polyfill in which context it should be applicable. For example if you are excecuting a script as a **webworker** then `this` and `self` are of `"DedicatedWorkerGlobalScope"`:

![image](https://user-images.githubusercontent.com/9318952/30211609-05930cc2-94a2-11e7-93c7-548d420fb93d.png)

in comparison to the **window**-scope where they are of `"Window"`:

![image](https://user-images.githubusercontent.com/9318952/30211657-34337dfa-94a2-11e7-8c3e-ef2f64b9da10.png)

Going by the constructor's name might not be the safest way to detect the scope, but there are Polyfills that are not applicable for a webworker (like for `Element` or `Document`) and there are some that are (like for `String`, `Number` or `Promise`).

**Comment by JakeChampion** [comment]
Will be fixed by https://github.com/Financial-Times/polyfill-service/pull/1394
