### ISSUE TITLE
Map.prototype.forEach fires the callback for an empty Map

### ISSUE THREAD

**Issue by gaearon** [polyfillpolyfill/polyfill-service#1299]
This bug in the polyfill impacts React 16 users, and we are shipping React 16 very soon.

Specifically, `Map.prototype.forEach` [attempts to skip deleted items](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Map/polyfill.js#L24) but then [always calls the callback](https://github.com/Financial-Times/polyfill-service/blob/c14494506bc2c95c70195d54d77110995b6cdf93/polyfills/Map/polyfill.js#L25). The problem is that it may be the case that *all* items were deleted, in which case it should have skipped the callback. In other words, [this check](https://github.com/Financial-Times/polyfill-service/blob/c14494506bc2c95c70195d54d77110995b6cdf93/polyfills/Map/polyfill.js#L22) should be done just before calling the callback as well.

Specific reproducing case:

```js
var x = new Map();
x.set(42, 'hi');
x.delete(42);
x.forEach(function() {
  throw new Error('Should never get here!');
});
```

This breaks with the provided `Map` polyfill but works with the native implementation.

**Comment by JakeChampion** [comment]
Thanks for the issue @gaearon, I really appreciate the reproducible test case!

**Comment by JSteunou** [comment]
Could this fix be in 3.21.1 instead of 3.22 ?

It is really a major fix for Map that I searched for a couple days because Map was totally broken in IE11 and make the usage of library like https://github.com/bendc/animateplus totally impossible

**Comment by JakeChampion** [comment]
If all goes well, we will be looking to release 3.22 next week

**Comment by gajus** [comment]
Is there a link for the hosted version of v3.22?, i.e. now I am using https://cdn.polyfill.io/v2/polyfill.min.js, which as far as I understand is v2.

Never mind. I am wrong. Just checked https://cdn.polyfill.io/v2/polyfill.js. It is actually v3.20.2.

**Comment by JakeChampion** [comment]
@gajus It will be on https://qa.polyfill.io/v2/docs/ sometime this week, we will announe this as a github prerelease and tweet about it.

**Comment by JSteunou** [comment]
Any news on this @JakeChampion ? Still blocked on polyfill-service deploiement because of this critical Map issue :/

**Comment by JakeChampion** [comment]
It is on qa now for testing -- https://github.com/Financial-Times/polyfill-service/releases/tag/v3.22.0-0

**Comment by JSteunou** [comment]
:+1:

**Comment by gaearon** [comment]
React 16 was released yesterday and relies on this fix to work.

**Comment by JakeChampion** [comment]
@gaearon Understood, we have a standard roll out plan for this service which is to have the next release go on qa.polyfill.io for our users to test with and after 7 days, if no issues are reported we promote to production.

**Comment by gaearon** [comment]
Yeah, I didn’t meant to be pushing :-). Just letting you know.

**Comment by green-arrow** [comment]
@JakeChampion - any update on if there were any issues discovered in QA?

**Comment by JSteunou** [comment]
@green-arrow  3.22 was shipped with the fix
