### ISSUE TITLE
[Question] Add URLSearchParams polyfill?

### ISSUE THREAD

**Issue by cherniavskii** [polyfillpolyfill/polyfill-service#1329]
What do you think about adding `URLSearchParams` polyfill? Here's a [polyfill](https://github.com/jerrybendy/url-search-params-polyfill) and [MDN doc](https://polyfill.io/v2/docs/contributing/common-scenarios). I can test it and submit a pull request ;)

**Comment by cherniavskii** [comment]
Just read source code, look like it's already present as part of `URL` polyfill, isn't it?

**Comment by JakeChampion** [comment]
It is present in our URL polyfill :-)

**Comment by cherniavskii** [comment]
Thanks! :)

**Comment by Gidgidonihah** [comment]
I realize this is closed, but it would nice to have this information on the [features list](https://polyfill.io/v2/docs/features/)

**Comment by JakeChampion** [comment]
Hi @Gidgidonihah, could you open a new issue which describes what the issue is you have come across and how you think it should be solved please? Thanks :-)
