### ISSUE TITLE
Potentially incorrect / failed NPM Releases

### ISSUE THREAD

**Issue by dcherman** [polyfillpolyfill/polyfill-service#1332]
Starting with 3.21.0, the `test` folder is no longer being published to `npm`, however it is required in order to start the service since it's used to register the `/test` endpoint.

This makes it so that the service immediately crashes when you try to start it.

**Comment by dcherman** [comment]
Side note:  I think there's a bug in your error handling since this code is never hit in this case even though the server failed to start:

https://github.com/Financial-Times/polyfill-service/blob/master/bin/polyfill-service#L16-L19

**Comment by JSteunou** [comment]
see #1342 ;)

**Comment by JSteunou** [comment]
This should be closed
