### ISSUE TITLE
Polyfill Array.prototype.includes breaks for...in (IE 11)

### ISSUE THREAD

**Issue by TimVevida** [polyfillpolyfill/polyfill-service#1333]
When I use the Array.prototype.includes polyfill in IE11, any `for...in` loop over an array will return the element "includes".
See [here](http://jsbin.com/rubeniselo/1/edit?html,console) for a JS Bin (run in IE11).

I believe the problem lies in the polyfill implementation, which does `Array.prototype.includes = ...` instead of `Object.defineProperty(Array.prototype, 'includes', ...)`. When I use the [polyfill on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Polyfill), that uses `Object.defineProperty`, everything works as intended.

**Comment by TimVevida** [comment]
It has been two months since I added this issue, any progress on this?

**Comment by JakeChampion** [comment]
PR for this work -- https://github.com/Financial-Times/polyfill-service/pull/1393

**Comment by TimVevida** [comment]
Hello Jake, thanks for the patch. Would you mind re-opening this issue until the patch is approved?

**Comment by triblondon** [comment]
@TimVevida it should be easy to follow progress on the PR.  The PR gets assigned to the release version so you can see when it goes out.  We close the issue to avoid duplication and people tracking things that don't have the most up to date or accurate info
