### ISSUE TITLE
Doc "feature" in-page navigation links take back to main page.

### ISSUE THREAD

**Issue by Kangz** [polyfillpolyfill/polyfill-service#1334]
On this page https://polyfill.io/v2/docs/features/ the o-techdocs modules adds navigation links of the form `href="#feature-list"` for in-page navigation. Clicking on the link browses to the doc's main page.

The problem seems to be that a `<base href="/"/>` inserted in the page that makes these links point to `https://polyfill.io/#feature-list` instead of `https://polyfill.io/v2/docs/features/#feature-list`. I wasn't able to pin-point where this `<base>` element was coming from though.

**Comment by JakeChampion** [comment]
This is now fixed, thanks for reporting the issue 👍
