### ISSUE TITLE
RUM Reporting broken on polyfill.io

### ISSUE THREAD

**Issue by roblabla** [polyfillpolyfill/polyfill-service#1337]
This page shows a bunch of error logs : https://polyfill.io/v2/docs/usage

```
[rumPerf] RUM disabled.  See README for environment variables required for RUM reporting.
```

It doesn't look like this is supposed to happen ? ^^

**Comment by JakeChampion** [comment]
Thanks for the issue, I am currently looking into this and should have a solution out shortly :-)

**Comment by JakeChampion** [comment]
This is now fixed and live 👍 https://polyfill.io/v2/docs/usage
