### ISSUE TITLE
3.21.x is broken and cannot launch

### ISSUE THREAD

**Issue by JSteunou** [polyfillpolyfill/polyfill-service#1342]
Release from npm do not include test folder, but router try to create test endpoint.

**Comment by JakeChampion** [comment]
Hi, this is because of a bug in npm https://github.com/npm/npm/issues/18341

I will use an older version of npm and publish a patch releas with the test directory

**Comment by JakeChampion** [comment]
I've also made a PR to fix the issue in NPM for other projects -- https://github.com/npm/npm/pull/18625

**Comment by JakeChampion** [comment]
Test folder is now included in the 3.1.24 release 👌

**Comment by JSteunou** [comment]
I understand better. I was searching through the history of `package.json` but see nothing.
Thank you for the fast release!
