### ISSUE TITLE
please support force param of classList.toggle()

### ISSUE THREAD

**Issue by 75lb** [polyfillpolyfill/polyfill-service#1346]
In IE11, please support the `force` parameter of the `classList.toggle` method. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList).

This example should always add the `something` class to the document body: 

```
document.body.classList.toggle('something', true)
```

However, the `force` param is ignored meaning the `something` class is toggled instead of being added by force.

**Comment by JakeChampion** [comment]
This will be fixed by #1347
