### ISSUE TITLE
Please add polyfill for the HTML dialog element

### ISSUE THREAD

**Issue by achun** [polyfillpolyfill/polyfill-service#1351]
* Please add polyfill X

see this:

https://github.com/GoogleChrome/dialog-polyfill

**Comment by JakeChampion** [comment]
Hi, thanks for raising this. We love to see people wanting to extend the polyfill service to accommodate new features. We don't keep feature request issues open without a PR, but we do provide feedback on how enthusiastic we are to adopt the suggested idea. In this case, the feature you've suggested is moderately appealing to the core team, and we would be happy to receive a PR for it, and help you with reviews and testing, or with how to get started if you are a new contributor. We would need to ensure that the polyfill is filling for a standard feature of the web platform, which we're not sure is the case here.

You can find out more about common contribution scenarios and how to make the perfect PR here:
https://polyfill.io/v2/docs/contributing/common-scenarios

If you need any further help before you submit your PR, feel free to reopen this issue!
