### ISSUE TITLE
ES2015 Map and Set complexities

### ISSUE THREAD

**Issue by thesnups** [polyfillpolyfill/polyfill-service#1355]
The polyfills for Map and Set implement insert, lookup, and delete in O(N) time. Has any consideration been given to supporting these operations in O(1) time by improving these implementations or using core-js?

**Comment by JSteunou** [comment]
Since the last [blocking bug into Map](#1299), I also asked myself why the hell going full re-write instead of using existing polyfill...

**Comment by JakeChampion** [comment]
@worsnupd If you know how to implement them in O(1) time, we are happy to accept a pull request

**Comment by JSteunou** [comment]
Hu?! Why the censorship? Is it forbidden to ask why you rewrite those polyfills instead of reusing existing one, like you do for a lot of others polyfills?

**Comment by JakeChampion** [comment]
We rewrite those polyfills as our versions can then depend upon the other polyfills in our service which in part makes the Map and Set polyfills smaller in size overall. The comment was removed as it doesn't aid in the conversation around this issue. Please make another issue for your discussion.

**Comment by thesnups** [comment]
@JakeChampion I will start working on this.

**Comment by JakeChampion** [comment]
Hi, thanks for raising this. We love to see people wanting to extend the polyfill service to accommodate new features. We don't keep feature request issues open without a PR, but we do provide feedback on how enthusiastic we are to adopt the suggested idea. In this case, the feature you've suggested is moderately appealing to the core team, and we would be happy to receive a PR for it, and help you with reviews and testing, or with how to get started if you are a new contributor. We would need to ensure that the polyfill is filling for a standard feature of the web platform, which we're not sure is the case here.

You can find out more about common contribution scenarios and how to make the perfect PR here:
https://polyfill.io/v2/docs/contributing/common-scenarios

If you need any further help before you submit your PR, feel free to reopen this issue!
