### ISSUE TITLE
ie11 - Object doesn't support property or method 'entries'

### ISSUE THREAD

**Issue by jwerardi** [polyfillpolyfill/polyfill-service#1356]
![image](https://user-images.githubusercontent.com/14876163/31345828-f9065724-ace4-11e7-927a-4f4ffecd861a.png)

This page uses a few es5/es6 array prototype, but really nothing crazy. I'm only having this issue on a single page, and I'm fairly certain this issue is new (but it's difficult to know for certain when this issue came up because only a few clients use ie11)

**Comment by JakeChampion** [comment]
<p>Hi @jwerardi , it looks like you've got an error in your website that you've tracked down to the code you're loading from the polyfill service. It would be really useful if you could follow these steps.</p>
<ol>
			<li>Create a test case using an online tool like <a href="https://jsbin.com">JSBin</a>, which loads <strong>only</strong> the polyfill service script, and then includes inline any code required to trigger the problem (which should be no more than a few lines).</li>
			<li>Raise a new issue on our issue tracker, and include:
			<ul>
				<li>A description of the problem (what you expected, what actually happened)</li>
				<li>A link to your test case on JSBin (or jsfiddle/codepen/whatever)</li>
				<li>The exact name and version number of the browser you're testing in</li>
				<li>If relevant, the console output or a screenshot of the problem</li>
			</ul></li>
		</ol><p>We ask for a JSBin demo because often these kinds of errors are actually errors in the host website's code, and even if they are a problem in the polyfill, we don't have the resources to debug your application.  Please also make sure you disable any browser plugins when you are testing in JSBin, so you are certain that you are only running the test code.</p>

**Comment by jwerardi** [comment]
Sure no problem! Makes sense, thanks for the timely response. I'll create a new issue after following your steps. 

Thanks for the product by the way, it's a real life saver.
