### ISSUE TITLE
classList polyfill doesn't apply to SVGElement in IE11

### ISSUE THREAD

**Issue by stsvilik** [polyfillpolyfill/polyfill-service#1358]
This applies to scenario when SVG is embedded directly into HTML and you want to use classList.add on one of its nodes.

**Comment by Garbanas** [comment]
This will be fixed by #1347

**Comment by stsvilik** [comment]
Just in case I missed something in this PR (I'm not 100% sure `SVGElement` inherits from `Element`), one issue I ran through when trying to polyfill this myself is that `SVGElement.className` is not a String like on regular `Element` its an Object, so I had to revert to reading classes from attribute instead. I guess what I'm saying is make sure you test it with real SVG nodes :)

**Comment by JakeChampion** [comment]
@stsvilik Thanks, we are aware of the difference between DOMTokenList support for Element and SVGElement, I haven't added SVGElement support yet, it will be added later before the PR is merged.

**Comment by JakeChampion** [comment]
This will be fixed via #1347 as it has SVG support now

**Comment by Rabadash8820** [comment]
I believe I am still experiencing this issue.  If I use any of the following URIs, then the classList polyfill is not downloaded for IE11, and I get errors when trying to work with `classList` on SVG elements.

- `https://cdn.polyfill.io/v2/polyfill.js?features=default&flags=gated`
- `https://cdn.polyfill.io/v2/polyfill.js?features=default,Element.prototype.classList&flags=gated`

The following URI _does_ download the polyfill, and has been my only workaround thus far.
- `https://cdn.polyfill.io/v2/polyfill.js?features=default,Element.prototype.classList|always&flags=gated`
