### ISSUE TITLE
Missing ParentNode interface polyfill

### ISSUE THREAD

**Issue by JSteunou** [polyfillpolyfill/polyfill-service#1391]
`Element`, `Document`, `DocumentFragment` inherit from `ParentNode` interface which provides convenient properties like `children`

methods & properties should be added in a `ParentNode` polyfill, thus `querySelector` and `append` / `prepend` polyfills should be moved.

Spec: https://dom.spec.whatwg.org/#interface-parentnode

**Comment by JakeChampion** [comment]
Hi, thanks for raising this. We love to see people wanting to extend the polyfill service to accommodate new features. We don't keep feature request issues open without a PR, but we do provide feedback on how enthusiastic we are to adopt the suggested idea. In this case, the feature you've suggested is moderately appealing to the core team, and we would be happy to receive a PR for it, and help you with reviews and testing, or with how to get started if you are a new contributor. We would need to ensure that the polyfill is filling for a standard feature of the web platform, which we're not sure is the case here.

You can find out more about common contribution scenarios and how to make the perfect PR here:
https://polyfill.io/v2/docs/contributing/common-scenarios

If you need any further help before you submit your PR, feel free to reopen this issue!

**Comment by JSteunou** [comment]
Incoming... meanwhile could you review my other PR please? Some get stuck on CI
