### ISSUE TITLE
Deployed version of Object.values is missing a semicolon

### ISSUE THREAD

**Issue by amannn** [polyfillpolyfill/polyfill-service#1392]
E.g. when using an URL like `https://cdn.polyfill.io/v2/polyfill.js?features=Object.values,Promise.prototype.finally` this currently throws an error, since `Object.values` is missing a trailing semicolon:

`Uncaught TypeError: (intermediate value)(...) is not a function`

I checked the [polyfill in the repository](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/values/polyfill.js#L12) and it looks like the semicolon is there.

Is it possible that the latest polyfills aren't deployed at cdn.polyfill.io? Or is something else causing the issue?

Tested with Safari Version 11.0.1 (12604.3.5.1.1) on macOS

[JS Bin reproduction](https://jsbin.com/vorihad/4/edit?html,output)

**Comment by JakeChampion** [comment]
That's correct, it is fixed in master and will be out in the next release which I am preparing for testing right now 👍

**Comment by amannn** [comment]
Alright, great – thanks for the quick response!
