### ISSUE TITLE
Object.defineProperty() being replaced in modern browsers with calls to deprecated methods that are sometimes undefined

### ISSUE THREAD

**Issue by mscalora** [polyfillpolyfill/polyfill-service#1399]
I have run into a compatibility issue on a third party site that is using your polyfill.js and our plug-in's use of Polymer/webcomponents-lite.

Specifically, your implementation of `Object.defineProperty()` fails to use the native function but overrides the behaviour to invoke `__defineGetter__()`  and `__defineSetter__()` methods for plain-old-js-objects (POJSOs) but not DOM, Element instances, etc.

It appears your implementation of Object.defineProperty() naively assumes POJSOs have a `__proto__` with `__defineGetter__()`  and `__defineSetter__()` Object methods. It fails when this is not the case when a POJSO does not inherit from Object as:

```var obj = Object.create(null, {});```

I don't know why Polymer/webcomponents-lite uses this type of POJSOs but they do in certain complex initialization cases and your `Object.defineProperty()` fails with `__defineGetter__()`  and `__defineSetter__()` undefined exceptions while the native Object.defineProperty() has no problems. Chrome and Firefox's native Object.defineProperty() works perfectly on this type of POJSO.

Firstly I find it odd that your polyfill replaces `Object.defineProperty()` in the very latest Chrome and Firefox browsers, are these implementations deficient in some respect? I see no support in the standard for the idea that `__defineGetter__()`  and `__defineSetter__()` `Object` methods should be preferred on POJSOs nor do I see any reason to unconditionally replace `Object.defineProperty()` with `__defineGetter__()`  and `__defineSetter__()` Object methods.

At the very least, when `object.__defineGetter__`  or `object.__defineSetter__` are undefined, the `Object.defineProperty()` should be used rather than inducing exceptions in latest versions of these evergreen browsers.

Mozilla documentation suggests that `__defineGetter__()`  and `__defineSetter__()` are deprecated but I didn't find explicit mention of that in the standards documents.  [MDN Wed Docs: __defineGetter__](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__)

I'm going to submit a pull request but given my inexperience in the world of polyfills and lack of understanding around the rational for some of the design and implementation decisions I'm somewhat unsure of the correct approach to resolve the issue I'm investigating.

Mike Scalora
Chief Architect - The World Table

Refs:

[ECMAScript 5.1 (ECMA-262)
The definition of 'Object.defineProperty' in that specification.](http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.3.6)
[ECMAScript 2015 (6th Edition, ECMA-262)
The definition of 'Object.defineProperty' in that specification.](http://www.ecma-international.org/ecma-262/6.0/#sec-object.defineproperty)
[ECMAScript Latest Draft (ECMA-262)
The definition of 'Object.defineProperty' in that specification.](https://tc39.github.io/ecma262/#sec-object.defineproperty)

**Comment by JakeChampion** [comment]
Hi, thanks for the issue, I would need some more information from you to help solve it.

Which browser and version was being used?
What is the exact polyfill.io url being loaded?

Could you be create a test case using an online tool like JSBin, which loads only the polyfill.io script, and then includes inline any code required to trigger the problem (which should be no more than a few lines preferably).

**Comment by mscalora** [comment]
> Which browser and version was being used? 

Verified incorrect behaviour: 

- Google Chrome 62.0.3202.94
- Firefox 57.0
- Version 11.0.1

>What is the exact polyfill.io url being loaded?

//cdn.polyfill.io/v2/polyfill.js?features=Array.prototype.includes,modernizr:es5array|always

>Could you be create a test case

JSBin: https://jsbin.com/bocegu/edit?html,output

My test page: https://test.worldtable.co/polyfill/polyfill-production-test.html with a working version using my patch: https://test.worldtable.co/polyfill/polyfill-patched-test.html

-Mike

**Comment by JakeChampion** [comment]
Thanks for the information.

The polyfill is being served because the url is explicitly asking to *always* serve the polyfill, regardless of the fact that a browser may not require it. When that is the case, we recommend also asking for the polyfills to be wrapped in feature detects. That can be done like so:
>//cdn.polyfill.io/v2/polyfill.js?features=Array.prototype.includes,modernizr:es5array|always|gated

I will update the tests and polyfill to fix the bug around objects having no prototypes not being able to use the `Object.defineProperty` method.

**Comment by JakeChampion** [comment]
This has been fixed via #1408
