### ISSUE TITLE
Mobile safari ui/wkwebview and Object.entries

### ISSUE THREAD

**Issue by gu-stav** [polyfillpolyfill/polyfill-service#1401]
At the guardian we noticed a very high number of errors thrown, because `Object.entries` seems to be not polyfilled for:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) AppleNews/608.0.1 Version/2.0.1
```

**Sentry data**

<img width="844" alt="screen shot 2017-11-27 at 12 02 31" src="https://user-images.githubusercontent.com/2244375/33265800-df5fe752-d36a-11e7-9705-a4e08abe7b2f.png">

I had a look at [UA.js](https://github.com/Financial-Times/polyfill-service/blob/master/lib/UA.js#L95) and found that `mobile safari ui/wkwebview` is actually interpreted as `ios_saf`. The `config.json` for `Object.entries` defines `"ios_saf": "*"`, so that means that also all instances of `webview` should be polyfilled, shouldn't it?

For some reason this doesn't happen in this case. Any ideas/ hints why and where we could have a look to find out?

**Comment by JakeChampion** [comment]
@gustavpursche Thanks for reporting the issue. You are correct that it would serve the polyfill if it detected the browser version correctly.

It looks like this might be an issue with our user-agent normalisation. The useragent module correctly detects the version as `Mobile Safari UI/WKWebView 2.0.1 / iOS 10.0.2`, we have a bug it seems where we are mapping it to `ios_saf/2.0.0`, which is a browser version we do not support and why it does not serve the polyfill.

A solution you can apply right now would be to include `&unknown=polyfill` onto the end of your polyfill.io request, that would tell the service to return polyfills for browsers which are unsupported or unknown.

**Comment by gu-stav** [comment]
@JakeChampion That sounds great, thank you! ❤️ 

Do you wan't me to open a new issue with a better description based on your comment, or should I leave this one open?

**Comment by JakeChampion** [comment]
You can leave this one open, I am looking into the issue now :-)

**Comment by JakeChampion** [comment]
@gustavpursche After some more digging it turns out this may be an issue inside the regex database that the useragent module is using. I have a PR to support AppleNews, if you have time to review that would be very helpful 👍  -- https://github.com/ua-parser/uap-core/pull/283/files

**Comment by awebdeveloper** [comment]
what about other webviews like facebook. does polyfill.io work for them

**Comment by JakeChampion** [comment]
Yes, we support facebook ios webview 👍

**Comment by JakeChampion** [comment]
This looks fixed in the new version of the service. Just incase it isn't working for you, that could be because you have not included Object.entries in the features query parameter.

Here is an example curl request which shows the user-agent string getting normalised to ios_saf/10:
```
➜  curl https://polyfill.io/v3/normalizeUa -H "user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) AppleNews/608.0.1 Version/2.0.1"
ios_saf/10.0.0
```
Here is a link to polyfill.io with the feature and the normalised user-agent:
https://polyfill.io/v3/polyfill.js?features=Object.entries&ua=ios_saf/10
