### ISSUE TITLE
Support Googlebot as a proper User Agent

### ISSUE THREAD

**Issue by alexlafroscia** [polyfillpolyfill/polyfill-service#1405]
I was just bitten by the fact that polyfill.io doesn't recognize Googlebot and, by default, sends it no polyfills. I was able to fix by adding `unknown=polyfill` to the URL, but didn't even realize that a missing polyfill was the issue because Googlebot fetch-and-render makes it hard to surface errors.

Is there a reason that Googlebot isn't handled by default? It's built on Chrome 41, so Polyfill.io should be capable of sending the polyfills it needs. Is there interest in handling Googlebot gracefully, or a specific reason it's ignored by default?

**Comment by JakeChampion** [comment]
Do you know what the user-agent strings are and if they update them when they update the version of Chrome being used by GoogleBot?

**Comment by alexlafroscia** [comment]
I don't know the user-agent string for Googlebot off the top of my head. They do have documentation on crawler user agents here, thougH:

https://support.google.com/webmasters/answer/1061943?hl=en

I believe that the UA does not reference the version of Chrome. My understanding is that there is work being done to get Googlebot running always using the latest Chrome release, but don't quote me on it 😅 

Here is the documentation on fetch-and-render, which references the fact that it's Chrome 41 under the hood right now:

https://developers.google.com/search/docs/guides/rendering

**Comment by HenrikJoreteg** [comment]
@JakeChampion I just tried tacking on `&ua=chrome/41` to the query string and Googlebot works great. I wonder if perhaps aliasing any user agent containing `Googlebot` to chrome 41 would be sufficient. 

I'd much rather load too many polyfills than not enough. Not loading polyfills for Googlebot is quite a bug for anyone expecting google to crawl their JS rendered content.

As a temporary stopgap it seems worth addressing even if rather bluntly :)

**Comment by JakeChampion** [comment]
The PR for this work is https://github.com/Financial-Times/polyfill-service/pull/1433

**Comment by TehShrike** [comment]
I switched to qa.polyfill.io and my site started rendering to googlebot! 👍

**Comment by JakeChampion** [comment]
It will be promoted to production tomorrow :-)

**Comment by alexlafroscia** [comment]
I'm so glad this landed, thanks for taking this on @JakeChampion! Hopefully this change helps prevent anyone else from having to go through what I did to debug the issues with Googlebot.
