### ISSUE TITLE
devicePixelRatio polyfill always enabled in iOS

### ISSUE THREAD

**Issue by thebuilder** [polyfillpolyfill/polyfill-service#1406]
Couldn't figure out why all my images when rendering at low res on iOS - turns out that including the `devicePixelRatio` detection, causes the devicePixelRatio to be set to `1` on iOS devices. It includes the polyfill, which overrides the actual `devicePixelRatio`.
https://cdn.polyfill.io/v2/polyfill.js?features=devicePixelRatio

**iPhone 8 - iOS11**
![iPhone 8 - iOS 11](https://user-images.githubusercontent.com/3764345/33431227-c4d890e4-d5d3-11e7-8154-7da49819d6d9.jpeg)

**Chrome Dev Tools**
![Chrome Dev tools](https://user-images.githubusercontent.com/3764345/33431290-f7531882-d5d3-11e7-87c4-b6f3094b7d38.png)

**Comment by JakeChampion** [comment]
Thanks for reporting this. PR for this work https://github.com/Financial-Times/polyfill-service/pull/1407
