### ISSUE TITLE
Map and Set method iterators are empty

### ISSUE THREAD

**Issue by bisubus** [polyfillpolyfill/polyfill-service#1409]
Iterators for `keys`, `values` and `entries` were introduced #1385, but they are empty.

A [demo](http://plnkr.co/edit/v84HDg3gWOzrfJJsGNyL?p=preview):

```
var map = new Map();
map.set('foo', 'bar');
console.log(
  [...map].length === 1, // true
  [...map.entries()].length === 1,  // false
);
```

This results from the fact that `Symbol.iterator` methods are not bound:
```
	Map.prototype['keys'] = function() {
		var iterator = makeIterator(this, function(i) { return decodeVal(this._values[i]); });
		iterator[Symbol.iterator] = this.keys;
		return iterator;
	};
```

They are expected to work properly with:
```
	Map.prototype['keys'] = function() {
		var iterator = makeIterator(this, function(i) { return decodeVal(this._values[i]); });
		iterator[Symbol.iterator] = this.keys.bind(this);
		return iterator;
	};
```

The issue appeared in v3.23.0 and persists in v3.24.0-0

**Comment by JSteunou** [comment]
maybe related to #1390 ?

**Comment by bisubus** [comment]
@JSteunou It looks like it isn't because linked issue is specific to Array.from and is solved by proper polyfill order http://plnkr.co/edit/dDMlzFS6tiEeevyVsxwS , as explained in https://github.com/Financial-Times/polyfill-service/issues/1390#issuecomment-346025532 . But thanks for the notification, that's the important one.

**Comment by JakeChampion** [comment]
This should be resolved via https://github.com/Financial-Times/polyfill-service/pull/1411.

Feel free to re-open this issue if that is not the case.

**Comment by bisubus** [comment]
It looks like it's both #1411 and #1413. I guess the issue will be solved once they are merged.
