### ISSUE TITLE
Object.values not a function on IOS Safari v10

### ISSUE THREAD

**Issue by testerez** [polyfillpolyfill/polyfill-service#1415]
Polyfill `Object.values` is not served in browser IOS Safari 10 (and it should be)

User agent:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0 Mobile/14C92 Safari/602.1
```

Strange because it seems to be well detected: https://cdn.polyfill.io/v2/polyfill.js?ua={Mozilla/5.0%20(iPhone;%20CPU%20iPhone%20OS%2010_2%20like%20Mac%20OS%20X)%20AppleWebKit/602.3.12%20(KHTML,%20like%20Gecko)%20Version/10.0%20Mobile/14C92%20Safari/602.1}

And well configured: https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/values/config.json#L11

**Comment by JakeChampion** [comment]
Hi @testerez, when making a request to https://cdn.polyfill.io/v2/polyfill.js without declaring specific features to polyfill, we will serve a default set of polyfills. The default set does not contain `Object.values`, if you want to include `Object.values` alongside the default set you can add the query parameter `features=default,Object.values` to the polyfill.io url.

Here is an example of serving only the `Object.values` polyfill and forcing the polyfill service to target iOS safari 10.

https://cdn.polyfill.io/v2/polyfill.js?features=Object.values&ua=%7BMozilla/5.0%20(iPhone;%20CPU%20iPhone%20OS%2010_2%20like%20Mac%20OS%20X)%20AppleWebKit/602.3.12%20(KHTML,%20like%20Gecko)%20Version/10.0%20Mobile/14C92%20Safari/602.1%7D

**Comment by testerez** [comment]
Oh makes sense thanks!
I'm just curious to know how you decide what's part or the default polyfills or not.

**Comment by JakeChampion** [comment]
@testerez This issue should hopefully explain how it is decided what goes into the default set -- https://github.com/Financial-Times/polyfill-service/issues/1203

**Comment by testerez** [comment]
Thanks for the link. I feel like `Object.values` kind of matches the criterias to be part of the default polyfills:

- It's very small: https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/values/polyfill.js
- It's supported by all major browsers except IE: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values
- I can't say if the demand is very high. At least there is me :)

**Comment by AlexLaforge** [comment]
`.values` is unsupported in many browsers - you can use .map to get an array of all the values:
```
var vals = Object.keys(countries).map(function(key) {
    return countries[key];
});
```

See MDN doc: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values or Official doc: https://tc39.github.io/ecma262/#sec-object.values

**Comment by testerez** [comment]
@AlexLaforge support for `.value` is no so bad:

<img width="1056" alt="screen shot 2018-07-05 at 8 02 21 am" src="https://user-images.githubusercontent.com/815236/42322292-de8ab746-8029-11e8-86ed-5d74a0e22545.png">

And yes it's easy to replace with `Object.keys(o).map(...)` but it also means that it's pretty easy to polyfill...
