### ISSUE TITLE
polyfill.min.js should pass sonarwhal check

### ISSUE THREAD

**Issue by willfarrell** [polyfillpolyfill/polyfill-service#1416]
Was running a sonarwhal.com scan on my site and found this:

```bash
https://cdn.polyfill.io/v2/polyfill.min.js
line 1  col 1771  Error  'content-type' header should have media type 'text/javascript' (not 'application/javascript')  content-type
line 1  col 1771  Error  'server' header is disallowed                                                                  no-disallowed-headers
line 1  col 1771  Error  'x-frame-options', 'x-xss-protection' headers are not needed                                   no-html-only-headers
✖ Found 3 errors and 0 warnings
```

Not the end of the world, but thought I'd bring it up. Reducing the header bloat will lead to some saving all around.

Docs:
- [content-type](https://sonarwhal.com/docs/user-guide/rules/content-type/)
- [no-disallowed-headers](https://sonarwhal.com/docs/user-guide/rules/no-disallowed-headers/)
- [no-html-only-headers](https://sonarwhal.com/docs/user-guide/rules/no-html-only-headers/)

**Comment by JakeChampion** [comment]
These are now all fixed, thanks for the report
