### ISSUE TITLE
Feature request: SVG polyfills

### ISSUE THREAD

**Issue by devuxer** [polyfillpolyfill/polyfill-service#1417]
I recently came across a key SVG feature that is not supported in IE or Edge: [dominant-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline). Any possibility that this and similar omissions relating to SVGs could be considered for a future version of polyfill.io?

**Comment by JakeChampion** [comment]
I've done some reading on this attribute and I'm not sure if it is even possible to polyfill the dominant-baseline svg attribute. If you know of a way to polyfill it or know of an already existing polyfill for it, we can definitely add it to the service.
