### ISSUE TITLE
Array.prototype.includes is not being served to safari 6.2.0 but config indicates it should be

### ISSUE THREAD

**Issue by kernow** [polyfillpolyfill/polyfill-service#1422]
I've tested on browser stack using safari 6.2.8, the browser version is correctly detected but `Array.prototype.includes` is not served. https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array/prototype/includes/config.json indicates it should be served to anything lower than version 9 of safari.

Here is a copy of what is served via https://cdn.polyfill.io/v2/polyfill.js on browser stack.

![bs_macml_safari_6 2](https://user-images.githubusercontent.com/3025/33950620-c91cad1a-e024-11e7-900e-dd22edd48ad4.jpg)

Thanks

**Comment by JakeChampion** [comment]
Hi @kernow, thanks for taking the time to create an issue for this. Array.prototype.includes is not included in the default set of polyfills that are sent for the request https://cdn.polyfill.io/v2/polyfill.js. You can see what is in the default set of polyfills by looking on this page, they are labelled with a star symbol - https://polyfill.io/v2/docs/features/

If you are wanting features which are not in the default set of polyfills, you can add a query parameter to the url which specifies which you are wanting. Here is how to request the default set of polyfills and Array.prototype.includes - https://cdn.polyfill.io/v2/polyfill.js?features=default,Array.prototype.includes
