### ISSUE TITLE
Object.assign is not served in QQ Browser

### ISSUE THREAD

**Issue by testerez** [polyfillpolyfill/polyfill-service#1431]
Polyfill `Object.assign` is not served in QQ Browser Version: 9.0.2524 (and it should be)

https://cdn.polyfill.io/v2/polyfill.js?features=Object.assign&ua=Mozilla/5.0%20(Windows%20NT%206.1;%20WOW64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/39.0.2171.95%20Safari/537.36%20MicroMessenger/6.5.2.501%20NetType/WIFI%20WindowsWechat%20QBCore/3.43.691.400%20QQBrowser/9.0.2524.400

User-agent:
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat QBCore/3.43.691.400 QQBrowser/9.0.2524.400
```

First time I ear about this browser! But we have users using it...

**Comment by njbotkin** [comment]
Seeing that this is the first time QQ Browser has been mentioned in this repo, I don't expect it will be worthwhile to add support for that specific browser.  

To get past this, you could set the `unknown` flag to `polyfill`, like so: 

https://cdn.polyfill.io/v2/polyfill.js?features=Object.assign&ua=Mozilla/5.0%20(Windows%20NT%206.1;%20WOW64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/39.0.2171.95%20Safari/537.36%20MicroMessenger/6.5.2.501%20NetType/WIFI%20WindowsWechat%20QBCore/3.43.691.400%20QQBrowser/9.0.2524.400&unknown=polyfill

Check out what https://polyfill.io/v2/docs/api has to say about it:

>Use caution when setting this argument to 'polyfill' on large feature sets, since huge polyfill bundles may cause crashes or lockups in extremely old or underpowered user agents.

**Comment by JakeChampion** [comment]
Thanks for the report. This is now fixed and works by default in polyfill.io/v3 

https://cdn.polyfill.io/v3/polyfill.js?features=Object.assign&ua=Mozilla/5.0%20(Windows%20NT%206.1;%20WOW64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/39.0.2171.95%20Safari/537.36%20MicroMessenger/6.5.2.501%20NetType/WIFI%20WindowsWechat%20QBCore/3.43.691.400%20QQBrowser/9.0.2524.400
