### ISSUE TITLE
Warn me if feature is used but not pollyfilled

### ISSUE THREAD

**Issue by plexigras** [polyfillpolyfill/polyfill-service#1435]
While developing you might not notice that you are missing a polyfill and getting a warning or an error message could save a lot of hassle.

It could be as simple as having something like this:

```js
Array.prototype.fill = function() { throw Error("Add Array.prototype.fill to polyfills!") }
...
```

**Comment by JakeChampion** [comment]
We do not know when a site is being developed and when it is not, which means we would not know when to replace methods with errors. I don't think this is a feature we would likely support. I'm going to close the issue for now, feel free to add comments to it if you think this can be implemented in a way that would be simple to understand.

**Comment by plexigras** [comment]
you could have a url query option?
