### ISSUE TITLE
HTMLCanvasElement.toBlob is not served in Microsoft Edge 14.14393 & 15.15063

### ISSUE THREAD

**Issue by Francismb** [polyfillpolyfill/polyfill-service#1437]
The polyfill HTMLCanvasElement.toBlob is not served in Microsoft Edge 14.14393 & 15.15063 when it should be.

**Comment by amarinov** [comment]
It isn't served for Edge 16.16299 too. The documentation is wrong stating that it's natively supported in Edge 15.
User Agent string:

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by JakeChampion** [comment]
This has been fixed in master and will go out in the next release. Thanks @amarinov for the pull-request 👍
