### ISSUE TITLE
Object.entries is not served in Chrome 49.0.2623.75

### ISSUE THREAD

**Issue by Francismb** [polyfillpolyfill/polyfill-service#1593]
The polyfill Object.entries is not served in Chrome 49.0.2623.75 when it should be.

**Comment by SpadeAceman** [comment]
See my answer on #1599 - include `es2017` among your requested features.

**Comment by JakeChampion** [comment]
@SpadeAceman That's correct, you can explicitly request `Object.entries` or use the alias `es2017`.

**Comment by JakeChampion** [comment]
@frazboyz We serve Object.entries to all chrome versions older than version 54. --> https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/entries/config.json#L8
