### ISSUE TITLE
IE11 Error: Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by tolgabalci** [polyfillpolyfill/polyfill-service#1595]
After the update today:
* Polyfill v3.25.0 loads and breaks in IE 11

When using:
https://cdn.polyfill.io/v2/polyfill.js?features=default,Array.prototype.includes,Array.prototype.find,Array.prototype.findIndex,Object.values

Getting error (and page fails to load properly):
`Assignment to read-only properties is not allowed in strict mode` in the below code on line `Object.assign = require('object-assign');`

`// @remove-on-eject-begin
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
// @remove-on-eject-end
'use strict';

if (typeof Promise === 'undefined') {
  // Rejection tracking prevents a common issue where React gets into an
  // inconsistent state due to an error, but it gets swallowed by a Promise,
  // and the user has no idea what causes React's erratic future behavior.
  require('promise/lib/rejection-tracking').enable();
  window.Promise = require('promise/lib/es6-extensions.js');
}

// fetch() polyfill for making API calls.
require('whatwg-fetch');

// Object.assign() is commonly used with React.
// It will use the native implementation if it's present and isn't buggy.
Object.assign = require('object-assign');

//////////////////
// WEBPACK FOOTER
// ./node_modules/react-scripts/config/polyfills.js
// module id = 392
// module chunks = 0`

**Comment by bthibault** [comment]
Also breaks earlier versions of chome at least to 38. 

This is major issue for me.

**Comment by gavinlove** [comment]
We are seeing the exact same problem. Lots of complaints from IE11 users

**Comment by bthibault** [comment]
In retrospect we should not be using a library in production that auto-updates with no way to specify a version

**Comment by gavinlove** [comment]
@bthibault This is exactly what I have decided today. Setting up a server it so I can roll back to the previous version

**Comment by JakeChampion** [comment]
This is now live in production on https://polyfill.io.
