### ISSUE TITLE
IE11 broke

### ISSUE THREAD

**Issue by kohesion** [polyfillpolyfill/polyfill-service#1596]
![image](https://user-images.githubusercontent.com/1246027/34899476-225fa80a-f7c7-11e7-8a8e-84a8c5197152.png)

**Comment by LOK-Soft** [comment]
can you estimate when the committed fix for this issue will be on production?
Thanks :)

**Comment by JakeChampion** [comment]
Middle of next week 👍

**Comment by AchimKre** [comment]
Is there a workaround for this? Because this breaks our page completely down in IE 11.

**Comment by kohesion** [comment]
Just download the file in IE11 and wrap the problem bit in a try catch block

**Comment by JakeChampion** [comment]
@AchimKre Yes, if you add `&excludes=Object.assign` to the end of your polyfill.io script url, that will fix the issue.

**Comment by AchimKre** [comment]
@JakeChampion Thx for your hint, but it does not work for us. It seems an other polyfill needs Object.assign and only excludes=Object.assign runs into an other javascript error.

We added the polyfill Object.assign polyfill from [1] inline before include https://cdn.polyfill.io/v2/polyfill.min.js?excludes=Object.assign

That seems to work.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by JakeChampion** [comment]
Hi @kohesion, @LOK-Soft, @AchimKre, @Turbo87, @tolgabalci, @bthibault, @gavinlove. If you could please test out https://qa.polyfill.io, it contains the fix, once proven to work I can put it into production.

**Comment by JakeChampion** [comment]
This is now live in production on https://polyfill.io.

**Comment by AchimKre** [comment]
It works. Thank you!
