### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by olehreznichenko** [polyfillpolyfill/polyfill-service#1597]
![image](https://user-images.githubusercontent.com/11960153/34904629-53448950-f852-11e7-89ac-5b02ec13ea79.png)

Failed install on step when clean `./polyfills/__dist` folder on Windows

**Comment by JakeChampion** [comment]
I'm sorry to say I do not have a windows machine on hand to fix this or to check if it has already been fixed. We don't officially support running the service on windows.
