### ISSUE TITLE
Zlib and Package.json issues on NPM

### ISSUE THREAD

**Issue by ecjs** [polyfillpolyfill/polyfill-service#1600]
I am experiencing something a bit odd with the current version of this package on NPM.  The version says its 3.25.1,  but the dependencies in Package.json are still the same from previous versions.

In particular, I am having issues with the zlib dependency, which continues to be included as a dependency even in the latest version on NPM.

Thanks to anyone who can help me out with this strange issue.

**Comment by kindlerm** [comment]
Just to mention it: we have the same problem. Install (of 3.25.1 and 3.25.0) only worked after manually removing the zlib dependency. Please correct this issue!

**Comment by JakeChampion** [comment]
This has been fixed in the recent releases of the service, please try them out 👍
