### ISSUE TITLE
Polyfill Array.prototype.includes is not served in Chrome 37 - but config says it should

### ISSUE THREAD

**Issue by philmbst** [polyfillpolyfill/polyfill-service#1678]
Hi!

I have read through https://polyfill.io/v2/docs/contributing/common-scenarios and it seems like the Array.prototype.includes config is correct and should be served in chrome 37 - but it doesn't actually appear.

Here's what is being served:

<img width="1431" alt="screen shot 2018-02-28 at 15 15 26" src="https://user-images.githubusercontent.com/17127379/36795195-47c6ba8c-1c9a-11e8-84ca-3ffde94bcd3f.png">

Thanks!

**Comment by JakeChampion** [comment]
This is because Array.prototype.includes is not in the default set, you would need to have this url for it to work:
https://cdn.polyfill.io/v3/polyfill.js?features=default,Array.prototype.includes
