### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [polyfillpolyfill/polyfill-service#1680]
The polyfill.io website is inaccessible over IPv6.

**Comment by JakeChampion** [comment]
Hi @tambry, I believe we have IPv6 support for https://cdn.polyfill.io. It looks like we don't have it for https://polyfill.io, I will see if this is possible for us to support :-)

**Comment by JakeChampion** [comment]
IPv6 added to https://polyfill.io :-)

**Comment by tambry** [comment]
Thank you very much!
