### ISSUE TITLE
Weird feature request: force polyfill in certain browsers

### ISSUE THREAD

**Issue by TehShrike** [polyfillpolyfill/polyfill-service#1682]
My case: I'm using IntersectionObserver, and it's great in Firefox, and the polyfill works great in all the other browsers.

Chrome's IntersectionObserver implementation is really bad, though.  Wildly inaccurate, not very usable for my purposes.

So: I want to be able to use polyfill.io in such a way that the polyfill will be loaded normally in all browsers, but always loaded in Chrome.

I have no idea how common this use case is.  I couldn't find an existing issue, so I'm making this one.  I understand that it's probably a stretch to expect it to be implemented.

**Comment by ChristianSiegert** [comment]
As a workaround, you can check if your code is running in Chrome and then delete IntersectionObserver so [the polyfill](https://polyfill.io/v2/polyfill.js?features=IntersectionObserver&flags=always,gated) kicks in:

```javascript
delete window.IntersectionObserver;
delete window.IntersectionObserverEntry;
```

**Comment by TehShrike** [comment]
That wouldn't work with the polyfill service because it would use user-agent detection to determine that the polyfill didn't need to be shipped to the browser.

**Comment by ChristianSiegert** [comment]
You can ask the polyfill service to always send the polyfill, independent of whether the browser already supports the feature, by appending the flag `|always` to the feature. If you also append the flag `|gated`, the polyfill will not overwrite existing browser implementations.

[The docs about the `|always` flag:](https://polyfill.io/v2/docs/api)
> Polyfill should be included regardless of whether it is required by the user-agent making the request.

Open the polyfill in Chrome (no flags; you will see no polyfill):
https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver

Open this polyfill again in Chrome (with flags, you will see the polyfill):
https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver|always|gated

**Comment by TehShrike** [comment]
Right, but I don't want to download the polyfill in browsers like Firefox where the native version works just fine.

Check the issue title - this is a very specific feature request to force a polyfill to be included in a specific browser where it normally wouldn't be included.

**Comment by rlightner** [comment]
It won't overwrite the built in implementation unless you delete it.

**Comment by rlightner** [comment]
`https://polyfill.io/v2/polyfill.js?features=IntersectionObserver&flags=always,gated` includes:

```javascript
// Exits early if all IntersectionObserver and IntersectionObserverEntry
    // features are natively supported.
    if ('IntersectionObserver' in window &&
        'IntersectionObserverEntry' in window &&
        'intersectionRatio' in window.IntersectionObserverEntry.prototype) {
      return;
    }
```

**Comment by TehShrike** [comment]
Yes - but only because you included the `gated` flag in the parameters.

**Comment by TehShrike** [comment]
(For what it's worth, this has nothing to do with my original request)

**Comment by rlightner** [comment]
without gated, it produces the same thing:
```javascript
// Exits early if all IntersectionObserver and IntersectionObserverEntry
// features are natively supported.
if ('IntersectionObserver' in window &&
    'IntersectionObserverEntry' in window &&
    'intersectionRatio' in window.IntersectionObserverEntry.prototype) {
  return;
}
```
Your original question was about forcing it on chrome. Which as @ChristianSiegert pointed out would work if you deleted it in chrome before the polyfill loaded. It's not the best implementation though.

Let's hope the 'powers that be' see a feature request out of this thread.

**Comment by TehShrike** [comment]
Huh, I wonder if that's a bug, or if the documentation is wrong.

Sure, I would have no problem manually deleting the original implementation in Chrome.

All that this feature request is requesting is the ability to say "`always` ship the polyfill in Chrome, but default behavior for the other browsers."  Nothing about gating behavior.

**Comment by chee** [comment]
you could user agent sniff before loading the script, and use `|always`
without `|gated` on that version of Chrome.

and use the non-always URL for everyone else.

**Comment by JakeChampion** [comment]
I don't think we would be interested in adding a feature to enable users to configure a polyfill to always load in specific browsers.

If a browser has a buggy implementation of a feature, we should update our polyfill configuration to send a polyfill to that browser.

If you could open an issue on https://github.com/Financial-Times/polyfill-library with the bugs you have found in IntersectionObserver for Chrome, I will happily write tests for those and have the polyfill get served to those specific versions of Chrome :-)
