### ISSUE TITLE
FR: please support Google Apps Script environment

### ISSUE THREAD

**Issue by salamanders** [polyfillpolyfill/polyfill-service#1683]
Google Apps Script says it ["is based on JavaScript 1.6, plus a few features from 1.7 and 1.8"](https://developers.google.com/apps-script/guides/services/#basic_javascript_features)

Which isn't very clear, and it would be excellent if polyfill-service could provide a fill that brings it up to ECMAScript 2016.  (or even v8)

**Comment by JakeChampion** [comment]
We won't be looking to support Google Apps Script directly as we have no way of automatically running our tests in that environment. Perhaps you could look into using https://github.com/zloirock/core-js/ instead?

If you know of a way for us to automatically test in Google Apps Script, comment on this issue and I will look into it.
