### ISSUE TITLE
Implement NodeList.prototype.forEach

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#1686]
Currently polyfill.io only polyfills Node.prototype[Symbol.iterator] and no other iterating methods for NodeLists.

Docs -- https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Comment by helloncanella** [comment]
+1

**Comment by amarinov** [comment]
Hey @JakeChampion ! Is there any progress on this?

**Comment by JakeChampion** [comment]
This polyfill was added in #1686 👍

**Comment by chee** [comment]
@JakeChampion this _is_ #1686

**Comment by cferdinandi** [comment]
I am unable to make it actually load, and it's not listed in the features list at polyfill.io. Am I missing something?

**Comment by loilo** [comment]
Well, the latest release of `polyfill-service` is [from January](https://github.com/Financial-Times/polyfill-service/releases), while the feature has been implemented in April.

**Comment by cferdinandi** [comment]
Ah... forgive me. I have no idea how this all works under the hood, and the docs don't make it particularly clear.

Do you/does anyone know when the next `polyfill-service` release will be?

**Comment by loilo** [comment]
I have no idea.

And to be honest, I had to first scan `require('polyfill-service').listAllPolyfills()` as well before I came up with the releases idea. 😉 Doesn't intuitively come to mind that there may be no releases in such a relatively long time.

But maybe @JakeChampion knows if/when releases are planned?

**Comment by ilanbm** [comment]
Any update on that? is it going to be released soon?

**Comment by loilo** [comment]
To alert subscribers here as well (sorry for spamming you, maintainers): [This feature is now available.](https://github.com/Financial-Times/polyfill-service/issues/1233#issuecomment-454339999)
