### ISSUE TITLE
Blob polyfill is not mentioned at the polyfill.io website

### ISSUE THREAD

**Issue by starkwang** [polyfillpolyfill/polyfill-service#1689]
Blob polyfill has been added in https://github.com/Financial-Times/polyfill-service/pull/1443, but the docs on the website doesn't mention it: https://polyfill.io/v2/docs/features/

**Comment by JakeChampion** [comment]
This is because version 3.26 has yet to be released. We announce releases via [Twitter](https://twitter.com/polyfillio) as well on [GitHub](https://github.com/Financial-Times/polyfill-service/releases).
