### ISSUE TITLE
Document.getElementsByClassName

### ISSUE THREAD

**Issue by monolithed** [polyfillpolyfill/polyfill-service#169]
I could not find the one. 
Are there any plans to implement it?

**Comment by triblondon** [comment]
Feature already has broad support except in IE, where support starts at 9. @wheresrhys could you consider adding this since you raised it as #444?

**Comment by triblondon** [comment]
@wheresrhys do you still want this?

**Comment by wheresrhys** [comment]
The 'live node list' requirement sounds tricky. I have no requirement for
this any more, so don't keep open on my account

On Friday, 18 March 2016, Andrew Betts notifications@github.com wrote:

> @wheresrhys https://github.com/wheresrhys do you still want this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Financial-Times/polyfill-service/issues/169#issuecomment-198256407

## 

---

_This email was sent by a company owned by Financial Times Group Limited 
("FT Group http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law._

**Comment by triblondon** [comment]
Existing polyfills appear to leverage queryselector, so I guess we can do that too.
