### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by harryy2510** [polyfillpolyfill/polyfill-service#1690]
On chrome browser 39.0.2171.0, with angular 5.2.9, it throws error `undefined is not a function`

**Comment by JakeChampion** [comment]
Hi @harryy2510, thanks for the issue.

I need some more information before I can start helping with this.

- The exact name and version number of the browser you're testing in.
- A test case using an online tool like JSBin, which loads only the polyfill.io script, and then includes inline any code required to trigger the problem (which should be no more than a few lines hopefully).

**Comment by JakeChampion** [comment]
Closing due to lack of information from the original author
