### ISSUE TITLE
polyfill.min.js:1 Uncaught TypeError: Illegal constructor

### ISSUE THREAD

**Issue by m-saifuddin** [polyfillpolyfill/polyfill-service#1692]
Encounter this issue which is not clear why polyfill prompting this error...

Any help would be appreciated. 

> polyfill.min.js:1 Uncaught TypeError: Illegal constructor
>     at SVGGElement.classList (polyfill.min.js:1)
>     at Array.<anonymous> (d3.v3.js:719)
>     at SVGGElement.classedFunction (d3.v3.js:712)
>     at d3.v3.js:1028
>     at d3_selection_each (d3.v3.js:1034)
>     at Array.d3_selectionPrototype.each (d3.v3.js:1027)
>     at Array.d3_selectionPrototype.classed (d3.v3.js:698)
>     at SVGGElement.<anonymous> (nv.d3.js:5041)
>     at d3.v3.js:1028
>     at d3_selection_each (d3.v3.js:1034)

**Comment by JakeChampion** [comment]
Hi, thanks for the issue.

I need some more information before I can start helping with this.

- The exact name and version number of the browser you're testing in.
- A test case using an online tool like [JSBin](https://www.jsbin.com), which loads only the polyfill.io  script, and then includes inline any code required to trigger the problem (which should be no more than a few lines _hopefully_).

**Comment by JakeChampion** [comment]
Closing based on lack of information to reproduce the issue
