### ISSUE TITLE
Cert expiration for [cdn.]polyfill.io in less than 30 days

### ISSUE THREAD

**Issue by asilvas** [polyfillpolyfill/polyfill-service#1696]
I'm sure you have a process in place to rotate, but just in case wanted to note the expiration due to the severity if it were to lapse. I'm accustom to more aggressive rotations so playing it safe... Cheers

**Comment by JakeChampion** [comment]
@asilvas Thanks for opening the issue. We will be rotating the certificate before the expiration date. This is likely to happen sometime next week.

**Comment by asilvas** [comment]
You guys are brave with less than a week before expiration.
