### ISSUE TITLE
The polyfill of Object.defineProperty doesn't work with React

### ISSUE THREAD

**Issue by starkwang** [polyfillpolyfill/polyfill-service#1700]
There are many common scenarios for raising issues against the polyfill service.  Is your issue one of these?

* Polyfill X doesn't work properly

Code to reproduce (just load polyfills, `react` and `react-dom`):

```html
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=Map,Set&unknown=polyfill&ua=abcd"></script>
<script src="https://cdn.bootcss.com/react/16.3.1/umd/react.development.js"></script>
<script src="https://cdn.bootcss.com/react-dom/16.3.1/umd/react-dom.development.js"></script>
```

And then the `react-dom` throws error:

```text
Uncaught TypeError: Cannot set property isMounted of [object Object] which has only a getter
    at assign (<anonymous>)
    at react.development.js:558
    at getOwnPropertySymbols (react.development.js:15)
    at react.development.js:16
    (anonymous) @ react.development.js:558
    getOwnPropertySymbols @ react.development.js:15
    (anonymous) @ react.development.js:16
Uncaught Error: ReactDOM was loaded before React. Make sure you load the React package before loading ReactDOM.
    at invariant (react-dom.development.js:66)
    at react-dom.development.js:79
    at validateFormat (react-dom.development.js:15)
    at react-dom.development.js:16
```

This may be caused by this line:

https://github.com/Financial-Times/polyfill-service/blob/bb5b0ee8975215a313847acbae421b5b1543976a/packages/polyfill-library/polyfills/Object/defineProperty/polyfill.js#L11-L13

This error is resolved after I changed it into:

```js
if (nativeDefineProperty) {
    return nativeDefineProperty(object, property, descriptor);
}
```

**Comment by JakeChampion** [comment]
Hi @starkwang, I believe this issue has been fixed some time ago, I forgot to close the ticket, sorry.

Lots of website that use polyfill.io are using react and not coming across this issue now.
