### ISSUE TITLE
bug: local polyfill sources are not used

### ISSUE THREAD

**Issue by aaarichter** [polyfillpolyfill/polyfill-service#1714]
https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-service/service/routes/api.js#L6
and
https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-service/service/routes/test.js#L6
are not initialized with the https://github.com/Financial-Times/polyfill-service/tree/master/packages/polyfill-library/polyfills `__dist` folder.

Instead the `polyfill-library` plugin falls back to some internal node_modules polyfill path.

This makes debugging and updating polyfills in this module useless. 😿

**Comment by JakeChampion** [comment]
This has since been fixed :-)
