### ISSUE TITLE
Release new npm packages to avoid 'The engine "node" is incompatible with this module.'

### ISSUE THREAD

**Issue by SebastianS90** [polyfillpolyfill/polyfill-service#1716]
Please update the [polyfill-library](https://www.npmjs.com/package/polyfill-library) package on npm. The latest version `3.26.2-1` there has
```json
"engines": {
    "node": "6.11.1 - 9"
  }
```

Yarn therefore does not install it with node 10:
```
error polyfill-library@3.26.2-1: The engine "node" is incompatible with this module. Expected version "6.11.1 - 9"
```

You have already [fixed](https://github.com/Financial-Times/polyfill-service/commit/b009b364620420fa70b088d9c4927f8959d10430#diff-d3a4d0e3a2b26bc7bdf9e9a9aca2e3d3L40) that entry as part of #1706, but it is not yet published on npm.

Thanks!

For others landing here via search: Use the `--ignore-engines` flag in yarn as temporary workaround.

**Comment by SebastianS90** [comment]
The same problem occurs when installing `polyfill-service`:

```
$ yarn add polyfill-service
yarn add v1.6.0
error polyfill-service@3.25.1: The engine "node" is incompatible with this module. Expected version "6.11.1 - 9".
error Found incompatible module
```

**Comment by DeTeam** [comment]
@JakeChampion could you or someone else please publish a new version?

**Comment by DeTeam** [comment]
Sorry to bother, @triblondon — is it possible that someone of maintainers take care of this issue? :)

**Comment by triblondon** [comment]
I'm afraid I don't work at the FT anymore and haven't managed to stay involved with the project.  I believe Jake is still the primary maintainer.

**Comment by jdachtera** [comment]
@JakeChampion any chance to get this resolved?

**Comment by gwardwell** [comment]
@JakeChampion The project I'm working on needs to move to node 10 LTS. Can we get this fixed, please?

**Comment by JakeChampion** [comment]
This is fixed 👍
