### ISSUE TITLE
Support headless chrome

### ISSUE THREAD

**Issue by Janpot** [polyfillpolyfill/polyfill-service#1725]
The polyfill service doesn't support headless chrome. It should be straightforward to add though. 
The headless UA is:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/66.0.3347.0 Safari/537.36
=> UA detected: headlesschrome/0.0.0 (unknown/unsupported; using policy `unknown=ignore`)
```
While the regular UA is:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/66.0.3347.0 Safari/537.36
=> UA detected: chrome/66.0.0
```
The only difference between the two is `HeadlessChrome/` vs. `Chrome/`. From the polyfill perspective, there shouldn't be any difference between the two.

Related https://github.com/GoogleChrome/puppeteer/issues/2571
<hr>
P.S. regarding your issue template, this link in your docs seems to be broken:
<img width="882" alt="screen shot 2018-05-31 at 12 44 54" src="https://user-images.githubusercontent.com/2109932/40778167-88621d06-64d0-11e8-8936-38b8ad0a990a.png">

**Comment by castilloandres** [comment]
Hello,

Just made this PR for this issue https://github.com/Financial-Times/polyfill-service/pull/1726

**Comment by Janpot** [comment]
@JakeChampion One issue is the missing UA detection.
But there's also the strange behavior of the `Symbol` polyfill described in https://github.com/GoogleChrome/puppeteer/issues/2571 . Do you think it's solvable?
