### ISSUE TITLE
Polyfill Array.prototype.find is not served in browser chrome/30+

### ISSUE THREAD

**Issue by 94cstyles** [polyfillpolyfill/polyfill-service#1735]
`Rajax/1 Coolpad/Coolpad_T2-00 Android/5.1.1 Display/V088 Napos/7.5.8 ID/*; KERNEL_VERSION:3.10.49-perf API_Level:22 Channel:360; Needle EleEnv(release) Mozilla/5.0 (Linux; Android 5.1.1; Coolpad T2-00 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 Needle`

`Rajax/1 OPPO/R7t Android/4.4.4 Display/R7t_11_150708 Napos/7.5.1 ID/*; KERNEL_VERSION:3.10.48+ API_Level:19 Channel:tencent; Needle EleEnv(release) Mozilla/5.0 (Linux; Android 4.4.4; R7t Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 Needle`

**Comment by JakeChampion** [comment]
Hi @94cstyles, Array.prototype.find is configured to be served to [chrome versions less than 45](https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-library/polyfills/Array/prototype/find/config.json#L9) and to all versions of Android.

The two user-agent strings you have posted are Android 5.1.1 and Chrome 33, which both would get `Array.prototype.find` if it is included in the https://polyfill.io url used to serve JS polyfills.

To help me debug this further with you, could you please:
- Post the full https://polyfill.io url you are using to serve the JS polyfills. E.G. `https://polyfill.io/v2/polyfill.js?features=default,Array.prototype.find`

Thanks in advance for your help with this

**Comment by 94cstyles** [comment]
I didn't get Array.prototype.find

test: `https://polyfill.io/v2/polyfill.js?ua=Chrome/33.0.0.0`

**Comment by JakeChampion** [comment]
@94cstyles, the reason you are not getting `Array.prototype.find` in your polyfill bundle is because you are requesting the default set of polyfills which does not include `Array.prototype.find`. To add `Array.prototype.find` to your polyfill bundle you can update the polyfill.io url to this:
https://polyfill.io/v2/polyfill.js?features=default,Array.prototype.find&ua=Chrome/33.0.0.0
