### ISSUE TITLE
How is this different from babel-polyfill?

### ISSUE THREAD

**Issue by sprlwrksAprilmintacpineda** [polyfillpolyfill/polyfill-service#1739]
HI I'm a bit new to polyfill stuff, so pardon my question. I can't find answers so I opened an issue...

**Comment by JakeChampion** [comment]
The differences between the two are:
- polyfill.io includes polyfills for more than ECMAScript features such as a polyfill for <picture> elements and other DOM features.
- polyfill.io will not serve polyfills to browsers which it knows already have the feature natively
- polyfill.io has the polyfills separate to the code for your application

- Babel does not polyfill DOM features, it is only for ECMAScript.
- Babel adds the polyfills into your application code.
- Babel by default will add polyfills for the lowest browser you support and you would be serving those polyfills to browsers which don't require them.

Babel and polyfill.io are both good services and both have their merits, I hope with this information you can decide which service is the one you want to use.
