### ISSUE TITLE
Feat: feature group aliases for frameworks

### ISSUE THREAD

**Issue by mina-skunk** [polyfillpolyfill/polyfill-service#1742]
Add feature group aliases that have all the polyfills required for a particular framework like

    <script src="https://cdn.polyfill.io/v2/polyfill.js?features=angular"></script>

or

    <script src="https://cdn.polyfill.io/v2/polyfill.js?features=react"></script>

**Comment by JakeChampion** [comment]
@gatimus If you know what features they need, we will gladly accept a pull-request to add the aliases. We have done this for blissfuljs already, happy to have other aliases. :-)
