### ISSUE TITLE
Promise polyfill not served for IE11 / Windows 7: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)

### ISSUE THREAD

**Issue by KeesCBakker** [polyfillpolyfill/polyfill-service#1744]
I have the following UA:

```Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)```

The `Promise` polyfill is missing for this UA.

It can be tested here: https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla/4.0%20(compatible;%20MSIE%207.0;%20Windows%20NT%206.1;%20WOW64;%20Trident/7.0;%20SLCC2;%20.NET%20CLR%202.0.50727;%20.NET%20CLR%203.5.30729;%20.NET%20CLR%203.0.30729;%20Media%20Center%20PC%206.0;%20.NET4.0C;%20.NET4.0E)

**Comment by JakeChampion** [comment]
This user-agent now works correctly in polyfill.io/v3
