### ISSUE TITLE
Samsung browser not getting any polyfills

### ISSUE THREAD

**Issue by CheloXL** [polyfillpolyfill/polyfill-service#1751]
The following query `https://cdn.polyfill.io/v2/polyfill.js?features=Promise.finally&ua=Mozilla/5.0%20(Linux;%20Android%207.0;%20SAMSUNG%20SM-G928G%20Build/NRD90M)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20SamsungBrowser/7.2%20Chrome/59.0.3071.125%20Mobile%20Safari/537.36` returns an empty js, but Promise.finally is not available on that version of samsung browser (not sure if there are any other missing features too...)

**Comment by sleagon** [comment]
First the correct feature name is Promise.prototype.finally. Second, you will  not get Promsie.prototype.finally in any version of SamsungBrowser, higher than 4. Could you provide any information about which version SumsungBrowser starting to support Promise.prototype.finally? And by the way, the Promise(yaku) itself has included finally already, there is no need Promise.prototype.finally anymore. #1757

**Comment by CheloXL** [comment]
@sleagon: I guess I made a mistake when trimming down the url (as I'm using several other features), but I do have the correct feature (Promise.prototype.finally) in my string.
Regarding your question, I don't know. The only thing that I know is that in that version of Samsung browser (that it's build upon Chrome/59) Promise.finally doesn't exists.
Also, I'm not sure why it is relevant at all your third assertion. Chrome, for example, needs Promise.finally but not Promise, so I need to ask for finally to get it as asking only for Promise makes PF to not send anything.

**Comment by decompil3d** [comment]
I've submitted a PR #1763 to address this. Just waiting on review from maintainers.
