### ISSUE TITLE
Array.from doesn't work with Set in IE11

### ISSUE THREAD

**Issue by formatlos** [polyfillpolyfill/polyfill-service#1753]
Browser: IE 11.15.16299.0

When using `Array.from` with `Set` the result is wrong.
https://jsbin.com/yuzeberogo/edit?js,console

expected result:
```
Array.from(new Set(['foo', 'bar'])) // = ['foo', 'bar'] 
```
![chrome](https://user-images.githubusercontent.com/214001/44517251-7d8e9880-a6c7-11e8-9ce5-4807739b0b11.png)

actual result:
```
Array.from(new Set(['foo', 'bar'])) // = [] 
```

![jsbin](https://user-images.githubusercontent.com/214001/44517220-5fc13380-a6c7-11e8-9b8c-38455cdb41f9.png)

**Comment by sleagon** [comment]
does https://b.alicdn.com/s/polyfill.js?features=Array.from,Set work? I think the version of polyfill.io is out of time more than half a year....

**Comment by formatlos** [comment]
I'm on vacation until end of the week, I will check a soon as I'm back

**Comment by formatlos** [comment]
https://b.alicdn.com/s/polyfill.js?features=Array.from,Set works as expected

**Comment by JakeChampion** [comment]
This has been fixed in the version 3 of polyfill.io available at https://polyfill.io/v3/polyfill.js?features=Array.from,Set
