### ISSUE TITLE
Promise polyfill, at least on IE11, has a bad "finally" implementation

### ISSUE THREAD

**Issue by eldanb** [polyfillpolyfill/polyfill-service#1757]
The implementation for the Promise polyfill when server for IE11 is wrong. Specifically,

Promise.reject(3).finally(function f() {}).then(function s() { alert('success'); }, function e() { alert('error'); })

Should alert an error, however it alerts 'success'.

The implementation of Promise.prototype.finally would fix this, however if it's loaded in 'gated' mode, it sees the (faulty) implementation provided by the Promise polyfill and doesn't load.

**Comment by sleagon** [comment]
oh, i got you.
Actually, as you can see in the source code, the polyfill of promise is yaku. I just tested the yaku, the polyfill is ok, and finally is supported too. I think the version of yaku used by polyfill.io server is out of date. You can try this link: http://b.alicdn.com/s/polyfill.min.js?features=Promise.

**Comment by sleagon** [comment]
@JakeChampion maybe redeploy the service?

**Comment by JakeChampion** [comment]
The service has been redeployed and this bug should now be fixed :-)
