### ISSUE TITLE
Microsoft EdgeHTML 17.17134 HTMLCanvasElement.prototype.toBlob polyfill is not served

### ISSUE THREAD

**Issue by Havunen** [polyfillpolyfill/polyfill-service#1758]
Hey!

HtmlCanvas.toBlob prototype is not served to Edge 17... It should be included for all versions of Edge and IE

UserAgent header is following:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134 
```

detection script:
```
'toBlob' in HTMLCanvasElement.prototype;  // returns false
```

There was PR fixing this issue in 3.25.1 ?  https://github.com/Financial-Times/polyfill-service/commit/7413a0f5304ff9f4eec8d2e53a85a56dc9493230

The site says its running 3.25.1 but there are no release notes in Github https://github.com/Financial-Times/polyfill-service/releases/tag/v3.25.1  and its not marked as latest release.

This is the URL we used:
```https://cdn.polyfill.io/v2/polyfill.min.js?features=HTMLCanvasElement.prototype.toBlob``` 
It seems to be delivered correctly to IE, but not MS Edge

**Comment by jimmywarting** [comment]
can confirm that edge don't have `toBlob` but it has a prefixed version `msToBlob`

**Comment by Havunen** [comment]
Shouldn't the polyfill service then provide polyfill that uses `msToBlob`? now it works in IE11 and just fails in  Edge

**Comment by JakeChampion** [comment]
In polyfill.io/v3 Edge is served the HTMLCanvasElement.prototype.toBlob polyfill 👍
