### ISSUE TITLE
SCRIPT5022: HierarchyRequestError in IE9

### ISSUE THREAD

**Issue by axetroy** [polyfillpolyfill/polyfill-service#1764]
![1](https://user-images.githubusercontent.com/9758711/45913644-eb65e580-be68-11e8-8ca0-604b2f883da4.PNG)

**Comment by JakeChampion** [comment]
Please post the full polyfill.io url you are using and any other code that is necessary for this bug to occur. I won't be able to help if I don't know what code is being executed.
