### ISSUE TITLE
Please add polyfill for `Promise.prototype.finally()`

### ISSUE THREAD

**Issue by angelmeraz** [polyfillpolyfill/polyfill-service#1770]
* Please add polyfill for `Promise.prototype.finally()`

https://developers.google.com/web/updates/2017/10/promise-finally

Love your work, thanks for the effort and putting out there!

**Comment by JakeChampion** [comment]
Hi @promptdev thanks for the nice words, we already have a polyfill for this feature -- https://polyfill.io/v2/docs/features/#Promise_prototype_finally

You can add this to your bundle like so `https://polyfill.io/v2/polyfill.js?features=default,Promise.prototype.finally`
