### ISSUE TITLE
Array.prototype.includes is not served on IE11

### ISSUE THREAD

**Issue by fabioricali** [polyfillpolyfill/polyfill-service#1771]
please check...

**Comment by JakeChampion** [comment]
It is served. https://polyfill.io/v2/polyfill.js?features=Array.prototype.includes&ua=ie/11

**Comment by fabiorc428** [comment]
but in default mode do not exists... it's correct?
https://polyfill.io/v2/polyfill.js?ua=ie/11

**Comment by JakeChampion** [comment]
Correct, if you want to add extra features to the default features, you can do this: `https://polyfill.io/v2/polyfill.js?features=default,Array.prototype.includes`
