### ISSUE TITLE
Gate polyfills for unknown UAs

### ISSUE THREAD

**Issue by robwierzbowski** [polyfillpolyfill/polyfill-service#1772]
Recently we were debugging an issue rendering our site inside the Pinterest iOS app. We found that:

- The webview returned the UA `UA detected: pinterest/0.0.0 (unknown/unsupported)`
- We added the parameter `unknown=polyfill` to the polyfill.io script
- Like others have mentioned, applying polyfills in unknown browsers can cause errors. Without the `gated` flag, the polyfill script crashed with a [`HeirarchyRequestError`](https://user-images.githubusercontent.com/925735/46499582-7c847700-c7ee-11e8-9dd4-f2bb10b83966.png)
- We gated the polyfills and everything worked

#### Problem

Although gated fixed our issue, it adds feature detects for known browsers as well. These detects are unnecessary bytes over the network, and unnecessary code execution.

#### Proposed solution

Can you add a feature to gate polyfills for unknown UA browsers only? I know this is a small optimization, but performance is cumulative.

#### Possible implementations

A `gated` value for the `unknown` parameter:
```
//cdn.polyfill.io/v2/polyfill.min.js?features=default&unknown=gated
```

A `gated` flag on the `polyfill` value for the `unknown` parameter:
```
//cdn.polyfill.io/v2/polyfill.min.js?features=default&unknown=polyfill|gated
```

**Comment by JakeChampion** [comment]
This has been implemented as part of https://polyfill.io/v3 
Unknown/Unsupported browsers by default now get served polyfills wrapped in feature detects.

Here is an example showing the response for Internet Explorer 5 (unsupported browser) when asking for Object.defineProperty feature --> https://polyfill.io/v3/polyfill.js?features=Object.defineProperty&ua=ie/5
