### ISSUE TITLE
Polyfill library without the service

### ISSUE THREAD

**Issue by JuanAntelo** [polyfillpolyfill/polyfill-service#1773]
Hi,

I'd like to integrate the polyfill library into my app but I don't want to use the CDN. How can I achieve this goal:

**Comment by gabemeola** [comment]
The library package is also up on npm: https://github.com/Financial-Times/polyfill-service/tree/master/packages/polyfill-library

**Comment by JakeChampion** [comment]
`npm install polyfill-library --save` and the code is hosted at https://github.com/Financial-Times/polyfill-library
