### ISSUE TITLE
Usage and performance Stats Down

### ISSUE THREAD

**Issue by jakesylvestre** [polyfillpolyfill/polyfill-service#1783]
Hi,

Just letting you know that on [polyfill.io](https://polyfill.io/v2/docs/usage)'s usage page the stats look like they're down:

<img width="1271" alt="screen shot 2018-10-20 at 11 05 19 am" src="https://user-images.githubusercontent.com/6392429/47257164-6a464200-d458-11e8-874c-6effd1531397.png">

Cheers!

**Comment by JakeChampion** [comment]
The stats is now on the homepage, it is no longer a graph but some text :-)
