### ISSUE TITLE
polyfill.io is down for me

### ISSUE THREAD

**Issue by aaronjensen** [polyfillpolyfill/polyfill-service#1784]
I apologize, but I wasn't able to find a status page so I'm leaving this here for others. It appears that polyfill.io is down for me right now, serving 503s:

<img width="482" alt="image 2018-10-23 at 8 13 20 am" src="https://user-images.githubusercontent.com/8588/47370882-84bc2d80-d69b-11e8-9f6b-187787cc427e.png">

Is there a status page somewhere and/or is there a backup server we could be using?

Thanks!

**Comment by DannyFeliz** [comment]
Same here, it started to happen today.

**Comment by iDiver76** [comment]
Same here, happend right now

**Comment by luglio7** [comment]
Same here, only the "basic url works" https://cdn.polyfill.io/v2/polyfill.min.js

**Comment by oliviertassinari** [comment]
Here is a reproduction url: https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en-US&flags=always.

**Comment by Tecktron** [comment]
Consistently an issue for me as well: https://cdn.polyfill.io/v2/polyfill.js?features=default-3.6,Intl.~locale.en
```
Error 503 Backend is unhealthy
Backend is unhealthy

Guru Mediation:
Details: cache-jfk8137-JFK 1540310102 3793895496

Varnish cache server
```

**Comment by JakeChampion** [comment]
Hi all, I'm looking into this issue. We have made no changes to the production service so I am currently not sure what is causing the issue.

**Comment by JakeChampion** [comment]
Update, we had a high amount of traffic bypass our CDN layer and overload our servers. I have scaled our servers to meet the large amount of traffic, the amount of errors has reduced completely to 0.

**Comment by JakeChampion** [comment]
I have now added autoscaling to our backend servers to help avoid this situation happening again in the future. 👍

**Comment by aaronjensen** [comment]
Thanks @JakeChampion. FWIW, we have been seeing intermittent issues for about 15 days. We know this because we started seeing errors from IE11 that should not be there if it was properly polyfilled from a handful of users.

**Comment by aaronjensen** [comment]
@JakeChampion we're still seeing occasional errors. They're being reported from user's browsers so I don't actually know how or if the polyfill service is failing to serve a file, but it still is. Is it possible that there are still 503s being served?

**Comment by hecktarzuli** [comment]
Why don't you have origin server protection so only your CDN can talk to your servers?
