### ISSUE TITLE
polyfill service is not compatible with node 10 (LTS)

### ISSUE THREAD

**Issue by EECOLOR** [polyfillpolyfill/polyfill-service#1785]
```
error polyfill-service@3.25.1: The engine "node" is incompatible with this module. Expected version "6.11.1 - 9". Got "10.12.0"
```

**Comment by mridgway** [comment]
@JakeChampion Any ETA on getting a new version out that supports Node 10? Anything that we can help with to get there?

**Comment by gwardwell** [comment]
@JakeChampion _Please_ get this updated so I can move my project to Node 10 LTS.

**Comment by JakeChampion** [comment]
@gwardwell You always can use this on any version of node that is greater that the supported version, this shouldn't be blocking you from moving to Node 10 LTS.

This is now fixed -- https://github.com/Financial-Times/polyfill-service/blob/a4d9434ae41eb11db7bf40c6ef8746873cceb3e3/package.json#L37
