### ISSUE TITLE
Intl not served in Chrome on XiaoMi phones

### ISSUE THREAD

**Issue by szyablitsky** [polyfillpolyfill/polyfill-service#1817]
We use Intl polyfill on our site. And we have many crash reports that say Intl polyfill must be provided. All of them are from the latest Android Chrome browsers on XiaoMi phones. It seems that versions of Android on those phones somehow compromise the ability of Chrome browser to provide the Intl API.
Is it possible to serve Intl polyfill for latest versions on Chrome but only if it has XiaoMi in UserAgent?

**Comment by JakeChampion** [comment]
Hi @szyablitsky, thanks for the issue. I have a few questions, if you could answer these it would help us be able to debug the issue with you :-)

Do you know what the full user-agent is that are not getting the Intl polyfill? I'm wondering whether XiaoMi have modified the user-agent string and are being served a different polyfill bundle then the one we serve for Chrome.

Do you know what the full url you are using to load the polyfill bundle is? It should look something like `https://polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en-GB`.

Having answers to these two questions should make more likely that we are able to reproduce the environment in which the error is occurring.

**Comment by szyablitsky** [comment]
Full URL to load polyfill is `https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.ru,URL|gated`.

The error `[React Intl] The 'Intl' APIs must be available in the runtime, and do not appear to be built-in. An 'Intl' polyfill should be loaded.`

UserAgent examples which generate the error:
```
Mozilla/5.0 (Linux; U; Android 7.0; ru-ru; Redmi Note 4 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.2.4-g
Mozilla/5.0 (Linux; U; Android 8.0.0; ru-ru; MI 5 Build/OPR1.170623.032) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.1.2
Mozilla/5.0 (Linux; U; Android 7.1.2; ru-ru; Redmi 4X Build/N2G47H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.0.2
Mozilla/5.0 (Linux; U; Android 7.1.2; ru-ru; Redmi 5 Build/N2G47H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.1.2
Mozilla/5.0 (Linux; U; Android 6.0.1; ru-ru; Redmi 3S Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.1.2
```

Now I see that real browser is MiuiBrowser, not Chrome. I think it is some kind of Chromium based fork.

**Comment by szyablitsky** [comment]
Any ideas about this case?

**Comment by uwelo** [comment]
We see the same errors.
```
Mozilla/5.0 (Linux; U; Android 6.0.1; en-in; Redmi Note 3 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.2.5-g
Mozilla/5.0 (Linux; U; Android 7.0; en-gb; Redmi Note 4 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.2.5-g
Mozilla/5.0 (Linux; U; Android 7.1.2; en-us; Redmi Note 5A Build/N2G47H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.2.4-g
Mozilla/5.0 (Linux; U; Android 8.1.0; en-us; Redmi 5 Plus Build/OPM1.171019.019) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.2.5-g
Mozilla/5.0 (Linux; U; Android 8.1.0; en-us; Redmi Note 5 Pro Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.2.5-g
```

With the polyfill URL `https://cdn.polyfill.io/v2/polyfill.min.js?features=default-3.6,Array.prototype.includes,Array.prototype.find,String.prototype.includes,Number.isFinite,fetch,Intl,Intl.~locale.en-CA,HTMLPictureElement`

**Comment by JakeChampion** [comment]
I can confirm this has been fixed in polyfill.io/v3

**Comment by SleepWalker** [comment]
@JakeChampion nope it's not:

https://cdn.polyfill.io/v3/polyfill.js?features=Intl&ua=Mozilla%2F5.0%20(Linux%3B%20U%3B%20Android%208.1.0%3B%20en-us%3B%20Redmi%20Note%205%20Pro%20Build%2FOPM1.171019.011)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Version%2F4.0%20Chrome%2F61.0.3163.128%20Mobile%20Safari%2F537.36%20XiaoMi%2FMiuiBrowser%2F10.2.5-g&unknown=polyfill

https://cdn.polyfill.io/v3/polyfill.js?features=Intl&ua=Mozilla%2F5.0%20(Linux%3B%20U%3B%20Android%205.1.1%3B%20ru-ru%3B%20MI%204S%20Build%2FLMY47V)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Version%2F4.0%20Chrome%2F61.0.3163.128%20Mobile%20Safari%2F537.36%20XiaoMi%2FMiuiBrowser%2F10.4.5&unknown=polyfill

**Comment by ChrisSargent** [comment]
@JakeChampion, we are also seeing this issue. Some example UA strings:

- `Mozilla/5.0 (Linux; U; Android 8.0.0; zh-cn; Mi Note 2 Build/OPR1.170623.032) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/9.3 Mobile Safari/537.36`
- `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0`

**Comment by JakeChampion** [comment]
Hi @ChrisSargent, please can you open a new issue about the issue you are seeing

**Comment by ChrisSargent** [comment]
Hi @JakeChampion - sorry, I'm an idiot :-). I was still using V2 in production. Have updated, will monitor and open a new case if it comes up again.
