### ISSUE TITLE
Broken pages on v2 site

### ISSUE THREAD

**Issue by silas** [polyfillpolyfill/polyfill-service#1828]
There are a couple of pages broken on the polyfill.io v2 site.

## Privacy Policy

The left nav link returns a `404` via https://polyfill.io/docs/privacy-policy, looks like it should be https://polyfill.io/v2/docs/privacy-policy

## Terms of Service

The left nav link returns a `404` via https://polyfill.io/docs/terms, looks like it should be https://polyfill.io/v2/docs/terms

**Comment by japrogramer** [comment]
yes, Is there a link to the term of service and the privacy policy
on the github repo?

**Comment by cs09g** [comment]
I guess it's occured by https://github.com/Financial-Times/polyfill-service/commit/5701e797f79ea5ba4baecfd1567fbd417abd1143
I don't know why the code changed like that from #1331

**Comment by kud** [comment]
+1

**Comment by JakeChampion** [comment]
The v2 site is no longer available, the links for privacy policy and terms and conditions are:
https://polyfill.io/v3/privacy-policy
https://polyfill.io/v3/terms
