### ISSUE TITLE
Fix vulnerabilities in NPM packages

### ISSUE THREAD

**Issue by madsgodvinjensen** [polyfillpolyfill/polyfill-service#1831]
`npm audit` reports a few critical/high vulnerabilities in dependencies of `polyfill-service`.

They are:
`growl`: path mocha > growl (critical)
`sshpk`: path: shrink-ray-current > node-zopfli-es > node-gyp > request > http-signature > sshpk (high)

I'm preparing a PR with updates, if possible. Hope to get this prioritized :)

**Comment by madsgodvinjensen** [comment]
I can't get this to work. The main issue is that the mocha version in this repo is a bit old. I've tried updating, but then the tests start failing. I've tried to fix them but I must admit I'm not a super user in Mocha.

I hope you'll have time to look into these at some point anyway.

You can run `yarn audit` in both packages to see which vulnerabilities there are. I'm happy to help with whatever questions you might have. Just shout :)

**Comment by JakeChampion** [comment]
All the issues come from either the old polyfill-library or the development dependencies. I will look into the development dependencies issues but I am not sure we can alter the old polyfill-library as that specific version is required to keep polyfill.io/v2 urls working

**Comment by madsgodvinjensen** [comment]
I'm not sure I understand, are you going to stop maintaining the polyfill-library?

**Comment by JakeChampion** [comment]
I maintain polyfill-library and it should be completely up-to-date.

What I was trying to explain was that the polyfill-service uses multiple versions of polyfill-library in order to support /v2/polyfill.js and /v3/polyfill.js endpoints, which means polyfill-service will always have that older version of polyfill-library which is the cause of those reports in `yarn aduit`.

**Comment by madsgodvinjensen** [comment]
Okay, I completely understand now :) Any plans on discontinuing v2 or moving it to a separate repo? I'm trying to figure out what to do with the service we have that use the polyfill-service and reports vulnerabilities.

**Comment by madsgodvinjensen** [comment]
Well that makes sense. We're switching to use the library as we speak. Thanks a lot for the help.
