### ISSUE TITLE
How to use with npm?

### ISSUE THREAD

**Issue by quantuminformation** [polyfillpolyfill/polyfill-service#1832]
We are trying to build in locally what the cdn provides `    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>`

We done yarn install polyfill-library and then import like so

import 'polyfill-library';

But when building with with create react app we get

`./node_modules/useragent/lib/update.js
Module not found: Can't resolve 'yamlparser' in '/Users/nikos/WebstormProjects/Us/node_modules/useragent/lib'`

Your install instructions are just for a node service it seems, and the name isn't the same

![image](https://user-images.githubusercontent.com/216566/49873997-31ea3100-fe15-11e8-8504-21f7f1db0470.png)

Would be nice to import an ie11 specific build too.

**Comment by JakeChampion** [comment]
https://github.com/Financial-Times/polyfill-library is the npm package and should have the documentation you need :-)
