### ISSUE TITLE
API reference/Live example down

### ISSUE THREAD

**Issue by temsa** [polyfillpolyfill/polyfill-service#1846]
The website documentation is not working anymore, probably just a deployment issue during last release ?
https://polyfill.io/v2/docs/examples :point_right: HTTP 404
https://polyfill.io/v2/docs/api :point_right: HTTP 404

**Comment by robwierzbowski** [comment]
We're seeing 503s on some polyfill.io calls as well. Large portions of our users are having polyfill errors, which might be related.

**Comment by RoyHP** [comment]
Same issue here, this is affecting our users.
<img width="433" alt="screen shot 2019-01-11 at 12 39 29 pm" src="https://user-images.githubusercontent.com/1066439/51050289-43eafb00-159e-11e9-9352-8cb1517e0c53.png">

**Comment by PaitoAnderson** [comment]
Same here, users are experiencing problems loading our site.

**Comment by JakeChampion** [comment]
All fixed now, looks to have been a bad deployment to our Fastly service which included a bug in the configuration
