### ISSUE TITLE
IE 11 on BrowserStack.com detected as ios_saf/12.0.0

### ISSUE THREAD

**Issue by mfb** [polyfillpolyfill/polyfill-service#1848]
When I load https://cdn.polyfill.io/v2/polyfill.js?features=Promise on IE 11 from browserstack.com, it's detected as ios_saf/12.0.0

However, if I add some cache-busting parameters onto the URL, like https://cdn.polyfill.io/v2/polyfill.js?features=Promise&myBrowserIsActually=IE11 then it's detected as IE 11.

So there appears to be some caching issue?  If so, could be cdn.polyfill.io reverse proxy or BrowserStack proxy, more testing would be needed.

**Comment by robwierzbowski** [comment]
We're seeing 503s on some polyfill.io calls as well. Large portions of our users are having polyfill errors, which might be related.

**Comment by JakeChampion** [comment]
This is now fixed 👍
