### ISSUE TITLE
Polyfill requests returning 503 response

### ISSUE THREAD

**Issue by mudy** [polyfillpolyfill/polyfill-service#1850]
There are many common scenarios for raising issues against the polyfill service.  Is your issue one of these?

* Polyfill X is not served in browser Y (and it should be)
* Polyfill X is served in browser Y (and it shouldn't be)
* My browser is not recognised correctly
* Please add polyfill X
* Please update polyfill X from the upstream repo
* Polyfill X doesn't work properly

If so please visit https://polyfill.io/v2/docs/contributing/common-scenarios for help putting together all the information you need for your issue.  Running through the appropriate checklist need not take much time and will make it much more likely that we can deal with the issue quickly.

**Comment by JakeChampion** [comment]
This is now fixed 👍

**Comment by mudy** [comment]
This seems to be a recurring issue. Did you try adding stale-while-revalidate and stale-while-error on your cache directives - https://www.fastly.com/blog/stale-while-revalidate-stale-if-error-available-today

**Comment by mudy** [comment]
@JakeChampion What was the issue and what was the fix?
