### ISSUE TITLE
Polyfills suddenly, selectively missing 

### ISSUE THREAD

**Issue by pinkfloydx33** [polyfillpolyfill/polyfill-service#1853]
We've been using this URL for a while. Up until a few hours ago, it returned `Array.prototype.findIndex` 
`https://cdn.polyfill.io/v2/polyfill.min.js?features=modernizr:es6array,Element,Element.prototype.classList,Element.prototype.cloneNode,Element.prototype.replaceWith,Array.prototype.map,Array.prototype.reduce,es7&flags=always,gated`

**Out of nowhere**, it has stopped returning at least the one function. What it is odd is that _this_ URL (which is just the first portion of the above) returns it just fine:
`https://cdn.polyfill.io/v2/polyfill.js?features=modernizr:es6array&flags=always,gated`

I'm not sure what else might be missing. I know `findIndex` is because we've got something in production that just broke for IE11 and we're trying to figure out a solution.

**Comment by mche1987** [comment]
Is it still down for you @pinkfloydx33 - ours just came back up. Ours specifically for `Object.assign` in IE 11.

**Comment by pinkfloydx33** [comment]
@mche1987 Nope, still down

**Comment by kelvinlouis** [comment]
Same here. We are experiencing the same with `https://cdn.polyfill.io/v2/polyfill.js?features=default-3.6,WeakMap,fetch,Array.prototype.find,Array.prototype.includes,IntersectionObserver,Element.prototype.dataset,HTMLPictureElement` It says `IntersectionObserver` is missing, after that `fetch` and so on.

**Comment by robwierzbowski** [comment]
It looks like this might have been caused by a bad Fastly configuration, based on https://github.com/Financial-Times/polyfill-service/issues/1846#issuecomment-453603845.

Related?

https://github.com/Financial-Times/polyfill-service/issues/1851
https://github.com/Financial-Times/polyfill-service/issues/1850
https://github.com/Financial-Times/polyfill-service/issues/1848
https://github.com/Financial-Times/polyfill-service/issues/1846

We too experienced a large volume of errors.

**Comment by pinkfloydx33** [comment]
Still experiencing the issue, whether *that* is fixed or not. 
Repro (IE11), fails
``` html
<html>
<head>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default-3.6,modernizr:es6string&flags=gated"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=modernizr:es6array,Element,Element.prototype.classList,Element.prototype.cloneNode,Element.prototype.replaceWith,Array.prototype.map,Array.prototype.reduce,es7&flags=always,gated"></script>
	<script>		
		try {
			var x = [1,2,4];
			var z = x.findIndex(function(i) {
				return i == 2;
			});
			console.log("Success!",z);
		} catch(e){
			console.error(e);
		}
	</script>
</head>
</html>
```

**Comment by JakeChampion** [comment]
Hi all, I have found the issue, it is a bug in the Fastly config where we didn't use the features parameter if it was above 100 characters. This has been fixed in https://github.com/Financial-Times/polyfill-service/commit/44b0adab53333c48bf3f8d89893ecbb0f294ed06 and will go live soon.

**Comment by kelvinlouis** [comment]
It seems to be working again. Thanks for the fix! We will be testing now.

**Comment by pinkfloydx33** [comment]
Thanks, all fixed!
