### ISSUE TITLE
v2 now has a default "ignore" policy for unknown UA, breaking custom clients

### ISSUE THREAD

**Issue by nldevis** [polyfillpolyfill/polyfill-service#1855]
Probably related to #1853. Our apps suddenly started to failing today.
After some debugging, it turns out that v2 now has "ignore" policy for unknown user agents (but should have "polyfill" by default according to [this](https://github.com/Financial-Times/polyfill-service/blob/master/fastly/vcl/main.vcl#L95-L97)).

To repro the issue, set UA to some random string (eg. in Chrome Device Emulator) and compare responses:
https://cdn.polyfill.io/v2/polyfill.js?features=default-3.6&flags=gated&rum=0

```
/* Polyfill service v3.25.1
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: other/0.0.0 (unknown/unsupported; using policy `unknown=ignore`)
 * Features requested: default-3.6
 *  */

(function(undefined) {

/* No polyfills found for current settings */

})
.call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});
```

and https://cdn.polyfill.io/v3/polyfill.js?features=default-3.6&flags=gated&rum=0 (OK – has polyfills).

Although #1853 is flagged as fixed, this issue still exists and is breaking our custom clients (with custom user agents).

**Comment by JakeChampion** [comment]
polyfill.io v2 defaults to unknown=ignore, polyfill v3 defaults to unknown=polyfill. Your issue is likely the same as #1853 and should have been fixed 👍

**Comment by nldevis** [comment]
@JakeChampion, it was working with unknown user agents until yesterday (ie. v2 was behaving like unknown=polyfill). Can you please clarify: is it a breaking change introduced recently?

I see in the response the header `normalized-user-agent: other/0.0.0` and no polyfills provided.
