### ISSUE TITLE
Is "Vary: User-Agent" missing?

### ISSUE THREAD

**Issue by shqld** [polyfillpolyfill/polyfill-service#1856]
## Summary

Seems `Vary: User-Agent` is missing in polyfill.io/v2 . Since 2 days ago, our product( https://r.nikkei.com ) that is using v2 via our CDN has been failed to load correct polyfills for IE.

https://github.com/Financial-Times/polyfill-service/pull/1843
https://github.com/Financial-Times/polyfill-service/search?q=Vary&type=Code

I checked some part of code and suspect each response isn't properly varied by UserAgent.

**Comment by shqld** [comment]
Can you take a look?

**Comment by JakeChampion** [comment]
This for the issue, this has now been fixed in v4.0.5
https://github.com/Financial-Times/polyfill-service/blob/342627dff759c77f9e9ee5dfb32a28806451c03a/fastly/vcl/polyfill-service.vcl#L164-L172

**Comment by shqld** [comment]
Thanks.
