### ISSUE TITLE
Documentation for sets in v3 is missing

### ISSUE THREAD

**Issue by exophunk** [polyfillpolyfill/polyfill-service#1863]
Im afraid, with the new website, I can't find any documentation anymore and it seems very unclear for me how to use the polyfills service.

– On the "old" website, I could see, which browsers need which polyfills, I can't find this feature anymore.
– I think you can somehow still require polyfill "sets" like es6,es7 but you can't find anywhere on the page what sets exist and what polyfills are in them. The documentation for this is not there anymore.

Is there a place where the available sets and browser support is documented?

**Comment by break-stuff** [comment]
I second that. I am about to implement this on multiple large websites but need that documentation for my developers.

**Comment by agriffis** [comment]
For what it's worth, you can get the full list of aliases by checking out the source code and then:

```
find polyfills -name config.json -print0 | xargs -0 jq -r '.aliases[]?' | sort -u
```

(That depends on having [jq](https://stedolan.github.io/jq/) installed)

Here is the output at the moment:

```
Navigator.prototype.geolocation
PageVisibility
blissfuljs
caniuse:audio-api
caniuse:console-basic
caniuse:datauri
caniuse:geolocation
caniuse:hashchange
caniuse:input-placeholder
caniuse:json
caniuse:matchesselector
caniuse:matchmedia
caniuse:namevalue-storage
caniuse:pagevisibility
caniuse:promises
caniuse:requestanimationframe
caniuse:visib
default
default-3.3
default-3.4
default-3.5
default-3.6
dom4
es2017
es5
es6
es7
html5shiv
innerHeight
innerWidth
modernizr:classlist
modernizr:customevent
modernizr:es5array
modernizr:es5date
modernizr:es5function
modernizr:es5object
modernizr:es5string
modernizr:es6array
modernizr:es6object
modernizr:es6string
modernizr:es7array
modernizr:geolocation
modernizr:hashchange
modernizr:json
modernizr:localstorage
modernizr:matchmedia
modernizr:pagevisibility
modernizr:placeholder
modernizr:promises
modernizr:requestanimationframe
modernizr:urlparser
modernizr:webaudio
pageXOffset
pageYOffset
scrollX
scrollY
viewport
```

**Comment by JakeChampion** [comment]
I have a work-in-progress pull-request for adding the aliases to the url-builder --> https://github.com/Financial-Times/polyfill-service/pull/1942

I'm not happy with the design but it is better than not showing them at all :-)

**Comment by JakeChampion** [comment]
https://polyfill.io/v3/url-builder/ now contains the sets/aliases and the tooltip for a specific set/alias contains the polyfills that it has.
