### ISSUE TITLE
Where can I disclose a security bug?

### ISSUE THREAD

**Issue by sjparkinson** [polyfillpolyfill/polyfill-service#1864]
On the Polyfill.io site it mentions the following at https://polyfill.io/v3/report-a-bug#security-bugs.

> Polyfill.io has a bounty program for the safe disclosure of security bugs. With that in mind, please do not file public issues; go through the process outlined on that page.

But it's not actually clear _where_ the mentioned page is.

A direct link to the HackerOne setup would be helpful.

**Comment by revolunet** [comment]
any news ?

**Comment by JakeChampion** [comment]
@revolunet Thank you for the reminder, we haven't yet opened up our bug bounty program to the public yet, if you have a security question or issue to report, please email `origami.support@ft.com`. I will update the website to say this as well :-)

**Comment by Cordazar** [comment]
@JakeChampion The page still doesn't include either a link to a separate page or the email address to use.
(no I don't have the need for it at this time, just thought I should mention it when I stumbled upon this issue)
