### ISSUE TITLE
https://cdn.polyfill.io/v2/polyfill.minify.js redirect to HTML

### ISSUE THREAD

**Issue by dotnetCarpenter** [polyfillpolyfill/polyfill-service#1865]
https://cdn.polyfill.io/v2/polyfill.minify.js redirects to a HTML page and thrashes every project we have that depends on polyfill.io!!!!

**Comment by dotnetCarpenter** [comment]
And why does https://cdn.polyfill.io/v3/url-builder always add `default` to the query? I know exactly which polyfills I want and I was under the impression that `default` adds a _package_  of polyfills. Did something change? Or can I safely delete `default` from my query?

My query from _url-builder_ is: `https://polyfill.io/v3/polyfill.min.js?flags=gated&features=default%2CArray.prototype.find%2CArray.prototype.findIndex%2CPromise%2CArray.from%2CMap`

What happens if I query `https://polyfill.io/v3/polyfill.min.js?flags=gated&features=Array.prototype.find%2CArray.prototype.findIndex%2CPromise%2CArray.from%2CMap`?

**Comment by dotnetCarpenter** [comment]
OK. I got a PC with IE11 and tested. **I do not need `default`**.

**Comment by dotnetCarpenter** [comment]
To be honest I'm shocked that this could happen...

**Comment by JakeChampion** [comment]
>https://cdn.polyfill.io/v2/polyfill.minify.js redirects to a HTML page and thrashes every project we have that depends on polyfill.io!!!!

The only documented routes which work have always been `.js` and `.min.js`. `.minify.js` was never meant to work, the fact that it did was a bug in the routing logic.

>And why does https://cdn.polyfill.io/v3/url-builder always add default to the query? I know exactly which polyfills I want and I was under the impression that default adds a package of polyfills. Did something change? Or can I safely delete default from my query?
>My query from url-builder is: https://polyfill.io/v3/polyfill.min.js?flags=gated&features=default%2CArray.prototype.find%2CArray.prototype.findIndex%2CPromise%2CArray.from%2CMap
>What happens if I query https://polyfill.io/v3/polyfill.min.js?flags=gated&features=Array.prototype.find%2CArray.prototype.findIndex%2CPromise%2CArray.from%2CMap?

You can choose to not include `default`, it will work as you expect it to. Most people want `default`, which is why it is there.

**Comment by dotnetCarpenter** [comment]
@JakeChampion I dont see any `default` option on https://cdn.polyfill.io/v3/url-builder. `default` just appear in the query string whenever I choose a polyfill.

**Comment by dotnetCarpenter** [comment]
~~https://cdn.polyfill.io/v2/polyfill.minify.js~~ should have been https://cdn.polyfill.io/v2/polyfill.min.js. It has been working for more than a year but broke today. Luckily it was in a project I still support and not a finished project. But today has tought me not to rely on https://cdn.polyfill.io for future projects. We have to plan at work but I'll suggest we start to self host _polyfill-service_. Thanks for the project and all the work you have put into it, though!

**Comment by dotnetCarpenter** [comment]
@JakeChampion  I get the  confusion now. We did use polyfill.minify.js before because the old documentation looked like that was suppose to be the name.
https://web.archive.org/web/20170606192731/https://polyfill.io/v2/docs/api

### GET /v2/polyfill:minify.:type

Param | Where | Description
-- | -- | --
minify | URL | Whether to minify the result. If omitted, output will include the full polyfill source, and a header comment with debug information about the user agent and which polyfills have been included in the bundle. If set to .min, the output will be minified.

**But after re-reading the description it does say to use `.min`.** 
Too bad that https://cdn.polyfill.io/v2/polyfill.minify.js worked for such a long time then.
