### ISSUE TITLE
Add polyfill on url builder itself

### ISSUE THREAD

**Issue by hkmaly** [polyfillpolyfill/polyfill-service#1873]
Considering you already have the polyfill, can you add it on your page itself? Specifically, on https://cdn.polyfill.io/v3/url-builder with Chrome 55 I get the bundle url as https://polyfill.io/v3/polyfill.min.js?%5Bobject+Object%5D= regardless of what I select. I suppose you are using some feature not available in it ...

Note that https://cdn.polyfill.io/static/polyfills.js is returning 404 and is referenced on that page ... and I also see this error:
```
jquery.js:19 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-0wIoD60yL42+1XJUY22zM8LflSmtzRyZIjM0qasci88='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
jquery.js:19 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-+1gZjPThUpVdzUAk0dH9fwK52R9/GjM+bgt7zsawajs='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by ashucg** [comment]
Filters are not working at all, I am on Firefox Nightly (67.0a1):

![filters-not-working](https://user-images.githubusercontent.com/11291284/52851763-d424de80-310e-11e9-8950-6b5373dc2062.gif)

**Comment by JakeChampion** [comment]
This is fixed now 👍

**Comment by hkmaly** [comment]
It is not.
