### ISSUE TITLE
v3 source zip for self-hosting

### ISSUE THREAD

**Issue by gsrx** [polyfillpolyfill/polyfill-service#1876]
What is the correct zip to use for self-hosting v3?

Thanks

**Comment by JakeChampion** [comment]
Any zips on the [releases](https://github.com/Financial-Times/polyfill-service/releases) page, you would need to run `npm install` and then `npm start`.

There is currently no documentation for this, it will be added at a later date.

**Comment by gsrx** [comment]
Which zip is the version currently hosted? The filename version doesn't match the version in package.json in zips >3.25.1 <4.04. Thanks

**Comment by JakeChampion** [comment]
https://github.com/Financial-Times/polyfill-service/releases/tag/v4.0.13
