### ISSUE TITLE
Which release zip contains the v3 source code?

### ISSUE THREAD

**Issue by gsrx** [polyfillpolyfill/polyfill-service#1877]
Which zip file contains the source of the latest version currently hosted here?
https://polyfill.io/v3/polyfill.min.js

I believe it is Polyfill service v3.27.1 but there is no zip filename with this version. (and multiple zip files specify v3.27.0 in pakages.config)

Also, more recent versions contain a yarn.lock file. Is yarn required to install and build these?

**Comment by JakeChampion** [comment]
https://github.com/Financial-Times/polyfill-service/releases/tag/v4.0.13
