### ISSUE TITLE
Can't get Object.values in v3 feature es6, es7

### ISSUE THREAD

**Issue by milkmidi** [polyfillpolyfill/polyfill-service#1878]
Bug

## What

https://polyfill.io/v3/polyfill.js?flags=always&features=es6,es7
Can't get Object.values

**Comment by JakeChampion** [comment]
That is because it was added in `es2017`, you would need to add `es2017` to the features query parameter.

https://polyfill.io/v3/polyfill.js?flags=always&features=es6,es7,es2017
