### ISSUE TITLE
Add dataset polyfill

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#188]
Requested in https://github.com/jonathantneal/polyfill/issues/48.  Also desired by FT.

**Comment by DavidBennettPIO** [comment]
@triblondon 

I've been writing a dataset polyfill and I have been able to get it working a lot closer to the spec then remy's one as discussed in jonathantneal#48 although it is a bit slower then his.

@aintgoin2goa I have the cases you outlined above working in IE9+ for the most part.

Points 4 and 6 happen 1ms after the fact though, I believe this would be fine in most cases but may lead to race conditions if someone mixes and matches `el.dataset.key` with `el.getAttribute('data-key')` within the same code execution. (currently trying to think of a better way)

If I cleaned this up do you think you would be interested in a dataset polyfill?

I might also be able to back-port it to IE8, as I don’t think I'm doing anything I couldn’t reproduce there, but for now I have just been targeting IE9+ to keep the code leaner (and myself saner).

**Comment by triblondon** [comment]
@complistic-gaff Sorry for the delayed response, yes we'd be thrilled to get your contribution, and this is a feature I think would be popular.

**Comment by triblondon** [comment]
@complistic-gaff are you still planning to work on this?

**Comment by triblondon** [comment]
No significant demand for this, and FT no longer needs it.

**Comment by aendra-rininsland** [comment]
:wave: I'd like this feature. I used it throughout the US Election headpiece and am now having to do a bunch of code changes because Circle's only failed it now. 😞

**Comment by JakeChampion** [comment]
@aendrew In case you missed it, we now have a dataset polyfill :-)
