### ISSUE TITLE
Return a 400 when requesting an invalid feature

### ISSUE THREAD

**Issue by i-like-robots** [polyfillpolyfill/polyfill-service#1886]
type: Feature request

## What

When requesting polyfills it is currently possible to request a non-existent feature and receive a JS bundle in response, e.g.:

https://www.ft.com/__origami/service/polyfill/v3/polyfill.min.js?features=abcde

## Details

I do not think this is desirable behaviour as it makes it possible for folks to incorrectly assume a feature exists or type in a feature name incorrectly without noticing. For example in [this PR][1] I referenced a different version of the docs (cc #1867) and because my page continued to work (and because my testing was _rubbish_) I assumed it was OK.

I think it may be beneficial to be stricter and respond with a `400: Bad Request` when an invalid feature is requested to protect fools like me from tripping themselves up.

[1]: https://github.com/Financial-Times/n-ui/pull/1376

**Comment by JakeChampion** [comment]
I like this. It would be good for a v4 release

**Comment by JakeChampion** [comment]
We could add a new query parameter to enable a "strict" mode which could do this, that way we would not need to increment the API version number.
