### ISSUE TITLE
Node.prototype.textContent shim for IE8

### ISSUE THREAD

**Issue by usmonster** [polyfillpolyfill/polyfill-service#189]
(Originally at jonathantneal/polyfill#67.)

`.textContent` is not available in IE8, so I just wanted to know if there would be any interest in providing a polyfill for it. (Using IE's proprietary `.innerText` is often not sufficient, since it's [not really equivalent](https://developer.mozilla.org/docs/Web/API/Node.textContent#Differences_from_innerText).)

If so, I can spruce up the one I'd written for [aight](https://github.com/shawnbot/aight) ([original PR](/shawnbot/aight/pull/27), [current version](https://gist.github.com/usmonster/d15e4475e3983bd35dba)) and make a pull request.

I hadn't made a pull request earlier since I was waiting on #20 to know exactly what was expected in one (**note to self:** see also the [contributors' guide](https://cdn.polyfill.io/v1/docs/contributing)). Something to note is that this shim is currently only for IE8 standards mode, though I haven't yet looked into whether or not it's easy/possible to get it working in quirks mode, either by adding dependencies on other polyfills within the ecosystem or just by implementing a couple more parts of the spec. (It seems impossible to get it to work in IE<8.)

So outstanding questions are:
- Are all polyfills expected to work in both standards and quirks/compatibility modes?
- Does it matter if they're for HTML(5) only, or should they ideally work on, e.g., XHTML pages as well?
- Any feedback on what's currently in the abovelinked gist (assuming tests will be included in the PR)?
  - E.g., should it be divided into patches on other IE8 polyfills?

**Comment by evanleck** [comment]
I'd love to see a polyfill for this though I do not have any input on quirks vs. standards mode etc.

**Comment by monolithed** [comment]
+1

**Comment by usmonster** [comment]
Any feedback from project collaborators on the outstanding questions mentioned above? @triblondon, @jonathantneal, et al.?

**Comment by triblondon** [comment]
Hey @usmonster, thanks for this.  

> Are all polyfills expected to work in both standards and quirks/compatibility modes?

Both, though compat mode is often presented by the browser as a different UA string, so we can treat it differently anyway.  For example, IE9 in compat mode sends an IE7 UA header, in my testing.

> Does it matter if they're for HTML(5) only, or should they ideally work on, e.g., XHTML pages as well?

Ideally both

> Any feedback on what's currently in the abovelinked gist (assuming tests will be included in the PR)  E.g., should it be divided into patches on other IE8 polyfills?

Rather than testing for dependencies like `defineProperty` you can just assume they exist and express a dependency on them in the polyfill config. I would also suggest that you name it after `Element.prototype.textContent` but alias all the other equivalent properties.

 Otherwise it looks fine.

**Comment by usmonster** [comment]
Thanks for the feedback, @triblondon! I'll take a look at what I can do.

A compat mode test shouldn't necessarily depend on the UA string; one can just do something like `isCompatMode =  document.compatMode!=="CSS1Compat";`. If the shim turns out to only work in standards mode, should I use `detect.js` to prevent the polyfill from loading when in compat mode, or will the UA string be enough for the service to not even try to load it in those cases?

Adding XHTML support should just be a matter of shimming `textContent` for certain node types that aren't really found HTML (e.g., CDATA).

Okay for replacing dependency tests with dependency names in the config.

**Comment by triblondon** [comment]
Thanks.  Targeting should ideally be left to the UA identification, we'd rather not complicate by detecting that we're actually in an emulated browser.

**Comment by usmonster** [comment]
Ah, just wanted to be clear that when I say "compatibility mode" I'm not talking about IE's proprietary emulated browsing mode/feature. I mean the actual, [standardized](https://dom.spec.whatwg.org/#dom-document-compatmode) rendering mode of the document. For example, go to www.oocities.org in any browser and type [`document.compatMode`](https://developer.mozilla.org/docs/Web/API/Document/compatMode) in the JS console. It will have the value `"BackCompat"`, which is to say, quirks mode. You can be in actual IE8 and visit one page that will render in quirks mode and then another that will render in standards-compliant mode. The browser/version doesn't matter, and the userAgent string won't change in either case--it's just a function of the page, which is why I'm still a bit wary of using the UA string.. Thoughts?

**Comment by triblondon** [comment]
OK, but my understanding is that `document.compatMode` is different from Microsoft's proprietary 'compatibility view'.  The former does not change the user agent, so polyfills need to take that into account and may target the browser in either mode.  The latter does change the user agent, so we ignore it and assume that our server-side UA sniffing will deliver different polyfills to browsers in compatibility view.

I may be totally wrong about all this.

**Comment by usmonster** [comment]
You're correct, `document.compatMode` is a standardized property completely unrelated to MS/IE or UA strings. I'll just do a bunch of testing to see where the shim might fail and decide which checks I need (one or both or none) based on that. Thanks again for the feedback!

**Comment by triblondon** [comment]
@usmonster are you still doing this?

**Comment by usmonster** [comment]
Yes! Sorry there's been no movement; life. Thanks for the poke, in any case. I'll try to throw together a PR, or at least a new status update, in the next week or so.

**Comment by triblondon** [comment]
@usmonster consider this a final poke :-)
