### ISSUE TITLE
Unable to filter polyfills on website

### ISSUE THREAD

**Issue by schrags08** [polyfillpolyfill/polyfill-service#1895]
[type]: bug

## What
I'm unable to filter using the "type to filter by name" box on the website.

## Details
- I'd expect to be able to filter the list by typing in the name of a polyfill
- Reproduce by typing something in the box; nothing happens

![image](https://user-images.githubusercontent.com/3410491/53429011-68b1fb00-39b1-11e9-9dd7-4caecb4e8242.png)

**Comment by thomas-dm** [comment]
Not only that, but the features list doesn’t seem to be available anywhere, and the documentation for `v2` is gone.

In its current state, I find the website completely useless.

**Comment by JakeChampion** [comment]
This is fixed now 👍
