### ISSUE TITLE
Encoded commas in the `flags` parameter 

### ISSUE THREAD

**Issue by aaronmars** [polyfillpolyfill/polyfill-service#1910]
https://polyfill.io/v3/polyfill.js?flags=gated%2Calways

[type]: Bug in v2 & 3 API

## What
When a request is made to the API, the `flags` query param causes the request to fail if the comma is URL-encoded.

## Details
This is successful: `https://polyfill.io/v3/polyfill.js?flags=gated,always`
...and this fails: `https://polyfill.io/v3/polyfill.js?flags=gated%2Calways`

Interestingly, this behavior is not seen with the `features` query param. The following two requests return the same JS:
`https://polyfill.io/v3/polyfill.js?features=String.prototype.startsWith,String.prototype.includes&flags=always`
`https://polyfill.io/v3/polyfill.js?features=String.prototype.startsWith%2CString.prototype.includes&flags=always`

**Comment by aaronmars** [comment]
Updated issue to indicate that this is present in v2 as well.

**Comment by JakeChampion** [comment]
This has now been fixed and is live on polyfill.io 

![image](https://user-images.githubusercontent.com/1569131/54604994-0e500b80-4a40-11e9-9dec-586f4342933a.png)
![image](https://user-images.githubusercontent.com/1569131/54605002-1445ec80-4a40-11e9-8b02-e79e77a78604.png)

**Comment by aaronmars** [comment]
:+1: Thanks! Looks good.

**Comment by RiZKiT** [comment]
The issue still exists with %7C, when I create a bundle with https://polyfill.io/v3/url-builder/, e.g. with gated & always it creates https://polyfill.io/v3/polyfill.js?flags=gated%7Calways, then I get no polyfill at all.

**Comment by JakeChampion** [comment]
@RiZKiT I believe it should be gated%2Calways and not gated%7Calways. Let's make a new issue for this.

**Comment by RiZKiT** [comment]
Done: https://github.com/Financial-Times/polyfill-service/issues/1959
