### ISSUE TITLE
Wrong polyfill name for IntersectionObserver

### ISSUE THREAD

**Issue by stevesy** [polyfillpolyfill/polyfill-service#1913]
When adding the IntersectionObserver polyfill while creating a bundle, "IntersectionObserver-polyfill" is added to the query string. This is incorrect as it does not pull in the polyfill. Instead, "IntersectionObserver" should be added. The same applies for IntersectionObserverEntry.

**Comment by samuliasmala** [comment]
Actually the *-polyfill* ending is added to all polyfill query strings, not just the IntersectionObserver polyfill. Thus none of them is working out of the box. After manually removing the *-polyfill* like stevesy wrote, then they work nicely.

**Comment by matthieudou** [comment]
Same here, removing `-polyfill` works like a charm but the website is giving wrong informations

Thanks

**Comment by JakeChampion** [comment]
This has now been fixed and is live on polyfill.io
