### ISSUE TITLE
Fetch 3.0.0 includes export statements breaking IE

### ISSUE THREAD

**Issue by jakob-e** [polyfillpolyfill/polyfill-service#1914]
## What
Version 3.0.0 served on [https://github.com/github/fetch](https://github.com/github/fetch) includes **export** statements – making the polyfill break on non ES compatible browsers (e.g. IE11)
 

## Details
The **export** problem is isolated to version 3.0.0 – [previous version 2.0.4](https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.4/fetch.js) works

**Comment by JakeChampion** [comment]
we use 2.0.4 -- https://github.com/Financial-Times/polyfill-library/blob/master/package.json#L76
