### ISSUE TITLE
IntlPolyfill is not defined

### ISSUE THREAD

**Issue by joshsalverda** [polyfillpolyfill/polyfill-service#1924]
Bug Report

## What

I'm not even sure where the exact problem is... Maybe it was a Chrome update? Polyfill update? But either way I'm getting an error when referencing the latest v3 Intl polyfill. It was working fine a few days ago, so must have been a recent change/fix. 

The problem I'm seeing is Chrome (v 73.0.3683.75) is returning 0 for `Intl.Collator.supportedLocalesOf('nl').length`

For example: https://cdn.polyfill.io/v3/polyfill.min.js?features=Intl.~locale.en displays nothing as expected, but: https://cdn.polyfill.io/v3/polyfill.min.js?features=Intl.~locale.nl adds the respective polyfill code due to the above length check.

It's fine to include the code if the detection is accurate, but the problem is that it's throwing an error: `IntlPolyfill is not defined` when trying to include that locale polyfill. I'm assuming this is due to the check for adding Intl is only looking for `'Intl' in this`, and since that is supported in Chrome the IntlPolyfill object never gets added?

## Details

Not sure if it matters, but in v2 the same url for nl returns nothing in Chrome: https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.nl

**Comment by JakeChampion** [comment]
Chrome 73 should not get any polyfill for Intl.~locale.nl .

We can test this by either opening the url in chrome 73:
![image](https://user-images.githubusercontent.com/1569131/54543542-bbba1500-4995-11e9-9c5a-cc02c04abfd8.png)

Or by adding `ua=chrome/73` to the url:
![image](https://user-images.githubusercontent.com/1569131/54543614-dee4c480-4995-11e9-8741-2f8960f7df32.png)

Any Chrome version higher than 34 does not get the polyfill -- https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Intl/config.json#L8

If you can post a screenshot and a jsbin.com page which reproduces your error that would be extremely helpful for me :-)

**Comment by joshsalverda** [comment]
Well that's really weird... I thought maybe it was a Chrome issue on my end, so I reset all my settings, but still seeing the same thing.

It's even happening for every locale now, including english:

![Screen Shot 2019-03-18 at 12 16 23 PM](https://user-images.githubusercontent.com/3029989/54547302-d1224580-497b-11e9-80df-437fcf90282c.png)

I'm not sure if a jsbin will be useful, since it would just be a script pointing to the polyfill service url and an error in the console (or at least that's what it shows for me).

For further info these are my network headers:

![Screen Shot 2019-03-18 at 12 55 49 PM](https://user-images.githubusercontent.com/3029989/54547947-2ca10300-497d-11e9-916b-a7d45c0598a7.png)

I asked a few others to test out the url as well and they are also seeing the problem (they see all the polyfill code in their Chrome as well).

Trying to dig through the code to see where this might be occurring but I'm not super familiar with the code base so it's taking some time.

**Comment by JakeChampion** [comment]
If you can set a request header of `fastly-debug: 1`, then the response headers will contain lots of debug information which should hopefully help us figure out what is going on here.

I've tested the urls you've posted on Chrome 73 in many different locations round the world (Thanks to BrowserStack's location feature) and they all seem to return the correct response.

**Comment by joshsalverda** [comment]
Here are the response headers, including debug ones:

![Screen Shot 2019-03-19 at 10 14 05 AM](https://user-images.githubusercontent.com/3029989/54612674-c4f7c000-4a2f-11e9-97d5-2178b51bfb2b.png)

**Comment by joshsalverda** [comment]
FYI looks like this issue is fixed in the latest version, didn't realize it was related to #1922
