### ISSUE TITLE
Differences between v2 and v3?

### ISSUE THREAD

**Issue by Ugoku** [polyfillpolyfill/polyfill-service#1938]
Type: question

## What
We are currently using v2 of polyfill.io, but need to add an extra feature detection and I noticed v3 is current.

- However, I can't find what the differences are. Can I safely use v3 in the same way as v2?
- What happened to `features=default` ?

## Details
URL we currently use: https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Promise

## Additional information
Keep up the good work, this service saves us a lot of headache having to include polyfills ourselves!

**Comment by JakeChampion** [comment]
Thanks for the kind works :-)

We have a migration guide for moving from v2 to v3 --> https://github.com/Financial-Times/polyfill-service/blob/master/MIGRATION.md#migrating-from-v2-to-v3

`features=default` still exists.

If you wanted to use the same polyfills with the same settings as v2 but through the v3 api, your URL would be: https://cdn.polyfill.io/v3/polyfill.min.js?features=default,fetch,Promise&unknown=ignore&version=3.25.1

**Comment by Ugoku** [comment]
Ah thanks, I was looking for `changelog.md` and completely missed `MIGRATION.md`.

Thanks for your fast and clear response!
