### ISSUE TITLE
What are the defaults?

### ISSUE THREAD

**Issue by remy** [polyfillpolyfill/polyfill-service#1941]
The new site design is nice, but the default set of polyfill's being delivered is no longer clear - or even whether there _is_ a default set.

For instance, I thought that `fetch` was part of the default polyfill, but not I'm unsure. The only way I could check now is to manually parse this source: https://polyfill.io/v3/polyfill.js?flags=always … which isn't ideal.

**Comment by JakeChampion** [comment]
I have a work-in-progress pull-request for adding the aliases to the url-builder --> https://github.com/Financial-Times/polyfill-service/pull/1942

I'm not happy with the design but it is better than not showing them at all :-)

**Comment by JakeChampion** [comment]
https://polyfill.io/v3/url-builder/ now contains the sets/aliases and the tooltip for a specific set/alias contains the polyfills that it has.

**Comment by tamb** [comment]
I actually think this should be reopened.  

> It's a service which accepts a request for a set of browser features and returns only the polyfills that are needed by the requesting browser

This is unclear.  The use of the word "needed" is too vague.  I'm hoping to implement this in a large production app, however, I want to know the goal of the service.

Is a "needed" polyfill an ECMAScript feature that isn't supported in that browser?  Say, we are in the year 2019, does polyfill.io fill as many ES2019 features as possible as well as all missing features between the year of request and the version of the browser? 

So does IE11 automatically get ES2015 - ES2019?

The newer the browser, the fewer features are sent back?

So Firefox's latest may only receive a handful of features from ES2019?

Are feature set requests inclusive?  Do we send only the polyfills requested or do we send the polyfills needed and additionally the pollyfills requested

**Comment by JakeChampion** [comment]
> I actually think this should be reopened.

A new ticket would be better I believe as your questions are different to the original issue.

> > It's a service which accepts a request for a set of browser features and returns only the polyfills that are needed by the requesting browser
> 
> This is unclear. The use of the word "needed" is too vague. I'm hoping to implement this in a large production app, however, I want to know the goal of the service.
> 
> Is a "needed" polyfill an ECMAScript feature that isn't supported in that browser? Say, we are in the year 2019, does polyfill.io fill as many ES2019 features as possible as well as all missing features between the year of request and the version of the browser?

That's correct, if you ask for all ES5,ES6,ES2015,ES2016,ES2017,ES2018,ES2019 then you will get all those features which are missing or incomplete in the browser which makes the request.

> So does IE11 automatically get ES2015 - ES2019?

Only if you ask for all those features, if you only ask for `fetch`, we will only send `fetch` and whatever `fetch` depends on that IE11 does not have such as `Promise`.


> The newer the browser, the fewer features are sent back?

Yes, that's usually the case but sometimes a new browser ships with a broken feature and so we then would send it a polyfill which we don't send to older versions of the same browser, but that is rare nowadays.

> So Firefox's latest may only receive a handful of features from ES2019?

That's correct.

> Are feature set requests inclusive? Do we send only the polyfills requested or do we send the polyfills needed and additionally the pollyfills requested.

We send the polyfills which are requested by the website and are actually required by the browser, a website could ask for `fetch` and `Promise` but if the browser is the latest Firefox version which has both those features, we would return no polyfills in the response.
