### ISSUE TITLE
[BUG] IE11 - Cannot redefine non-configurable property 'find'

### ISSUE THREAD

**Issue by hstaniszewski** [polyfillpolyfill/polyfill-service#1949]
[BUG]

## What
The IE11 browser returns an error `Cannot redefine non-configurable property 'find'` when trying to use polyfill `features=default,es6` on page, which already has the `Array.prototype.find` with attribute `configurable: false` defined.

## Details
I believe that polyfill should not cause an error in this case. Here is a link with reproduction example:
https://jsfiddle.net/xk8afqbu/

Environment:
Browser: Internet Explorer 11

**Comment by kameliyon** [comment]
What was the resolution to this? I am having a similar issue trying to use polyfill with C# Blazor and am getting this error in IE11 `Cannot redefine non-configurable property 'includes'`

**Comment by JakeChampion** [comment]
@aHulswitt36 can you please post the full polyfill.io url you are using and the full user-agent string of the browser which sees the error please? If any extra code needs to run to make the error occur, could you also post that as well :-)

With that information I should be able to help debug the issue

**Comment by kameliyon** [comment]
url: https://polyfill.io/v3/polyfill.min.js?features=fetch
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; NMTE; rv:11.0) like Gecko

I get the error on the home page, where nothing else runs. 

Thanks!

**Comment by JakeChampion** [comment]
@aHulswitt36 Can you post a link to a page where I can reproduce the issue please?

I used IE11 and opened a page with only that polyfill.io url and it all works.
This is the page I used to test it -- https://jsbin.com/yirihubiye/edit?html,console,output

![bs_win8 1_IE_11 0](https://user-images.githubusercontent.com/1569131/81201039-b3b79d00-8fbc-11ea-8f47-6628dd736f94.jpg)
![bs_win8 1_IE_11 0(1)](https://user-images.githubusercontent.com/1569131/81201049-b6b28d80-8fbc-11ea-9b97-117f4da426e4.jpg)

**Comment by kameliyon** [comment]
@JakeChampion  Sorry! It appears it has something to do with the order of other js files being imported.  If I put the polyfill url at the very top of the `<head>` it works just fine.   I can try and track down what other library might be causing the issue and report back, if you'd like.
