### ISSUE TITLE
[ SCRIPT1003: Expected ':'  ]  in IE11

### ISSUE THREAD

**Issue by ghost** [polyfillpolyfill/polyfill-service#1951]
A bug

## What

Getting this error in IE11 `SCRIPT1003: Expected ':'` which means short-hand functions is not supported in IE11
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions
## Details

	- Browser ( IE 11 )

A related babel plugin :
@babel/plugin-transform-shorthand-properties

**Comment by JakeChampion** [comment]
We don't use object property shorthand notation in our polyfills, we author everything in ES3 so I don't think it will be an issue on our side of things.

What is the full polyfill.io url you are using?

**Comment by ghost** [comment]
I have added this:
`<script crossorigin="anonymous" href="https://polyfill.io/v3/polyfill.min.js"></script>`

**Comment by JakeChampion** [comment]
Okay, the issue is not one in polyfill.io but one somewhere in your application I believe. I'll be closing this issue as I believe that to be the case.

If you have a stacktrace or anything else which points more towards polyfill.io, please comment on this issue and I can re-open it.
