### ISSUE TITLE
[V3]: Object assign polyfill IE11 not working

### ISSUE THREAD

**Issue by JonathanCallewaert** [polyfillpolyfill/polyfill-service#1953]
## What
Hi, 
I'am working with React and used some polyfills. All these polyfills work except the Object.assign polyfill.
I get this error: 
![image](https://user-images.githubusercontent.com/17174776/56211672-a7327080-6058-11e9-8ee5-59de6e308019.png)
At first sight, this doesn't look like a bug in Object.assign, but if I'm adding Object.assign of Polyfill V2, I don't get this error.

I'm working with IE11 on windows 10

**Comment by JakeChampion** [comment]
Hi @JonathanCa97, could you please post the full polyfill.io url you are using and some code to trigger the error please? A good place to put this stuff is in a new jsbin.com project and posting the link as a comment on this issue.

Without that type of information it will be very difficult to help resolve this issue.

**Comment by KevinDenys** [comment]
Works on IE 11: https://cdn.polyfill.io/v2/polyfill.min.js?features=Object.assign&flags=gated,always 
Does not work on IE 11: https://polyfill.io/v3/polyfill.min.js?features=Object.assign&flags=gated,always

**Comment by KevinDenys** [comment]
After some more debugging when we added "gated" to the flags it started working.

https://polyfill.io/v3/polyfill.min.js?features=Object.assign&flags=gated,always
