### ISSUE TITLE
[Feature]: allow `encodedFeatures` query param

### ISSUE THREAD

**Issue by nicksrandall** [polyfillpolyfill/polyfill-service#1954]
## What
I'm working on a tool that is functionally very similar to `@babel/preset-env` in that it inspects the AST of your JavaScript code and finds all the features that are being used that potentially need to be polyfilled. The tool then automatically generates a Polyfill.io URL for you to insert as a script tag in your document.

In large projects, these URLs can get quite long (because they include several polyfills) and in some cases, they can get longer than is allowed by Internet Explorer (2082 chars). 

In these extreme cases where the URL is very long, I'd like to gzip and then url-safe base64 encode the features list to shorten the length of the URL. 

I'm thinking it would make sense for users to opt into this feature by including a `encodedFeatures` query param instead of the usual `features` query param. 

In any case where the user has included the `encodedFeatures` query param, this service would need to decompress that value before it is passed to the `polyfill-library`.

## Details
Here is an example of a really long URL (2113 chars): 

```text
https://polyfill.io/v3/polyfill.min.js?features=Array.from%2CArray.isArray%2CArray.prototype.%40%40iterator%2CArray.prototype.entries%2CArray.prototype.every%2CArray.prototype.fill%2CArray.prototype.filter%2CArray.prototype.find%2CArray.prototype.findIndex%2CArray.prototype.forEach%2CArray.prototype.includes%2CArray.prototype.indexOf%2CArray.prototype.keys%2CArray.prototype.lastIndexOf%2CArray.prototype.map%2CArray.prototype.reduce%2CArray.prototype.slice%2CArray.prototype.some%2CArray.prototype.values%2CArrayBuffer%2CBlob%2CCustomEvent%2CDOMTokenList.prototype.%40%40iterator%2CDataView%2CDate.now%2CDate.prototype.toISOString%2CDocumentFragment.prototype.append%2CElement%2CElement.prototype.after%2CElement.prototype.append%2CElement.prototype.before%2CElement.prototype.classList%2CElement.prototype.cloneNode%2CElement.prototype.matches%2CElement.prototype.placeholder%2CElement.prototype.remove%2CEvent%2CEventSource%2CFunction.prototype.bind%2CFunction.prototype.name%2CIntl%2CJSON%2CMap%2CMath.log10%2CMath.log2%2CMutationObserver%2CNode.prototype.contains%2CNodeList.prototype.%40%40iterator%2CNodeList.prototype.forEach%2CNumber.parseFloat%2CNumber.parseInt%2CObject.assign%2CObject.create%2CObject.defineProperties%2CObject.defineProperty%2CObject.entries%2CObject.freeze%2CObject.getOwnPropertyDescriptor%2CObject.getOwnPropertyNames%2CObject.getPrototypeOf%2CObject.isFrozen%2CObject.keys%2CObject.preventExtensions%2CObject.seal%2CObject.setPrototypeOf%2CObject.values%2CPromise%2CPromise.prototype.finally%2CSet%2CString.prototype.%40%40iterator%2CString.prototype.includes%2CString.prototype.trim%2CSymbol%2CSymbol.isConcatSpreadable%2CSymbol.iterator%2CSymbol.species%2CSymbol.toPrimitive%2CSymbol.toStringTag%2CUint8Array%2CUint8ClampedArray%2CWeakMap%2CWeakSet%2CWebAnimations%2CXMLHttpRequest%2Cconsole.error%2Cconsole.info%2Cconsole.log%2Cconsole.trace%2Cconsole.warn%2Cdocument%2Cdocument.currentScript%2Cdocument.head%2Cdocument.querySelector%2Cfetch%2CgetComputedStyle%2ClocalStorage%2Clocation.origin%2CmatchMedia%2Cperformance.now%2CrequestAnimationFrame%2CsetImmediate&flags=gated
```

What I am proposing is that we optionally accept a URL like so (only 1053 chars): 
```text
https://polyfill.io/v3/polyfill.min.js?encodedFeatures=H4sIAAAAAAAAE31VbW_aMBD-Nf0aTdP-AGVhQypQFSb2rTqcS-I19mW2Q5v9-p2dQNziVELYzz13tu81C2Ogz6Rd-PXu6zKsGZXXbWlIXUFryJHrW8wEtf1RulrqBHn37Qv_pEMDjkxCAbUzEm2KOaPpE_JSNk1azLckCV2sdYFvM1xK3ICbEW-gTTBSi6Yrkm6UZHIQddKIH7UrE8wL9qmjVPLuBqxbzx5lSWFCfIamG57bFZKWpB2-eZfvGzrxsuysI5WfOTuMvu82B3pB_SBtgOAw0_TqtyQ6xUorA5UalT-Ioktbgy2GgH-iBO2okzc4HjnuYqVyyHWC-WAeUSfkXGCSEhxEO7qXYknjloo5W7I4Y1mAA4tpzqCic_rIKVAJrgGBNTXFTAAUOFGH1KauDNa-Wz0_pjesWQ22FjXoCq-ikrNkQ1uvOi2cJB1Hc2idBKMhlNzPw-bhkucRPkrhOoNTZtdcd8ZiOGF3smjOwauUOOdB0Q-cb_-hDzfg6gz4jfUVCLITcDAx4mTcZV_3LQXQOfhwt8_zu-mmHUhtR8bXyGfjbdupE5pss_j9vF-s8uf19pD_yJ8mRtqV1GwQS7y7FZpYtIUtw93pDweBHbSy0hMWBiGcMOICeY7ho6EWjRuGaYrpJ7mMdCp0u1d90dly8mysuDL0D6PLx9k0ouscYXslrX_UPtT7nse6rt7XHkKSaaHYOzBzXB7q7IaJRu4Nx71jxyK_4W5SdqPB2H_nfnFJHKRizoOnB_4_IrwMhed3g6NHPC20VKGM_GOO3BdhNvLxfpRyAVlqcNr5dGLw9iIQDYKJcCFj1FAVIalLiqCTCocAxRKGxdh5meiM4XUvjGxdTHDex0a09_3SD8AtvDetEfzJJbrw_WKDJam2c8j56oNLDQlo9hxHqC4wDAMysgqDI0yjDRYSGBj8y8XiruHi6R8utFzQGIz41sB4Ibq1Ut7S4X8N4JZFmwgAAA&flags=gated
```

One concern I have is that we'd be tied to a specific implementation of "URL safe" base64.

## Additional information
In my testing, the decoding of these encoded values is very fast (under 1ms).

Here is some pseudo-code that shows what an implementation could look like:

```js
// /server/lib/get-polyfill-parameters.js
"use strict";

const latestVersion = require("polyfill-library/package.json").version;
const featuresfromQueryParam = require("./features-from-query-parameter");
const { gunzipSync } = require('zlib');
const { unescape } = require("base64-url");


module.exports = function getPolyfillParameters(req = {}) {
	const query = req.query || {};
	const path = req.path || "";
	const { excludes = "", rum, unknown = "polyfill", version, callback, encodedFeatures } = query;
	const uaString = query.ua || (req.headers && req.headers["user-agent"]) || (typeof req.get === "function" && req.get("User-Agent")) || "";
	const compression = query.compression !== "identity" ? query.compression : undefined;
	
	let features = query.features || "default";
	if (query.encodedFeatures) {
		features = gunzipSync(
			Buffer.from(unescape(query.encodedFeatures), "base64")
    	).toString("utf8");
	}

	return {
		excludes: excludes ? excludes.split(",") : [],
		features: featuresfromQueryParam(features, query.flags),
		minify: path.endsWith(".min.js"),
		rum: Number.parseInt(rum, 10) === 1,
		stream: false,
		callback: /^[\w\.]+$/.test(callback || "") ? callback : false,
		unknown,
		uaString,
		version: version || latestVersion,
		compression
	};
};

```

I'm happy to open up a PR if the maintainers are open to this contribution.

**Comment by JakeChampion** [comment]
Hi @nicksrandall, excellent idea with regards to detecting what features you are using, I attempted the same thing with a babel plugin, are you going to open source your work? I'd love to help with it.

I think we can avoid adding an encodedFeatures if we instead improve the system you have to use `polyfill-library` and figure out what polyfill sets could be used together to cover all the features that were detected.

**Comment by nicksrandall** [comment]
Hi @JakeChampion. This project is not Open Source *YET*, but hopefully it will be soon. With regard to using "polyfill sets" are you referring to the "ES6", "ES7", ect. feature values? My fear there is that we'll be including more polyfills that we need.

**Comment by JakeChampion** [comment]
That is what I am suggesting, yes, but only using a "polyfill set" if all the polyfills in the set are ones which are required by the application. E.G. We can make an Array polyfill set which contains all array methods and then if your application uses all the array methods, you would only need to add "Array" to the features query parameter.

**Comment by nicksrandall** [comment]
@JakeChampion Hi, sorry I had to step away for a bit. I think what you're suggesting would work for 95% of use cases but there could still be a case where an application uses lots of different polyfills *except* one from every "set" and therefore could still run into the URL being too long. 

My proposal would be a worst-case-scenario solution for when we've exhausted every other means that we could shorten the url (including your set proposal).

As I mentioned above, this can be implemented with a few lines of code and, IMO, does not add much complexity to the code base.

**Comment by JakeChampion** [comment]
@nicksrandall Is your tool similar to this project? https://github.com/JakeChampion/js-features-analyser

**Comment by nicksrandall** [comment]
@JakeChampion yes, very similar.

My version includes a babel plugin and a webpack plugin but it does not *yet* have a CLI (I didn't think of that). 

We're using it internally at my company and will hopefully *soon* open source it.

That said, I'm happy to collaborate with you if you're open to it.

**Comment by JakeChampion** [comment]
@nicksrandall, 100% open to collaboration :-)

**Comment by JakeChampion** [comment]
@nicksrandall Have you found out how to correctly infer the instance method being used based upon the type of the object it is called on?
I.E.
```js
function example (a, b) {
  return a.includes(b);
}

example(new Uint16Array(10), 0)
```
should detect Uint16Array, Uint16Array.prototype, Uint16Array.prototype.includes and not Array.prototype.includes.

**Comment by nicksrandall** [comment]
My approach copies the approach here: https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/polyfills/corejs3/usage-plugin.js

We just detect the usage of `.includes()` method and add `Array.includes` and `TypedArray.includes` polyfill because it *might* be either of them. 

We would even include the polyfill if neither item was an Array (ex `someObj.includes()`)

It would be nice to make the logic smarter but we're not there yet. I figure it's better to over polyfill than under polyfill.

**Comment by andrew--r** [comment]
Also had an idea to generate polyfill.io URL based on used features, so glad to see some progress already made!

If there are any other unsolved problems, please share it, I might try to help.

**Comment by JakeChampion** [comment]
@andrew--r and @nicksrandall, I published an update to the tool and now it reads your browserslist config file and builds the polyfill.io url with that and your javascript bundle -- https://twitter.com/JakeDChampion/status/1158525125467287552

**Comment by JakeChampion** [comment]
Closing this issue as we won't be implementing an encoded features query parameter and there are now tools which can build a polyfill.io URL without requiring that feature. 

If you think this issue should be reopened, please comment on it with your use case for the feature and if none of the above tools solve it
