### ISSUE TITLE
Polyfill Builder uses pipe instead of comma to seperate flags

### ISSUE THREAD

**Issue by RiZKiT** [polyfillpolyfill/polyfill-service#1959]
Bug report

The polyfill builder (https://polyfill.io/v3/url-builder/) generates url's, where the flags are separated with encoded pipe symbols "%7C" instead of encoded commas "%2C". 

A similar issues regarding the acceptance of encoded commas is here: https://github.com/Financial-Times/polyfill-service/issues/1910.

**Comment by JakeChampion** [comment]
This has been done in https://github.com/Financial-Times/polyfill-service/commit/0ddd17dfbbaa5585a6bd4d570d63baa9393791de
