### ISSUE TITLE
[feature-request]: Provide UserAgent Parsing Feature For Consumers

### ISSUE THREAD

**Issue by derekdowling** [polyfillpolyfill/polyfill-service#1961]
### Feature Request

It would be extremely useful for the Polyfill Service to be able to include the client's general platform, device, OS, and browser characteristics (derived from the requestor's UserAgent header) and attach that information as a global variable on window as part of the polyfill script execution. This information would could then be read by the consuming application and used for purposes such as tracking, differentiating product features by platform (obviously not a good idea to use this as a proxy for Browser API feature detection), app behavior, etc. This seems like a great feature because:

- Polyfill Service already does extensive UserAgent parsing
- UserAgent parsing libraries are very large to include in client application bundles especially if they are exhaustive
- The script download from this service is already blocking in most SPA initialization flows so there wouldn't be a race condition
- with the growth of the Mobile Web / Progressive Web App's, doing User Agent parsing is more or less inevitable if you want to link to Native App stores, implement iOS/Android specific features, etc

To opt into this, the Polyfill consumer would provide a new query param in the script URL (admittedly not sure how this would work at a detailed level surrounding your API conventions) allowing them to opt into this feature. The variable that this information is assigned to on window could be static, or customized and defined as a query parameter key/value pair: `/polyfill.js?parseUA=ua_client_info`.

Then on the client after the polyfill script has downloaded and executed, you can consume that information like so:
```
console.log(window.ua_client_info);

/* Example output from a UA parser called [Bowser](https://github.com/lancedikson/bowser) for inspiration:
{
  browser: {
    name: "Internet Explorer"
    version: "11.0"
  },
  os: {
    name: "Windows"
    version: "NT 6.3"
    versionName: "8.1"
  },
  platform: {
    type: "desktop"
  },
  engine: {
    name: "Trident"
    version: "7.0"
  }
}
*/
```

**Comment by JakeChampion** [comment]
Hi @derekdowling, I don't think this is a feature we would have for polyfill.io as it is not a polyfill and all this service should ever do is serve polyfills. If there was a proposal for the feature you want to be added to the web platform in some manner, then we could implement that as a polyfill once it has been implemented in multiple user-agents. We follow the advice given by the W3C TAG about when to implement a polyfill --> https://www.w3.org/2001/tag/doc/polyfills/#don-t-squat-on-proposed-names-in-speculative-polyfills
