### ISSUE TITLE
Add polyfill on url builder itself, attempt 2

### ISSUE THREAD

**Issue by hkmaly** [polyfillpolyfill/polyfill-service#1964]
Considering you already have the polyfill, can you add it on your page itself? Specifically, on https://cdn.polyfill.io/v3/url-builder with Chrome 55 I get the bundle url as https://polyfill.io/v3/polyfill.min.js?%5Bobject+Object%5D= regardless of what I select. I suppose you are using some feature not available in it ...

Note that https://cdn.polyfill.io/static/polyfills.js is returning 404 and is referenced on that page ... and I also see this error:
```
jquery.js:19 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-0wIoD60yL42+1XJUY22zM8LflSmtzRyZIjM0qasci88='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
jquery.js:19 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-+1gZjPThUpVdzUAk0dH9fwK52R9/GjM+bgt7zsawajs='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

Note that I already submitted this as #1873 but someone else commented on that bug and you fixed just what he reported and not my original complain.

**Comment by JakeChampion** [comment]
Hi @hkmaly, sorry for not seeing your issue.

I can't see https://cdn.polyfill.io/static/polyfills.js referenced on https://cdn.polyfill.io/v3/url-builder  at all, that must have been an older version of the page, could you do a hard-refresh and see if you still see it being referenced?

Looking at the JavaScript being used on the page, we are using these features which may require polyfills:
- Object.keys
- URLSearchParams
- Object.assign
- Array.from
- Array.prototype.forEach
- Event
- Object.entries
- Array.prototype.includes
- Element.prototype.classList
- Array.prototype.filter
- Array.prototype.reduce
- requestAnimationFrame
- Element.prototype.closest
- Element.prototype.matches
- Function.prototype.bind
