### ISSUE TITLE
Expired token for fastly - breaks CI

### ISSUE THREAD

**Issue by DanielRuf** [polyfillpolyfill/polyfill-service#1966]
## What
Currently CI is failing because the token for fastly has expired on 2019-05-01.
See https://circleci.com/gh/Financial-Times/polyfill-service/13704

## Details

CI should be running. But currently it does not on CircleCI because the token for fastly has expired.

> Error: fastly_service_v1.app (import id: 2l7QhcR5rkdg691tcdRTD7): 1 error(s) occurred:
> 
> * import fastly_service_v1.app result: 2l7QhcR5rkdg691tcdRTD7: fastly_service_v1.app: [WARN] Error listing services (2l7QhcR5rkdg691tcdRTD7): 401 - Unauthorized
Message: Token 3RiIwJRqEEsoS2dUrtX24f expired at 2019-05-01T09:00:00Z

**Comment by JakeChampion** [comment]
Thanks @DanielRuf, my alert for this didn't seem to fire, I'll look into that now. I've updated the token and the deployment is on the way now 👍

**Comment by DanielRuf** [comment]
It's green now 🚀 🎉 
https://github.com/Financial-Times/polyfill-service/runs/133910198
https://circleci.com/workflow-run/02eccaa1-919d-4c81-be3e-c52c384a8784
