### ISSUE TITLE
[bug-report] Bad request when URL is too long

### ISSUE THREAD

**Issue by paramaggarwal** [polyfillpolyfill/polyfill-service#1967]
## What

Currently the API of polyfill.io is to expect a long list of JS features in the URL. This will cause issues sooner or later once the URL starts becoming very long.

To test the extreme case, I went to https://polyfill.io/v3/url-builder/ and selected all the polyfills and [got this really long URL](https://polyfill.io/v3/polyfill.min.js?features=blissfuljs%2Cdefault%2Ces2015%2Ces2016%2Ces2017%2Ces5%2C~viewport%2C~html5-elements%2CsetImmediate%2Cscreen.orientation%2CrequestIdleCallback%2CrequestAnimationFrame%2Cperformance.now%2Cnavigator.sendBeacon%2Cnavigator.geolocation%2CmatchMedia%2Clocation.origin%2ClocalStorage%2CgetComputedStyle%2Cfetch%2Cdocument.visibilityState%2Cdocument.querySelector%2Cdocument.getElementsByClassName%2Cdocument.head%2Cdocument.currentScript%2Cdocument%2CdevicePixelRatio%2Cconsole.warn%2Cconsole.trace%2Cconsole.timelineEnd%2Cconsole.timeline%2Cconsole.timeStamp%2Cconsole.timeEnd%2Cconsole.time%2Cconsole.table%2Cconsole.profiles%2Cconsole.profileEnd%2Cconsole.profile%2Cconsole.markTimeline%2Cconsole.log%2Cconsole.info%2Cconsole.groupEnd%2Cconsole.groupCollapsed%2Cconsole.group%2Cconsole.exception%2Cconsole.error%2Cconsole.dirxml%2Cconsole.dir%2Cconsole.debug%2Cconsole.clear%2Cconsole.count%2Cconsole.assert%2Cconsole%2Catob%2CXMLHttpRequest%2CWindow%2CWebAnimations%2CWeakSet%2CWeakMap%2CUserTiming%2CURL%2CSymbol.unscopables%2CSymbol.toStringTag%2CSymbol.toPrimitive%2CSymbol.split%2CSymbol.species%2CSymbol.search%2CSymbol.replace%2CSymbol.match%2CSymbol.iterator%2CSymbol.isConcatSpreadable%2CSymbol.hasInstance%2CSymbol%2CString.prototype.trim%2CString.prototype.startsWith%2CString.prototype.repeat%2CString.prototype.padStart%2CString.prototype.padEnd%2CString.prototype.includes%2CString.prototype.endsWith%2CString.prototype.codePointAt%2CString.prototype.%40%40iterator%2CString.fromCodePoint%2CSet%2CRegExp.prototype.flags%2CPromise.prototype.finally%2CPromise%2CObject.values%2CObject.setPrototypeOf%2CObject.seal%2CObject.preventExtensions%2CObject.keys%2CObject.isSealed%2CObject.isFrozen%2CObject.isExtensible%2CObject.is%2CObject.getPrototypeOf%2CObject.getOwnPropertyNames%2CObject.getOwnPropertyDescriptor%2CObject.freeze%2CObject.entries%2CObject.defineProperty%2CObject.defineProperties%2CObject.create%2CObject.assign%2CNumber.parseInt%2CNumber.parseFloat%2CNumber.isSafeInteger%2CNumber.isNaN%2CNumber.isInteger%2CNumber.isFinite%2CNumber.MIN_SAFE_INTEGER%2CNumber.MAX_SAFE_INTEGER%2CNumber.Epsilon%2CNodeList.prototype.forEach%2CNodeList.prototype.%40%40iterator%2CNode.prototype.contains%2CMutationObserver%2CMath.trunc%2CMath.tanh%2CMath.sinh%2CMath.sign%2CMath.log2%2CMath.log1p%2CMath.log10%2CMath.imul%2CMath.hypot%2CMath.fround%2CMath.expm1%2CMath.cosh%2CMath.clz32%2CMath.cbrt%2CMath.atanh%2CMath.asinh%2CMath.acosh%2CMap%2CJSON%2CIntl%2CIntersectionObserverEntry%2CIntersectionObserver%2CHTMLPictureElement%2CHTMLDocument%2CHTMLCanvasElement.prototype.toBlob%2CFunction.prototype.name%2CFunction.prototype.bind%2CEventSource%2CEvent.hashchange%2CEvent.focusin%2CEvent%2CElement.prototype.toggleAttribute%2CElement.prototype.replaceWith%2CElement.prototype.remove%2CElement.prototype.prepend%2CElement.prototype.placeholder%2CElement.prototype.matches%2CElement.prototype.dataset%2CElement.prototype.closest%2CElement.prototype.cloneNode%2CElement.prototype.classList%2CElement.prototype.before%2CElement.prototype.after%2CElement.prototype.append%2CElement%2CDocumentFragment.prototype.prepend%2CDocumentFragment.prototype.append%2CDocumentFragment%2CDate.prototype.toISOString%2CDate.now%2CDOMTokenList.prototype.%40%40iterator%2CDOMTokenList%2CCustomEvent%2CBlob%2CAudioContext%2CArray.prototype.values%2CArray.prototype.some%2CArray.prototype.reduceRight%2CArray.prototype.reduce%2CArray.prototype.map%2CArray.prototype.lastIndexOf%2CArray.prototype.keys%2CArray.prototype.indexOf%2CArray.prototype.includes%2CArray.prototype.forEach%2CArray.prototype.flatMap%2CArray.prototype.flat%2CArray.prototype.findIndex%2CArray.prototype.find%2CArray.prototype.filter%2CArray.prototype.fill%2CArray.prototype.every%2CArray.prototype.entries%2CArray.prototype.copyWithin%2CArray.prototype.%40%40iterator%2CArray.of%2CArray.isArray%2CArray.from%2Ces7%2Ces6) which is 4kb in size!

## Details

The above URL gives a 400 Bad Request in Google Chrome. Even if it works, this pattern of accepting list of feature names in URL might cause issues in future.

**Comment by JakeChampion** [comment]
We have aliases which are for groups of polyfills, I believe aliases avoids the issue you have mentioned. 
The aliases are listed at the top of the list on the url-builder page.

Some examples aliases are:
- `es5`
- `es6`
- `es7`
- `all` <-- That one is deprecated but is how you can request all polyfills.
