### ISSUE TITLE
Are there plans to update the polyfill-service package

### ISSUE THREAD

**Issue by bimbiltu** [polyfillpolyfill/polyfill-service#1969]
## What

I see that the [polyfill-service](https://www.npmjs.com/package/polyfill-service) npm package was last updated 6 months ago but there have been updates to the service since then. Are there plans to publish the updated service to NPM?

## Details
I have been using the polyfill-service npm package to self host a copy of this service and noticed today that it had not been updated in a while. Is the recommended way to host this service now just to fork the repo or download a tarball from the [releases](https://github.com/Financial-Times/polyfill-service/releases) page instead?

**Comment by JakeChampion** [comment]
The npm package was meant for people to use the programmatic API for the polyfill-service, which is now in a separate package called [polyfill-library](https://www.npmjs.com/package/polyfill-library).

You are correct, the recommended way to host a copy of the service would be to either download a tarball or to clone the repo and checkout the specific tag of the service you are wanting to use.

I'll be closing this issue as I believe we have answered your question, please do comment on this issue if you have any other questions about this :-)
