### ISSUE TITLE
Promise.prototype.finally not working on Edge 

### ISSUE THREAD

**Issue by marwan2** [polyfillpolyfill/polyfill-service#1999]
I added
https://polyfill.io/v3/polyfill.js?features=Promise.prototype.finally

But when I tested it on Microsoft Edge 17, it didn't work

**Comment by JakeChampion** [comment]
Hi @marwan2, could you please post the full user-agent string of the browser you are seeing this issue with?

It looks to work correctly when we explicitly set edge/17 as the ua https://polyfill.io/v3/polyfill.js?features=Promise.prototype.finally&ua=edge/17

**Comment by marwan2** [comment]
Just added it to my app header

<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=Promise.prototype.finally"></script>

**Comment by marwan2** [comment]
OK how can I include all EDGE versions 15 to 18 ?

**Comment by JakeChampion** [comment]
>But when I tested it on Microsoft Edge 17, it didn't work

How did you test it? Could you post the code you use to test it please?

Here is a JSBin page with some test code which you can use to prove it works or fails.
https://jsbin.com/sujukigoro/1/edit?html,console

Here is a screenshot of the test code being run in Edge 17 and working.
![bs_win10_Edge_17 0 (2)](https://user-images.githubusercontent.com/1569131/61725680-1f02ec00-ad68-11e9-9a12-823bcda4bcd0.jpg)

**Comment by JakeChampion** [comment]
It's done automatically by the service, we serve that polyfill to all edge
browsers
https://github.com/Financial-Times/polyfill-library/blob/55fda2f7fafa93cdb336c9113ad1062b38dd1e99/polyfills/Promise/prototype/finally/config.toml#L21
