### ISSUE TITLE
server issue? no content generated.

### ISSUE THREAD

**Issue by rmesser** [polyfillpolyfill/polyfill-service#2011]
When I browse to https://polyfill.io/v3/polyfill.js?features=default , I currently get this reply:
```
/* Polyfill service v3.38.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * Features requested: default
 *  */


/* No polyfills found for current settings */
```

I've tried various other settings and still get nothing. Is there a server issue perhaps?

**Comment by JakeChampion** [comment]
If you are using a browser which already has all the features that were requested then polyfill.io will not return any polyfills. Have you tried opening the link in a older browser such as Internet Explorer 11?

**Comment by rmesser** [comment]
Ok, I didn't realize that you could only download polyfills targeted at your current browser. I was able to switch over to IE11 using browserstack and get it to generate polyfills. So I will close this issue. As a side note it might be a useful feature request to allow an option to create files for browsers other than the current one, just to avoid the need to hop around to different browsers to generate polyfills.

In any event, thanks for your reply.

**Comment by quantuminformation** [comment]
Can we add a feature so that we get the requested polyfills? I need to copy paste the result over to an embedded system with no devtools.

**Comment by notlee** [comment]
hey @QuantumInformation, set the [flags query param](https://polyfill.io/v3/api/#request) to `always` to return the polyfills regardless of the current browsers support. There's also a `gated` flag to wrap every polyfill within feature detection, to only use the polyfill if the feature was not detected 

e.g. https://polyfill.io/v3/polyfill.min.js?features=Array.from&flags=always,gated

**Comment by quantuminformation** [comment]
Ah excellent work thanks !

**Comment by quantuminformation** [comment]
Have you ever seen an error like

`console.log(...) is not a function` I started getting that when I added

I started getting that when I added https://polyfill.io/v3/polyfill.js?features=Map&flags=always 
just after a console.log.

![image](https://user-images.githubusercontent.com/216566/73927148-bffe6200-48c8-11ea-8c0d-9124fd131f0f.png)


 If I remove that log I get other errors like:

![image](https://user-images.githubusercontent.com/216566/73927210-da384000-48c8-11ea-9ff5-25585dbbba2c.png)

**Comment by JakeChampion** [comment]
If using the always flag you should also used the gated flag to ensure the polyfill is only applied when the user-agent does not already have the feature natively, that will likely fix the issue you are having 

https://polyfill.io/v3/polyfill.js?features=Map&flags=always,gated
