### ISSUE TITLE
In chrome39, 'polyfill.io/v3' not has the 'Object.values()' function

### ISSUE THREAD

**Issue by magicbing** [polyfillpolyfill/polyfill-service#2015]
I import the script tag in html

<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js"></script>

But in chrome39, 'polyfill.io/v3' not has the 'Object.values()' function

**Comment by JakeChampion** [comment]
Hi @magicbing, you will need to add Object.values to the `features` query parameter like so:
https://polyfill.io/v3/polyfill.js?features=default,Object.values

We can show it is served to Chrome 39 by adding `ua=chrome/39` like so:
https://polyfill.io/v3/polyfill.js?features=Object.values&ua=chrome/39

**Comment by magicbing** [comment]
> Hi @magicbing, you will need to add Object.values to the `features` query parameter like so:
> https://polyfill.io/v3/polyfill.js?features=default,Object.values
> 
> We can show it is served to Chrome 39 by adding `ua=chrome/39` like so:
> https://polyfill.io/v3/polyfill.js?features=Object.values&ua=chrome/39

It works, thanks.
