### ISSUE TITLE
[bug] Focusin, focusout polyfill is not gated.

### ISSUE THREAD

**Issue by Psithief** [polyfillpolyfill/polyfill-service#2017]
## What

The polyfill for Event.focusin and Event.focusout are always executed because there is no feature detection wrapping it.

## Details

* Expected behaviour: Polyfill uses feature detection when the `gated` URL parameter is specified.
* Actual behaviour: Polyfill always executes because feature detection is absent. This causes an additional `focusin` event to fire and almost certainly the same applies to `focusout`.

**Comment by JakeChampion** [comment]
Hi @Psithief, thanks for reporting this issue.

It turns out that this is because Event.focusin did not have a feature detect. I've have just added one today and it should be going out in the next release of polyfill-library and polyfill-service.
