### ISSUE TITLE
EventSource polyfill not working on IE

### ISSUE THREAD

**Issue by gunnarsireus** [polyfillpolyfill/polyfill-service#2028]
I have an Angular application which I try to make running on Internet Explorer. I do get a lot of errors, one fo them was about EventSource missing. Then I added the EventSource polyfill which resulted in the following error:

SCRIPT5022: EventSource's response has a status 404 Not Found that is not 200. Aborting the connection.
polyfill.min.js (3,17044)

**Comment by JakeChampion** [comment]
@gunnarsireus This is not an issue with the polyfill. That error is saying the URL does not exist, either the URL you are using as the source of the EventSource has a spelling mistake or the server has not been configured correctly to serve a response for that URL. You will need to double-check the URL you are using is spelt correctly and that that server does respond to a request for that URL.
