### ISSUE TITLE
[bug] CORS error

### ISSUE THREAD

**Issue by Slessi** [polyfillpolyfill/polyfill-service#2032]
## What
As per https://polyfill.io/v3/url-builder/ when using the "Copy HTML to clipboard" functionality, you are given the following HTML:

```html
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js"></script>
```

However the `crossorigin="anonymous"` attribute causes the following error

```
Access to script at 'https://polyfill.io/v3/polyfill.min.js' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

## Details

Expected behaviour:
-  CORS works

OR

- `crossorigin` attribute is not specified in the provided HTML

**Comment by JakeChampion** [comment]
Hi @Slessi, 

I can not reproduce the error unfortunately. All responses have access-control-allow-origin set to *, this is done within the CDN configuration here --> https://github.com/Financial-Times/polyfill-service/blob/c15fe9079118111067cf43d1b0eefac5ddd4d8da/fastly/vcl/polyfill-service.vcl#L212

I tried to reproduce the error by making an index.html with the script tag and serving on localhost, here is the screenshot of the response having the access-control-allow-origin header and no CORS errors shown.
```html
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js"></script>
```

<img width="976" alt="Screenshot 2019-11-01 at 10 33 03" src="https://user-images.githubusercontent.com/1569131/68019409-8b5c8800-fc93-11e9-8404-f315a02ad871.png">

Are you able to always reproduce the CORS error? If so, what is the specific setup you have got? I.E. Which browser are you using, do you have a proxy setup or a modified hosts files?

**Comment by Slessi** [comment]
@JakeChampion Yes it is 100% reproducible, happens to me on my local environment as well as our staging/production environments.

Browser: Chrome 78.0.3904.70
Proxy: No
Hosts: No

URL in use (if it makes a difference): https://polyfill.io/v3/polyfill.min.js?features=fetch%2Ces6%2CArray.prototype.flatMap

![image](https://user-images.githubusercontent.com/3223500/68020211-15115300-fc9e-11e9-8c9c-6b1a56e6e169.png)

**Comment by JakeChampion** [comment]
@Slessi Could you post a screenshot showing the request headers please? I am expecting that the origin request header is perhaps not being sent.

**Comment by Slessi** [comment]
@JakeChampion I updated Google chrome from `78.0.3904.70` to `78.0.3904.87` and it fixed itself

`¯\_(ツ)_/¯`

sorry to have wasted your time
