### ISSUE TITLE
CSS colors not loading in IE

### ISSUE THREAD

**Issue by ghost** [polyfillpolyfill/polyfill-service#2038]
Hi. I'm building a Vue app and we're using the polyfill to get our app to display an IE - which is a great accomplishment already. The problem is now that it's loading in IE (v 11.0.160), the colors are not displaying properly, they seem to have defaulted to grayscale. My colleague was getting this error: "Object doesn't support property or method 'values'," ... But I'm not seeing it. 

Also, is this only available on CDN?

Thank you!

**Comment by JakeChampion** [comment]
@BradenLinick I'll need some more information to be able to help:
- What is the full polyfill.io url you are using on the page?
- What is the full user-agent string for the browser which has this error?
- Could you post a small webpage which produces this error?

My guess based on what you've said so far is that you are using `Object.values` and have not included it in your polyfill.io script tag. This is how to include the default set of polyfills and `Object.values`: `<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?feaures=default,Object.values"></script>`
