### ISSUE TITLE
Node.js 12 support

### ISSUE THREAD

**Issue by teawithfruit** [polyfillpolyfill/polyfill-service#2041]
Am I right, that Node.js 12 is not supported till now?
I'm trying to install the polyfill service with Node.js 12 and I get a bunch of errors.

**Comment by JakeChampion** [comment]
That's correct, the engines we support are listed in the engines field of package.json 

https://github.com/Financial-Times/polyfill-service/blob/ccf92993741a7c6204319919bd4246a1c6c90d81/package.json#L37

**Comment by teawithfruit** [comment]
Ok, thanks for the answer. Is an update for Node.js 12 a part of the roadmap?

**Comment by JakeChampion** [comment]
This was added in #2044
