### ISSUE TITLE
[feature request] Docker Support

### ISSUE THREAD

**Issue by LeuisKen** [polyfillpolyfill/polyfill-service#2043]
## What

Docker Support for private deployment

## Details

Maybe we could build a docker image to docker hub that can help us deploy this service more easier.

**Comment by teawithfruit** [comment]
It is not official, but you can try this.
https://github.com/3YOURMIND/js-polyfill-docker

I'm using it in my environment and till now it's working very good.

**Comment by JakeChampion** [comment]
Hi @LeuisKen and @teawithfruit, we won't be publishing images to Docker Hub as we do not use Docker ourselves and it would be an extra piece of maintenance that we would have to take on to keep it up-to-date with any security patches and/or updates.
