### ISSUE TITLE
Could you have the website say what is deployed on an unsupported browser?

### ISSUE THREAD

**Issue by Lazerbeak12345** [polyfillpolyfill/polyfill-service#2049]
This is a feature request for the website

## What

I noticed it's hard to understand what happens when an unsupported web-browser is encountered.
## Details

I don't exactly have any need to know, but it would be nice.

N/A

**Comment by chee** [comment]
hey, @Lazerbeak12345 ! that's mentioned under the request docs for the `unknown` querystring parameter: https://polyfill.io/v3/api/#request

i notice it doesn't mention what the default is though!
