### ISSUE TITLE
[Bug report] Browser caching problem

### ISSUE THREAD

**Issue by gmetais** [polyfillpolyfill/polyfill-service#2053]
Hello and thank you for your tool!

## What
The CDN caching headers prevents the file to be correctly cached on the browser's side.

## Details
Example URL: https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Array.prototype.find,Element.prototype.matches

This is due to the response headers that currently include:

- cache-control: public, s-maxage=31536000, **max-age=604800**, stale-while-revalidate=604800, stale-if-error=604800

- age: **3497422**

When age is > max-age, the browser considers the file has already expired. On successive calls, the browser will send a new request. Even if the CDN responds with "304 Not modified", this is an unnecessary request that slows down page load. It would be great if you could fix it.

Note: The same issue happens on the V3 API too.

**Comment by JakeChampion** [comment]
Thanks for the issue @gmetais. 

I've added a test for this to ensure we never regress on this functionality.

I will ensure to get this released today.
