### ISSUE TITLE
Publish version 4 to npm

### ISSUE THREAD

**Issue by paladox** [polyfillpolyfill/polyfill-service#2054]
Hi, could version 4 of polyfill-service be published to npm please?

https://www.npmjs.com/package/polyfill-service shows the last version to be 3.25.3.

**Comment by JakeChampion** [comment]
We no longer publish the service to npm, if you are wanting to use the NodeJS API it is now a new package called polyfill-library. If you are wanting to run your own self hosted version of polyfill-service I recommend downloading the git repo or the zip folder from the GitHub releases page.
