### ISSUE TITLE
Declared variable with const causing script error in IE 10

### ISSUE THREAD

**Issue by truecastdesign** [polyfillpolyfill/polyfill-service#2055]
Declared variable with const causing script error in IE 10

The below page causes this error in IE 10.

SCRIPT1002: Syntax error 
index.html, line 14 character 3

Line 14 is the: const a = "Hello World!";

With es2015 asked for, I would expect something simple like this to work. No?

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es2015%2Ces2016%2Ces2017"></script>
    <title>Document</title>
</head>
<body>
    <div id="test"></div>
    <script>
    window.addEventListener('load', function(){
		const a = "Hello World!";
    	document.querySelector('#test').textContent = a;
    })
   
    </script>
</body>
</html>

**Comment by aladdin-add** [comment]
you need to compile to es5(using `babel` or something else).

polyfill is not the same thing! e.g. es2015 providing `promise`, `set`...

**Comment by JakeChampion** [comment]
@truecastdesign, @aladdin-add is correct, polyfills do not make browsers understand new syntax, you will need to use a compilter such as babel or typescript to support new syntax in older browsers.
