### ISSUE TITLE
Age header value is never reset, causing re-fetch from browser

### ISSUE THREAD

**Issue by tbillet** [polyfillpolyfill/polyfill-service#2072]
[type]: bug

## What
Polyfill is fetched every time from the browser. Browser cache is ignored.

## Details

1. open browser tab (ex: chrome, firefox)
2. load https://polyfill.io/v3/polyfill.min.js?unknown=polyfill&features=es2018
3. open devtools, go in the "network" tab and uncheck "disable cache"
4. refresh the page

This way you can see that the content get's re-fetched from the server every-time instead of coming from the browser cache.
![image](https://user-images.githubusercontent.com/344302/72427586-56d57400-378c-11ea-934e-eb8c77caa008.png)

## Additional information
- A similar issue was fixed in august 2017, but it seems to have re-appeared: See https://github.com/Financial-Times/polyfill-service/issues/1276

**Comment by JakeChampion** [comment]
Thanks for the issue @tbillet  

I've added a test for this to ensure we never regress on this functionality.

I will ensure to get this released today.

**Comment by tbillet** [comment]
Thanks a lot @JakeChampion :)

Edit: Just tested, and it's working well now :tada:
