### ISSUE TITLE
Document polyfill causes long delay in element creation in IE8

### ISSUE THREAD

**Issue by roland-vachter** [polyfillpolyfill/polyfill-service#211]
Hi,

First I would like to describe the use case. It is about Livefyre comments integration. What we need: Event polyfill and HTML5shiv.

FT.com is actively using https://github.com/aFarkas/html5shiv, adding the polyfill service script to any FT.com page throws several errors in IE8.

Using https://github.com/aFarkas/html5shiv seems to be a good alternative.

**Comment by roland-vachter** [comment]
@triblondon the widget is loading, so the jsonp issue (script loading) is fixed. Now the CSS styles doesn't apply to the elements, not sure why..

**Comment by triblondon** [comment]
does the polyfill bundle include the html5-elements feature?

**Comment by roland-vachter** [comment]
It seems it does, yes

**Comment by roland-vachter** [comment]
It seems to be unrelated to the polyfill service, the polyfill seems to be fine.

**Comment by roland-vachter** [comment]
All fine, everything works fine.

**Comment by roland-vachter** [comment]
When will this be released?

**Comment by triblondon** [comment]
Fixed by #222
