### ISSUE TITLE
Documentation website design distorted on some pages

### ISSUE THREAD

**Issue by sarpavci** [polyfillpolyfill/polyfill-service#2118]
[type]: bug

## What
Documentation website design distorted on some pages

## Details
- Browser + version: Google Chrome **Version** 80.0.3987.87 (Official Build) (64-bit)
- Device: MacBook Pro (Retina, 15-inch, Mid 2015) **Version** 10.15.3 (19D76)
- Screenshots
![image](https://user-images.githubusercontent.com/6714468/74090455-8b52fc00-4abc-11ea-9330-3613566ba1a5.png)

**Comment by chee** [comment]
Thank-you for this, @usameavci !

note to self for monday:
* doesn't appear to happen with chrome 78
* does happen on chromium 80
* doesn't happen on firefox 73
* happens at the `(min-width: 46.25em)` breakpoint
* probably to do with `o-grid`
* fix probably needs to be on [o-layout](https://github.com/Financial-Times/o-layout)

**Comment by notlee** [comment]
Thanks for reporting 😊  closing as this is fixed now in Chrome 80 
![Screenshot 2020-02-13 at 11 28 08](https://user-images.githubusercontent.com/10405691/74430035-f8b3b380-4e53-11ea-8eb8-a38aec4a6eca.png)
