### ISSUE TITLE
Website detail window is not visible

### ISSUE THREAD

**Issue by b-strauss** [polyfillpolyfill/polyfill-service#2131]
Tooltip element flows outside of container.

`.o-layout__main` has overflow hidden

![image](https://user-images.githubusercontent.com/6588177/74765218-724c0700-5283-11ea-8f2c-3fb1d7897a1a.png)

**Comment by JakeChampion** [comment]
this is now fixed on the live website :-)

![image](https://user-images.githubusercontent.com/1569131/75034858-0990a480-54a6-11ea-99d0-a2a196ae3922.png)
