### ISSUE TITLE
[bug] Did flags=all stop working?

### ISSUE THREAD

**Issue by agriffis** [polyfillpolyfill/polyfill-service#2133]
## What
https://polyfill.io/v3/polyfill.js?features=default&flags=all sends to Firefox

```
/* Polyfill service v3.42.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * Features requested: HTMLPictureElement,Symbol,console.debug,console.log,console.warn,default,es2017,es5,es6,es7,fetch
 *  */


/* No polyfills found for current settings */
```

## Details
I thought that ?flags=all was supposed to return the polyfills regardless of user agent.

**Comment by chee** [comment]
@agriffis i think you might be looking for `flags=always` :)

https://polyfill.io/v3/polyfill.js?features=default&flags=always

(documented here: https://polyfill.io/v3/api/#request)

**Comment by agriffis** [comment]
@chee I read that page so many times, and I just kept translating "always" to "all"

Thanks!!
