### ISSUE TITLE
Website documentation: clicking tooltip button does nothing

### ISSUE THREAD

**Issue by kevinwilde** [polyfillpolyfill/polyfill-service#2173]
## What

https://polyfill.io/v3/url-builder/
Previously clicking the tooltip button next to a polyfill/polyfill-set showed what was included. Now, nothing is happening.
![image](https://user-images.githubusercontent.com/9701176/76364007-764ad200-62e1-11ea-8809-dbfc148d34b3.png)

## Details

Tried on Chrome and Firefox

**Comment by JakeChampion** [comment]
Thanks for the issue, this was fixed in https://github.com/Financial-Times/polyfill-service/commit/35e5f091afb11b7573f6bb51e3a2dd52e0779752 and will be going live later today :-)
