### ISSUE TITLE
iOS 9.3 Safari Mobile's user agent is no longer detected properly

### ISSUE THREAD

**Issue by ubergeek42** [polyfillpolyfill/polyfill-service#2192]
## What

Mobile Safari running in an iOS 9.3 simulator is no longer detected properly and instead returns:
`UA Detected: other/0.0.0 (unknown/unsupported; using policy 'unknown=ignore')`
![image](https://user-images.githubusercontent.com/672279/77608634-2deffe80-6ef4-11ea-8c99-600f6de4e54b.png)

It then fails to provide the needed polyfills for my application(`fetch` mainly)

## Details
On March 16th this was working properly and returning the following comment along with the polyfills.
```
UA detected: ios_saf/9.0.0
```

The URL I'm requesting is: https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch
My iOS Simulator is an Iphone 6, running iOS 9.3. The user agent is in the screenshot below, along with the request details.

![image](https://user-images.githubusercontent.com/672279/77608340-4f9cb600-6ef3-11ea-95ea-2554ab18d9ea.png)

I guess there was probably a change to the useragent parsing definitions, but I couldn't find anything when I took a quick look.

If there's any other details I can provide please let me know.

**Comment by JakeChampion** [comment]
Hi @ubergeek42 

Could you post the full exact user-agent string which is showing the issue please? I've typed ou the one I can see in the last image you posted and it looks to work correctly, which you can see by visiting this link: https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch&ua=Mozilla/5.0%20(iPhone;%20CPU%20iPhone%20OS%209_3%20like%20Mac%20OS%20X)%20AppleWebKit/601.1.46%20(KHTML,%20like%20Gecko)%20Version/9.0%20Mobile/13E233%20Safari/601.1

We don't change anything on the v2 API of polyfill.io, not even the useragent parser, which makes me concerned that something unexpected may have happened.

**Comment by ubergeek42** [comment]
@JakeChampion thanks for the quick response!

If I take the user agent and send the request using `curl` I see the same behavior, so hopefully that'll help you to reproduce it as well. I compared the user agent you manually typed against what was being sent and they're identical.
```
curl 'https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13E233 Safari/601.1'  -v
*   Trying 199.232.34.109...
* Connected to cdn.polyfill.io (199.232.34.109) port 443 (#0)
* found 149 certificates in /etc/ssl/certs/ca-certificates.crt
* found 601 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: f3.shared.global.fastly.net (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=San Francisco,O=Fastly\, Inc.,CN=f3.shared.global.fastly.net
* 	 start date: Wed, 29 May 2019 14:48:29 GMT
* 	 expire date: Thu, 23 Apr 2020 21:26:12 GMT
* 	 issuer: C=BE,O=GlobalSign nv-sa,CN=GlobalSign CloudSSL CA - SHA256 - G3
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /v2/polyfill.js?features=default,fetch HTTP/1.1
> Host: cdn.polyfill.io
> Accept: */*
> User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13E233 Safari/601.1
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,HEAD,OPTIONS
< Cache-Control: public, s-maxage=31536000, max-age=604800, stale-while-revalidate=604800, stale-if-error=604800
< Content-Type: text/javascript; charset=utf-8
< Last-Modified: Tue, 24 Mar 2020 01:13:52 GMT
< Server-Timing: HIT-CLUSTER, fastly;desc="Edge time";dur=1
< Request_Came_From_Shield: FTY
< X-Content-Type-Options: nosniff
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< Referrer-Policy: origin-when-cross-origin
< Timing-Allow-Origin: *
< Normalized-User-Agent: other/0.0.0
< Detected-User-Agent: Mobile Safari/WKWebView/9..
< Content-Length: 464
< Accept-Ranges: bytes
< Date: Thu, 26 Mar 2020 13:05:43 GMT
< Age: 199183
< Connection: keep-alive
< Vary: User-Agent, Accept-Encoding
< Server-Timing: HIT-CLUSTER, fastly;desc="Edge time";dur=1
< 
/* Polyfill service v3.25.1
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: other/0.0.0 (unknown/unsupported; using policy `unknown=ignore`)
 * Features requested: default,fetch
 *  */

(function(undefined) {

/* No polyfills found for current settings */

})
.call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});
* Connection #0 to host cdn.polyfill.io left intact
```

It's quite odd that when using the `ua` request parameter it works properly but curl doesn't. Switching to v3 in the url when running curl does return the correct thing.

What are the differences between v2 and v3? If they're basically the same I might be able to upgrade. Is v2 still supported(and for how long)?

**Comment by JakeChampion** [comment]
@ubergeek42 Thank you so much for replying, with your information that when using the ua query parameter works and when using the User-Agent header doesn't work has shown me exactly where the bug is :-)

We've been using the wrong user-agent parser for polyfill.io/v2 for the last week or so, I'm fixing it right now 👍

**Comment by JakeChampion** [comment]
PR which fixes this issue --> https://github.com/Financial-Times/polyfill-service/pull/2194

**Comment by ubergeek42** [comment]
Awesome thank you @JakeChampion! I see the PR has been merged, do you know how long it takes before it is shipped/released/available in production?

**Comment by JakeChampion** [comment]
it is being deployed to production right now
