### ISSUE TITLE
Demo site always return empty ?

### ISSUE THREAD

**Issue by chrisribe** [polyfillpolyfill/polyfill-service#2214]
The generated url:
https://polyfill.io/v3/polyfill.js?version=3.52.1&features=Array.of%2Ces2016

Always returns:

```
/* Polyfill service v3.52.1
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * Features requested: Array.of,es2016
 *  */


/* No polyfills found for current settings */

```

**Comment by JakeChampion** [comment]
That means the browser you are using already supports those features :-)

**Comment by chrisribe** [comment]
Ah ok, but does that even make sense ? I get it if the script is loaded on the page (executed), you would do feature detection etc to see if you need the polyfill or not. 

Right now you just check the user-agent string ? I initially was testing to take a look at the code that was returned, having empty made me think the service was broken. Maybe have a switch to allow display / download ? 

Only my 2 cents, keep up the good work.

**Comment by JakeChampion** [comment]
You can add the flags query parameter and set it to always load polyfills like this:
https://polyfill.io/v3/polyfill.js?version=3.52.1&features=Array.of%2Ces2016&flags=always

**Comment by DanielRuf** [comment]
> You can add the flags query parameter and set it to always load polyfills like this:
> [polyfill.io/v3/polyfill.js?version=3.52.1&features=Array.of%2Ces2016&flags=always](https://polyfill.io/v3/polyfill.js?version=3.52.1&features=Array.of%2Ces2016&flags=always)

This should be added as an option. It seems the relevant option was removed in the UI.

**Comment by JakeChampion** [comment]
It's documented in the api documentation page -- https://polyfill.io/v3/api/

We don't include it as an option in the url builder page because we don't recommend using the flags query parameter to always load polyfills. Always loading polyfills is the opposite goal of what polyfill.io was built for.

**Comment by DanielRuf** [comment]
Sure but when you search for polyfills you come to the builder website and afaik there was the option in the past. At least you should mention it. Even if there is no option to enable it. Makes debugging easier.

**Comment by antony** [comment]
@DanielRuf it's mentioned in the docs. I agree with @JakeChampion that it makes sense for the UI to provide features people use, whereas users who want debugging capability and advanced options can refer to the docs for these extra flags.

**Comment by DanielRuf** [comment]
> @DanielRuf it's mentioned in the docs

Probably buried deep in the docs and not clear enough. Can you point me to it? Still, we should link / mention that in the UI. This is not the first time that people face this "issue".

**Comment by DanielRuf** [comment]
What I need is just a clear information that flags like `always` can be used for debugging purposes and to see the polyfill so we can copy paste it to our projects. Because selfhosting the service or using it directly (well, a CDN and problematic regarding GDPR) is not an option for us at least.

**Comment by DanielRuf** [comment]
> @DanielRuf it's mentioned in the docs

Still, we should link / mention that in the UI. This is not the first time that people face this "issue".

What I need is just a clear information that flags like `always` can be used for debugging purposes and to see the polyfill so we can copy paste it to our projects. Because selfhosting the service or using it directly (well, a CDN and problematic regarding GDPR) is not an option for us at least.

**Comment by JakeChampion** [comment]
@DanielRuf I'd recommend using the underlying [polyfill-library](https://www.npmjs.com/package/polyfill-library) package if you can not use the public service or self-host it.

**Comment by DanielRuf** [comment]
Thanks but in our case we just needed single polyfills so we checked the checkboxes and wanted to copy the code. The library would require a full Node.js setup for a Java project. And as already mentioned, self-hosting the full solution is not an option either ;-)

I guess I'll create a fork with an option for `always` to enable the preview and display of all selected polyfills so users can copy them into their static files.
