### ISSUE TITLE
Placeholder text incorrect on the https://polyfill.io/v3/url-builder/ page in the callback text input

### ISSUE THREAD

**Issue by richardhuf84** [polyfillpolyfill/polyfill-service#2219]
Bug Report

## What
On the url-builder page, I noticed that the placeholder text for the callback input reads 'Type to filter by name'. This is the same placeholder text as the above filter input. Is this correct? Should it read something like 'Enter callback name'?

## Details

Can be seen on thi page of the polyfill.io website: https://polyfill.io/v3/url-builder/

Thanks for providing such an awesome service!

**Comment by JakeChampion** [comment]
Thanks for spotting this!
