### ISSUE TITLE
TypeError with IE8

### ISSUE THREAD

**Issue by Daniel-Knights** [polyfillpolyfill/polyfill-service#2243]
I'm using the default script: 
`<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js"></script>`

It works fine in all user agents except IE8 where I get this error: 
`TypeError: undefined is not an object (evaluating 'l.constructor.prototype=n')`

Error is coming from here: 
```
CreateMethodProperty(Object, "create", function o(n, r) {
            if ("object" !== Type(n) && "null" !== Type(n))
                throw new TypeError("Object prototype may only be an Object or null");
            if ("null" === Type(n))
                var l = t();
            else
                e.prototype = n, l = new e, l.__proto__ = n, l.constructor.prototype = n, l.__proto__ = n;
            return 1 in arguments ? Object.defineProperties(l, r) : l
})
```

Not sure if there is something wrong with my code or the script itself. 
Testing this with safari's IE8 user agent.

**Comment by JakeChampion** [comment]
Hi @Daniel-Knights, thanks for the issue. Could you please explain what you mean by this part:
> Testing this with safari's IE8 user agent.

I'm confused by the mention of Safari and IE8 there.

**Comment by Daniel-Knights** [comment]
Hi @JakeChampion, Safari has the option to switch user agents in the 'develop' menu. Could this be why I'm seeing this error?

**Comment by JakeChampion** [comment]
@Daniel-Knights yes, that would be why. We would be sending IE 8 polyfills to the browser when infact the browser is Safari. Some of the polyfills required for IE8 are not required in more modern browsers and infact would cause errors such as this if they are attempted to run in modern browsers.

**Comment by Daniel-Knights** [comment]
Ohh okay, that's good to know. Thanks for the quick responses @JakeChampion, really helpful. 👍
