### ISSUE TITLE
Idea: move UA normalization to origin

### ISSUE THREAD

**Issue by jamesarosen** [polyfillpolyfill/polyfill-service#2245]
## What
Currently, the [Fastly VCL](https://github.com/Financial-Times/polyfill-service/blob/master/fastly/vcl/normalise-user-agent-3-25-1.vcl) handles normalizing the `User-Agent` header. This is very fast, but it has some downsides:

1. It can't easily be unit-tested
2. It locks the site to Fastly. You can't easily pursue a multi-CDN strategy to improve resiliency.
3. It's difficult to run multiple versions simultaneously

## Details
It's possible to make subrequests in Fastly. See, for example, https://docs.fastly.com/en/guides/authenticating-before-returning-a-request

It would look something like this:

```vcl
# vcl_recv
if (req.restarts == 0) {
  # First, send the request to /v3/normalize_ua:
  set var.normalized_ua = "";
  set var.original_url = req.url;
  set req.url = "/v3/normalize_ua?" req.http.user-agent;
  return(lookup); # fetch from cache or origin
}

# vcl_fetch
if (req.url ~ "/v3/normalize_ua" && beresp.status == 200) {
  # When that comes back (hopefully from cache), restart the
  # original request with the user agent attached as a query param:
  set var.normalized_ua = beresp.http.normalized-user-agent;
  set req.url = querystring.set(var.original_url, "ua", var.normalized_ua);
  restart;
}
```

If you're interested in pursuing this, I'm happy to help. If you think the additional request would cause too much latency or too much risk, feel free to close the ticket.

**Comment by JakeChampion** [comment]
We used to use the sub-request (vcl restart) approach, we moved to embedding directly into the vcl because it lowered the amount of requests to our origin by quite a lot and improved our cache-hit-ratio.

**Comment by jamesarosen** [comment]
OK. I actually opened this because we're running an instance of polyfill-service behind Cloudflare. Replicating the user-agent-parsing VCL in JavaScript is annoying, but that's my problem to deal with.

**Comment by JakeChampion** [comment]
@jamesarosen this person has written up how to use cloudflare workers for polyfill.io -- https://blog.annamalai.me/posts/replicating-polyfill.io-using-cloudflare-workers/

**Comment by JakeChampion** [comment]
When Fastly release their Compute@Edge support, we will change our implementation to use that, which is based on Web assembly, which then CloudFlare could also use.

In case it is useful, here it the user-agent normaliser project we use, it has a VCL and a npm JavaScript api, which you could use on your origin server -- https://github.com/Financial-Times/polyfill-useragent-normaliser/
