### ISSUE TITLE
Website look weird, no styles loading.

### ISSUE THREAD

**Issue by kevinfilteau** [polyfillpolyfill/polyfill-service#2251]
Website looks weird, no styles loading.

**Comment by antony** [comment]
@kevinfilteau I'm not seeing this. It's useful to include browser versions etc, and possibly check if your network panel is loading the CSS correctly.

Either that or it is resolved now.

**Comment by JakeChampion** [comment]
I've tested this in multiple different browsers and can not replicate the issue. If you are still seeing this issue, could you please post a screenshot and the browser version you are using.

**Comment by kevinfilteau** [comment]
Hi,

I tested with Safari, Chrome and Brave and Safari on my iPhone, same issues
everywhere

[image: Screen Shot 2020-06-05 at 09.41.37.png]
—
Kevin Filteau vous guide vers l'autogestion de votre commerce en ligne.
418-254-7193 de 10h à 16h du lundi au jeudi
info@kevinfilteau.com

Si vous désirez ne plus recevoir de courriel de ma part, demander ou faire
un changement à vos informations personnelles ou formuler une plainte, veuillez
immédiatement m'en informer par courriel.

**Comment by antony** [comment]
@kevinfilteau the screenshot didn't work, sorry.

Can you check your network tab in the browser and see if there are errors. I feel like this might just be you.

**Comment by kevinfilteau** [comment]
https://www.dropbox.com/s/dsobidmwhvzrljk/Screen%20Shot%202020-06-05%20at%2009.41.37.png?dl=0
—
Kevin Filteau vous guide vers l'autogestion de votre commerce en ligne.
418-254-7193 de 10h à 16h du lundi au jeudi
info@kevinfilteau.com

Si vous désirez ne plus recevoir de courriel de ma part, demander ou faire
un changement à vos informations personnelles ou formuler une plainte, veuillez
immédiatement m'en informer par courriel.

**Comment by kevinfilteau** [comment]
Back online : )
—
Kevin Filteau vous guide vers l'autogestion de votre commerce en ligne.
418-254-7193 de 10h à 16h du lundi au jeudi
info@kevinfilteau.com

Si vous désirez ne plus recevoir de courriel de ma part, demander ou faire
un changement à vos informations personnelles ou formuler une plainte, veuillez
immédiatement m'en informer par courriel.

**Comment by antony** [comment]
Hate to be the bearer of bad news, but it's happening to me now, on Chrome latest.

Seems to be a caching / deployment issue:

![Screenshot from 2020-06-07 09-37-16](https://user-images.githubusercontent.com/218949/83964137-87848a00-a8a2-11ea-9879-b9214938200d.png)
![Screenshot from 2020-06-07 09-37-02](https://user-images.githubusercontent.com/218949/83964138-87848a00-a8a2-11ea-8dc5-c4f5f9cb0f8a.png)


![Screenshot from 2020-06-07 09-35-32](https://user-images.githubusercontent.com/218949/83964114-599f4580-a8a2-11ea-8f77-f9e063578e36.png)

**Comment by antony** [comment]
Looks like a few refreshes bring it back - but it's a totally different CSS hash.

I think there's some overly-aggressive caching going on for `index.html`

![Screenshot from 2020-06-07 09-38-50](https://user-images.githubusercontent.com/218949/83964161-cdd9e900-a8a2-11ea-98a4-d39591388675.png)
