### ISSUE TITLE
A feature request: possibility to add own basepath to url router?

### ISSUE THREAD

**Issue by maapteh** [polyfillpolyfill/polyfill-service#2253]
Awesome service.

We want to use it in another route path. So not snip.com/v3/polyfill.js but something like snip.com/foo/polyfill/polyfill.js because we deploy inside container but cant enroll on just /v3

I see the routes are now set here:
https://github.com/Financial-Times/polyfill-service/blob/master/server/routes/v3/polyfill.js#L74

```
app.get(["/v3/polyfill.js", "/v3/polyfill.min.js"], async (request, response, next) => {
```

Now i can make it an optional ENV var, but would like to know if FT is willing to see this as a feature request to start with :)

Maarten

**Comment by JakeChampion** [comment]
@maapteh good feature request, we would definitely accept it

**Comment by maapteh** [comment]
Thanks, i added the PR. Tested the app with and without (default) process.env.CONTEXT_PATH being set.

**Comment by JakeChampion** [comment]
resolved via https://github.com/Financial-Times/polyfill-service/pull/2254
