### ISSUE TITLE
"Accept-Encoding: gzip, deflate, br" serves compressed content without "content-encoding: gzip"

### ISSUE THREAD

**Issue by andersjanmyr** [polyfillpolyfill/polyfill-service#2266]
Bug, when querying for compressed content with `Accept-Encoding: gzip, deflate, br`, the server sends compressed content without sending the `content-encoding: gzip` header.

This makes the client think that the content is uncompressed even though it is.
```
# Valid
curl -v 'https://polyfill.io/v3/polyfill.min.js'  -H 'Accept-Encoding: gzip, deflate' --compressed

# Invalid
curl -v 'https://polyfill.io/v3/polyfill.min.js'  -H 'Accept-Encoding: gzip, deflate, br' --compressed
```

**Comment by JakeChampion** [comment]
The second one responds with a content encoding header set to `br` because the request stated it supports `br` encoding.

Here are the two requests in your examples but with the response limited to just the encoding.

```
❯ curl -v 'https://polyfill.io/v3/polyfill.min.js'  -H 'Accept-Encoding: gzip, deflate' --compressed 2>&1 | grep "encoding"
< content-encoding: gzip
```

```
❯ curl -v 'https://polyfill.io/v3/polyfill.min.js'  -H 'Accept-Encoding: gzip, deflate, br' --compressed 2>&1 | grep "encoding"
< content-encoding: br
```
