### ISSUE TITLE
fastly macro question

### ISSUE THREAD

**Issue by chenrui333** [polyfillpolyfill/polyfill-service#2278]
Hi 👋 

I am trying to model my Fastly VCL code structure like yours (which is much clean and easy to understand), I wonder if you folks can help me understand why we put the `#FASTLY recv` in `fastly/vcl/polyfill-service.vcl` rather than `fastly/vcl/fastly-boilerplate-begin.vcl`?

Thanks!

**Comment by JakeChampion** [comment]
because the macro contains code specific to polyfill-service and not the boilerplate fastly logic
