### ISSUE TITLE
System.import (ES6 modules) polyfill

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#228]
I've been looking into the idea of adding a polyfill for System.import, and have found a couple of promising projects:
- [ES6 module loader](https://github.com/ModuleLoader/es6-module-loader)
- [ES6 micro loader](https://github.com/caridy/es6-micro-loader)

Both of these implement a `System.import` method, but the problem comes in the syntax you use within the module you're importing to export endpoints for the module's external API.  It's not recommended to to live transpilation in the browser, so you need to transpile on the server before loading, converting modules into `System.register` form, using Traceur's `--modules=instantiate` mode.

My knowledge of how ES6 modules work, such as it is, is about 4 hours old, but it feels like a straightforward unobtrusive polyfill isn't going to be possible here.  The only viable option is that the polyfill service could serve one of the shims listed above, on the understanding that the developer would need to compile the modules to `System.register` format (and hopefully these will also work with native implementations of `System.import`!)

**Comment by guybedford** [comment]
What about polyfilling just the `<script type="module">` tag with very basic linking, without circular reference support.

Effectively a polyfill to match the first modules implementations in browsers, without the full `System` loader API.

A tokenizer could be put together that would scan and replace `export` and `import` statements with simple `_registry.get` calls, and normalization would be entirely URL-based normalization.

The codebase for this could certainly fit under 10KB and be production-efficient, acting as a stable polyfill of the first browser implementations.

I'd love to work on something like this, but am a little overstretched right now. If someone else is interested, happy to discuss ideas anytime.

**Comment by juandopazo** [comment]
I like that idea! /cc @caridy

**Comment by caridy** [comment]
the suggestion from @guybedford seems reasonable. we should have a more clear picture of what will be the first implementation of the <script type=module/> next week.

as for the limitation of circular deps, I'm ok with that as the first step, but we can try to figure things out later on.

**Comment by triblondon** [comment]
System.import is (afaict) now the [loader](https://github.com/whatwg/loader/) API, but that effort seems to be stalled, with no updates for the last 5 months.  It was mentioned above that this feature was too early stage to polyfill and I think it probably still is.  Let's close this and bring it back when there's something worth polyfilling.

**Comment by caridy** [comment]
@triblondon that's correct, we are mostly looking at dynamic `import()` as a function as the way to import modules programatically, and that one cannot be polyfilled, instead it needs to be transpiled. Eventually, we might provide some hooks to control the registry, but that's all up in the air at the moment.

**Comment by asilvas** [comment]
From what I can tell https://github.com/ModuleLoader/es6-module-loader is pretty stable. Any intention in revisiting this? SystemJS leverages this. ES Module Loader is a pretty fragmented topic, so it's been challenging tracking down the real state of affairs.
