### ISSUE TITLE
all requested permutations of polyfill.min.js no longer contain code, just a block comment.

### ISSUE THREAD

**Issue by oneeyedziggy** [polyfillpolyfill/polyfill-service#2280]
# Type: Bug? Outage?
## What

Some time between june 17th and june 20th 202 according to the internet archive history... 'https://polyfill.io/v3/polyfill.min.js?features=Intl', 'https://polyfill.io/v3/polyfill.min.js?version=3.48.0', 'https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=es7%2Ces6', and several other versions i tried... stopped containing actual code, and now instead contains a single block comment. Was this intentional? Where would I sub for notifications to changes like this? and if intentional, at that point, why not 404 or return some other error code instead of an http success returning an empty script?

**Comment by JakeChampion** [comment]
Hi @oneeyedziggy, the last deployment was in May. Nothing _should_ have changed between the dates you have mentioned. Could you please post the full user-agent string of the browser which is making the polyfill.io request please?

I have a suspicion that the browser which is making the request does not need any polyfills and that is why we are serving an empty script file (containing only a comment)

**Comment by oneeyedziggy** [comment]
"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0" for the above, and

for https://polyfill.io/v3/polyfill.min.js?version=3.52.1 only, the same happens w/
chrome 83 win 7
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

chrome 83 osx
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

firefox 77 osx
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:77.0) Gecko/20100101 Firefox/77.0

safari 13 osx
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15

chrome 83 android
Mozilla/5.0 (Linux; Android 8.0.0; SM-G935V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile Safari/537.36

I'm starting to see this might be a feature... The only places i do get a response w/ more than a block comment is firefox 68 on android
Mozilla/5.0 (Android 8.0.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
and 
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko 
( I forgot I even had internet explorer... as everyone should, I don't think i knew it can't even navigate to javascript files... it tries to download them... but when it does, this one contains code. )

-------

so... is the idea, the code is only sent to browsers you expect will need it? The response changing based on who's asking...

**Comment by JakeChampion** [comment]
> so... is the idea, the code is only sent to browsers you expect will need it? The response changing based on who's asking...

That is the exact idea, yes :-) polyfill.io is a service which accepts a request for a set of browser features and returns only the polyfills that are needed by the requesting browser.

**Comment by oneeyedziggy** [comment]
k, thanks. That answers my main issue, as the dev who inherited the requesting code, I was trying to inspect contents from MY browser, not the oldest one I could find, and was expecting it to return what was requested w/o trying to be clever. Probably one of the first things stated in the docs had i bothered to read them :), though not your problem, I could see other devs checking, seeing a placebo script w/ no functional code, and pulling it from their project.

Might be worth checking what internet archive's UA is and maintain consistency for it, as the response to them changed last week. That's the main way I was able to confirm this script wasn't ALWAYS empty. I use it to check historical states of public scripts, especially when behavior changes unexpectedly.

**Comment by torian257x** [comment]
hey guys, AWESEOME project! <3

I was perplexed for a second as well, but I figured it out... still: what I would recommend instead of writing:

>No polyfills found for current settings

I would write:

>No polyfills needed for current settings and browser 


btw I am coming from https://github.com/zloirock/core-js/issues/567#issuecomment-665846272 with the recent issue introduced to recaptcha

**Comment by JakeChampion** [comment]
@Jossnaz excellent suggestion :-) I'll make a pull-request for that 👍

**Comment by JakeChampion** [comment]
@Jossnaz here it is -- https://github.com/Financial-Times/polyfill-library/pull/763
