### ISSUE TITLE
Polyfill.io website navbar doesn't work

### ISSUE THREAD

**Issue by sayinserdar** [polyfillpolyfill/polyfill-service#2281]
Bug Report

## What

Polyfill.io href on navbar doesn't redirect to link
## Details

MacOS Catalina v10.15.3
Google Chrome Version 83.0.4103.106 (Official Build) (64-bit)

https://polyfill.io/v3/  navbar doesn't redirect to expected page

After a while I've encountered with this error while waiting for something to happen
<img width="649" alt="Screen Shot 2020-06-29 at 5 01 20 PM" src="https://user-images.githubusercontent.com/26919126/86015531-5d019900-ba2a-11ea-9c43-471a0a409274.png">

**Comment by JakeChampion** [comment]
@sayinserdar Could you explain some more please? I've visited the website and to me, all the links go to the expected places.

**Comment by sayinserdar** [comment]
@JakeChampion  I edited the issue. I didn't get any error at first now there is 503 error.

**Comment by JacobSoderblom** [comment]
I also get the same result when I go to https://polyfill.io/v3/packages for instance

**Comment by JakeChampion** [comment]
This should be fixed now, it looks like our US server crashed and didn't automatically restart. I'll be doing an investigation as to why it did not automatically restart.

**Comment by sayinserdar** [comment]
It's working as expected now. Thanks!
