### ISSUE TITLE
Add Intl.Locale and other Intl.* Polyfills

### ISSUE THREAD

**Issue by wopian** [polyfillpolyfill/polyfill-service#2310]
# Feature Request

## What

Only `Intl`, `Intl.PluralRules` and `Intl.RelativeTimeFormat` are available in polyfill-io at the moment. FormatJS has written and maintains spec-compliant npm polyfills for these missing methods:

- https://formatjs.io/docs/polyfills/intl-getcanonicallocales (IE11 only)
  - https://formatjs.io/docs/polyfills/intl-listformat
  - https://formatjs.io/docs/polyfills/intl-locale
  - https://formatjs.io/docs/polyfills/intl-displaynames
  - ~~https://formatjs.io/docs/polyfills/intl-pluralrules~~ (`Intl.PluralRules` on polyfill-io)
    - https://formatjs.io/docs/polyfills/intl-numberformat (ES2020)
      - ~~https://formatjs.io/docs/polyfills/intl-relativetimeformat~~ (`Intl.RelativeTimeFormat` on polyfill-io)
      - https://formatjs.io/docs/polyfills/intl-datetimeformat

Graph of what methods / polyfills are required for each method:

![](https://formatjs.io/img/polyfills.svg)

From the documenation of the `Intl` polyfill polyfill-io uses, the current implemented methods do not appear to be wholly spec compliant either (and abandoned for years), so could do with being replaced all together with the FormatJS provided polyfills.

## Details

`Intl` is polyfilled by polyfill-io, but several of the methods exposed by the `Intl` class are not polyfilled. 

I recently implemented a feature that made use of `Intl.Locale` that has been widely supported by browsers for several years...except for Safari. And was not aware it wasn't being polyfilled until a user testing a staging build brought it up.

I use `ember-cli-polyfill-io` which handles the polyfill CDN URL.

**Comment by JakeChampion** [comment]
We did this work in September and forgot to close the ticket.

All Intl features have now got polyfills implemented, the work was done in [v4.33.0](https://github.com/Financial-Times/polyfill-service/tree/v4.33.0)

**Comment by wopian** [comment]
Thank you for the update @JakeChampion 🎉
