### ISSUE TITLE
Move config, syntax checks, gating and minification to build step

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#233]
Following #230, it seems sensible to move the following processes to a build step:
- Syntax checks on config.json
- Standardising config format (eg creating default variant)
- Transpiling ES6 -> ES5
- Minification

We could then write out a single file for each polyfill containing the processed sources, which would (currently) include four copies of each polyfill - gated and not, minified and not.  These files can then be read on startup.

Or we could even combine all of that into one monster JSON file.

**Comment by samgiles** [comment]
This seems sensible.  We should run the build process (transpiling, minification, etc) using the 'install' script in the `package.json`.

`config.json` syntax checks should be a separate process run as part of the CI test.

**Comment by azproduction** [comment]
> We should run the build process (transpiling, minification, etc) using the 'install' script in the package.json.

That would be awesome :+1:
