### ISSUE TITLE
Can web platform tests be used here?

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#235]
https://github.com/w3c/web-platform-tests contains canonical tests for a lot of the web platform. Is there scope for consuming these in some way (perhaps manually copying at first for those polyfills that don't already have tests, then aiming towards some kind of automation)

**Comment by triblondon** [comment]
@juandopazo do you have a view on this?

**Comment by juandopazo** [comment]
I wasn't aware of those tests!

I'm planning on giving the new test262 harness a try and after that I'll check these tests out!

**Comment by triblondon** [comment]
See https://github.com/Financial-Times/polyfill-service/issues/192.  Which tests are the better ones?

**Comment by sideshowbarker** [comment]
I contribute a bit to https://github.com/w3c/web-platform-tests and would happy to help figure out if/how relevant test cases from it could be consumed in some way by the polyfill-service test system.

**Comment by JakeChampion** [comment]
Hi, thanks for raising this. We love to see people wanting to extend the polyfill service to accommodate new features. We don't keep feature request issues open without a PR, but we do provide feedback on how enthusiastic we are to adopt the suggested idea. In this case, the feature you've suggested is moderately appealing to the core team, and we would be happy to receive a PR for it, and help you with reviews and testing, or with how to get started if you are a new contributor. We would need to ensure that the polyfill is filling for a standard feature of the web platform, which we're not sure is the case here.

You can find out more about common contribution scenarios and how to make the perfect PR here:
https://polyfill.io/v2/docs/contributing/common-scenarios

If you need any further help before you submit your PR, feel free to reopen this issue!
