### ISSUE TITLE
Polyfill service loads wrong polyfills in IE compatibility view

### ISSUE THREAD

**Issue by roland-vachter** [polyfillpolyfill/polyfill-service#238]
IE10 in compatibility view behaves as an IE7, but the polyfill service doesn't handle it and serves polyfills for IE10.

**Comment by triblondon** [comment]
Thanks for raising this.  I'd been vaguely aware that it was likely to be a problem.  My only suggested solution at the moment is to do something like:

```
<!--[if IE ]>
  <script>
    document.write('<'+'script src='//cdn.polyfill.io/v1/polyfill.min.js?ua=ie/'+document.documentMode+'></'+'script>');
  </script>
<![endif]-->
<!--[if !IE]>-->
  <script src='//cdn.polyfill.io/v1/polyfill.min.js'></script>
<!--<![endif]-->
```

**Comment by triblondon** [comment]
If that works, let me know and I'll add it to the docs

**Comment by roland-vachter** [comment]
Thanks Andrew.

The code was not syntactically correct, here is the corrected version:

``` html
<!--[if IE ]>
    <script>
      document.write('<'+'script src="//cdn.polyfill.io/v1/polyfill.min.js?ua=ie/'+document.documentMode+'"></'+'script>');
    </script>
<![endif]-->
<!--[if !IE]>-->
    <script src="//cdn.polyfill.io/v1/polyfill.min.js"></script>
<!--<![endif]-->
```

This is better, in IE9 or IE10 browser mode and IE8 document mode this is working fine.

However, it seems that the polyfills for IE7 are not the best, polyfill itself throws an error:
SCRIPT16385: Not implemented
7, line 3 character 11588

Then the code that uses it:
SCRIPT438: Object doesn't support property or method 'addEventListener' 

But that could be considered another issue regarding polyfills for IE7.

**Comment by triblondon** [comment]
If there's a bug in a polyfill, please do raise that as a separate issue.

If the conditional comments are version specific, do they act on the document mode, or the real browser version?  If they act on the document mode, you can make a slightly better solution that doesn't use document.write by doing something like this (_note that when I say 'something like' I am not guaranteeing syntactically correct code_):

```
<!--[if IE 7 ]><script src="//cdn.polyfill.io/v1/polyfill.min.js?ua=ie/7"></script><![endif]-->
<!--[if IE 8 ]><script src="//cdn.polyfill.io/v1/polyfill.min.js?ua=ie/8"></script><![endif]-->
<!--[if IE 9 ]><script src="//cdn.polyfill.io/v1/polyfill.min.js?ua=ie/9"></script><![endif]-->
<!--[if IE 10 ]><script src="//cdn.polyfill.io/v1/polyfill.min.js?ua=ie/10"></script><![endif]-->
<!--[if IE 11 ]><script src="//cdn.polyfill.io/v1/polyfill.min.js?ua=ie/11"></script><![endif]-->
<!--[if !IE]>--><script src="//cdn.polyfill.io/v1/polyfill.min.js"></script><!--<![endif]-->
```

**Comment by roland-vachter** [comment]
The current solution works fine, maybe I give it a try to the last one as well.

I corrected the syntax just because you said you would add it to the documentation, and I just wanted to help not to add an incorrect code by mistake :)

**Comment by triblondon** [comment]
I've done some research here and found that in compatibility mode IE actually modifies it's user agent string.  I can't find any scenario in which the solutions above are necessary.  @roland-vachter can you provide a test case?

**Comment by roland-vachter** [comment]
Yes, that's true, IE modifies the user agent to IE7. Still, I think polyfill service does not handle it as an IE7. I will double check again, but that's what I observed.

**Comment by roland-vachter** [comment]
It seems it recognizes IE7 and the polyfill is served for IE7, probably it's not working due to the other issue that IE7 polyfill is not the best so far .. So I think this can be closed.
