### ISSUE TITLE
Outdated version of polyfill-library

### ISSUE THREAD

**Issue by rmja** [polyfillpolyfill/polyfill-service#2387]
## What

The current polyfill library served is version v3.89.4, which is way older than the currently released version of the library which is 3.96.0.

## Details

Requesting e.g. `https://polyfill.io/v3/polyfill.js?features=default,es6,fetch,Intl,Intl.~locale.da,Intl.~locale.de,Intl.~locale.en` returns version v3.89.4. 
The request has been tested from Chrome, IE11, and using curl.

The following is a snippet from the Chrome network tab:
![image](https://user-images.githubusercontent.com/2112306/91722488-9d9ca080-eb9a-11ea-9735-a56f2f1e26d3.png)

![image](https://user-images.githubusercontent.com/2112306/91722555-b60cbb00-eb9a-11ea-973b-4086346c7409.png)

**Comment by JakeChampion** [comment]
Yes, this is on purpose, the polyfill-library gets released more often than polyfill.io. This is because polyfill.io is run on so many websites that it requires a much more deliberate deployment/release process. The newer versions of polyfill-library have a brand new set of polyfills for Intl which have had slight issues and meant we can not confidently release those changes to polyfill.io

**Comment by rmja** [comment]
Ahh, I see. Is it possible using a parameter to force a specific version, or maybe a latest/unstable version?

(edit: It seems that https://polyfill.io/v3/polyfill.js?features=default&version=3.96.0 does not work)

**Comment by JakeChampion** [comment]
We allow parameter to choose the version based on previously deployed versions yes, but as you already know the newer versions have not been deployed.

The versions currently available on polyfill.io are

- 3.25.1
- 3.25.2
- 3.25.3
- 3.27.4
- 3.28.1
- 3.34.0
- 3.35.0
- 3.36.0
- 3.37.0
- 3.38.0
- 3.39.0
- 3.40.0
- 3.41.0
- 3.42.0
- 3.43.0
- 3.44.0
- 3.45.0
- 3.46.0
- 3.48.0
- 3.49.0
- 3.50.2
- 3.51.0
- 3.52.0
- 3.52.1
- 3.52.2
- 3.52.3
- 3.53.1
- 3.89.4

**Comment by rmja** [comment]
I am closing this as it seems that we are now on par with the latest version of the library. Thanks:)
