### ISSUE TITLE
IE7: error thrown

### ISSUE THREAD

**Issue by roland-vachter** [polyfillpolyfill/polyfill-service#239]
SCRIPT16385: Not implemented
7, line 3 character 11588

Then the code that uses it:
SCRIPT438: Object doesn't support property or method 'addEventListener'

**Comment by triblondon** [comment]
It would be very helpful if you could 
- provide the URL of the polyfill bundle that produces this error (unminified with `ua` parameter included);
- narrow down the issue to a bundle with a single polyfill
- confirm the use case (seems like you might be calling `addEventListener`? If so are you calling it on document or a node?)

**Comment by roland-vachter** [comment]
I think addEventListener is not polyfilled because polyfill itself throws an uncaught error which stops executing the script.

In an unminified, another error is thrown (weird, but it's IE...):
SCRIPT5022: HierarchyRequestError 
polyfill.js, line 373 character 2

The line is:

``` javascript
vbody = document.appendChild(document.createElement('body')),
```

**Comment by roland-vachter** [comment]
The URL is: https://cdn.polyfill.io/v1/polyfill.js?ua=ie/7

**Comment by triblondon** [comment]
HierarchyRequestError does not exist in IE7, so I suspect you were loading the IE7 polyfill bundle in IE10 or 11, which explains the change in error message.  I can replicate the Not implemented though, and I think it's the hashchange polyfill.  Suggested fix in https://github.com/Financial-Times/polyfill-service/pull/244.

**Comment by csabapalfi** [comment]
I can still reproduce the same error with IE11 compatibility view.

The Element polyfill seems to trigger a HierarchyRequestError. See [/polyfills/Element/polyfill.js#L13](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Element/polyfill.js#L13).

**Comment by jan-vodila** [comment]
@triblondon: I have same error as @csabapalfi 
My users are not able to load a page via compatibility mode, because all script execution dies on [/polyfills/Element/polyfill.js#L13](/polyfills/Element/polyfill.js#L13).

Any news about it?
