### ISSUE TITLE
Object.values doesn't get served if other features are included

### ISSUE THREAD

**Issue by heroje** [polyfillpolyfill/polyfill-service#2390]
https://polyfill.io/v3/polyfill.js?features=Object.values,Object.keys|always|gated
gives:
```
 * Features requested: Object.keys,Object.values
 * 
 * - Object.defineProperty, License: CC0 (required by "Object.keys", "_ESAbstract.CreateMethodProperty")
 * - _ESAbstract.CreateMethodProperty, License: CC0 (required by "Object.keys")
 * - Object.keys, License: MIT */
```
This is also seen in the resulting code omitting anything to do with Object.values.

Omitting Object.keys in this case gives the proper feature set:
https://polyfill.io/v3/polyfill.js?features=Object.values|always|gated
```
* Features requested: Object.values
 * 
 * - _ESAbstract.ArrayCreate, License: CC0 (required by "Object.values", "Array.prototype.map", "_ESAbstract.ArraySpeciesCreate")
 * - _ESAbstract.Call, License: CC0 (required by "Object.values", "Array.prototype.map", "_ESAbstract.ToString", "_ESAbstract.ToPrimitive", "_ESAbstract.OrdinaryToPrimitive")
```
(...)

**Comment by JakeChampion** [comment]
@heroje which browser is this? It is likely the browser supports Object.values and that is why we are not returning a polyfill for it.

**Comment by heroje** [comment]
I agree!
I have included _|always_ in the URL, as per the Querystring features section [in the API doc ](https://polyfill.io/v3/api/)
But only now I noticed the mention about this flag defaulting to a variant for browsers not requiring the polyfill. It's still possible to force the .values polyfill by using e.g. _|ua=ie6_, as a workaround. The full URL would then be:
https://polyfill.io/v3/polyfill.js?features=Object.values,Object.keys|always|gated|ua=ie6

Thus I think the question would be - if both the methods get outputted fine with the _always_ flag, when requested separately, why when combined only .keys get included in the output? Is there a polyfill for both of the methods, or some sort of a conditional saying .values isn't required if a polyfill for .keys is requested?

**Comment by JakeChampion** [comment]
Okay I understand now.

The always flag you have applied is per feature. If you want both features to always be loaded then you have two options:
- Add the always and gated individual flags to both features like this ->  https://polyfill.io/v3/polyfill.js?features=Object.values|always|gated,Object.keys|always|gated
or
- Add the always and gated group flags like this -> https://polyfill.io/v3/polyfill.js?features=Object.values,Object.keys&flags=always,gated
