### ISSUE TITLE
String.prototype.contains -> String.prototype.includes

### ISSUE THREAD

**Issue by samgiles** [polyfillpolyfill/polyfill-service#240]
String.prototype.contains has been changed in the ES6 spec to includes: http://people.mozilla.org/~jorendorff/es6-draft.html#sec-string.prototype.includes

More information here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#String.prototype.contains

**Comment by triblondon** [comment]
https://github.com/Financial-Times/polyfill-service/pull/245
