### ISSUE TITLE
Feature Request: list popular polyfills

### ISSUE THREAD

**Issue by jezmck** [polyfillpolyfill/polyfill-service#2405]
Would it be possible to show which polyfills are most commonly added to bundles?

**Comment by JakeChampion** [comment]
Yes, our privacy policy states we record "the set of polyfills that were requested by the web page". It would be possible to achieve this by creating a system which searches our logs for the set of polyfills being requested and then updating a page on the site with this information.

What's the scenario where you would want this information?

**Comment by jezmck** [comment]
I'm thinking it could be a shortcut to know what polyfills are likely to be necessary in a new project.

**Comment by JakeChampion** [comment]
We are not going to be implementing this feature, it would be a lot of work to implement and I don't see it being very useful.

[We have a tool available](https://polyfill.io/v3/packages/#create-polyfill-service-url) which can analyse javascript files and generate the correct polyfill.io url, which seems to solve the problem in a more targeted way.
