### ISSUE TITLE
Not working for gridsome + Bootstrap Vue

### ISSUE THREAD

**Issue by ngoclx** [polyfillpolyfill/polyfill-service#2425]
## What

Our site got some bugs working on IE (11), no input is clickable/functioning.  b-pagination, b-form-checkbox, etc...

## Details
I checked bootstrap vue (the package we added to gridsome) and found out that it requires polyfill for older browsers. They suggested to use polyfill.io but the bug is still there. - Const must be initialized

![image](https://user-images.githubusercontent.com/4980223/95943166-42073900-0e0f-11eb-9141-deb0e6dea424.png)

Do you have any idea why?

(Bootstrap vue's instruction about loading polyfill package: https://bootstrap-vue.org/docs#js)

**Comment by JakeChampion** [comment]
@ngoclx The code loaded in the browser must be compiled to ES5, I think you may be loading code with modern syntax such as `const` and `let`.

Can you please post the error message you are seeing?

**Comment by ngoclx** [comment]
Sorry guys, it was actually a bug from flexsearch plugin of gridsome. I'll be closing this tiket!
