### ISSUE TITLE
Adding "br" on Accept-Encoding modifies the minified polyfill

### ISSUE THREAD

**Issue by lucis** [polyfillpolyfill/polyfill-service#2428]
Sorry for the lack of details on this issue, I didn't have time to narrow down the cause, but I think the example are clarifying.

**Request with `Accept-Encoding: gzip, br`**
```
curl --location --request GET 'https://cdn.polyfill.io/v3/polyfill.min.js?features=Object.values,Object.entries,Object.assign,Array.from,Array.prototype.findIndex,Array.prototype.fill,Array.prototype.find,Array.prototype.includes,String.prototype.startsWith,String.prototype.endsWith,String.prototype.includes,Symbol,fetch,Promise,Map,WeakMap,Number.isInteger,Number.isNaN,Set,Function.name,URL,IntersectionObserver,Intl.~locale.en-GB&flags=gated' \
--header 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1' \
--header 'Accept-Encoding: gzip, br'
```

Results: the `Intl` polyfill is **not included**.

![image](https://user-images.githubusercontent.com/18706156/96146966-3e41e800-0edd-11eb-9298-c8f28c65d5ca.png)

**Request with `Accept-Encoding: gzip`**
```
curl --location --request GET 'https://cdn.polyfill.io/v3/polyfill.min.js?features=Object.values,Object.entries,Object.assign,Array.from,Array.prototype.findIndex,Array.prototype.fill,Array.prototype.find,Array.prototype.includes,String.prototype.startsWith,String.prototype.endsWith,String.prototype.includes,Symbol,fetch,Promise,Map,WeakMap,Number.isInteger,Number.isNaN,Set,Function.name,URL,IntersectionObserver,Intl.~locale.en-GB&flags=gated' \
--header 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1' \
--header 'Accept-Encoding: gzip'
```

Results: the `Intl` polyfill is included:
![image](https://user-images.githubusercontent.com/18706156/96146913-308c6280-0edd-11eb-85bb-b82ff1d8e2e9.png)

**Other points**
- If I ask only for `Intl` on the parameters, both cases come with the requested Polyfill, so that's why I couldn't narrow down what also impacts this.
- If I ask for the asset **not minified**, on both cases the `Intl` comes, so I was wondering there might be something related with caching.

**Comment by aronwoost** [comment]
Ok, this is the actual issue for #2421 

Different polyfills are delivered for 

`curl --location --request GET 'https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver' \
--header 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1' --header 'Accept-Encoding: gzip'`

and 

`curl --location --request GET 'https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver' \
--header 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1' --header 'Accept-Encoding: gzip, br'`

The `br` one does not include `ResizeObserver`.

**Comment by aronwoost** [comment]
Also for IE11.

Different polyfills are delivered (here only with `gzip`)

`curl --location --request GET 'https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko'`

`curl --location --request GET 'https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' --header 'Accept-Encoding: gzip'  --compressed`

**Comment by JakeChampion** [comment]
@lucis thanks for the issue. This was a caching issue and has been fixed now, I've tried all the curl requests in this issue's comments and they are all returning the expected polyfills now 👍 

```
curl --location --request GET 'https://cdn.polyfill.io/v3/polyfill.min.js?features=Object.values,Object.entries,Object.assign,Array.from,Array.prototype.findIndex,Array.prototype.fill,Array.prototype.find,Array.prototype.includes,String.prototype.startsWith,String.prototype.endsWith,String.prototype.includes,Symbol,fetch,Promise,Map,WeakMap,Number.isInteger,Number.isNaN,Set,Function.name,URL,IntersectionObserver,Intl.~locale.en-GB&flags=gated' \
--header 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1' \
--header 'Accept-Encoding: gzip, br' | brotli --decompress
```
that returns Intl ☝️ 

```
curl --location --request GET 'https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver' \ --header 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1' --header 'Accept-Encoding: gzip, br' | brotli --decompress
```
that returns ResizeObserver

The ie11 reqeuests return the same polyfills regardless of the compression used:
```
[[ `curl --location --request GET 'https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver' \ --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' --header 'Accept-Encoding: gzip' --compressed` == `curl --location --request GET 'https://polyfill.io/v3/polyfill.min.js?features=ResizeObserver' \ --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko'` ]] && echo "Equal" || echo "Not equal"

Equal
```

**Comment by lucis** [comment]
Thanks, @JakeChampion!

Do you think I can close the issue now, or is there any other development necessary to this problem?

**Comment by JakeChampion** [comment]
Let's close this since nothing else is needed to be done 👍
