### ISSUE TITLE
Uncaught TypeError: Illegal constructor on classList

### ISSUE THREAD

**Issue by yoshkinawa** [polyfillpolyfill/polyfill-service#2445]
This is a bug report

I got an error on Explorer 11: "Uncaught TypeError: Illegal constructor on classlist"
after running this code on my website: 
elmnt.classList.remove( className );

It also happend after this code:
document.body.classList.add( 'rtlJs' );

I can't reproduce this error on my IE11.
This happened only to other users (maybe it is a different build of IE11).
This is the user agent:  'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' 

I saw it was already reported in the past: (https://github.com/Financial-Times/polyfill-service/issues/1692)

**Comment by JakeChampion** [comment]
Hi @yoshkinawa, what is the full polyfill.io url you are using to load in the polyfills?

Also, could you write a small page on https://jsbin.com/ which replicates the bug, that way we can hopefully help figure out the root cause of this issue you are seeing :-)

**Comment by yoshkinawa** [comment]
I use this: https://cdn.polyfill.io/v2/polyfill.min.js

Here is a small script I wrote.
I've included other pollyfill libraries I used, in case they may have caused conflicts.
I could not replicate the error though. 


```
<script src="https://cdn.jsdelivr.net/npm/svgxuse@1.2.6/svgxuse.min.js"></script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>

<div id="div" class="originalClass">hellow world</div>
    
<script>

       var div = document.getElementById('div');

       div.classList.add( 'testClass' );
       console.log( div.classList );

       div.classList.remove( 'testClass' );
       console.log( div.classList );

       document.body.classList.add( 'bodyClass' );
       console.log( document.body.classList );

</script>
```
