### ISSUE TITLE
[Bug] Chrome/49 - Cannot redefine property: isConcatSpreadable

### ISSUE THREAD

**Issue by hkano** [polyfillpolyfill/polyfill-service#2471]
- Browser: Chrome/49.0.2623.112
- Os: Mac OS X 10.6.8
- Error: Cannot redefine property: isConcatSpreadable

__Error as described in Datadog__
```
TypeError: Cannot redefine property: isConcatSpreadable
  at Function.defineProperty(native) @ undefined
  at <anonymous> @ https://polyfill.io/v3/polyfill.min.js?features=default%2Ces2015%2CNodeList.prototype.forEach%2Cfetch:3:17130
  at <anonymous> @ https://polyfill.io/v3/polyfill.min.js?features=default%2Ces2015%2CNodeList.prototype.forEach%2Cfetch:3:25647
```

__User-Agent as described in Datadog__
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
```

__Our polyfill.io url__
```
https://polyfill.io/v3/polyfill.min.js?features=default%2Ces2015%2CNodeList.prototype.forEach%2Cfetch
```

I tried spoofing the user agent and using only `isConcatSpreadable`, so polyfill was called for.
```
URL: https://polyfill.io/v3/polyfill.min.js?features=Symbol.isConcatSpreadable
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
```

> ![https___polyfill_io_v3_polyfill_min_js_features_Symbol_isConcatSpreadable](https://user-images.githubusercontent.com/1640433/102180187-cba8b500-3eeb-11eb-91e6-d53a261c3c57.png)

I think the correct behavior is that it will not be called if the chrome version is 48 or higher.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/isConcatSpreadable

The config for `isConcatSpreadable` is `chrome = "<48"`.
https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Symbol/isConcatSpreadable/config.toml#L13

Please confirm the above.

**Comment by JakeChampion** [comment]
Symbol.isConcatSpreadable was changed to serve to Chrome lower than 48 [yesterday in polyfill-library](https://github.com/Financial-Times/polyfill-library/releases/tag/v3.99.0).

polyfill.io is not using the latest version of polyfill-library yet, the version it is using does serve Symbol.isConcatSpreadable to Chrome versions lower than 50, which is what you are seeing.

**Comment by hkano** [comment]
Oh, it was just released? I’m sorry, I missed the release.
When do you plan to have the latest version of polyfill-library on polyfill.io?

**Comment by JakeChampion** [comment]
I'll be doing a release today 👍

**Comment by JakeChampion** [comment]
Here is the pull-request updating to the latest version https://github.com/Financial-Times/polyfill-service/pull/2472

**Comment by hkano** [comment]
@JakeChampion I was able to confirm it as well. Thank you!
