### ISSUE TITLE
[feature] missing String.replaceAll polyfill

### ISSUE THREAD

**Issue by daniele-orlando** [polyfillpolyfill/polyfill-service#2473]
### Feature Request

The service is missing the **String.prototype.replaceAll()** polyfill.

## Details
Is there any plan to integrate the aforementioned polyfill?
It is in the Standard and ships in all modern Browsers.

References:
Financial-Times/polyfill-library#803

**Comment by JakeChampion** [comment]
Array.prototype.replaceAll is not a standard or a proposal. Do you mean String.prototype.replaceAll?

**Comment by JakeChampion** [comment]
String.prototype.replaceAll is already in polyfill.io -- https://polyfill.io/v3/polyfill.js?features=String.prototype.replaceAll|always

**Comment by daniele-orlando** [comment]
Yes, sorry I meant **String.prototype.replaceAll**.

As you can see I can't find it through the filter form on the web site.

![Schermata 2020-12-16 alle 05 31 55](https://user-images.githubusercontent.com/504386/102305439-60e59100-3f60-11eb-97d7-0b2f2918bd75.png)

**Comment by daniele-orlando** [comment]
@JakeChampion should I fill a new ticket?

**Comment by JakeChampion** [comment]
@daniele-orlando Thanks for pointing that out, I've just updated the website to include it :-)
You may need to clear your browser cache for the page before you can see it

![image](https://user-images.githubusercontent.com/1569131/102609802-01d07980-4124-11eb-8380-1194cac3e2d4.png)

**Comment by daniele-orlando** [comment]
Awesome, I see it.

Thank you very much! ❤️
