### ISSUE TITLE
Element.prototype.replace has been renamed to `replaceWith`

### ISSUE THREAD

**Issue by mislav** [polyfillpolyfill/polyfill-service#248]
https://github.com/whatwg/dom/commit/b7563aaf0864c8d104d18c36a9eda036c5205131

/cc @jonathantneal

**Comment by triblondon** [comment]
HI @mislav thanks for this issue, though we don't currently have an `Element.prototype.replace` polyfill.  We'd be very happy to add a `replaceWith` polyfill, if you'd consider contributing one.

**Comment by jonathantneal** [comment]
We do have a [replace polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Element.prototype.mutation/polyfill.js#L50-L54) in [mutation](https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/Element.prototype.mutation). I’ll make an update now.

And kudos to @mislav for making clear issues that lead me to feel like I can checkin on GitHub again.

**Comment by triblondon** [comment]
Whoops, sorry, thanks Jonathan.

**Comment by triblondon** [comment]
OK, let's continue this in #254
