### ISSUE TITLE
Error on Safari iOS 9.3.5 when using Promise%2CIntl%2Cfetch - 14672:11: ReferenceError: Can't find variable: Intl

### ISSUE THREAD

**Issue by bmarotta** [polyfillpolyfill/polyfill-service#2481]
Bug report

## What

The following errors occur on clients using Safari on an Apple iPad running iOS 9.3.5
Error on https://polyfill.io/v3/polyfill.js?features=Promise%2CIntl%2Cfetch 14672:11: ReferenceError: Can't find variable: Intl

## Details

Error found on following combinations
- Browser: Safari or Chrome 61 or Chrome 63
- Device: iPad
- OS: iOS 9.3.5

A similar error happens on other browsers
Error on https://polyfill.io/v3/polyfill.js?features=Promise%2CIntl%2Cfetch 11163:3: Uncaught ReferenceError: Intl is not defined 
- Chrome 57 on a Meizu M6 running Android 6.0
- Chromium   WebView 61 on a Xiaomi Redmi 5 Plus running Android 7.1.2
--

**Comment by JakeChampion** [comment]
Hi @bmarotta, could you post a short amount of code which replicates the issue please?

I've tried to replicate the issue using only the polyfill.io script you mention but no error happens and the polyfills work as expected for me

![image](https://user-images.githubusercontent.com/1569131/102770299-d1831800-437b-11eb-9fa2-130fcb0f6d7e.png)

**Comment by rangrasjay** [comment]
> Hi @bmarotta, could you post a short amount of code which replicates the issue please?
> 
> I've tried to replicate the issue using only the polyfill.io script you mention but no error happens and the polyfills work as expected for me
> 
> ![image](https://user-images.githubusercontent.com/1569131/102770299-d1831800-437b-11eb-9fa2-130fcb0f6d7e.png)

Could you be able to try the same on safari 9 on ipad?

**Comment by JakeChampion** [comment]
I just checked this in browserstack and could no longer replicate the issue, I suppose it was fixed in a release that happened in the last year
