### ISSUE TITLE
atob polyfill: not the same as native

### ISSUE THREAD

**Issue by roland-vachter** [polyfillpolyfill/polyfill-service#250]
It seems that the new Livefyre API is using this function, and it fails to run in IE8 and 9 due to the way the polyfill is made.

Run the following code in Chrome:

``` javascript
atob("eyJkb21haW4iOiJmdC0xLmZ5cmUuY28iLCJleHBpcmVzIjoxNDIxOTQxOTE1LCJ1c2VyX2lkIjoiODk0ODc0MzkiLCJkaXNwbGF5X25hbWUiOiJyb2xpIG1haW4ifQ")
```

The result:

``` javascript
"{"domain":"ft-1.fyre.co","expires":1421941915,"user_id":"89487439","display_name":"roli main"}"
```

Run the same code in IE8/9 with polyfill: it throws an error saying invalid base64.

Even if that's the case, the native version is fault tolerant, and adds the missing "==" at the end.
The reason why it fails is the test in the polyfill:

``` javascript
input.length % 4 > 0
```

If this is true, the input is considered invalid.

A better way would be to handle it as the native atob is handling it in Chrome: add the missing ending "==".

**Comment by triblondon** [comment]
Good idea.  Could you do a PR to the polyfill?  I think we can probably aim
for a release next week.

**Comment by roland-vachter** [comment]
Yep, I will.

**Comment by roland-vachter** [comment]
Are there individual tests for the polyfills? I can't find any..

**Comment by triblondon** [comment]
Yes there are and details of how to author are in the contributors guide.
This particular polyfill may not have tests, in which case obviously
writing a couple would be excellent.

**Comment by roland-vachter** [comment]
Please let me know when this is released so that we can retest the fix. Thanks

**Comment by roland-vachter** [comment]
Hi Andrew,

Apparently this is not yet released, and we have the same errors.
Is there an approximate date when this will be released?

Thanks

**Comment by triblondon** [comment]
Working on it.  Was having trouble with heroku, hope to resolve today.

**Comment by roland-vachter** [comment]
Ok, thanks. Please let me know

**Comment by matthew-andrews** [comment]
trouble with heroku was my bad — sorry @roland-vachter
