### ISSUE TITLE
Unsupported browsers

### ISSUE THREAD

**Issue by juandopazo** [polyfillpolyfill/polyfill-service#252]
The service is returning an empty response for UA strings it can´t parse. What´s the rationale behind this? Shouldn't it default to serving the polyfills?

**Comment by matthew-andrews** [comment]
:+1:

**Comment by monolithed** [comment]
+1.

**Comment by triblondon** [comment]
Which polyfills would you serve?  We could use the default set of features, but do you assume that your mystery browser lacks all the features and needs every polyfill?  Some polyfills have only browser specific variants, so the generic case simply doesn't exist.

**Comment by juandopazo** [comment]
Whatever was requested. If the default set was requested, then respond with the default set.

And the browser specific variants wouldn't apply.

**Comment by triblondon** [comment]
OK, sorry being dumb on the features to consider front - it's in the request.  But my point is that you get every single one.  A mystery browser is probably a very poor browser, and I'd rather not crash it by getting it to parse every polyfill we have!

**Comment by matthew-andrews** [comment]
Sorry to bikeshed but could this be an option?

```
GET /v1/polyfill.js?ua=sparta/1&fallback=ie/9&features=promises
```

**Comment by triblondon** [comment]
I don't think this is bikeshedding.  The issue has been mentioned to me before too, so a significant number of people do think intuitively that an unknown browser should get a ton of polyfills.

So you're proposing a new `fallback` param (perhaps `fallbackUa`?), which is used if the `ua` property (or the user agent header) fails to map to a known browser.  If `fallbackUa` also fails to map to a known browser, we then deliver an empty file.

What would be the use cases?  Would you always use an older browser as your fallbackUa?  If so, the effect may not be substantially different from delivering all polyfills (except with a specific named fallback browser you would potentially get variants designed for that browser's proprietary hooks).

Another alternative is to simply add a boolean param, `enableUnknown`, which if set to true will cause the service to bundle all polyfills for the requested feature set, using only default variants.

**Comment by triblondon** [comment]
@juandopazo any further thoughts on this?

**Comment by juandopazo** [comment]
Not a fan of "fallbackUA". We need the ability to, from the programmatic API, request a polyfill without a UA for cases like Autopolyfiller. What fallback UA would Autopolyfiller use?

But also as you've said, intuitively most people expect not to see an empty response for unknown UAs. I understand your concerns about certain devices having trouble parsing big JS files, but what about all those Android 2.3 variants out there? Are we sure `user-agent` is able to identify them all?

**Comment by triblondon** [comment]
Well, I wouldn't stake my life on it, but it does do pretty well with everything I've thrown at it so far.  I think the best compromise here is `enableUnknown`.  Anyone object to that?

**Comment by matthew-andrews** [comment]
I think the empty response solution is very much compatible with cuts the mustard approach we take at FT. Other people don't use same approach so something like enableUnknown seems sensible.

I'd slightly prefer unknown=enable or unknown=polyfill or I'd even be comfortable with making it the default but I'm an outsider on this project to some extent so definitely defer to you all that have put much more thought into this service than I have.

Sorry not perfect English. Github mobile sucks and I had to rewrite this answers three times!!!

**Comment by triblondon** [comment]
OK, went with `unknown`, with options `ignore` and `polyfill`, defaulting to 'ignore'.  See https://github.com/Financial-Times/polyfill-service/pull/276.
