### ISSUE TITLE
Feature request: isSecureContext

### ISSUE THREAD

**Issue by jimmywarting** [polyfillpolyfill/polyfill-service#2530]
Want to have a way to detect if the origin is a secure context
it's possible with `globalThis.isSecureContext` but not all browser have implemented it

> Locally-delivered resources such as those with http://127.0.0.1 URLs, http://localhost and  http://*.localhost URLs (e.g. http://dev.whatever.localhost/), and file:// URLs are also considered to have been delivered securely.

> Note: Firefox 84 and later support http://localhost and http://*.localhost URLs as trustworthy origins (earlier versions did not, because localhost was not guaranteed to map to a local/loopback address).

So to sum it up i need something like this:
```js
window.isSecureContext = location.origin.test(all possible safe urls)
```

**Comment by JakeChampion** [comment]
This would not be possible to implement correctly because it depends on knowing how a document was opened/created, which is not something that client-side javascript is capable of figuring out.

For example, if you were on a non-secure context such as `http://lorem.com` and clicked a link which went to a https page but it did not set `rel` to `noopener`, then the new document would be non-secure also
```html
<a href="https://example.com/" target="_blank">I link to a https document but it won't be secure</a>
```

Another example would be if a non-secure context had an iframe to `https://example.com`. `https://example.com` would be non-secure in that situation as well.

The non-secure context can travel further than two documents, it would travel to all documents and resources in the chain. For example if the top-level document is non-secure and loads an iframe to `https://example.com/`, and that loads a javascript worker with `https://example.com/worker.js`, then neither the iframed document nor the worker are secure contexts.

I'm not sure we should polyfill something which has to do with security if we would end up falsely saying a context is secure when it is not.

**Comment by jimmywarting** [comment]
oh, i had no idea that it was that complicated 😕 
isn't there a way to test some power javascript feature instead then?

like checking if crypto.subtle exist.

**Comment by JakeChampion** [comment]
> oh, i had no idea that it was that complicated 😕
> isn't there a way to test some power javascript feature instead then?
> 
> like checking if crypto.subtle exist.

That's clever!

I tried crypto.subtle but it looks to not exist in IE11 --

![image](https://user-images.githubusercontent.com/1569131/108702893-c70f0700-7501-11eb-9e56-3374beb5634b.png)

**Comment by jimmywarting** [comment]
Well, dah... IE is so old/dead that it don't even have web crypto - Everyone should switch to edge or some other browser.
Is there some other "power full" tool that we can check for? 

Edit i found my way back to this [list](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features):

> “Secure origins” are origins that match at least one of the following (scheme, host, port) patterns: 
> - (https, *, *)
> - (wss, *, *)
> - (*, localhost, *)
> - (*, 127/8, *)
> - (*, ::1/128, *)
> - (file, *, —)
> - (chrome-extension, *, —) 

Think there must be some kind of list of aka power full feature that is behind a secure context flag
looking at the [spec](https://w3c.github.io/webappsec-secure-contexts/#informative) it looks a bit like some other possible stuff could be plausible

- webcrypto 
- bluetooth 
- service worker 
- mediacapture 
- indexeddb 
- geolocation 
- fullscreen 
- encrypted media (MSE) 
- the credential api
- native file system access

Most of those dose not even exist in IE
...speaking of indexeddb i guess it exist in non secure context also, i mean it was invented long before "secure context" where a thing to get behind
also have made a [stackoverflow post](https://stackoverflow.com/a/37091058/1008999) about how to detect private browser mode and IE removes indexeddb in private mode from the window. so i needed another IE feature detection that got introduced at the same time indexeddb got released to make sure it got removed and wasn't just not-implemented.

**Comment by jimmywarting** [comment]
When i went to example.com and compared what did exist in window on http and https then i found this differences

0: "onscreenschange"
1: "caches"
2: "ondevicemotion"
3: "ondeviceorientation"
4: "ondeviceorientationabsolute"
5: "cookieStore"
6: "nativeIO"
7: "getScreens"
8: "isMultiScreen"
9: "showDirectoryPicker"
10: "showOpenFilePicker"
11: "showSaveFilePicker"
12: "getDigitalGoodsService"

**Comment by jimmywarting** [comment]
> This would not be possible to implement correctly because it depends on knowing how a document was opened/created, which is not something that client-side javascript is capable of figuring out.
> 
> For example, if you were on a non-secure context such as http://lorem.com and clicked a link which went to a https page but it did not set rel to noopener, then the new document would be non-secure also

Would i be possible to check it has a opener and in that case look at `window.top` if that is secure or not

**Comment by JakeChampion** [comment]
> > This would not be possible to implement correctly because it depends on knowing how a document was opened/created, which is not something that client-side javascript is capable of figuring out.
> > For example, if you were on a non-secure context such as http://lorem.com and clicked a link which went to a https page but it did not set rel to noopener, then the new document would be non-secure also
> 
> Would i be possible to check it has a opener and in that case look at `window.top` if that is secure or not

I don't think that will work for the scenario where the iframe'd document loads some javascript in a worker.

This scenario:

>If the top-level document is non-secure and loads an iframe to `https://example.com/`, and that iframe loads a javascript worker with `https://example.com/worker.js`, then neither the iframed document nor the worker are secure contexts.
