### ISSUE TITLE
Create a feature group that includes all polyfills

### ISSUE THREAD

**Issue by JonathanWolfe** [polyfillpolyfill/polyfill-service#258]
Since `http://cdn.polyfill.io/v1/polyfill.js?features=es6` is a thing, it would be nice to have `http://cdn.polyfill.io/v1/polyfill.js?features=all` which includes all polyfills available instead of just the default or es6 groups.

You should also create a list of all the feature groups and what they include.

**Comment by triblondon** [comment]
See https://github.com/Financial-Times/polyfill-service/pull/275
