### ISSUE TITLE
Making the API async

### ISSUE THREAD

**Issue by juandopazo** [polyfillpolyfill/polyfill-service#260]
Would it make sense to make the `getPolyfillString` family of functions asynchronous?

**Comment by samgiles** [comment]
Potentially.  `getPolyfillString` however really doesn't do anything asynchronously, we don't do any IO beyond network.  I'd like to measure it but it might add unnecessary latency if we make it async using `process.nextTick` or something.  The response time we get on the node process is on average 3ms at the moment, (we should measure 95th and 99th percentile) but the max as of right now is 88ms.

**Comment by juandopazo** [comment]
I meant not caching everything on startup. Instead `getPolyfillString` could read everything on demand and the service could use https://www.npmjs.org/package/async-cache.

I don't really need this, so I'll close it. But we can keep discussing if you find it interesting.
