### ISSUE TITLE
Function.prototype.bind error on Safari 5.1

### ISSUE THREAD

**Issue by blainekasten** [polyfillpolyfill/polyfill-service#261]
When loading the polyfill in Safari 5.1 on Windows 7.

The following is spit into the console:

`TypeError: instanceof called on an object with an invalid prototype property.`

It occurs in this function:

```
Function.prototype.bind = function bind(scope) {
    var callback = this,
    prepend = Array.prototype.slice.call(arguments, 1),
    Constructor = function () {},
    bound = function () {
        return callback.apply(
            this instanceof Constructor && scope ? this : scope,
            prepend.concat(Array.prototype.slice.call(arguments, 0))
        );
    };

    Constructor.prototype = bound.prototype = callback.prototype;

    return bound;
};
```

**Comment by jkimbo** [comment]
:+1: I've just come across this problem in OSX Lion with the same version of Safari

**Comment by triblondon** [comment]
Thanks for the report.  We'd be grateful if you could debug it and contribute a fix if you have time.

**Comment by triblondon** [comment]
Note that issue https://github.com/Financial-Times/polyfill-service/issues/313 also has a problem with the `bind` polyfill.  If you can confirm that es5-shim version fixes your problem, we could switch to that.

**Comment by jkimbo** [comment]
@triblondon I've just added in the es5-shim version and it seems to work on Safari.

**Comment by jonathantneal** [comment]
Yes, my polyfill was more like the MDN one. John Dalton even tried to warn me about this long long ago. Unfortunately, I did not yet fully understand prototype inheritance at that time. So, I’ve been reviewing those notes and these and refactoring the polyfill early this morning. I needed to break for my daily work, but I expect to complete the update tonight.

Here’s a snippet of where I left off, and my new thinking for the polyfill:

``` js
function Empty() {}

var splice = Array.prototype.splice;

Function.prototype.bind = Function.prototype.bind || function bind(scope) {
    var
    callback = this,
    args = splice.call(arguments, 1),
    index = -1,
    length = 0,
    buffer = 'return function (',
    binder = function () {
        var
        self = this,
        isNew = self instanceof bound,
        result = callback.apply(isNew ? self : scope, args.concat(splice.call(arguments, 0)));

        return !isNew || Object(result) !== result ? result : self;
    };

    if (!(callback instanceof Function)) {
        throw new TypeError(callback + ' is not a function');
    }

    length = Math.max(length, callback.length - args.length);

    while (++index < length) {
        buffer += '$' + index;
    }

    /* final magic */
};
```

I’ve also been referencing @jussi-kalliokoski [ref](https://gist.github.com/jussi-kalliokoski/978329) and @ljharb’s [es5-shim](https://github.com/es-shims/es5-shim/blob/master/es5-shim.js#L196-L330) implementations. I believe the major fault in my and MDN’s implementation was inheritance. However, I also noticed in the ES5 shim that native bind properly preserves/calculates the new bound function length.

**Comment by ljharb** [comment]
fwiw `callback instanceof Function` is not a valid test for "is a function", because of iframes/other realms, as well as host objects. I'm afraid that all the awfulness in https://github.com/ljharb/is-callable/blob/master/index.js is what's required for a proper "is callable" check.

**Comment by jonathantneal** [comment]
You are correct. Any polyfill that uses a function (be they event listeners, array prototype methods, etc.) limit themselves to the same frame. Should we support cross-frame polyfilling, it needs to be addressed in a separate issue. Something like (or exactly as) what you’ve shared would need to be added as a private dependency and then integrated into the dozen or more polyfills that use the current check. It would not be wise to integrate this check here, and then slowly duplicate such a verbose check across every other polyfill.

Also, I’m naive to the use case for this kind of cross frame scripting. Could someone show me an example?

@triblondon, @juandopazo, thoughts?

**Comment by juandopazo** [comment]
Cross-frame is a real thing. :ghost: One example in the wild is WYSIWYG editors which use iframes to isolate styles. Also at Yahoo we have teams using iframes to isolate code. And in the future with a Realm reflection API we might see even more code isolation using different realms.
