### ISSUE TITLE
Bug: Array.from is adding unwanted properties to prototype

### ISSUE THREAD

**Issue by SimplySayHi** [polyfillpolyfill/polyfill-service#2621]
[Bug]

## What
Polyfill Array.from is adding unwanted properties to object prototype

## Details
If I load the polyfill for Array.from and then I run this code:
```
var a = {};
for(var p in a){
    console.log(p);
}
```
I get something like:
```
__�symbol:iterator0.78666530507841011
__�symbol:meta_51354793889167840.78666530507841013
__�symbol:undef0.78666530507841014
__�symbol:undef0.78666530507841015
__�symbol:species0.78666530507841012
__�symbol:undef0.78666530507841017
__�symbol:toStringTag0.78666530507841016
```
This can cause errors and block the js application.

I don't expect to see these properties added to the prototype object.

I noticed this in a legacy project where we are using jQuery 3.5.1, where $.each() applied to a js object {} is causing an error.
I know it depends on how for...in loop is used but I think the mentioned props should not be there.

I noticed this bug in IE11 but it can be reproduced in any browser if you load the polyfill with flag "always".
I've read a suggestion about adding flag "gated" when using "always" but this is not a solution for me, since the code would cause an error in any case in IE11 ( or other browsers not natively supporting Array.from ).

Browser: any
Device: any

**Comment by JakeChampion** [comment]
Thanks for opening this issue and apologies for taking so long to respond.

This is unfortunately something we won't be fixing as it is an edge case that not many people are having an issue with and we don't have the capacity to work on changing our Symbol polyfill to not have cause this side-effect
