### ISSUE TITLE
IE 11 have no Array.prototype.find

### ISSUE THREAD

**Issue by OrbSang** [polyfillpolyfill/polyfill-service#2623]
## What

BUG：IE 11 have no ` Array.prototype.find`
## Details
my code：
```javascript
<script crossOrigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js"></script>
```

polyfill don't return  `Array.prototype.find`

**Comment by JakeChampion** [comment]
Hi @liupeng1997, that is because `Array.prototype.find` is not in the default collection of polyfills.

If you want to include it along the default set of features then the url would look like this
-- `https://polyfill.io/v3/polyfill.min.js?features=default,Array.prototype.find`
