### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [polyfillpolyfill/polyfill-service#2624]
Hi, it seems that http://polyfill.io websites no longer reachable via IPv6 connections.

Is there any issue regarding IPv6 support?

Thank you.

**Comment by JakeChampion** [comment]
Yes, Fastly are not yet offering ipv6 support on the new setup we had to migrate to. It is something they are working on to enable :+1:

**Comment by tambry** [comment]
What new Fastly offering are you using that has the issue?

The would-be Anycast IPv6 addresses work fine for me:
```
2a04:4e42::282
2a04:4e42:200::282
2a04:4e42:400::282
2a04:4e42:600::282
```

**Comment by JakeChampion** [comment]
We are using their new tls certificate offering and it does not come with ipv6 addresses unfortunately 
![screenshot of the fastly admin page showing the certificate for polyfill.io has no associated ipv6 addresses](https://user-images.githubusercontent.com/1569131/128490686-7f38a2e7-5448-4e02-99f6-62514a9fe70c.png)

**Comment by tambry** [comment]
Did you specifically ask Fastly support to enable IPv6 and they said it isn't possible?  
To me it seems they moved you to a customer-specific hostname. Per my experience you [specifically need to ask support](https://docs.fastly.com/en/guides/ipv6-support#enabling-ipv6-on-customer-specific-hostnames) to enable IPv6 for those.

All Fastly CDN offerings (sans old or specific offerings/features I might not be aware of) support IPv6 and it can't be disabled. The formula with `151.101.x.y` is `x * 256 + y` for the service ID, which you can suffix to any of their Anycast or POP prefixes.  
Having them "enable" IPv6 only does one of the following:

1. They manually give you the Anycast IPv6 addresses to add to DNS.
2. They add them to your customer-specific hostname or create a separate one.

One can calculate that and test it manually:
```
root@deb:~# curl https://[2a04:4e42::282]/v3/ -H "Host:polyfill.io" -k
<!doctype html>
<html class="no-js" lang="en">

<head>

                <meta charset="utf-8">
                <meta http-equiv="x-ua-compatible" content="ie=edge">
                <meta name="description" content="Polyfill.io">
                <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
...
```

**Comment by JakeChampion** [comment]
> Did you specifically ask Fastly support to enable IPv6 and they said it isn't possible?

I did, but I will ask again now 👍

**Comment by JakeChampion** [comment]
Hi all, IPV6 support has been added and released to production now 🎉

**Comment by tambry** [comment]
While the AAAA records for `polyfill.io` seem to have been added, they're still unfortunately [missing for `cdn.polyfill.io`](https://www.whatsmydns.net/#AAAA/cdn.polyfill.io) (really `polyfill.map.fastly.net`).

**Comment by JakeChampion** [comment]
@tambry the cdn.polyfill.io aaaa records will be going out later today 👍

**Comment by JakeChampion** [comment]
@tambry we will be moving from polyfill.map.fastly.net to dualstack.polyfill.map.fastly.net.
