### ISSUE TITLE
Feature Request: Embed HackerOne submission form in security policy page

### ISSUE THREAD

**Issue by notlee** [polyfillpolyfill/polyfill-service#2625]
Embed a HackerOne submission form on the [security policy page](https://polyfill.io/v3/security-policy/#reporting-a-security-issue), instead of listing an email to 
gain access to the HackerOne program. 

Instructions here: https://docs.hackerone.com/programs/embedded-submissions-form.html
Real world example here: https://docs.hackerone.com/programs/embedded-submissions-form.html

**Comment by notlee** [comment]
Currently we forward requests to the Cyber Security team, who take requests from there. 
It's a little inefficient and requests can get missed.

**Comment by JakeChampion** [comment]
I looked into doing this but I do not have the ability to view the "Embedded Submission Form" in the HackerOne settings -- I've updated the [internal Jira SRS ticket](https://financialtimes.atlassian.net/browse/SRS-363?atlOrigin=eyJpIjoiMDFhNGE1YjlhZTQ1NDM2ZWEzNzJhZWMzNGI5ODZjOWUiLCJwIjoiaiJ9) with this information to let them know we are blocked by this
