### ISSUE TITLE
https://polyfill.io/v3/json/library-3.53.1.json is not found

### ISSUE THREAD

**Issue by dujushi** [polyfillpolyfill/polyfill-service#2626]
On the [URL builder](https://polyfill.io/v3/url-builder/) page, when select a version, it will send out a request to `https://polyfill.io/v3/json/library-version.json` . When you select 3.53.1 or 3.52.3, the request returns 404.

**Comment by JakeChampion** [comment]
Thank you for the report @dujushi, this will be fixed when https://github.com/Financial-Times/polyfill-service/pull/2630 is merged and released 👍
