### ISSUE TITLE
Intl.DisplayNames not loaded when specifying a version

### ISSUE THREAD

**Issue by screendriver** [polyfillpolyfill/polyfill-service#2628]
Bug

## What

`Intl.DisplayNames` does not get loaded in older Safari versions.

## Details

When I try to load the `Int.DisplayNames` polyfill in Safari 13.1.2 with the a version defined in the URL `https://polyfill.io/v3/polyfill.min.js?version=3.53.1&features=default%2CIntl.DisplayNames` I'm getting

<img width="1439" alt="Screenshot 2021-07-08 at 07 07 02" src="https://user-images.githubusercontent.com/149248/124865822-af6d8200-dfbb-11eb-8aae-8b436ea2233e.png">

When I try to load it **without** the version `https://polyfill.io/v3/polyfill.min.js?features=default%2CIntl.DisplayNames` it seems to work:

<img width="1439" alt="Screenshot 2021-07-08 at 07 07 18" src="https://user-images.githubusercontent.com/149248/124865876-c1e7bb80-dfbb-11eb-89ce-666c4560ba9a.png">

**Comment by JakeChampion** [comment]
Looking at polyfill-library versions, Intl.DisplayNames was added in version [3.94.0](https://github.com/Financial-Times/polyfill-library/releases/tag/v3.94.0) - which is why you are not seeing if when setting the version to 3.53.1

**Comment by screendriver** [comment]
Ok. But then the bug is that the website is showing `3.53.1` as latest version (which is was relying on):

<img width="281" alt="Screenshot 2021-07-08 at 10 59 20" src="https://user-images.githubusercontent.com/149248/124894032-91b01500-dfdb-11eb-8787-57e1e49975db.png">

**Comment by JakeChampion** [comment]
Thanks for letting us know about the out of date url-builder page @screendriver. I've made a [pull-request to update it](https://github.com/Financial-Times/polyfill-service/issues/2628) and updated the contributing guide to help ensure this step isn't missed in the future

**Comment by screendriver** [comment]
Nice. Thanks 👍
