### ISSUE TITLE
IntersectionObserver && ResizeObserver is not defined using polyfill.io on Firefox 78 ESR

### ISSUE THREAD

**Issue by yadue** [polyfillpolyfill/polyfill-service#2635]
Bug

## What
Some Firefox 78 ESR versions doesn't support ResizeObserver and IntersectionObserver, in that case they are not polyfilled correctly.

## Details
When using 
```<script src="//cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en-US,URL,ResizeObserver,IntersectionObserver"></script>```

and User Agent:
* Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

our sentry logs logs thousands of errors
* ReferenceError: 'ResizeObserver' is undefined
* ReferenceError: 'IntersectionObserver' is undefined

**Comment by Petrux99** [comment]
This also happens in Firefox 52.9.0 ESR (where support is hidden behind a config toggle according to Caniuse) on Windows XP, according to a user. I have tested in the same version on Ubuntu but there it works (the polyfill is included in the response).

**Comment by JakeChampion** [comment]
@yadue IntersectionObserver was added in firefox 55, i'm not sure why firefox 78 would not have it defined. to resolve that you will need to request the polyfill to always be returned in the bundle and wrapped in a feature detect like so:

```
 <script src="//cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en-US,URL,ResizeObserver,IntersectionObserver|always|flag"></script>
```
