### ISSUE TITLE
Idea: Reverse Proxy Docs / Spec

### ISSUE THREAD

**Issue by jamesarosen** [polyfillpolyfill/polyfill-service#2637]
Type: discussion

## What
We currently run our own instance of Financial-Times/polyfill-service. The primary reason is that we want to avoid the extra DNS+TCP+HTTP+TLS cost of connecting to `polyfill.io`. We maintain a custom reverse proxy in Cloudflare that largely mimics the Fastly implementation here.

The compute cost to run the instance is pretty minimal, but there are some maintenance costs.

I'd like to propose a different model: we continue to run the reverse proxy in Cloudflare, but we use `polyfill.io` as the origin.

## Details

Some questions for the Financial-Times team:

* Are you OK with third-party edge proxies connecting to `polyfill.io`?
* Should we establish some sort of "authorized" client scheme?
* If we were to open-source our Cloudflare worker implementation, would you like to adopt that under the Financial-Times GitHub organization? Or would you prefer we the the primary maintainers?
* Should there be some sort of spec that the Fastly and Cloudflare implementations can code to so they remain aligned?

**Comment by JakeChampion** [comment]
>     * Are you OK with third-party edge proxies connecting to `polyfill.io`?

Yes we are okay with this, I know of quite a few companies which do this, The Guardian does this or did this (I haven't checked recently).

>     * Should we establish some sort of "authorized" client scheme?

I don't know what this means, could you elaborate? I don't think we need to establish anything as we already have customers which proxy through to polyfill.io and it all works correctly

>     * If we were to open-source our Cloudflare worker implementation, would you like to adopt that under the Financial-Times GitHub organization? Or would you prefer we the the primary maintainers?

We would not take ownership of it as we do not use CloudFlare and would not be able to test any changes work as expected -- it would be great if you maintain it as the primary owners

>     * Should there be some sort of spec that the Fastly and Cloudflare implementations can code to so they remain aligned?

I'm not sure how much alignment is required for a reverse proxy to polyfill.io - I believe no extra code is required for a proxy to work, all the code we have in the Fastly config is optional performance and caching optimisations

**Comment by jamesarosen** [comment]
> I'm not sure how much alignment is required for a reverse proxy to polyfill.io - I believe no extra code is required for a proxy to work, all the code we have in the Fastly config is optional performance and caching optimisations

We would want to be able to cache at our edge for resiliency and performance, so we would at least want the agent-denormalization there.

**Comment by JakeChampion** [comment]
We have that available in VCL and JS and we keep those always in sync via this project :-) -> https://github.com/Financial-Times/polyfill-useragent-normaliser

**Comment by jamesarosen** [comment]
Thanks! I hope this issue serves as documentation for other teams that want to pursue the reverse-proxy approach. If we end up publishing our Cloudflare implementation, I'll link to it here.
