### ISSUE TITLE
polyfill CDN down

### ISSUE THREAD

**Issue by wendylw** [polyfillpolyfill/polyfill-service#2638]
## What

polyfill failed to load

## Details

A large number of CDNs in Malaysia cannot load this file

**Comment by lukeupup** [comment]
Hello,

this problem seems to still be there in Malaysia. The browser shows "ERR_CONNECTION_TIME_OUT".

![240684481_994315578049278_8563533695576855680_n](https://user-images.githubusercontent.com/558673/131140309-858cb9fb-9a23-4f97-86d4-6df10305d8d2.png)

**Comment by JakeChampion** [comment]
I looked into this, I see no issue on [Fastly's status-page](https://status.fastly.com/) or any issues recorded on our backend servers dashboards either. I'm not sure what this issue is but it seems to be sporadic in nature?

**Comment by lukeupup** [comment]
> I looked into this, I see no issue on [Fastly's status-page](status.fastly.com/) or any issues recorded on our backend servers dashboards either. I'm not sure what this issue is but it seems to be sporadic in nature?


Hi,

Thanks for reply. Per our monitor system, this issue seems have impact extensive users in Malaysia (where our product majoyly serves). We ask several team members to try to open the url from their home in Malaysia, but none of them can open it. The server won't send any errors immediately. It just hangs there and gets timeout after 30 seconds. However our team member from China can open it without any problem. So I am guessing whether it could be a CDN problem.

We understand that the service uptime or reachability is not guaranteed, but we still hope that you can take a bit more look, since there should be more than us to use polyfill.io in Malaysia. And the service timeout will cause a 30 sec blank page for those webpages that are not importing the polyfills in async way.

Again, thank you for any help or suggestions.

**Comment by hueiyik** [comment]
It's not working here in Malaysia since Friday. Can we have a fix? Polyfill.io is not opening either.

**Comment by jgiambona** [comment]
We are also experiencing the same in Malaysia. Doesn't seem to be sporadic, some ISPs consistently having issues it seems.

**Comment by smaeda-ks** [comment]
Could you please tell us what ISP are you on? You may want to reach out to the ISP then.

Also, I'm curious what happens if you disable IPv6 on your machine. For instance, if you're using the macOS,
https://support.nordvpn.com/Connectivity/macOS/1047410442/How-to-disable-IPv6-on-macOS.htm

Does that make any difference?

[updated]
As someone pointed out, I don't believe this problem belongs to Fastly. Seem more like a regional issue specific to a certain ISP or something.

**Comment by jgiambona** [comment]
From one of our users- "Our office is using Unifi and has this issue. My mobile data is under Maxis, do not have this problem"

Same user also said it's fine if he changes his DNS to Google.

Update:
Another user reported Digi Mobile is also having problems. Have also asked the users to check what responses they're getting from their ISP's nameservers

Update 2:
Maxis no longer working.

**Comment by jgiambona** [comment]
I have asked user to do a nslookup and traceroute, you'll notice that the response for cdn.polyfill.io is a canonical name to a ISP-related hostname.  This is for Maxis, cdn.polyfill.io is no longer reachable when using the mobile provider's own nameservers, along with many other ISPs in Malaysia.  

The government there has censorship and I wonder if they are mistakenly blocking the hostname and/or IPs

![WhatsApp Image 2021-09-02 at 12 08 53](https://user-images.githubusercontent.com/17823639/131785968-0778b5c8-4568-41b0-a7b0-01dd9c083d9f.jpeg)

**Comment by hueiyik** [comment]
I'm on maxis on mobile and have this issue. Polyfill.io ain't opening from browser either

**Comment by kbajaj-eightfold** [comment]
This issue is directly impacting our customers as well. 
@JakeChampion who from the team can look into this? Meanwhile any workaround you would suggest?

**Comment by JakeChampion** [comment]
Hi, I am looking into this as are some people within Fastly, the CDN provider which sponsor the service

**Comment by JakeChampion** [comment]
Thanks @jgiambona, it does look like a collection of ISPs are blocking the site.

Could we collect a list in this issue of all the ISPs which are blocking polyfill.io?

**Comment by lukeupup** [comment]
For people looking for temporary workaround - you can either import a static polyfill file (like https://github.com/es-shims/es5-shim) or try an old version of polyfill service: 
 https://polyfill.alicdn.com/polyfill.min.js (v1.5)

**Comment by JakeChampion** [comment]
@lukeupup I can add polyfills.io as a new domain for you to use

**Comment by JakeChampion** [comment]
I've opened up a pull-request to enable the service to work via polyfills.io as an alternative domain -- https://github.com/Financial-Times/polyfill-service/pull/2639

**Comment by john-opsec** [comment]
> I have asked user to do a nslookup and traceroute, you'll notice that the response for cdn.polyfill.io is a canonical name to a ISP-related hostname. This is for Maxis, cdn.polyfill.io is no longer reachable when using the mobile provider's own nameservers, along with many other ISPs in Malaysia.
> 
> The government there has censorship and I wonder if they are mistakenly blocking the hostname and/or IPs
> 
> ![WhatsApp Image 2021-09-02 at 12 08 53](https://user-images.githubusercontent.com/17823639/131785968-0778b5c8-4568-41b0-a7b0-01dd9c083d9f.jpeg)

MCMC = Malaysian Communications and Multimedia Commission.  This is likely happening at the request of the Malaysian government.

**Comment by JakeChampion** [comment]
@john-opsec Thanks, I've sent a few emails to MCMC to see if they can unblock the website 👍

**Comment by hueiyik** [comment]
This seems to impact everyone in Malaysia as far as i know. Almost all isp is blocking.

**Comment by JakeChampion** [comment]
> This seems to impact everyone in Malaysia as far as i know. Almost all isp is blocking.

Yes, please try and use polyfills.io instead, we have made that an alternative domain for this service

**Comment by JakeChampion** [comment]
I recommend people fill out this form and inform the MCMC that this website should not be blocked -- https://www.mcmc.gov.my/en/contact/website-experience-feedback

**Comment by ikomwrestling** [comment]
> I recommend people fill out this form and inform the MCMC that this website should not be blocked -- https://www.mcmc.gov.my/en/contact/website-experience-feedback

This only provide feedback on MCMC websites.

I would recommend Malaysian to file complaint on MCMC complaint portal
https://aduan.skmm.gov.my/

**Comment by JakeChampion** [comment]
> > I recommend people fill out this form and inform the MCMC that this website should not be blocked -- [mcmc.gov.my/en/contact/website-experience-feedback](https://www.mcmc.gov.my/en/contact/website-experience-feedback)
> 
> This only provide feedback on MCMC websites.
> 
> I would recommend Malaysian to file complaint on MCMC complaint portal
> [aduan.skmm.gov.my](https://aduan.skmm.gov.my/)

@ikomwrestling What did you put in the form fields?
I tried on that form and got this response:
> Note: This complaint is not within MCMC jurisdiction. We advice you to contact the relevant authority for further action. 

![image](https://user-images.githubusercontent.com/1569131/132358093-f86e20b3-f2f8-456d-bba5-675111a33c1a.png)

**Comment by jayddaniels** [comment]
I am getting "GET https://polyfill.io/v3/polyfill.min.js net::ERR_CERT_AUTHORITY_INVALID" when including in the html file.
I am in Germany.
The alternative "polyfills.io", tho loads, seems to have  only a comment in the file instead of the full javascript.

**Comment by aimensasi** [comment]
In our company, we ended up downloading the js file and loading locally from [here](https://www.cdnpkg.com/babel-polyfill/file/polyfill.min.js/). It seems to solve the problem
