### ISSUE TITLE
DOMTokenList is not defined in IE<=9

### ISSUE THREAD

**Issue by composite** [polyfillpolyfill/polyfill-service#265]
IE>=10 is fine to load. but IE 9 and less, IE is show this error message when rendering.
(Due to my IE's locale is Korean, message format will probably looks like different.)
SCRIPT5009: 'DOMTokenList' is not defined.
polyfill.min.js, row: 3, col: 422

(Windows 8.1 64bit, IE 11 with compatibility view)

**Comment by triblondon** [comment]
We do target DOMTokenList to IE9, and it's one of the combinations that gets automatically tested.  Are you sure you were setting the User agent correctly when you emulated the document mode?  The symptom you describe would appear if you emulated IE9 but with an IE11 user agent.
