### ISSUE TITLE
Promise polyfill is too slow

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#266]
Following discussions in https://github.com/Financial-Times/polyfill-service/pull/255 and https://github.com/Financial-Times/polyfill-service/issues/126, we adopted a new Promise polyfill, but left the following issue unresolved: The polyfill relies on [setImmediate](https://developer.mozilla.org/en-US/docs/Web/API/Window.setImmediate) which is only implemented by IE and not expected to be adopted by any other browser.  It contains an embedded implementation of setImmediate which is slower than alternatives such as [ASAP](https://github.com/kriskowal/asap).  The polyfill service also already has a separate implementation of setImmediate offered as a standalone polyfill for that feature.

Options here include:
1. Continue to support setImmediate with one of the implementations we already have, remove the other (such that the surviving implementation is in the setImmediate polyfill.js rather than embedded in Promise's polyfill.js), and make setImmediate a dependency of Promise.
2. Continue to support setImmediate with a new implementation based on asap (or other), make that a dependency of Promise, and remove the embedded implementation within the Promise polyfill.js
3. Drop support for setImmediate, and use a scoped function within the Promise polyfill to provide the desired async task spawning, possibly by embedding asap.js

**Comment by monolithed** [comment]
@triblondon, 
Do you mean this [dummy code?
](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Promise/polyfill.js#L332-L338)

**Comment by triblondon** [comment]
Yup.

**Comment by monolithed** [comment]
Why not use the [setImmediate polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/setImmediate/polyfill.js)?

Actually, there's no reason to keep this code in the polyfill:

``` js
    setImmediate = setImmediate || function (func) {
        var args = Array.prototype.slice.call(arguments, 1);

        return setTimeout(function () {
            func.apply(null, args);
        });
    };
```

My user-case:

``` js
uaString: 'MSIE 9.0',

features: {
    'Promise': {
        flags: ['gated']
    },

    'setImmediate': {
        flags: ['gated']
    },
}
```

**Comment by triblondon** [comment]
Yes, the question is more a) whether setImmediate is the right interface semantically, because it's not standards-track, although there is (to my knowledge) no equivalent that is, and b) if setImmediate IS the right interface, which of our two implementations should we standardise on.

**Comment by domenic** [comment]
setImmediate is not the right interface semantically: https://github.com/YuzuJS/setImmediate#macrotasks-and-microtasks

**Comment by jonathantneal** [comment]
Related to #240, we may wish to breakout the microtask library as well, which is quite simple now that I look at it.

**Comment by jonathantneal** [comment]
I’ve created a [branch](https://github.com/Financial-Times/polyfill-service/tree/feature/enqueueMicrotask) with a [polyfill](https://github.com/Financial-Times/polyfill-service/tree/feature/enqueueMicrotask/polyfills/enqueueMicrotask) called `enqueueMicrotask` which would handle the abstract operation of microtasks used in `Promise`, `MutationObserver`, and `Object.observe`. However, since we should not expose this private method to the global scope, resolution may depend on #280.
