### ISSUE TITLE
Support tests that require network IO (eg fetch)

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#267]
See https://github.com/Financial-Times/polyfill-service/pull/246.  We need to look at improving the test process so we can test things that require network IO, such as fetch.

**Comment by triblondon** [comment]
We actually already run the service during the sauce labs functional tests, because the tests hit the service to fetch the test pages.  Perhaps we could build an API endpoint that delivers test responses based on request data, but it seems really specific to fetch (I guess it would also be useful for XHR 2)

**Comment by samgiles** [comment]
Can we just use an existing endpoint?

**Comment by triblondon** [comment]
Yes, or http://httpbin.org/ should be fine for this actually.
