### ISSUE TITLE
Publish the latest changes to the npm

### ISSUE THREAD

**Issue by monolithed** [polyfillpolyfill/polyfill-service#270]
I'd like to have all the latest updates via npm. 
Could you follow the rule to publish all changes to the npm?

It's really easy with the [grunt-release](https://www.npmjs.com/package/grunt-release)

**Comment by triblondon** [comment]
This seems like a good thing to automate to make sure we don't forget it.  But we're up to date right now, I believe - latest release is 1.1.0, and that's the version in npm.

**Comment by monolithed** [comment]
I mean

```
npm install polyfill-service@1.1.0
find node_modules/polyfill-service/polyfills/ -name fetch
```

Where is the `fetch` method?
Although there's in the [master branch](https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/fetch)

I propose to make a separate repository like `polyfill-service-db`.

```
// polyfill-service package.json

"dependencies": {
      "polyfill-service-db": "^0.0.1"
}
```

It seems like more reasonable

**Comment by triblondon** [comment]
We haven't made a new release since fetch was added.  A release is not as simple as just tagging and pushing to npm - we need release notes, fair warning to users and a QA period on qa.polyfill.io.  I know you're keen to have the fetch polyfill.  Bear with us, it should be out this week!

**Comment by monolithed** [comment]
Got it, thanks!
