### ISSUE TITLE
Old Firefox: addEventListener and removeEventListener

### ISSUE THREAD

**Issue by roland-vachter** [polyfillpolyfill/polyfill-service#274]
Both addEventListener and removeEventListener has a third parameter (capture) which is optional in modern browsers, but it was required in old Firefox (3.6 for example).
Polyfill service could override these functions and add the third parameter by default if none is specified.

**Comment by triblondon** [comment]
Our support for FF3.6 is pretty poor at the moment, but it is above the baseline, so it would be good to fix it.  This isn't a priority for FT because all browsers that pass our JS baseline have the correct addEventListener behaviour, but we'll gratefully accept a contribution here.

**Comment by roland-vachter** [comment]
Tried to contribute on this, and solve the problem. Unfortunately Firefox doesn't let you to override addEventListener on prototype, so this is not possible to fix.

**Comment by jonathantneal** [comment]
Before you give up entirely, @roland-vachter, have you tried:

Overriding the element’s closest constructor’s prototype? `HTMLAnchorElement.prototype.addEventListener = function () {};`

Overriding the element’s method? `someElement.addEventListener = function () {};`

**Comment by roland-vachter** [comment]
I tried Document.prototype, Window.prototype, HTMLDocument.prototype, HTMLElement.prototype, nothing works. window.addEventListener can be overriden, but not on prototype.

There are also bugreports for Firefox about this, but I doubt anyone will fix it for FF3.6 for example :)

Overriding it for an element I think works (not sure), but it should be overriden on prototype the solution to make sense.
