### ISSUE TITLE
defineProperty for polyfilling native methods

### ISSUE THREAD

**Issue by juandopazo** [polyfillpolyfill/polyfill-service#277]
Many polyfills (but not all) are requiring `Object.defineProperty` just to add themselves to their corresponding native objects. For example, `Array.isArray` is using `Object.defineProperty(Array, 'isArray', ...)`. What do you think about not being super correct and just use a plain old assignment for these cases?

**Comment by triblondon** [comment]
What's the downside?

**Comment by juandopazo** [comment]
Maybe a couple of Test262 tests not passing in browsers that support `Object.defineProperty`. They won't pass anyway in older browsers.

**Comment by triblondon** [comment]
And the benefit is the polyfill has one fewer dependencies and a smaller code footprint?

It sounds fine to me.  @jonathantneal may have a view ;-)

**Comment by jonathantneal** [comment]
This sounds like [how we handled things before](https://github.com/Financial-Times/polyfill-service/commit/a5ea11cb04ce668ceec66a37418e0d4750edb8b5).

To be more accurate to the spec, I actually think more things should require `Object.defineProperty`, especially those affecting `Array.prototype` where users may actually depend on enumerability. As users migrate away from IE≤8, this will be especially helpful.

In the case of `Array.isArray`, let’s consider the most basic polyfill:

``` js
Array.isArray = function (object) {
    return Object.prototype.toString.call(object) === '[object Array]';
};
```

That’s 107 bytes. Readable, but not totally performant. Depending on usage, the bit about `Object.prototype.toString` could be improved.

``` js
(function (toString) {
    Array.isArray = function (object) {
        return toString.call(object) === '[object Array]';
    };
})(Object.prototype.toString);
```

That’s 122 bytes. Still readable and now performance optimized. The wrapping function is perhaps the only part of this polyfill that reads less easily.

``` js
(function (toString) {
    Object.defineProperty(Array, 'isArray', {
        configurable: true,
        value: function isArray(object) {
            return toString.call(object) === '[object Array]';
        },
        writable: true
    });
})(Object.prototype.toString);
```

That’s 177 bytes. Still readable, performance optimized, and now far more compliant. The wrapping function is still perhaps the only part of this polyfill that reads less easily.

In total, the difference is 170B. Our largest `Object.defineProperty` polyfill is 369B. No connection will feel these things, as I’ve read most transfers occur in chunks of at least 14KB. 

Readability is awesome and I am all for it, but I do not think this is where we should optimize.

**Comment by juandopazo** [comment]
I wasn't going for readability. I was avoiding the dependency. :P

Fair enough.
