### ISSUE TITLE
Geolocation polyfill relies on freegeoip.net which is sometimes down

### ISSUE THREAD

**Issue by samgiles** [polyfillpolyfill/polyfill-service#28]
This is not ideal, particularly as freegeoip.net is currently down.

Alternatives:  
- Host our own (https://github.com/fiorix/freegeoip)
- ???

**Comment by triblondon** [comment]
FT doesn't use geo, and I don't want to provide the endpoint through the CDN since that seems to breach Fastly's terms of use. The service built into the polyfill seems to be working currently, so I'm inclined to leave this as it is.
