### ISSUE TITLE
Custom user agent string

### ISSUE THREAD

**Issue by dy** [polyfillpolyfill/polyfill-service#282]
Hello!

I'm trying to setup an app builder command to automatically create needed polyfill:
`curl "http://cdn.polyfill.io/v1/polyfill.js?features=WeakMap|always,Element.prototype.classList|always&gated=1" > polyfill.js`.

But now I get `/* Unsupported UA detected: curl/7.30.0 */`in response, which is unfortunate and illogical.

I can workaround that by passing custom agent `curl -A "..."`, but it seems really weird in the case when I manually pick features I need polyfilled.

**Comment by triblondon** [comment]
In my view it would be better to ask why something works as it does rather than to assert that it is 'illogical'.  You're of course welcome to fork the project and make it conform to your own logic if you like, and if it's better than what we have we can then learn from your greater wisdom.

Also see https://github.com/Financial-Times/polyfill-service/issues/253

**Comment by dy** [comment]
@triblondon ow, sorry for my probably a bit obtrusive manner, but it seems counterintuitive when you point exact features to polyfill and get nothing in response.

Thank you for the reference )

As far I've found, `unknown` flag is what was needed:

```
$ curl "http://cdn.polyfill.io/v1/polyfill.min.js?features=WeakMap,WeakSet&flags=always&unknown=polyfill" > polyfill.js
```

**Comment by dy** [comment]
Yet it doesn't work with `curl`, returns `Unsupported UA detected`:
`curl "http://cdn.polyfill.io/v1/polyfill.min.js?features=WeakMap,WeakSet&flags=always&unknown=polyfill"`.

@triblondon is it intentionally implemented so to ignore `curl`? Is it because `curl` is not browser? But there seems to be a use-case for that.

**Comment by triblondon** [comment]
That URL returns polyfill code for me.

**Comment by dy** [comment]
Hmm, this request returns `Unsupported` both on my Win7 laptop and OSX. Also if I emulate it in chrome with UA string replaced to `curl/7.10`, it also returns `Unsupported`...

**Comment by triblondon** [comment]
Sorry, you're right, I was inadvertently sending a supported UA header.  OK, if you send a UA in the format `XXXXX/YYY` then that will be considered a canonical name so is treated as a known browser.  If we don't have polyfills for it, you don't get any.

We could alter the implementation of `isUnknown` to require it to be a valid member of `baselineVersions`, here:

https://github.com/Financial-Times/polyfill-service/blob/master/lib/UA.js#L155

I'm open to that.
