### ISSUE TITLE
New dependency without a license

### ISSUE THREAD

**Issue by davglass** [polyfillpolyfill/polyfill-service#283]
In 31b805c02ee00cfc67f932d0f74f6cf9241d99e7 you added the [haikro](https://github.com/matthew-andrews/haikro) to the production dependencies and this module is unlicensed.

I have asked the author to add a license, but until then it makes it very hard to use this module.

https://github.com/matthew-andrews/haikro/issues/62

**Comment by matthew-andrews** [comment]
my bad, fixed now. https://github.com/matthew-andrews/haikro/commit/e57ff2888746c582469dcbc953afbf584dcc9200

**Comment by davglass** [comment]
:metal: Thanks again!

**Comment by triblondon** [comment]
@davglass @matthew-andrews is a colleague at the FT, so I hadn't checked the license, thank you for pointing this out.
