### ISSUE TITLE
IE8 Error: "Member not found."

### ISSUE THREAD

**Issue by blainekasten** [polyfillpolyfill/polyfill-service#296]
On line 136 (unminified) IE8 throws error "Member not found." due to the following code:

`(this.Window = this.constructor = new Function('return function Window() {}')()).prototype = this;`

This is a show stopping error for IE8.

**Comment by triblondon** [comment]
Hi Blaine - is that with URL https://cdn.polyfill.io/v1/polyfill.js or are you adding any query params?

**Comment by blainekasten** [comment]
that is the code from the `polyfill.js` yes. No query paramaters. Also happens in the `.min` version

**Comment by triblondon** [comment]
I can't reproduce this, unfortunately.  I'm using Microsoft's modern.ie VMs, and I've tried both the IE8 and IE11 emulating IE8.  Any tips?

**Comment by blainekasten** [comment]
Strangely, today it is no longer having issues... I guess I have no explanation for what had happened. I was testing using browserstack's IE8 on Windows 8. I suppose we can close this for now.

**Comment by triblondon** [comment]
OK.  A URL to a test case is always useful, JSBin works pretty well, then we can make sure we're looking at the same thing.

**Comment by jrf0110** [comment]
Interestingly, I'm seeing the same issue on BrowserStack, IE8. I have had weird problems with BrowserStack not properly forwarding request headers, but I can't really think of why this would be happening.

I messed around with the build params a lot trying to finagle into working. Here's a screenshot:

![http://storage.j0.hn/polyfill-ie8-error.png](http://storage.j0.hn/polyfill-ie8-error.png)

I'll try and see if this happens outside of BrowserStack
