### ISSUE TITLE
Additional config properties

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#297]
I'd like to propose some additional config properties for config.json files:
- `notes`: Array of notices in markdown that developers should be aware of, useful for deprecated features like String.prototype.contains, eg "This feature was [deprecated](...) due to poor existing native implementations, and replaced with String.prototype.includes"
- `repo`: URL of the repository from which the polyfill has been copied.  It's otherwise been tempting to put that into the `author` property, and it would be better in such cases to provide repo and leave author blank.
- `spec`: URL of the document that is the canonical technical definition of the feature (the spec, preferably with fragment referencing the specific heading)
- `docs`: URL of an online resource with the most helpful description of the feature for developers (likely to be MDN)

Thoughts?

**Comment by monolithed** [comment]
Good idea!

I propose to use `package.json` format like

``` json
"name"       : "URL",
"version"    : "1.0.0",
"author"     : "Mail.Ru Group Limited",
"description": "https://url.spec.whatwg.org/",

"man": "README.md"

"os" : [ "darwin", "linux", "!win32" ]
"cpu" : [ "x64", "ia32" ]

"maintainers": [
    {
        "name" : "Alexander Abashkin",
        "email": "<a.abashkin@corp.mail.ru>"
    }
],

"repository" : {
    "type": "git",
    "url" : "git@gitlab.corp.mail.ru:cloud/aviary.git"
},

"licenses": [
    {
        "type": "MIT",
        "url" : "http://www.opensource.org/licenses/mit-license.php"
    }
]
```

**Comment by triblondon** [comment]
I disagree with that - the data we're describing is quite different to a node module, there's no equivalent to the `browsers` and `variants` objects for example.

I'd like to also add a `spec` property to contain the URL of an appropriate spec doc, to make the most of the behaviour of adding a spec URL to the top of the polyfill, which is a great idea that @jonathantneal has started doing with stuff like https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Element.prototype.after/polyfill.js#L1.  That's incredibly valuable for those of us who struggle to find the canonical description of a feature.

I've updated the OP with this.

**Comment by triblondon** [comment]
Closed by https://github.com/Financial-Times/polyfill-service/pull/337
