### ISSUE TITLE
IE8 Event polyfill typo

### ISSUE THREAD

**Issue by tejacques** [polyfillpolyfill/polyfill-service#299]
https://github.com/Financial-Times/polyfill-service/blob/de07f9237ec4a73624e8f2479a1b308a7c8d56b0/polyfills/Event/polyfill-ie8.js#L99

The line:

``` .js
listener = arguments[1].
```

Should be:

``` .js
listener = arguments[1],
```

**Comment by triblondon** [comment]
Thanks for reporting this.
