### ISSUE TITLE
Event ie8-polyfill.js removeEventListener breaks addEventListener

### ISSUE THREAD

**Issue by tejacques** [polyfillpolyfill/polyfill-service#302]
### Bug

Calling removeEventListener on the last listener on an element detaches the event handler and addEventListener no longer re-adds it because the `_events[type]` object still exists.

The problem is the event is detached when the list is empty, but `element._events[type]` is not removed.
### Fix:

Change: https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Event/polyfill-ie8.js#L108-L112

From:

``` .js
                if (!element._events[type].list.length) {
                    if (element.detachEvent) {
                        element.detachEvent('on' + type, element._events[type]);
                    }
                }
```

To:

``` .js
                if (!element._events[type].list.length) {
                    if (element.detachEvent) {
                        element.detachEvent('on' + type, element._events[type]);
                    }
                    delete element._events[type];
                }
```
### Steps to reproduce

**Note**: You must use a real DOM event and not a custom one, because otherwise dispatchEvent catches the fireEvent error, and manually runs the event listeners.

``` .js
var listener = function() { console.log('should log'); };
document.addEventListener('click', listener);
document.removeEventListener('click', listener);
document.addEventListener('click', listener);
// click the document
document.dispatchEvent(new Event('click'));
```
#### Expected output

```
should log
```
#### Actual output

```
```
#### Mocha Test

``` .js
it('should fire event', function (done) {
    var listener = function() {
        // remove listener
        document.removeEventListener('click', listener);
        done();
    };
    document.addEventListener('click', listener);
    document.removeEventListener('click', listener);
    document.addEventListener('click', listener);
    // click the document
    document.dispatchEvent(new Event('click'));
});
```

**Comment by triblondon** [comment]
Thanks @tejacques this is excellent work.  If you could do a PR that will enable us to merge this change in faster (and my only suggestion is that your mocha test needs an assertion)

**Comment by tejacques** [comment]
Sure I'd be happy to. I'll put this together tomorrow.
