### ISSUE TITLE
CORS polyfill

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#305]
I'm busy forking xdomain https://github.com/Financial-Times/xdomain to

a) make it check for cors support and only run if cors unsupported
b) fire an event on load so that it can be non-blocking

Could xdomain be a good enough cors polyfill to be added to the service?

**Comment by triblondon** [comment]
No, because it requires the proxy.html file on the target host, so it's not a proper polyfill.  Unless it can mirror the spec, we can't have it in the library.  I can't see how we could do that with CORS.
