### ISSUE TITLE
Array.prototype.find is not polyfilled in latest chrome

### ISSUE THREAD

**Issue by jkimbo** [polyfillpolyfill/polyfill-service#308]
The detection for `Array.prototype.find` doesn't seem to be working in Chrome (41).

http://cdn.polyfill.io/v1/polyfill.js?features=default,Array.prototype.find doesn't polyfill it. 

You have to add the `always` flag to get it work: http://cdn.polyfill.io/v1/polyfill.js?features=default,Array.prototype.find|always

**Comment by triblondon** [comment]
The targeting config for this polyfill only applies it to Chrome <=29.  The targeting was introduced here:

https://github.com/Financial-Times/polyfill-service/commit/e2cdedaaed30a9fbc73348b0381402d44ea11291#diff-60cffac6d7c997bfa14860f5d1bf5eaf

However, MDN reports find is not currently supported by any version of Chrome, IE or Opera.  FF settings look fine.  Testing on my local Chrome 40, it's not present, so the settings we have are obviously incorrect.

**Comment by jkimbo** [comment]
Thanks!
