### ISSUE TITLE
Use a module to include FT specific web service endpoints

### ISSUE THREAD

**Issue by samgiles** [polyfillpolyfill/polyfill-service#312]
Consider open sourcing: `express-ftwebservice` (searchable from our internal git server) and using it to remove the `__gtg`, `__about` etc endpoints hardcoded in this service.

We can then do exactly this instead of defining the syntax and routes ourselves in `service/index.js`.

``` JS
var ftwebservice = require('ftwebservice');
var express = require('express');
var app = express();

ftwebservice(app, {
    serviceName: "polyfill-service",
    serviceDesciption: "Open API endpoint for retrieving Javascript polyfill libraries based on the user's user agent.  More at http://github.com/Financial-Times/polyfill-service.",
    serviceVersions: {
        v1: {
            dateCreated: "2014-07-14T10:28:45Z",
            support: origamijson.support,
            supportStatus: "active"
        }
    },
    healthcheck: function() {
        return Promise.resolve([
            {
                name: "Server is up",
                ok: true,
                severity: 2,
                businessImpact: "Web page rendering may degrade for customers using certain browsers. Dynamic client side behaviour is likely to fail.",
                technicalSummary: "Tests that the Node JS process is up.",
                panicGuide: "This application consists of Node JS processes on any number of nodes in an environment.  The process must have read permissions on files within its deployment.",
                checkOutput: "None",
                lastUpdated: new Date().toISOString()
            }
        ]);
    }
});
```

**Comment by triblondon** [comment]
Maybe.  Cons:
- this gives the service a very proprietary flavour, even if the ftwebservice module is open source.
- the code above is not substantially less than the code you're proposing to replace.
- we are discussing changing the service description endpoints so that they are not versioned.  This abstraction does not help make it easier to do that

**Comment by samgiles** [comment]
Closing for now.  I still think this module is a good idea (particularly for 'Next'), but we should revisit this when the changes to the endpoints have been finalised..
