### ISSUE TITLE
Function.prototype.bind on iOS 5 (old iPads & iPhones)

### ISSUE THREAD

**Issue by Savageman** [polyfillpolyfill/polyfill-service#313]
This is a missing polyfill.

I'm not too sure which "ios_safari" version to check against in the **config.json** file...

Another important information is that the [MDN polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill) doesn't work (triggers some `instanceof` error), I had to use the one from **es5-shim.js**.

**Comment by triblondon** [comment]
I don't have an iOS 5 device to test on.  Does the polyfill we have in the service already work on Safari on iOS 5?

**Comment by Savageman** [comment]
I just tested it and no, it doesn't work. I have the same error as the MDN polyfill: "TypeError : instanceof called on an object with an invalid prototype property".

**Comment by triblondon** [comment]
OK, if the es5-shim polyfill works on our test browsers (IE 6,7,8 and FF3.6 for this one) then I'm happy to switch to that.  Can you do a PR?

**Comment by Savageman** [comment]
You closed this, but the original issue is still not resolved.

The included polyfill should now work on iOS 5, but it's still not included (I can't see the `ios_safari` version in the `config.json` file).

**Comment by triblondon** [comment]
Sorry, I didn't check that the targeting was correct.  I'll push a commit to target iOS < 6.
