### ISSUE TITLE
Refactor Promise dependencies

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#316]
Our promise polyfill is now a substantial modification of https://github.com/Octane/Promise/blob/master/promise.js.  I'd like to propose we go back to the original source of this polyfill, and make just the following change to it:
- set the value of `setImmediate` on [L24](https://github.com/Octane/Promise/blob/master/promise.js#L24) to `_enqueueMicrotask`.
- give `_enqueueMicrotask` the same API as `setImmediate` (ie optional subsequent params that are bound as args to the function), so that it is compatible with the expected setImmediate function used by Octane's polyfill.

We can then list `_enqueueMicrotask` and `Array.isArray` as dependencies - since we have polyfills for both of those already, and we should be good to go with only one line of the original polyfill changed.  The rationale for this is:
- By not forking third party polyfills, it makes it far easier for us to take updates.
- By not making changes, we can lean on the results of third-party libraries' own test suites (whereas if we modify, we're on our own, as demonstrated by #307).

There were some changes made in our version which would be good to merge upstream, so I think it would be great to propose those as a PR to the original library, which would then enable those changes to be verified by the library's own CI process and approved by the library author.

**Comment by Octane** [comment]
How to better specify a external async scheduler?
I do not want to become attached to a specific npm module.
Any suggestions? I don't mind to fix it.

**Comment by triblondon** [comment]
@Octane we're finding that we have multiple use cases for certain behaviour for which there is no web platform API, and asyncing tasks is one of those.  We don't want to use setImmediate as it will likely not be a standard (for historical reasons, we have a polyfill for it).  I don't really have any suggestions for how you could modify your code to make it easier for us.

I did also consider whether we could take your polyfill _completely_ unmodified, and do something like this:

``` javascript
(function() {
   var require = function() { return {setImmediate: _enqueueMicrotask} };
   // Your polyfill here
})();
```

That would mean when your code does `require('timers').setImmediate`, you get a reference to our `_enqueueMicrotask` util function. But we don't have a mechanism for wrapping third party libraries currently, so I'm not sure how we would do this.

For now, I'd just be really happy to only have to modify one line :-)

**Comment by juandopazo** [comment]
@Octane how about this?

``` js
// In your promise code
Promise._enqueue = function (fn) {
  setImmediate(fn);
};
```

Then users can overwrite `_enqueue` with whatever they see fit and you can add the `require('timers')` as a build step.

**Comment by triblondon** [comment]
I'm going to try my approach that defines `require` inside the closure, which would mean no need for Octane to do anything and would avoid exposing a public property of Promise that doesn't exist in the Promise spec.

**Comment by triblondon** [comment]
Merged PR, also see https://github.com/Financial-Times/polyfill-service/pull/338 for clarification on use of third party polyfills.
