### ISSUE TITLE
Event/polyfill-ie8.js certain event listeners on window in IE8 never fire

### ISSUE THREAD

**Issue by tejacques** [polyfillpolyfill/polyfill-service#317]
### Bug

Currently if you use the polyfill service for Events in IE8, and try to add a `click` handler to the `window`, it will never fire, because in IE8 `click` events (and others, listed below) are fired on the `document` but not `window`.
#### Test Case

``` .js
it('should bubble to window when fired from element', function() {
    var fired = false;
    window.addEventListener('click', function() {
        fired = true;
        // cleanup
        window.removeEventListener(type, listener);
        document.body.removeChild(element);
    });
    var element = document.createElement('div');
    document.body.appendChild(element);
    element.dispatchEvent(new Event('click', { bubbles: true }));
    expect(fired).to.be(true);
}
```
#### Fix

Re-target event listeners for events triggered on the `window` in modern browsers, but `document` and not `window` in IE8 to the `document` when added to the `window`. Care needs to be taken to ensure that:
1. The listeners for `window` fire after `document` when events bubble up
2. Stopping propagation on the event from a listener on `document` properly stops the event from bubbling/triggering on the `window`
3. The listeners for `window` only fire if `window` is the target, or the event bubbles up.
##### Discussion

I'm currently working on this in a side-fork because I need it for a project (creating as close to a polyfill as possible for IE8 StorageEvents). I'm happy to upstream the changes if you're interested in a pull request for this issue, but I'm not sure whether the fix is actually worth the added complexity since most of the time developers will add handlers to the `document` instead of `window` for these events anyway:
- `click`
- `dblclick`
- `keypress`
- `keyup`
- `keydown`
- `mousedown`
- `mouseup`
- `mousemove`
- `mouseover`
- `mouseout`

`storage` is broken as-is though as modern browsers only trigger the `storage` event on `window` whereas IE8 triggers it on `document`. Unfortunately, just retargeting the `storage` event isn't sufficient because the `Storage` API on IE8 is busted

**Comment by triblondon** [comment]
Wow, nice diagnosis, thanks.  I think you're right, this is a real edge case.  It wouldn't be hard to add a line to addEventListener to bind the listener to document instead of window, but as you say this potentially has unexpected consequences on stopPropagation.

Potentially the best thing to do here is to throw an error to the console if addEventListener is called on window for an element specific event, with a message that links to this issue.  What do you think?

**Comment by tejacques** [comment]
That sounds like a good middle ground.

**Comment by triblondon** [comment]
@tejacques would you consider contributing a PR for this?

**Comment by tejacques** [comment]
Sure -- I'll try to take a stab at it this week.

**Comment by tejacques** [comment]
Hey @triblondon I've got a commit with the behavior we discussed but not sure how best to add a test for it targeting IE8 specifically (or if it makes sense to do so) -- is there a way to do this with the way the tests are set up? I was considering using this technique: http://stackoverflow.com/questions/5574842/best-way-to-check-for-ie-less-than-9-in-javascript-without-library

**Comment by triblondon** [comment]
I'd suggest not restricting it by browser - that's a minefield that we have to tread carefully. Erroring whenever a listener is bound to `window` for something element specific with advice to bind to `document` should be fine.  Your change looks good, except I'd add advice to bind to document, and remove the specific reference to IE8 (presumably it also happens in 7 and 6)

**Comment by tejacques** [comment]
Hmm, I was under the impression that the polyfill-ie8.js file was only used for IE8 (or under), but the tests applied to both polyfill.js and polyfill-ie8.js, I didn't want to add a test for this new behavior which wouldn't occur for browsers using the other polyfill file.

**Comment by triblondon** [comment]
Sorry, I totally didn't read your earlier comment properly and eagerly clicked the commit links.  I thought we were talking about the polyfill implementation, not the tests.

Still, I guess the test is a matter of binding to window for one of the affected events, firing it, and then asserting that EITHER it works, or you get the error we've put in the polyfill.

**Comment by tejacques** [comment]
That makes sense, I'll add that in and submit a PR later today.

**Comment by triblondon** [comment]
Hi @tejacques can we finish this off?

**Comment by tejacques** [comment]
Oh wow, I think I just forgot to actually make a PR -- sorry about that. Will re-familiarize myself with this and hopefully get that up today.

**Comment by tejacques** [comment]
This is up in #463
