### ISSUE TITLE
grunt build can't find setImmediate polyfill

### ISSUE THREAD

**Issue by blainekasten** [polyfillpolyfill/polyfill-service#325]
With latest code, running grunt build reports the following:

```
{ name: 'Missing polyfill source file',
  message: 'Path ..../polyfill-service/polyfills/__versions/v1.0.2/setImmediate/polyfill-onreadystatechange.js not found' }
```

I looked and I found it under with a `.` instead of a `-` naming convention.

Like so: `..../polyfill-service/polyfills/__versions/v1.0.2/setImmediate/polyfill.onreadystatechange.js`

**Comment by triblondon** [comment]
Sorry, that output could be clearer - it's an error in an earlier version of the library, which we can't fix because it's a locked version (it was, in fact, fixed in the next version of the library).  It doesn't cause a build failure, but I could and probably should suppress the error entirely.

**Comment by blainekasten** [comment]
Ahh, okay. Totally up to you then. Probalby would be a good idea as it'll likely just come up again by someone else if they try and build their own.
