### ISSUE TITLE
Using the test262 harness

### ISSUE THREAD

**Issue by juandopazo** [polyfillpolyfill/polyfill-service#326]
I've been playing around with @bterlson's Nodejs test262 harness and there are some quirks to get it to work, but it could be integrated into the service's testing runway.

Here's what I had to do:
1. Add the harness as a dev dependency
2. During build, clone the test262 repo (I'm using grunt-git)
3. During build, generate a bundle with all the Ecmascript polyfills. They must be non-gated.
4. In an npm script, run the harness with a config file `-c myconfig.js`. I haven't been able to run the harness in a child process. I think it's because it's using child processes of its own. I need to try a different runner than the default.
5. In the config file, set the `prelude` pointing to the bundle
6. Here's the hacky part:

``` js
var t262 = require('test262-harness');
// Use defineProperty to force the harness to run the tests we want instead of
// getting the list from the command line
Object.defineProperty(t262.config, '_', {
  value: [/* list of globs pointing to the test262 builtins the service has polyfills for*/]
});
```

Just letting you know it can be done...

**Comment by triblondon** [comment]
Cool. What form do you get results in? Could it be run through our Sauce integration?

Presumably we have a ton of fails at the moment?

**Comment by juandopazo** [comment]
> What form do you get results in?

The most interoperable format seems to be `tap`.

> Could it be run through our Sauce integration?

Yes. But it needs a bit more work. I'll eventually dive into the code and see if I can contribute it back. Follow https://github.com/bterlson/test262-harness/issues/6.

> Presumably we have a ton of fails at the moment?

Yup. Most Array APIs have the `length` issue we've already been discussing. Some have others around mutability during iteration. I want to fix them all. We should also consider delegating to stuff in https://github.com/es-shims/.

**Comment by maxnordlund** [comment]
Has anything happened with this? It would be a very sweet thing to have :smile_cat:

**Comment by triblondon** [comment]
@maxnordlund no, it's totally fine for you to work on this, no-one else is looking at it right now.

**Comment by triblondon** [comment]
Duplicates #192
