### ISSUE TITLE
Testing object property existence

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#332]
A number of the detects in the service test for the existence of an object property, but we have a number of ways of doing this.

This seems to be most popular

```
bar.foo
```

But we also have quite a lot of

```
'foo' in bar
```

We rarely do this:

```
bar.hasOwnProperty('foo')
```

But probably should if the property is an own property.  Are there some simple rules we can establish for which method of checking a property's existence should be used when?

**Comment by triblondon** [comment]
@juandopazo @jonathantneal can you help me out here?

**Comment by juandopazo** [comment]
I honestly don't have any guidance to give here. I'll think about it.

**Comment by monolithed** [comment]
@triblondon, Maybe you'd pay attention to [JSCS](https://github.com/jscs-dev/node-jscs) and [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)

**Comment by triblondon** [comment]
@monolithed I don't believe either of those contains guidance on this issue.  Can you quote the specific section?

**Comment by rauschma** [comment]
- When I’m lazy, I do `bar.foo`. That will become more convenient in ES6, because `undefined` triggers default values.
- If you truly want to to test whether a property exists (versus – possibly – a property that has a falsy value): `'foo' in bar`
- If you want to restrict yourself to _own_ (non-inherited) properties:
  - `Object.prototype.hasOwnProperty.call(bar, 'foo')`
  - Shorter: `{}.hasOwnProperty.call(bar, 'foo')`
  - Do not use `bar.hasOwnProperty('foo')`, which fails if, e.g., `bar` has an own property whose name is `hasOwnProperty`.

**Comment by triblondon** [comment]
Thanks @rauschma, that's extremely helpful.  If you don't mind, can you also suggest the best way of checking for the existence of a global?  Just evaluating the symbol name throws a referenceerror, so my usual method is:

```
typeof foo !== 'undefined'
```

Is that reasonable?

**Comment by rauschma** [comment]
That’s OK. Ideally, you should never have to do this. What’s your use case?

**Comment by triblondon** [comment]
Feature detects for polyfills, though I've now adopted the pattern of doing:

``` javascript
"Thing" in this
```

Where `this` is near-guaranteed to be a reference to the global scope because of this:

``` javascript
(function(undefined) {
   // All polyfills
}).call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});
```

**Comment by rauschma** [comment]
I don’t like using `this` in this manner. How about:

``` js
(function(glob) {
    var undefined;
    // All polyfills
}(getGlobalObject()));

function getGlobalObject() {
    if (isObject(window)) return window;
    if (isObject(self)) return self;
    if (isObject(global)) return global;
    return {};
}
function isObject(value) {
    return value !== null && typeof value === 'object';
}
```

I also tried to make the code more self-explanatory. I don’t think that performance is an issue here.

Note: if your code doesn’t have to run on ES3 then you can omit the `undefined` trick.

**Comment by triblondon** [comment]
The problem with that is that the polyfills are largely written by third parties, so we have to provide an execution context in which they will work.  Some attach their APIs to window, some to self, others to this.  All of those are the same if you load the polyfill into global scope in a browser window and you haven't redefined any of them.  But none are guaranteed.  See https://github.com/Financial-Times/polyfill-service/issues/352 for the full discussion if you're interested!
