### ISSUE TITLE
classList polyfill doesn't work alone in IE9 and used with all included bundle it's highly inneficient

### ISSUE THREAD

**Issue by thednp** [polyfillpolyfill/polyfill-service#346]
I tested more classList polyfills and none throws any error or show any performance issues. The performance issues are related to requestAnimationFrame animations.

I would personally recommend testing and changing it.

UPDATE: when using classList alone, the error is

<pre>
SCRIPT5007: Unable to get property 'prototype' of undefined or null reference 
classList.js, line 23 character 4
</pre>

here
<code>original = NativeDOMTokenList.prototype,</code>

The error is thrown no matter where I link the script to: header/footer.

I tested this and worked very well

<pre>
&lt;script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/2014.01.31/classList.min.js"> &lt;/script>
</pre>

**Comment by juandopazo** [comment]
Do you have performance data? What kind of performance issues are you running into?

`classList` is implemented by polyfilling `DOMTokenList` which seems fair.

**Comment by thednp** [comment]
I am new to this and to Native JS in general, perhaps my finding is my own code related, but I will provide an example as soon as I can. Thank you.

**Comment by juandopazo** [comment]
I'll be happy to help. A performance issue in classList would be pretty bad for everybody. However, keep in mind that the native implementation is very likely slower than string manipulation. See https://github.com/jquery/standards/issues/13 for some context (it's a few years old though).

**Comment by triblondon** [comment]
@eligrey's polyfill is objectively better than ours in at least one respect: it covers the incomplete implementations in browsers that don't support multiple classes.  See #268.

We do have an IE9 test suite for classList, and it's passing right now, so I'm inclined to think the error is a problem introduced by your own code, but if you have a test case showing otherwise please do post it.

**Comment by thednp** [comment]
Thanks for taking the time to think about it. I am still working on the code. I am going to move forward with my work and will provide exact information as soon as I can isolate the specific case.

**Comment by triblondon** [comment]
OK.  We'll close this, but do please feel free to reopen or create a new issue if you turn up some data that points in our direction.

**Comment by thednp** [comment]
FYI: I solved the issue, it was indeed my own code doing requestAnimationFrame animation in IE9 with 2 properties at the same time for same element: position: top and translateY. The browser does not support translate obviously, but it had to calculate the (be)tween values for it. Sometimes translate was undefined and the code couldn't make any logic while tweening the values, which created some unnecessary loops. As the result, frame rate dropped very very low.

When using classList from another source, somehow that eliminated my unwanted loops and I was thinking your code is incorrect.

Issue solved. Please disregard this issue. Great work everybody.
