### ISSUE TITLE
Polyfill error on Safari 6: "Can't find variable: performance"

### ISSUE THREAD

**Issue by Vallach** [polyfillpolyfill/polyfill-service#347]
When initializing an overlay on Safari the following error occurs:

Can't find variable: performance
polyfill.min.js:3:1343

Affects:
- Safari 6.1.6 | OSX 10.7.5

Note:
- no error if remaping "http://cdn.polyfill.io/v1/polyfill.min.js" to "http://cdn.polyfill.io/v1/polyfill.js"

**Comment by roland-vachter** [comment]
Hi Sam,

I saw you mentioned this issue in a pull request, which haven't been merged. Do you have an update on this one please?

Thank you,
Roland

**Comment by triblondon** [comment]
Merged.  Will be in 1.4 release.

**Comment by roland-vachter** [comment]
Cool, thanks!
