### ISSUE TITLE
this === undefined when polyfills are wrapped in an IIFE containing `use strict`

### ISSUE THREAD

**Issue by monolithed** [polyfillpolyfill/polyfill-service#352]
##### Explanation

``` js
(function () {
   'use strict';

   (function (global) {
       function Promise () {
                // ...
       }
       global.Promise = Promise; //  Uncaught TypeError: Cannot set property 'Promise' of undefined
   }(this));
}())
```
##### Problem files

```
➜ git grep --name-only '[}|)](this)' -- polyfills/*polyfill.js

polyfills/Event.hashchange/polyfill.js
polyfills/JSON/polyfill.js
polyfills/Navigator.prototype.geolocation/polyfill.js
polyfills/Promise/polyfill.js
polyfills/URL/polyfill.js
polyfills/atob/polyfill.js
polyfills/devicePixelRatio/polyfill.js
polyfills/document.querySelector/polyfill.js
polyfills/getComputedStyle/polyfill.js
polyfills/localStorage/polyfill.js
polyfills/matchMedia/polyfill.js
polyfills/performance.now/polyfill.js
polyfills/requestAnimationFrame/polyfill.js
polyfills/viewport/polyfill.js
```

_15_ polyfills does not work as expected

**Comment by juandopazo** [comment]
So what you're saying is that you're wrapping everything in 'use strict' in Autopolyfiller, right?

I don't think you should do that. Instead, we should `use strict' in each polyfill.

**Comment by monolithed** [comment]
The problem is that many people can use a wide variety of tools like minifiers, concatenators, transplillers and son on. 
The polyfills must be encapsulated and does not depend on the environment!

The following string:

``` js
 }(this));
```

Should be replaced with:

``` js
 }(window));
```

or 

``` js
 }(Function('return this')()));
```

**Comment by triblondon** [comment]
I believe the justification for the use of the `}(this));` pattern is that the polyfills may be loaded in a worker rather than a window.  We don't want to stop the polyfills from working in a web worker.  I agree with Juan, if the polyfill wanted to set use strict, it could do so, but the reason use strict works in the way it does is to avoid breaking the web for code that already exists and would stop working if the stricter rules of use strict were applied.

I don't have any objection to `Function('return this')()` if that works in everything above our baseline, however, you used `Promise` as your example use case, and that's interesting because we are simply copying the source of the promise polyfill from the third party repo, which uses the `}(this));` pattern, so we don't have control over the use of the pattern there.

Potentially the easiest and cleanest solution would be to add a definition of `this` at the top of the closure that we output when we generate the polyfill bundle:

``` javascript
(function() {
  var this = window || self;  // <-- New line added by service
  // All applicable polyfill sources here
})();
```

This will solve your problem provided that you generate your autopolyfiller bundle by using the service API rather than simply reading the polyfill source files individually.  That would probably be a good idea anyway, since it would enable you to easily output a polyfill service CDN URL from autopolyfiller rather than a one-size-fits-all bundle.

**Comment by monolithed** [comment]
> Potentially the easiest and cleanest solution would be to add a definition of this at the top of the closure that we output when we generate the polyfill bundle:

``` js
(function() {
  var this = window || self;  // <-- New line added by service
  // All applicable polyfill sources here
})();
```

Nope!  `this` cannot be redefined!

The possible solution:

``` js
(function() {
  'use strict';

  // ... polyfills
}.call(window));
```

**Comment by triblondon** [comment]
But that assumes that `window` exists, and we're back to the web worker problem.  Does this work?

``` javascript
(function() {

  // ... polyfills
}.call(window || self));
```

Also note that you cannot apply use strict to all polyfills.  The library includes lots of third party polyfils, not all of which are compatible with strict mode.  Use strict needs to be done inside each polyfill.

**Comment by monolithed** [comment]
@triblondon

`window` (not exists in Workers environment) and `self` can also be redefined. 

``` js
var blob = new Blob( [ 
   'onmessage = function (event) { console.log(Function('return this')() === self);  }'
]);

var url = window.URL.createObjectURL(blob);
var worker = new Worker(url);

worker.onmessage = function (event) {
    console.log(event.data);
};

worker.postMessage('hello');
```

Works fine, but it can be blocked by CSP

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".`

However who in their right mind would use the polyfills with `Worker`? 

And `window` 

``` js
'onmessage = function (event) { window }';  // Uncaught ReferenceError: window is not defined
```

So, `self` sounds more reasonable.

**Comment by triblondon** [comment]
`self` is commonly redefined by developers as a poor man's alternative to 'bind(this)`, but window is not, so why not use`window || self`?

**Comment by monolithed** [comment]
> so why not use `window || self`?

With your words, the polyfills should work in any environment:

> We don't want to stop the polyfills from working in a web worker.

But, it's impossible when used `window || self`:

```
var blob = new Blob( [ 
   'onmessage = function (event) { (function () { /** POLYFILLS */ }.call(window || self)) }' 
]);

var url = window.URL.createObjectURL(blob);
var worker = new Worker(url);

worker.onmessage = function (event) {
    console.log(event.data);
};

worker.postMessage('hello');
```

**Comment by triblondon** [comment]
If `window` is undefined, as I understand it the expression `window||self` will return the value of `self` so I'm afraid I don't see why that wouldn't work in a web worker.

**Comment by monolithed** [comment]
`window` is not defined, and `window||self` throws an error like `Uncaught ReferenceError: window is not defined`

It's like `foo || self`. `foo`— is not defined before
Please, try execute my example in your the console

**Comment by triblondon** [comment]
Ah, I see. I guess that would only happen in strict mode, but ok, I see what you mean. Let me have a play around when I get back to a screen larger than a phone.

**Comment by triblondon** [comment]
OK, how about:

``` javascript
(function() {
  var window = this, self = this;
  // ... all polyfills
}.call(typeof window !== 'undefined' ? window : self));
```

I've tested this and it seems to work.  window will not throw a referenceerror if used with typeof, and then inside the IIFE we can redefine `window` and `self` to be equal to `this`.  That gives us the most flexible options for supporting third party polyfill code which might be assigning into properties of `window`, `self` or `this`, it's compatible with web workers, while still being able to cope with environments in which the developer has redefined `self` or `this`.

**Comment by monolithed** [comment]
> `var window = this, self = this;`

It doesn't make sense in [WorkerGlobalScope](https://developer.mozilla.org/ru/docs/Web/API/)

Web Workers don't have a `window` object and we do not have to add them in this environment. 
This may affect the third-party code!

**Comment by jonathantneal** [comment]
Is there a CSP-safe way to check for the real global scope?

Is `this` always declared? Is `self` always declared ([WorkerGlobalScope.self](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self))?

``` js
this || self || {}
```

If `this` and `self` are always declared, but there is no CSP-safe way to check for the global scope, may we fall back on a new object? If we fall back on a new object, should we expose it as `self`?

``` js
self = this || self
```

**Comment by monolithed** [comment]
> Is there a CSP-safe way to check for the real global scope?

Nope, because `this`, `window` (web), `self` (workers) and `global` (node) can be redefined and `eval` code is blocked by `CSP`

I like `Function('return this')()`, but CSP does not think so

> Is this always declared? Is self always declared (WorkerGlobalScope.self)?

`this === self`

> If this and self are always declared, but there is no CSP-safe way to check for the global scope, may we fall back on a new object? If we fall back on a new object, should we expose it as self?
> 
> ``` js
> self = this || self
> ```

We should not export the `window` or `self`, because this may affect the third-party code!

**Comment by jonathantneal** [comment]
A browser and a worker will expose `self` even when `this` is undefined.
Node will expose `global` even when `this` is undefined.

Therefore, the CSP-safest way to catch the global may be this:

``` js
this || 'object' === typeof self && self || 'object' === typeof global && global || {}
```
- Use `this`.
- If `this` is falsey then use `self`.
- If `self` is not a declared object or is falsey then use `global`.
- If `global` is not a declared object or is falsey then use a new object.

Using `typeof` protects us from undeclared variables and non-objects. Using `||` protects us from null objects.

All together, if we want a **very safe** IIFE, it may look like this:

``` js
(function () {
    'use strict';

    (function (undefined) {
        // polyfills
    }).call(this || 'object' === typeof self && self || 'object' === typeof global && global || {});
})();
```

Still, can’t the outermost IIFE be cool like this:

``` js
(function (undefined) {
    'use strict';

    // polyfills
}).call('object' === typeof global && global || this);
```

Just a thought.

**Comment by monolithed** [comment]
@jonathantneal

> use strict';

@triblondon wrote

> if the polyfill wanted to set use strict, it could do so, but the reason use strict works in the way it does is to avoid breaking the web for code that already exists and would stop working if the stricter rules of use strict were applied.

I fully agree with @triblondon

**Comment by triblondon** [comment]
OK, I think the sweet spot here is to remove the `use strict` but otherwise follow @jonathantneal's proposal:

``` javascript
(function (undefined) {
    // polyfills
}).call(this || 'object' === typeof self && self || 'object' === typeof global && global || {});
```

**Comment by monolithed** [comment]
@triblondon, 

```js
typeof null === 'object'; // true
```

**Comment by triblondon** [comment]
On second thoughts, if we include `this` in the `call()`, we allow the possibility that `this` within the IIFE will not be a reference to the global scope.  And referring back to a previous comment, `self` is more likely to be overridden than `window`.  So I'm going with this:

``` javascript
(function (undefined) {
    // polyfills
}).call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});
```

**Comment by monolithed** [comment]
A similar discussion https://github.com/paulmillr/es6-shim/issues/301
