### ISSUE TITLE
Support info for setImmediate is wrong

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#353]
The [feature table](https://cdn.polyfill.io/v1/docs/features/#setImmediate) says `setImmediate` is supported natively everywhere:

![image](https://cloud.githubusercontent.com/assets/250617/6739232/5c226f20-ce6f-11e4-8581-a30ad9a750a1.png)

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) says it's not:

![image](https://cloud.githubusercontent.com/assets/250617/6739270/870bc42a-ce6f-11e4-8120-33b1e92c0dfb.png)

**Comment by triblondon** [comment]
Ah, this is because setImmediate doesn't even have a feature detect.  Pushed a fix.
