### ISSUE TITLE
Travis fails because it expects environment variables?

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#356]
I did a [PR](https://github.com/Financial-Times/polyfill-service/pull/354) but the build [failed](https://travis-ci.org/Financial-Times/polyfill-service/builds/55082538) on this:

```
Warning: SAUCE_USER_NAME and SAUCE_API_KEY must be set in the environment Use --force to continue.
```

Is Travis supposed to be configured with these env vars somehow?

**Comment by triblondon** [comment]
This is because we are using a Sauce Labs account to test the polyfills that's owned by the FT.  To run the CI tests, I have to push your PR to a branch of the main repo.

**Comment by callumlocke** [comment]
OK. Is this resolveable or shall I close this issue?

**Comment by triblondon** [comment]
There is a way to add encrypted env vars to the travis.yml file:

http://docs.travis-ci.com/user/encryption-keys/

We could do that, I suppose.  But then anyone would be able to run tests on our Sauce account, which just doesn't strike me as a good idea.

**Comment by maxnordlund** [comment]
Actually Travis doesn't allow PR tests to use encrypted environmental variables.

http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

**Comment by triblondon** [comment]
Ah, so not resolvable then.  Thanks for pointing that out.

**Comment by maxnordlund** [comment]
Well you could use something like https://github.com/twbs/savage

**Comment by maxnordlund** [comment]
However it would be nice if Travis didn't always fail, so just skip Sauce Labs per the example in the documentation above for PR:s.
