### ISSUE TITLE
Number.toLocaleString polyfill

### ISSUE THREAD

**Issue by dy** [polyfillpolyfill/polyfill-service#359]
There's nice little method of `Number`, allowing to format value to any locale: [`Number.toLocaleString`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString).
There're [some](https://github.com/willsp/polyfill-Number.toLocaleString-with-Locales) [polyfills](https://github.com/TheIronDeveloper/NumberToLocaleStringPatch) for that, which, I suppose, might be included into the central repository.
Just a notion.
Any thoughts?

**Comment by monolithed** [comment]
The [second](https://github.com/TheIronDeveloper/NumberToLocaleStringPatch) polyfill is [not completed](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) yet!

**Comment by triblondon** [comment]
MDN is a bit vague on current support. Presumably you're looking for the additional support for the locales argument, rather than basic support which seems to be relatively universal?  Very happy to take a polyfill.  There are updated guidelines on contributing third party maintained polyfills in the contributor guide.

**Comment by everyonesdesign** [comment]
Actually this issue is just a part of polyfilling INTL standard (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl)) which is quite spacious and will require lots of efforts to be implemented.

**Comment by triblondon** [comment]
Is this issue covered off by our full support for the Intl polyfill and all the locales?

**Comment by triblondon** [comment]
Ping @dfcreative - is our support for Intl solving this?

**Comment by triblondon** [comment]
See also #497.

**Comment by dy** [comment]
@triblondon at some point all my browsers, including IE in compatible mode and node, started supporting `toLocaleString`, so I don’t have a chance to check it. If you can check it in old browser - try this code:

``` html
<!doctype html>
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en-US|always&gated=0"></script>
<script>(12345).toLocaleString();</script>
```

**Comment by JakeChampion** [comment]
Closing this as the `Intl` polyfill provides a `Number.prototype.toLocaleString` method - https://github.com/andyearnshaw/Intl.js/blob/20f322dcb47624cec6ba72addcef107c2de94e71/src/core.js#L40
