### ISSUE TITLE
Add remaining ES6 collections (Map, Set, WeakSet)?

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#364]
There seem to be a few:

https://github.com/EliSnow/Blitz-Collections
https://github.com/Benvie/harmony-collections
https://github.com/zloirock/core-js#ecmascript-6-collections

I don't know how good they are. But the last one is used by Babel.js for [collections support](https://babeljs.io/docs/learn-es6/#map-set-weak-map-weak-set), so it is probably OK.

**Comment by callumlocke** [comment]
Then again [this one](https://github.com/eriwen/es6-map-shim) claims Map 'cannot be shimmed'.

**Comment by triblondon** [comment]
Very happy to accept these.  Would be interested to know why Map is not polyfillable.

**Comment by mhevery** [comment]
Here are the reasons why they claim they can not be shimmed. https://github.com/eriwen/es6-map-shim/commit/2d6bb9dd9bef03500a8e770fcfe6e8feaf15fa37

They recommend using https://github.com/WebReflection/es6-collections Could we get that added into this repo?

**Comment by triblondon** [comment]
I'm working on Map, but I need the Symbol polyfill from Jake to land first.

**Comment by mhevery** [comment]
Sweet! Do you have an estimate? How can we help?

**Comment by JakeChampion** [comment]
Work for Map can be found in #670

**Comment by triblondon** [comment]
Map is shipped, and we already had WeakMap and WeakSet.  Set should be fairly simple.  Let's have a new issue for that.

**Comment by mhevery** [comment]
YAY! When will it show up on http://cdn.polyfill.io/v2/docs/features/ and on CDN?
