### ISSUE TITLE
XMLHttpRequest.prototype.overrideMimeType does not work in IE8

### ISSUE THREAD

**Issue by jamesnicholls** [polyfillpolyfill/polyfill-service#365]
The XMLHttpRequest polyfill contains a overrideMimeType method, but this just proxies through to the browser's XMLHttpRequest/ActiveXObject. However, the overrideMimeType method doesn't exists on IE8's ActiveXObject.

See https://jsfiddle.net/gfwhqdr3/

**Comment by triblondon** [comment]
Thanks.  Do you know of any polyfill that works correctly in IE8 and offers that method?

**Comment by jamesnicholls** [comment]
From my limited research, it isn't polyfill-able.

**Comment by triblondon** [comment]
@jamesnicholls what do you suggest we do about this?  I haven't checked in IE8 - is the impact bad? We can add handling for it in the polyfill to throw an exception or ignore it?  In any case a note in the polyfill docs is probably worthwhile.

**Comment by jamesnicholls** [comment]
I came across this bug because of a third-party library that first checked for the existence of overrideMimeType before attempting to use it. Given that the polyfill is only served to IE <= 8, and overrideMimeType seems to be un-polyfillable in those browsers, I think that the polyfill just shouldn't define this method.

**Comment by triblondon** [comment]
Define it as a no-op, you mean, ie `function() {}` ?

**Comment by jamesnicholls** [comment]
Sorry, updated my comment. Meant to say "shouldn't define this method".

**Comment by triblondon** [comment]
Since the FT's browser support guidelines recommend no JavaScript execution in IE8, we won't fix this, but a community fix or an improved polyfill for XHR is welcome.
