### ISSUE TITLE
Consider more granular detects and remove variants

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#366]
Following a suggestion from @hgl in #268 and an issue raised by @azproduction in https://github.com/azproduction/autopolyfiller/issues/18#issuecomment-88467588: There are a few problems that are cropping up repeatedly:
1. The existence of _variants_ of polyfills means that it is impossible to create a polyfill bundle that is UA-agnostic.  You have to specify a UA in order that the service can choose the right variations of polyfills.  However the use case of using the service to build a generic bundle and send it to all browsers is a popular one.  I think it's somewhat misguided but supporting it would give the project more traction.
2. There's often repeated code between variants because while implementations are different for two browsers, they're not _very_ different.

Suggestion:
- Change `detect.js` to return either `true`, `false` or an object of multiple boolean flags, eg `{basic:true, multipleArgs:false}`.
- Scrap variants, and put the entire solution, for all browsers, in one polyfill.js file
- Scrap all the targeting data from the config.json files
- In the polyfill source, use `if` statements to apply polyfill code conditionally based on the results of the detect, eg:

``` javascript
if (!PolyfillService.detectResults.multipleArgs) {
   // Code to polyfill multiple arg support
}
```
- Initially, serve the full polyfill source gated with a feature detect, along with (if user opts in) a bit of code that beacons the results of the detect back to the service.  Once the service has the support data for a particular browser, it can then re-run minification, using Uglify's dead code removal flag, to create a dynamic variation of the polyfill source for a particular UA.  Uglify will remove any `if` statements including all the contained code if it knows that the condition is false.

Advantages:
- Maintains the existing benefit of serving smaller amounts of code to browsers that already have some of the functionality
- Simplifies the maintenance of polyfills, fewer files in the source tree, simpler polyfill config
- Targeting becomes automatic which means no targeting mistakes and no targeting config to maintain
- We are now able to support the unknown UA use case easily

Disadvantages:
- For browsers where we don't have support data, polyfills will be potentially larger
- Requires sending beacon data back to the service from third party websites (opt in, but people might still complain)
- Third party polyfills will not use our detect data, so will not be optimisable (we could mitigate this a bit by automatically wrapping third party polyfills in a single `if` that checks the detect result, but it would be all-or-nothing, rather than offering the ability to optimise away just the unnecessary parts)
- Runtime minification adds overhead to the server process
- It requires a fairly major refactor

I'm not sure how using the service as a node module would work with this - presumably on a regular basis we'd want to download the detect data from the CDN app and commit it into the source tree, so that users who want to run their own version don't have to start from no detect data at all.

Thanks to @hgl for the inspiration for this.  @juandopazo @jonathantneal what do you think?

**Comment by juandopazo** [comment]
FWIW I haven't been using variants.

> a bit of code that beacons the results of the detect back to the service

Trust me, this is a security nightmare.

I suggest sticking to a truthy value in `detect.js` and keeping an eye on the size of each polyfill while we rewrite them into a single file (I'll help).

**Comment by triblondon** [comment]
The use of detect results to remove unnecessary code is an optimisation, so we could start with just scrapping variants and keeping the manual targeting data.  But I'd be keen to investigate the possibility of adding that optimisation later.  After all, serving the smallest possible amount of code is one of Jonathan's original design goals, and I'm on board with that goal.  But we are certainly finding it harder to adopt third party polyfills if the parts that target separate browsers are meant to be in different variants.

The beacon could be an analytics style image-beacon, and it would be opt in... I'm rubbish on security so can you point out some of the more obvious nightmares?  I'm thinking it would create a URL like:

```
/recordDetectData?result={"Element.prototype.classList": {"basic":true,"multipleArgs":false}}
```

And that would return the usual 1x1 gif.

How are you using the service without using the variants?

**Comment by jonathantneal** [comment]
Variants are not just about file size. Variants are about performance and maintainability. Also, variants are becoming less common. They were especially useful for old browsers like IE≤8. Variants are used to quickly and clearly referencing the most performant or most capable thing in a particular browser that is used to create a polyfill.

The name of the game is writing the most accurate, most readable, fastest running, and fastest initializing polyfill, in that order of priorities IMHO. Maintainability is up to the community surrounding this project, no matter how you slice it (third-party / as-is vs originals / retooled), IMHO.

**Comment by hgl** [comment]
@triblondon Thank you for writing this up.

I have a few more suggestions:

> Initially, serve the full polyfill source gated with a feature detect

I think that's inefficient. We should first serve the feature detect to a testing cluster like saucelabs to get the feature detect data for most popular browsers:

``` json
{
  "ie6": { "classList": false, "fetch": false },
  "ie >6 <12": "...",
  "chrome 1": { "classList": false, "fetch": false },
  "chrome >1 < 39": "...",
  "chrome 39": { "classList": { "toggleForceArg": false, "multipleArgs": true }, "fetch": true }
}
```

We then run the dead code elimination step on the combo of feature detect data and full polyfill to generate the smallest polyfill code for each browser. So when popular browsers request the service, they get precompiled file immediately.

Only when an unknown UA request the service, we service the detect code + full polyfill, and optionally beacon back the detect data (for unkown UA, we have to collection large amount of the **same** detect data, before the mapping between the unknown UA and the detect data can be trusted). After we have the detect data for that UA, we then compiled the polyfill for it, declare the UA as known.

---

However, the code amount of full polyfill can potentially be very large for old browsers, especially as time goes by.

I think we can take it to the next level by letting users specify which kinds things they like to polyfill:

```
https://cdn.polyfill.io/v1/classList+fetch.js
```

When they request this url, they only get classList and fetch polyfills (if the browser doesn't support them).

We can even develop a tool to automatically detect the web APIs a particular code base uses, and return a list of polyfill names. (This should be easy, we just need to wrap web APIs and see which ones get called.)

We can even define a few keywords which will combine popular polyfills:

```
https://cdn.polyfill.io/v1/core+network.js
```

`core` can map to es shims + dom polyfill, and `network` can map to xhr + fetch for example.

---

And finally for development environment, we can offer the detect + full polyfill as a downloadable file, so users don't need to use the service while developing.

**Comment by hgl** [comment]
Also I tried uglifyjs when I made the suggestion. It doesn't eliminate dead code if the condition is a property of an object.

``` js
var support = { foo: true, bar: false };

if (!support.foo) {
  window["foo"] = "foo"
  alert("foo polyfilled");
}

if (!support.bar) {
  window["bar"] = "bar"
  alert("bar polyfilled");
}
```

Try compress this on http://lisperator.net/uglifyjs/#demo

Only google closure compiler's "advanced compilation" eliminates it.

But you have to expose global variables via the `["name"]` syntax, otherwise it gets renamed.

**Comment by hgl** [comment]
I also have thoughts on how we should test the polyfills, maybe we can discuss it later. (tl;dr: leverage https://github.com/w3c/web-platform-tests)

**Comment by hgl** [comment]
We can also use module syntax to solve the problem of polyfill dependencies.

performance.now.js

``` js
import "./data.now";

// polyfill performance.now
```

data.now.js

``` js
Date.now = function now() {
    return new Date().getTime();
};
```

If we can make sure no circular dependencies exist, the bundled code can be very lightweight (no commonjs or amd boilerplate code).

**Comment by jonathantneal** [comment]
@hgl, using the ES6 `import` and transpiling the code to work in ES5 would be dreamy. Could you create a simple example?

**Comment by hgl** [comment]
Sure, in this example I use [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler)'s bundle format:

data.now.js

``` js
var customVar = new Date().getTime();
Date.now = function now() {
    return customVar;
};
```

performance.now.js

``` js
import "./data.now";

var customVar = "polyfill performance.now";
alert(customVar);
```

```
compile-modules convert performance.now.js
```

=>

``` js
(function() {
    "use strict";
    var customVar = new Date().getTime();
    Date.now = function now() {
        return customVar;
    };

    var performance$now$$customVar = "polyfill performance.now";
    alert(performance$now$$customVar);
}).call(this);
```

And if you do

```
compile-modules convert performance.now.js data.now.js
```

It's smart enough to not repeat the `data.now.js` file.

**Comment by triblondon** [comment]
> Variants are about performance and maintainability

@jonathantneal could you give me an example of how variants improve performance and maintainability?  In terms of maintainability I see variants as a problem, not a solution, because they result in repeated code (eg see the [Node.prototype.contains](https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/Node.prototype.contains) polyfill which repeats largely the same code across three variants), require manual targeting, and more complex config.  In terms of performance I can't see that there's any difference, provided that we have a mechanism for removing the dead code.

On the other hand the existence of variants prevents us supporting something lots of people are asking for.

> I think we can take it to the next level by letting users specify which kinds things they like to polyfill

@hgl this is already supported.

> We can even define a few keywords which will combine popular polyfills

This is also already supported.

> I tried uglifyjs when I made the suggestion. It doesn't eliminate dead code if the condition is a property of an object

OK then, it can be a single symbol name:

``` javascript
if (_PolyfillDetects_multipleArgs) {
   // insert code to polyfill multiple argument support here
}
```

I don't want to use Closure compiler, it's a Java tool which would make deploying the app significantly more complex.

Regarding dependencies, can you guys move that to another thread?  It seems orthogonal to this discussion.

**Comment by hgl** [comment]
Just to provide an example how granular detects support variants:

Take `Node.prototype.contains` for an example:

``` js
if (!NodeHasContains) {
    if (!isNodeExtendable && isElementExtendable) {
        document.contains = Element.prototype.contains = contains;
    } else if (isNodeExtendable) {
        Node.prototype.contains = contains;
        if (HTMLElementHasContains) {
            delete HTMLElement.prototype.contains;
        }
    }
}
function contains() {
    //...
}
```

``` yaml
ie * - 8: 
  NodeHasContains: false
  isNodeExtendable: false
  isElementExtendable: true
ie 9 - *:
  NodeHasContains: false
  isNodeExtendable: true
  HTMLElementHasContains: true
firefox * - 8, safari * - 2:
  NodeHasContains: false
  isNodeExtendable: true
  HTMLElementHasContains: false
```

> This is also already supported.

Sorry, didn't notice it.

**Comment by azproduction** [comment]
I'll try to improve a bit variant of @hgl.

We could use Modernizr or Modernizr-ish feature detection with manual/runtime feature resolve.
- our feature tests will be formed as a code, not just file with JS expression: [eg](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array.prototype.find/detect.js#L1).
- possible to use without relaying on UA-string (runtime feature resolution).

Runtime resolution

``` js
function supports(what) {
    // vvv the code below is generated vvv
    if (what=== 'Array.prototype.forEach') {
       return Boolean(Array.prototype.forEach);
   }

   // ...
}
if (supports('Array.prototype.forEach')) {
    // Apply common polyfill part
    if (supports('Smth.else')) {
        // Apply spec. polyfill condition
    }
}
```

User Agent-based resolution (we already know what they support)

``` js
var supports = {
     'Array.prototype.forEach': true,
     'Smth.else': false
};

if (supports['Array.prototype.forEach']) {
    // Apply common polyfill part
    if (supports['Smth.else']) {
        // Apply spec. polyfill condition
    }
}
```

Which will be minified as

``` js
// Apply common polyfill part
```

**Comment by triblondon** [comment]
I'm keen to pick this up again, and convinced that eliminating variants will help us maintain the service (simpler service code, fewer polyfill files, easier adoption of third party polyfills, simpler configs).  But we can do _just that_, without the dead code removal, as @juandopazo suggests at the top of this thread.  I've created https://github.com/Financial-Times/polyfill-service/issues/461 to talk about scrapping variants, and we can follow that up with an issue for dead code removal separately.
