### ISSUE TITLE
JavaScript Error on http://polyfill.io website in IE <= 8

### ISSUE THREAD

**Issue by whitneyit** [polyfillpolyfill/polyfill-service#367]
I noticed that the website is throwing an error when viewed in IE 8 and below. This error is captured in the following [screenshot](http://i.imgur.com/a3v1Mz5.png).

This isn't a bug with `polyfill.js` but with [`ui.js`](https://github.com/Financial-Times/polyfill-service/blob/e26f1391d5fa61162364a33b4b4a06a26334d93c/docs/assets/js/ui.js) instead.

IE is getting tripped up on the use of `Object.defineProperty` by `Array.from` and the use of `document.querySelectorAll`.

I'm not sure how you want to proceed or whether or not whether or not this _bug_ needs fixing. I just wanted to give a heads up since I initially thought it was a bug with `polyfill.js` and not `ui.js` which lead to a bit of confusion.

**Comment by triblondon** [comment]
This is because the docs use the FT's techdocs component, which in turn uses the modern jQuery and that relies on the ability to create objects with accessor functions, which is not polyfillable in IE8.  I'm idly working on removing the jQuery dependency but it's not a high priority.

**Comment by triblondon** [comment]
Incidentally, for the record I don't believe the trigger of the error is in UI.js, I think it's in the external script we load from build.origami.ft.com

**Comment by triblondon** [comment]
Now fixed by adding a cuts the mustard test which doesn't run any of the UI JS in IE8
