### ISSUE TITLE
Use module syntax to manage polyfill dependencies

### ISSUE THREAD

**Issue by hgl** [polyfillpolyfill/polyfill-service#369]
Continue from #366.

In this example I use [es6-module-transpiler](https://github.com/esnext/es6-module-transpiler)'s bundle format:

data.now.js

``` js
var customVar = new Date().getTime();
Date.now = function now() {
    return customVar;
};
```

performance.now.js

``` js
import "./data.now";

var customVar = "polyfill performance.now";
alert(customVar);
```

```
compile-modules convert performance.now.js
```

=>

``` js
(function() {
    "use strict";
    var customVar = new Date().getTime();
    Date.now = function now() {
        return customVar;
    };

    var performance$now$$customVar = "polyfill performance.now";
    alert(performance$now$$customVar);
}).call(this);
```

And if you do

```
compile-modules convert performance.now.js data.now.js
```

It's smart enough to not repeat the `data.now.js` file.

This actually implies modular feature detection, if we ever decide to go that route:

``` js
import support from "feature-detection/performance.now";
import "./data.now";

if (!support) {
  // Use Date.now();
}
```

We do need to figure out how to avoid importing unused files (in the example, data.now is never used if `support` is true). Probably going to rely on [Loader](http://whatwg.github.io/loader/), which [Systemjs](https://github.com/systemjs/systemjs) implements.

~~Well, `data.now.js` itself should make sure its code get eliminated when browsers support it.~~

**Comment by triblondon** [comment]
I'm afraid I don't like this.  The dependencies in the polyfill service are not absolute - in many cases they are satisfied by the browser environment in which we run the polyfill code, and the sub-polyfill is not needed. There might be an argument for something like this for private polyfills like _enqueueMicrotask, but I don't think there's value in having two different mechanisms.  The current dependency system works well.

**Comment by hgl** [comment]
The current dependency system works because you use different files for different variants.

If a polyfill become something like this:

``` js
if (!supportPerformanceNow) {
 // use Date.now() to polyfill performance.now()
}
```

It's no longer always depends on `Date.now()`, it only depends on it when `supportPerformanceNow` is `false`.  This kind of "depend on a file under a condition" is best expressed with a module loader.

See [systemjs's meta config](https://github.com/systemjs/systemjs/wiki/Configuration-Options), which supports this kind of thing.

And my previous code sample should actually be

``` js
import support from "feature-detection/performance.now";

if (!support) {
  // Use Date.now();
}
```

Loading `data.now.js` or not is controlled by the config we pass to systemjs.

The only thing is that systemjs generates boilerplate code when bundling file, but shouldn't be hard to develop a new bundling format for it. 

---

On second thought, if you can generate feature detect data for each browser, then current system does work. But it does reinvent the module loader system.

**Comment by hgl** [comment]
Using module syntax to polyfill is probably not a good idea.

From caridy on [stackoverflow](http://stackoverflow.com/questions/27870974/what-is-the-correct-way-to-load-polyfills-and-shims-with-browserify#answer-28965677).

> Your modules should assume that the runtime is patched (when needed), and that should be part of the contract.

If we write polyfills in module syntax, we are breaking that contract.

For one, modules don't have access to the global object unless the host environment provides one (e.g., window, self, etc). That means we at least shouldn't use modules to polyfill the js standard library (e.g., Map, Symbol, etc).
