### ISSUE TITLE
Support Babel-compiled code

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#373]
Babel-compiled code depends on a big drop-in [polyfill bundle](http://babeljs.io/docs/usage/polyfill/).

It would be nice if people could just use polyfill.io instead. But currently polyfill.io does not satisfy all the requirements.

afaict, this is what we would need to do:
- [x] Add a [`Symbol`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol) polyfill.
- [x] Update our `Array.from()` polyfill to support [iterables](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols).

I'm basing this on info from [Babel's caveats page](http://babeljs.io/docs/usage/caveats/) and a [comment](https://github.com/babel/babel/issues/1125#issuecomment-88156131) from a Babel committer.

NB. We'd also need to add all the ES6 collection classes (separate issue [here](https://github.com/Financial-Times/polyfill-service/issues/364)) for more complete ES6 support, but these aren't actually required by Babel's internal mechanics in the way that `Array.from()` and `Symbol` are.
### more info

The existing [babel polyfil bundle](https://github.com/babel/babel/blob/master/src/babel/polyfill.js) comprises:
- the whole of [core-js/shim](https://github.com/zloirock/core-js/blob/master/shim.js)
- the [runtime](https://github.com/facebook/regenerator/blob/master/runtime.js) for Facebook's [regenerator](http://facebook.github.io/regenerator/)
  - (n.b currently they are using [their own fork](https://github.com/babel/regenerator-babel) of this, but they are [planning to switch to the original](https://github.com/babel/babel/issues/1123))

Technically the regenerator runtime is not a polyfill. It doesn't actually make generators work (generators are unpolyfillable due to syntax). It just supports Babel's compilation output for source code that included generators. I don't think we should worry too much about this. I think the ideal situation would be: "You don't need Babel's polyfill bundle if you're using polyfill.io, but you do still need to drop in Facebook's regenerator runtime if you're using generators."

**Comment by triblondon** [comment]
End goal aside, adding a polyfill for Symbol and improving the Array.from one is fine by me.

**Comment by barneycarroll** [comment]
@callumlocke do you think it's worth investigating a system for modular compilations of core-js's shims? The likelihood is that there will be diminishing returns on output size as fewer polyfills are required, but the polyfills themselves are robust and accountable. The practice still adds a layer of complexity, because it's no longer a case of just concatenating discrete files.

**Comment by triblondon** [comment]
We've been discussing looking at a mechanism for importing most of core-js into the service.  I've created #421 to cover this.

**Comment by triblondon** [comment]
@callumlocke the following are now both supported:
- Add a Symbol polyfill.
- Update our Array.from() polyfill to support iterables.

What do you want to do with this issue now?

**Comment by JakeChampion** [comment]
We should take one of our applications which use babel and replace core-js polyfill with polyfill-service and see if it works.

**Comment by JakeChampion** [comment]
Closing this issue since the features requested are now implemented. If you find an application which uses babel and doesn't work using our polyfills please create a new issue covering the specific case.
