### ISSUE TITLE
"fetch" polyfill licence info is wrong

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#374]
site has a warning about `fetch` polyfill having a proprietary licence:

![image](https://cloud.githubusercontent.com/assets/250617/7024268/62dd9678-dd33-11e4-910d-8792bd0f7e6f.png)

..but it doesn't, it just uses the MIT licence:

https://github.com/github/fetch/blob/master/LICENSE

**Comment by triblondon** [comment]
Doesn't say MIT anywhere except in the commit message, but if it matches
the MIT licence text, then feel free to update the polyfill metadata.

**Comment by callumlocke** [comment]
after normalising line breaks, it matches exactly with the one at http://opensource.org/licenses/MIT
