### ISSUE TITLE
Incorrect fetch polyfill usage note

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#375]
The [note](https://github.com/Financial-Times/polyfill-service/blob/a3940972c89c156377ac72e9a7fa59a7afa52e35/polyfills/fetch/config.json#L20) about `fetch` says:

> Uses FileReader and Blob if they exist, and depends on FormData

But I'm not clear on what this means for me as a user. The compatibility table says the fetch polyfill works in all IE versions, but [caniuse says](http://caniuse.com/#feat=xhr2) FormData is only available in IE10+. So am I supposed to polyfill FormData myself for IE<10, and if so, why doesn't polyfill.io just do this for me?

**Comment by triblondon** [comment]
Based on https://github.com/Financial-Times/polyfill-service/pull/246#issuecomment-69977678 it looks like that note is incorrect.  I'll change it.

**Comment by zslabs** [comment]
Even after the above PR, still a little confused if there's a workaround built-in for FormData for older versions that don't have it natively. Could you please clarify?

**Comment by JakeChampion** [comment]
Unfortunately we don't have a FormData polyfill, we will gladly accept a pull-request if you know of one or are willing to create one yourself. Here are our [guidelines for authoring a polyfill](https://cdn.polyfill.io/v2/docs/contributing/authoring-polyfills#authoring-guidelines). If you get stuck at any step, feel free to create an issue and we will aim to help :-)

**Comment by zslabs** [comment]
Gotcha, appreciate the response. I did come across https://github.com/moxiecode/moxie/blob/master/src/javascript/xhr/FormData.js and https://gist.github.com/lemonhall/3120320 which appears to be a fairly solid solution, but don't have my head wrapped around the internals of this lib for contributing just yet. Have you heard of this one before?
