### ISSUE TITLE
CustomEvent feature detect seems broken in Android browser 4.2

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#378]
Consistently fails to get polyfilled https://app.getsentry.com/nextftcom/ft-next-frontend/?browser=Android+4.2

**Comment by samgiles** [comment]
Just need to update the config, there are ideas floating around to automate the collection of these configs.
- https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/CustomEvent/config.json

**Comment by matthew-andrews** [comment]
do we not have stock android on SauceLabs?

**Comment by samgiles** [comment]
Our full test suite does, but, it's quite unreliable.  We also don't automatically generate targeting data from the tests, yet.

**Comment by matthew-andrews** [comment]
how come the customevent polyfill never failed on android stock then?

**Comment by samgiles** [comment]
iirc CI only tests targeted browsers, so it would've been skipped for CustomEvent as it's not targeted.

**Comment by wheresrhys** [comment]
what a pleasantly easy fix. But I take it this would need a polyfillservice release? In the meantime `CustomEvent|always` should fix it for us?

**Comment by matthew-andrews** [comment]
@wheresrhys yup

**Comment by triblondon** [comment]
Neither CanIUse nor MDN has android support info for customevent.  Looks like our tests show that the polyfill works on 4.0 to 4.3, and it's native in 4.4 (which uses Chrome 30 for its webview).  I just found a 2.3 emulator and found the polyfill also works in that, so will configure it for Android <= 4.3
