### ISSUE TITLE
1.4.0 release

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#384]
Following my new release policy, I've made a 1.4.0-rc.1 release rather than going direct to 1.4.

[Release notes](https://github.com/Financial-Times/polyfill-service/releases/tag/v1.4.0-rc.1) are available.

The RC is also pushed to qa.polyfill.io for ease of testing:

![image](https://cloud.githubusercontent.com/assets/1735391/7179626/e1170f88-e431-11e4-9c8d-4ccf51c1e35a.png)

This is proposed as a MINOR release, so there should be no backwards incompatible API changes.  Please test with your project and post here if you find one.  The RC will be available for testing for at least 1 week before I release a stable version.

**Comment by triblondon** [comment]
Ping @monolithed, @juandopazo, @matthew-andrews, @Bockit, @callumlocke

**Comment by monolithed** [comment]
#### 1.4.0-rc.1

```
➜ grunt test
Loading "polyfill-service.js" tasks...ERROR
>> Error: Cannot find module '../polyfills/String.prototype.startsWith/polyfill'
Loading "polyfillService.js" tasks...ERROR
>> Error: Cannot find module '../polyfills/String.prototype.startsWith/polyfill'
Warning: Task "polyfillService" not found. Use --force to continue.
```

PS: I've tested with [grunt-polyfill-service](https://www.npmjs.com/package/grunt-polyfill-service)

**Comment by triblondon** [comment]
Sorry, errant code there, removed.  Released 1.4.0-rc.2.  Have not redeployed to QA env since the change has no effect when run as a service.

**Comment by monolithed** [comment]
```
➜ grunt test
Running "polyfillService:production" (polyfillService) task
>> File "tests/fixtures.js" created.

Running "nodeunit:tasks" (nodeunit) task
Testing test.js.OK
>> 1 assertions passed (10ms)

Done, without errors.
```

**1.4.0-rc.2** looks good

**Comment by triblondon** [comment]
Barring other objections, 1.4.0-rc.2 will be released as 1.4.0 tomorrow.

**Comment by Bockit** [comment]
I haven't had time to do anything exhaustive but testing a couple of sites it was working fine. No objections here.

**Comment by triblondon** [comment]
Thanks guys. Release now in prod and npm.
