### ISSUE TITLE
Don't use protocol-relative URLs in examples?

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#386]
The [examples page](https://cdn.polyfill.io/v1/docs/examples) recommends protocol-relative URLs.

There is [some advice](http://www.paulirish.com/2010/the-protocol-relative-url/) that protocol-relative URLs are now an anti-pattern, and that if an asset is available on HTTPS then you should always load it over HTTPS... Supposedly this can mitigate some attacks. I don't know about that, but I would have thought that for any user-agent-sniffing service, always using HTTPS would be a good idea anyway, to guarantee that each client gets its own copy (just in case an errant reverse caching proxy fails to honour headers like `Vary: User-Agent`).

**Comment by triblondon** [comment]
Yes, happy to have these changed to https.

**Comment by konklone** [comment]
I just put a few minutes into trying to find where to change this, and can't figure it out -- happy to submit a PR.

**Comment by triblondon** [comment]
Thanks for the offer, @konklone, much appreciated.  It is actually a very simple change so I went ahead and did it.

**Comment by konklone** [comment]
Thank you! :)
