### ISSUE TITLE
Object.keys not polyfilled on Firefox < 4

### ISSUE THREAD

**Issue by szeryf** [polyfillpolyfill/polyfill-service#387]
`Object.keys` is not implemented on Firefox < 4 (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys), however its `config.json` doesn't mention Firefox at all. 

My workaround: use `//cdn.polyfill.io/v1/polyfill.min.js?features=default,Object.keys|always|gated`

**Comment by szeryf** [comment]
Same thing with `Object.create` (see https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/create).

**Comment by triblondon** [comment]
Fixed in https://github.com/Financial-Times/polyfill-service/commit/47eeae66dda4759ffbdc9001c2b16a249ed07a55
