### ISSUE TITLE
Event target gets redefined in Event IE8 variant

### ISSUE THREAD

**Issue by jamesnicholls** [polyfillpolyfill/polyfill-service#391]
When dispatching a custom event, the `event.target` gets assigned to the DOM element that invoked the function (line 144). However, in the event handler, `event.target` gets re-assigned to either `event.srcElement` or the element the handler was registered on (line 66). When using event delegation, this is not going to be the element that dispatched the event.

**Comment by triblondon** [comment]
Interesting.  Do you have a test case for this, and a proposed solution?  Or is there an alternative polyfill that doesn't exhibit the problem?

**Comment by jamesnicholls** [comment]
Test case: http://jsbin.com/corupaxuce/3/

I think the solution is as simple as checking for the existence of `event.target` in the event handler (line 66).
