### ISSUE TITLE
Firefox focusin support

### ISSUE THREAD

**Issue by jamesnicholls** [polyfillpolyfill/polyfill-service#392]
The browser features page claims that Firefox supports the `focusin` event from v3.6, but the event still isn't supported in Firefox (see https://bugzilla.mozilla.org/show_bug.cgi?id=687787).

**Comment by triblondon** [comment]
Yes, this is annoying.  See https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Event.focusin/detect-disabled.js and #213.

**Comment by thasmo** [comment]
@triblondon It seems this was fixed in Firefox 52. `https://ft-polyfill-service.herokuapp.com/v2/polyfill.js` still polyfills the events although Firefox 52+ doesn't need the polyfills afaik.

**Comment by JakeChampion** [comment]
Hi @thasmo, do you mean that Firefox 52 supports this feature natively? If so, could you open a new issue which links to the MDN page showing the browser support or similar please. This issue was about our browser feature page (https://polyfill.io/v2/docs/features/) showing the wrong information.
