### ISSUE TITLE
Element.prototype.closest not getting polyfilled on chrome 40

### ISSUE THREAD

**Issue by andyburke** [polyfillpolyfill/polyfill-service#395]
I'm seeing an issue where Element.prototype.closest is not being polyfilled on chrome 40. I'm not clear on why. According to the config.json, it should be getting filled afaict. There is a dependency on Element.prototype.matches, but that polyfill is not needed on chrome 40, could that be the issue?

Here are the detections on chrome 40:

```
'document' in this && "matches" in document.documentElement
true
'document' in this && "closest" in document.documentElement
false
```

So my reading would be that Element.prototype.matches is not needed, but Element.prototype.closest is.

**Comment by triblondon** [comment]
Works for me:
http://cdn.polyfill.io/v1/polyfill.js?features=Element.prototype.closest&ua=chrome/40

``` javascript
 * UA detected: chrome/40.0.0
 * Features requested: Element.prototype.closest
 * Library version: latest
 * 
 * - Element.prototype.closest, License: CC0  */

(function(undefined) {

// Element.prototype.closest
Element.prototype.closest = function closest(selector) {
    var node = this;

    while (node) {
        if (node.matches(selector)) return node;
        else node = node.parentElement;
    }

    return null;
};

})
.call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});
```

**Comment by andyburke** [comment]
I see, I misunderstood the 'features' parameter, I didn't expect that to stop it loading the defaults.

**Comment by samgiles** [comment]
You can include 'default' as a feature to include the default set
additionally:  
http://cdn.polyfill.io/v1/polyfill.js?features=Element.prototype.closest,default

On Tue, May 5, 2015 at 2:10 PM, Andy Burke notifications@github.com wrote:

> I see, I misunderstood the 'features' parameter, I didn't expect that to
> stop it loading the defaults.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Financial-Times/polyfill-service/issues/395#issuecomment-99074141
> .

## 

_Sam Giles_
Developer
FT Labs

For Origami questions: origami.support@ft.com

Number One Southwark Bridge, London SE1 9HL

## 

---

This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by andyburke** [comment]
Yep, facepalmed after re-testing and re-reading docs.
