### ISSUE TITLE
MutationObserver polyfill

### ISSUE THREAD

**Issue by dy** [polyfillpolyfill/polyfill-service#397]
Hello!
There are some tasks related with handling element mutations, able to be polyfilled in IE8+.
There’s a polyfill-like lib, [mutation-observer](https://github.com/webmodules/mutation-observer), which does this, but there’s no such polyfill in the service.
Is it reasonable to add `MutationObserver` polyfill?
Thank you.

**Comment by triblondon** [comment]
Yes, we'd very much welcome that.

**Comment by matthewrobb** [comment]
Hello, curious if this is still in the pipe?

**Comment by ghost** [comment]
Will MutationObserver be available?

For some reason google cache shows it on the feature list. Was it removed?

**Comment by sheriff91** [comment]
Please add this, I'd love you forever! Is it in v3?

**Comment by triblondon** [comment]
PR is #695, but it has some failing tests.  FT doesn't need it, so we're probably going to close it, but it's close, so if you have an interest, you could pick it up and finish it off?

**Comment by sheriff91** [comment]
I can certainly have a gander. Especially considering this would be incredibly helpful for me. @triblondon Pulled the muOb branch.

**Comment by triblondon** [comment]
@hipkiss91 are you still intending to work on this?

**Comment by JakeChampion** [comment]
This was added in version 3.17 https://github.com/Financial-Times/polyfill-service/releases/tag/v3.17.0
