### ISSUE TITLE
Window.fetch(); does not appear to be polyfilled in Safari 8

### ISSUE THREAD

**Issue by alexwilson** [polyfillpolyfill/polyfill-service#400]
We've experienced a few issues while using `fetch();` through the Polyfill service, in that it does not appear to be defined in Safari 8, both on mobile and on desktop.  In every other browser this appears to work fine, but whenever attempting to use `fetch();` in Safari 8 we run into javascript errors.

```
> window.fetch();
< TypeError: undefined is not a function (evaluating 'window.fetch()')
```

**Comment by triblondon** [comment]
We chatted on Slack - turns out the polyfill was not included in your features list.
