### ISSUE TITLE
Support screen.orientation in webkit/blink

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#402]
Can use something like https://github.com/Financial-Times/o-viewport/blob/master/main.js#L28

**Comment by triblondon** [comment]
Afraid I can't work out what you're suggesting here.  That line just tests `typeof screen.orientation === 'string'`, and I can't see how that helps polyfill webkit/blink.

**Comment by wheresrhys** [comment]
chrome defines `screen.orientation` as an object, one of whose properties is (I think) equivalent to the string defined in the W3C spec

**Comment by triblondon** [comment]
OK, makes sense.  Happy to have a PR that changes the Chrome behaviour to the spec behaviour

**Comment by triblondon** [comment]
See #403
