### ISSUE TITLE
Can't get it working as a library

### ISSUE THREAD

**Issue by seibei-iguchi** [polyfillpolyfill/polyfill-service#405]
I try to use the service as a library, via `polyfills = require('polyfill-service')`.
But when I call:

```
polyfills.getPolyfillString({
  uaString: 'Mozilla/5.0 (Windows; U; MSIE 7.0; Windows NT 6.0; en-US)',
  minify: false
});
```

I get:

```
 * UA detected: ie/7.0.0
 * Features requested:
 * Library version: latest
```

Which is obviously wrong. I found out that in order to get the proper polyfills I have to call:

```
polyfills.getPolyfillString({
  uaString: 'chrome/43.0.0',
  minify: false,
  features: {
        'default': {}
  }
});
```

Which results in:

```
 * UA detected: chrome/43.0.0
 * Features requested: default
 * Library version: latest
```

That is quite different from what can be found in the documentation and the UA detection is somehow not working. What am I doing wrong?

**Comment by seibei-iguchi** [comment]
All of a sudden, it correctly recognizes `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36` as `chrome/43.0.0`. But I still have to pass in the `features` property as noted above, or else I don't get any polyfills back.

**Comment by triblondon** [comment]
Your initial example is doing the UA detection correctly - you supplied an IE7 UA and that's what it detected.  You do have to provide the features list, and it you don't the list is empty - the docs are wrong on that, I'll fix.

**Comment by seibei-iguchi** [comment]
Thanks! Sorry about the UA detection, I don't know how I missed that.
