### ISSUE TITLE
CustomEvent is not getting polyfilled in ie mobile

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#406]

**Comment by matthew-andrews** [comment]
Next team don't really have the equipment / resources to fix this…… Can Origami help? @triblondon

**Comment by JakeChampion** [comment]
Is this still an issue? I see that CustomEvent targets [IE mobile 10 and higher](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/CustomEvent/config.json#L9)

**Comment by wheresrhys** [comment]
If polyfill.io acid test page is ready coudl just load it in a device (I believe you coudl borrow one from Dillip)

**Comment by JakeChampion** [comment]
It's available on QA -- http://qa.polyfill.io/v2/docs/features/

**Comment by JakeChampion** [comment]
The acid test page is now on the live cdn.polyfill.io

**Comment by triblondon** [comment]
https://cdn.polyfill.io/v2/polyfill.js?ua=ie_mob/10&features=CustomEvent returns the CE polyfill for ie mobile. And it's also in the default set so https://cdn.polyfill.io/v2/polyfill.js?ua=ie_mob/10 returns it too.

Are we misrecognising the ie_mob UA?  If so could you raise an issue for that?  Closing this one.
