### ISSUE TITLE
query polyfill for Elements and ParentNode

### ISSUE THREAD

**Issue by jonathantneal** [polyfillpolyfill/polyfill-service#408]
I want to see if there is interest in polyfilling the `query` and `queryAll` methods and the `Elements` collection from the [DOM Living Standard](https://dom.spec.whatwg.org/).

https://github.com/jonathantneal/query

I think this polyfill could be broken into:
- `_queryAll`: Returns a context-aware collection of elements from a selector. Depends on `Array.prototype.filter` and `Array.prototype.forEach`.
- `Elements`: A collection of elements (like NodeList) that is also a subclass of Array.
- `Elements.prototype.queryAll`: => Returns a context-aware collection of elements from a selector. Depends on `_queryAll`.
- `ParentNode.prototype.queryAll`: => Returns a context-aware collection of elements from a selector. Depends on `_queryAll`.
- `ParentNode.prototype.query`: => Returns the first context-aware element from a selector. Depends on `_queryAll`.

**Comment by triblondon** [comment]
We'd be very keen to have a good polyfill for this in the collection

**Comment by triblondon** [comment]
@jonathantneal will you be doing this?

**Comment by triblondon** [comment]
https://github.com/barberboy/dom-elements

**Comment by triblondon** [comment]
I think I'll take this on.

**Comment by triblondon** [comment]
This has been removed from the WHATWG spec:

https://github.com/whatwg/dom/commit/10b6cf1ba02806220d5461a3bdb7939728b73635

And to my knowledge has never been in the W3C spec.  This is a bit of a shame, hopefully it will come back, but in the meantime it's not really our business to polyfill things that are not specced.
