### ISSUE TITLE
No polyfills being served for Chrome on iOS

### ISSUE THREAD

**Issue by jkimbo** [polyfillpolyfill/polyfill-service#409]
Doesn't look like Chrome on iOS gets served any polyfills (user agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) CriOS/30.0.1599.12 Mobile/11A501 Safari/8536.25`). I'm not quite sure what polyfills it would need since I believe it runs UIWebView but I thought I should raise it.

**Comment by triblondon** [comment]
We have very few polyfills that target `ios_chr`.  It's not a platform that gets much love from us since we have a vanishingly small number of users using it.  We'd certainly welcome some help expanding the targeting of polyfills to benefit Chrome on iOS.

**Comment by samgiles** [comment]
We've updated this in the current master branch, `ios_chr` should now look like the underlying UIWebView based on the version of Safari.

**Comment by AndrewIngram** [comment]
Can we assume that this is now in production?

**Comment by triblondon** [comment]
No, sorry - but we'll do our best to make a RC today, and when it does go live it'll be on 1.5
