### ISSUE TITLE
iOS non-Safari browsers detection issue

### ISSUE THREAD

**Issue by kaelig** [polyfillpolyfill/polyfill-service#411]
With this Chrome for iOS UA string:

`Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/43.0.2357.56 Mobile/12F70 Safari/600.1.4`

The polyfill service returns this response:

``` js
/* Unsupported UA detected: ios_chr/43.0.0 */

(function(undefined) {

})
.call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});
```

**Comment by kaelig** [comment]
@triblondon note that this is affecting FT's subscription page and every page that requires o-tabs.

**Comment by AutoSponge** [comment]
I had the same issue in production. Because the `unknown` parameter doesn't seem to work from the cdn, my workaround was to override the useragent as Windows IE8 for all requests :(

``` html
<script src="https://cdn.polyfill.io/v1/polyfill.min.js?features=default,es6,fetch&flags=gated&ua=Mozilla%2F5.0%20(Windows%3B%20U%3B%20MSIE%209.0%3B%20Windows%20NT%209.0%3B%20en-US)"></script>
```

**Comment by iSimonWeb** [comment]
:+1: Up, drove me crazy for an hour just now.

**Comment by samgiles** [comment]
Should we alias `ios_chr` to `chrome`.  I have no idea what the feature parity is like but I suspect they are the same.  Although I notice we don't set a baseline for `ios_chr` and claim to support it: http://cdn.polyfill.io/v1/docs/contributing#browser-support

**Comment by kaelig** [comment]
Chrome in iOS is essentially the same as iOS Safari (with a few exceptions since it's a webview), which is far from reaching feature parity with Chrome desktop / Android.

**Comment by samgiles** [comment]
So it does :disappointed:..  maybe we should just try and do the safest thing for chrome ios, as we can't easily say Chrome on iOS at 43 is equivalent to this particular version of UIWebView.  There isn't a correlation :/

**Comment by kaelig** [comment]
Chrome 41, 42, 43… all depend on the version of iOS's webview they run on.

Until Apple starts opening the door to other rendering engines, I think we can safely match UIWebView of specific iOS versions on which Chrome runs.

**Comment by samgiles** [comment]
Ok, I think the way forward is to simply:

``` JS
var userAgent = ua.replace(/(CriOS\/(\d+)\.(\d+)\.(\d+)\.(\d+))/, '');
/* ... parse(userAgent); ... */
```

The `useragent` module seems to then parse it as ios_safari at an appropriate version.  Will make a PR.

**Comment by kaelig** [comment]
The same happens in:

#### Opera Mini iOS (Both Turbo mode & Opera mini off)

```
Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) OPiOS/10.2.0.93022 Mobile/12F70 Safari/9537.53
```

#### Puffin iOS

```
Mozilla/5.0 (X11; U; Linux x86_64; en-GB) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.114 Safari/537.36 Puffin/4.4.0IP
```

I also looked in Dolphin browser which somehow works well.

**Comment by samgiles** [comment]
Ok, Opera Mini is easy to fix.  What is Puffin doing with that UA :disappointed:?  That's going to be harder as it's reporting `X11` rather than anything to do with iOS.  Is that UA correct for the iOS version?

EDIT: Turns out the two letter code at the end of the UA indicates the platform.  Unfortunately no platform version exists. This might not matter as it seems like the page is cloud rendered. May actually be Chrome 30.

**Comment by kaelig** [comment]
Puffin's UA looks completely made up and isn't synced with the iOS version (8.3). The simplest way to get it to work might be to send them a bug report.

**Comment by samgiles** [comment]
PR updated to strip `OPiOS`.  Any further issues related to CriOS or OPiOS specfically, report in the PR or open a new issue.

**Comment by samgiles** [comment]
Updated master to support CriOS and OPiOS.   Puffin and friends may remain, let's open issues on a case by case basis.
