### ISSUE TITLE
Nokia N9 UA unsupported

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#417]
### Steps to reproduce
- Open https://cdn.polyfill.io/v1/polyfill.min.js
- Spoof user agent to: `Mozilla / 5.0 (MeeGo; NokiaN9) AppleWebKit / 534.13 (KHTML, like Gecko) Nokia Browser / 8.5.0 Mobile Safari / 534.13`
- Reload the page

**Comment by triblondon** [comment]
Can't find anything definitive on the subject.  Nokia browser for symbian (versions up to 8.3) seems to be based on webkit.  8.5 is cited here.  Interestingly our normalisation engine describes it as `nokia/9`, picking up on the `NokiaN9` bit.

If we go with the webkit version, then the best equivalent is Safari 5.  But I would be happy to just not support polyfilling this browser.  Let's leave this one to implement if/when we support client-side detects.
