### ISSUE TITLE
Make it possible to import core-js

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#421]
https://github.com/zloirock/core-js is a remarkably complete and modular collection of polyfills maintained by @zloirock.  They use commonjs to import dependencies.  It would be good to extend the ideas we started working on in #410 (first proposed in https://github.com/Financial-Times/polyfill-service/pull/410#issuecomment-113134056), so that polyfills with varying but common interfaces can be recognised and built by the polyfill service.

@zloirock are you interested in supporting this?  In short the purpose of our service is to automatically polyfill only features that are missing in a particular user-agent.

**Comment by JakeChampion** [comment]
A PR for this work is at https://github.com/zloirock/core-js/pull/88

**Comment by zloirock** [comment]
I watch your project. One day we were discussing the possibility of adding `core-js` to `polyfill-service` in gitter - it's required only commonjs build step. [This idea](https://github.com/Financial-Times/polyfill-service/pull/410#issuecomment-113134056) LGTM.

**Comment by zloirock** [comment]
Any news about adding commonjs build step?

**Comment by maxnordlund** [comment]
I also would like to know the status of this. How's it going? What needs to be done in order for this to work?

**Comment by triblondon** [comment]
We need a `build.module` property added to config.json so that a module can specify it has a commonjs interface and be built appropriately.  I'm not sure whether we would need to go as far as implementing require, or whether it's just a case of converting module.exports declarations into assignments to the appropriate global.

I don't have time to work on this right now but if anyone wants to do it, your starting point is the buildsources task.

**Comment by JakeChampion** [comment]
Initial work on this - https://github.com/Financial-Times/polyfill-service/pull/568

**Comment by maxnordlund** [comment]
Lovely, it would be a very welcome addition I think if you could pull it off.

**Comment by JakeChampion** [comment]
Here is the latest version -- https://github.com/Financial-Times/polyfill-service/pull/585 -- code reviews welcome!

**Comment by Gheoan** [comment]
Using `core-js` as polyfill would be awesome. :+1:

**Comment by jonathantneal** [comment]
:+1: the work so far looks great

**Comment by JakeChampion** [comment]
core-js is a large polyfill and not really sensible to import only a part of it's feature set due to size. If all of core-js' polyfills were included in polyfill-service I think then the size trade-off may be worth it for more robustly tested polyfills. The reasoning behind why the size doesn't matter as much when we include all the polyfills is because many of them require the same modules, which will get bundled together, keeping the size from growing too large.

**Comment by triblondon** [comment]
This work depended on supporting a commonjs build step, which [caused significant problems](https://github.com/Financial-Times/polyfill-service/pull/744). We don't have any plans to support commonjs right now, and there is also the issue of core-js compatiblity issues with other libraries (see [lodash](https://github.com/lodash/lodash/commit/e156459176c1f35964fc443b39f04c4cb0a96763#comments)) which suggests it would be a risky move to push it as a polyfill solution.  Let's close this.
