### ISSUE TITLE
v1.5.0-rc.1 is now on QA

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#430]
[Release notes](https://github.com/Financial-Times/polyfill-service/releases/tag/v1.5.0-rc.1) are available.

[Merged pull requests](https://github.com/Financial-Times/polyfill-service/pulls?q=is%3Apr+milestone%3A1.5+is%3Aclosed) since previous version.

This is proposed as a MINOR release, so there should be no backwards incompatible API changes.  Please test with your project and post here if you find one.  The RC will be available for testing for at least 1 week before I release a stable version.

**Comment by hannesj** [comment]
Would be nice to have a tarball (or even a version pushed to npmjs.com) that could be readily installed using npm. Now you have to run grunt buildsources, which doesn't fly really nicely with our automated deployment.

**Comment by JakeChampion** [comment]
@hannesj we were discussing today about publishing RC versions to NPM. You can track this work at https://github.com/Financial-Times/polyfill-service/pull/431

**Comment by hannesj** [comment]
@JakeChampion, thanks, will be looking forward to that.

**Comment by JakeChampion** [comment]
### New release - v1.5.0-rc.2 ([Changelog](https://github.com/Financial-Times/polyfill-service/compare/v1.5.0-rc.1...v1.5.0-rc.2))

This release fixes an issue with the `appVersion` key containing the wrong version.
It is now also available on NPM for testing.

/cc @hannesj

**Comment by triblondon** [comment]
1.5 is now live.
