### ISSUE TITLE
IE8 querySelectorAll invalid argument

### ISSUE THREAD

**Issue by roland-vachter** [polyfillpolyfill/polyfill-service#432]
For the following statement, the polyfill of querySelectorAll throws the "Invalid argument" error:

``` javascript
document.querySelectorAll("li > a:not([href])") 
```

It is valid with the native function, or at least it doesn't fire an error.

**Comment by AlbertoElias** [comment]
The `:not` selector isn't supported in IE8 I believe, so there's probably not much you can do there except for finding another selector which does work nicely in IE8. We removed our `:not` selectors in Origami modules

**Comment by roland-vachter** [comment]
Ah ok. I just realized that querySelector is partially supported in IE8 and it's not polyfilled (if my assumption is correct).

**Comment by AlbertoElias** [comment]
It is not polyfilled, no

**Comment by roland-vachter** [comment]
Ok, thanks for the clarification.
