### ISSUE TITLE
"Polyfill source" links in docs don't work for Array methods

### ISSUE THREAD

**Issue by ShimShamSam** [polyfillpolyfill/polyfill-service#436]
The link for Array.from takes me to:
https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/Array.from

But the correct link is:
https://github.com/Financial-Times/polyfill-service/tree/master/polyfills/Array/from

**Comment by triblondon** [comment]
Well spotted.  This will have been introduced when we reorganised the repo, changes which haven't been published yet, so the live app lags behind the state of the repo.  Should resolve itself with the release of 1.5.

**Comment by triblondon** [comment]
Actually come to think of it (and look at the actual code) this does need a fix.

**Comment by triblondon** [comment]
Fixed by https://github.com/Financial-Times/polyfill-service/pull/458
