### ISSUE TITLE
Placeholder polyfill not present for IE9.

### ISSUE THREAD

**Issue by ghost** [polyfillpolyfill/polyfill-service#443]
The Element.prototype.placeholder polyfill is not being loaded for IE9 when using either of the following URLs:

https://cdn.polyfill.io/v1/polyfill.js
https://cdn.polyfill.io/v1/polyfill.js?features=default,Element.prototype.placeholder

I expect the first one doesn't load as it isn't a default polyfill but when including it in the features list it still does not load.

When using the "always" flag the polyfill then loads correctly.

https://cdn.polyfill.io/v1/polyfill.js?features=default,Element.prototype.placeholder|always

**Comment by JakeChampion** [comment]
Confirmed via [user agent query string override](https://cdn.polyfill.io/v1/polyfill.js?features=Element.prototype.placeholder&ua=Mozilla/5.0%20%28Windows;%20U;%20MSIE%209.0;%20WIndows%20NT%209.0;%20en-US%29)
