### ISSUE TITLE
Intl support for Firefox OS/Mobile

### ISSUE THREAD

**Issue by kennethaasan** [polyfillpolyfill/polyfill-service#449]
Hi,

Just wanted to let you know that Intl polyfill isn't provided for Firefox OS/Mobile browser. Have to add "|always" to get it working.

Best regards,
Kenneth

**Comment by samgiles** [comment]
Hey, is it possible to let us know which version of FxOS you're on and what the user agent string is?

**Comment by kennethaasan** [comment]
Firefox OS 2.0
User-agent: "Mozilla/5.0 (Mobile; rv:32.0) Gecko/20100101 Firefox/32.0"

**Comment by triblondon** [comment]
That UA normalises to firefox/32.0.0. According to config for the Intl polyfill, it is only served to FF up to 28. If FFOS is using the FF32 engine, it's odd that it's not exhibiting the same behaviour as that version of FF.

We don't separately split out FFOS as a targetable browser, and probably won't as it will add a large maintenance overhead.  Perhaps someone from Mozilla can clarify what's going on here?

**Comment by wilsonpage** [comment]
Firefox OS should be no different to normal desktop Firefox. Can someone clarify what the issue is here?

**Comment by triblondon** [comment]
@wilsonpage hi Wilson.  Essentially, @kennethaa is saying that `Intl` is not available on FFOS 32, whereas MDN (and as a result, us too) say that it is, so we don't serve a polyfill to it.

**Comment by wilsonpage** [comment]
I just downloaded an [old Firefox 32 build](https://ftp.mozilla.org/pub/firefox/releases/32.0/mac/en-GB/) and `window.Intl` is defined. Not sure how to debug this any further; builds and releases aren't really my area of expertise :(

**Comment by wilsonpage** [comment]
To investigate this further I could flash a 2.0 version of FxOS and poke around. But Gecko _should_ be identical to desktop.

**Comment by triblondon** [comment]
Can the original author of this issue provide a specific build and screenshot of the test URL?http://cdn.polyfill.io/test/tests?feature=Intl

**Comment by kennethaasan** [comment]
I'll do that tomorrow.

**Comment by kennethaasan** [comment]
![screenshot from 2015-08-11 11 29 50](https://cloud.githubusercontent.com/assets/1437394/9194561/64494fc4-401c-11e5-8dd7-5d5d897ad7ca.png)
![screenshot from 2015-08-11 11 29 32](https://cloud.githubusercontent.com/assets/1437394/9194566/66f89680-401c-11e5-9d36-36700c8786aa.png)
![screenshot from 2015-08-11 11 28 25](https://cloud.githubusercontent.com/assets/1437394/9194623/df1412a2-401c-11e5-803e-2453a74bfae9.png)

I'm on the latest build.

**Comment by triblondon** [comment]
Looking for a screenshot of the test result, something like:

![image](https://cloud.githubusercontent.com/assets/1735391/9195306/c064c37c-4019-11e5-9ef0-0c973c457351.png)

Also are you using a particular device for this testing?  Maybe give us to FFOS build number?  I don't know what else to suggest - we can't target this polyfill at FF32 because Intl is supported by desktop FF 32.

**Comment by kennethaasan** [comment]
I'm using Firefox WebIDE with Firefox OS 2.0 that you can install on your computer to simulate Firefox OS. It's the same case with my friends Android phone with a Firefox browser.

![screenshot from 2015-08-11 12 55 41](https://cloud.githubusercontent.com/assets/1437394/9196099/50100d34-4028-11e5-89a6-76cc14a71776.png)

**Comment by triblondon** [comment]
So it does appear to pass the tests...

**Comment by eek** [comment]
Intl pollyfill doesn't work on:

`Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H141 Safari/600.1.4`
nor
`Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53`

:(

**Comment by triblondon** [comment]
@eek if those are iOS devices can you raise that as a separate issue?

**Comment by triblondon** [comment]
Closing this since it appears that the FFOS device is passing the Intl tests.  @kennethaa the screenshot you have with the error shows it occurring on line 11,331 - so in the absence of a reduced test case and with our own tests passing on your device we'll assume the fault is in your code. Feel free to reopen the issue if you can add a test to our test suite that fails under your conditions.
