### ISSUE TITLE
setImmediate() does not get polyfilled for iOS browsers

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#450]
Loading `features=setImmediate` [on an iPad](https://cdn.polyfill.io/v1/polyfill.js?features=setImmediate&ua=Mozilla/5.0%20%28iPad;%20CPU%20OS%207_0%20like%20Mac%20OS%20X%29%20AppleWebKit/537.51.1%20%28KHTML,%20like%20Gecko%29%20Version/7.0%20Mobile/11A465%20Safari/9537.53) or [on an iPhone](https://cdn.polyfill.io/v1/polyfill.js?features=setImmediate&ua=Mozilla/5.0%20%28iPhone;%20CPU%20iPhone%20OS%208_0%20like%20Mac%20OS%20X%29%20AppleWebKit/600.1.3%20%28KHTML,%20like%20Gecko%29%20Version/8.0%20Mobile/12A4345d%20Safari/600.1.4) gets you an empty polyfill bundle.

But iOS Safari (and also Chrome for iOS) do not have `setImmediate`.
- Demo: https://jsfiddle.net/jjw23346/4/ (visit on an iPad/iPhone)
  - includes https://cdn.polyfill.io/v1/polyfill.js?features=default,setImmediate
  - ...but hits error: `ReferenceError: Can't find variable: setImmediate`

**Comment by triblondon** [comment]
Looks like browser config is incomplete - https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/setImmediate/config.json.  Can you update, do a PR and check CI?

**Comment by callumlocke** [comment]
I already did, look above, PR #451

**Comment by triblondon** [comment]
whoops, didn't spot the xref.  Thanks.
