### ISSUE TITLE
Is there a polyfill of MouseEvent?

### ISSUE THREAD

**Issue by sarbbottam** [polyfillpolyfill/polyfill-service#453]
Is there a polyfill of MouseEvent? Thanks.

**Comment by callumlocke** [comment]
Not currently. I googled and couldn't find anything.

What do you need a MouseEvent polyfill for?

**Comment by sarbbottam** [comment]
I need to trigger/simulate mouse events (mousemove, mouseover, click) for unit testing my client side JS code.

I am currently using [this code](https://github.com/sarbbottam/accessible-dropdown/blob/master/polyfill/event.js#L29-L61) to address the cross browser compatibility (mainly IE).

I would like to drop this in favor of a library/module if already available, otherwise create one instead of copy pasting the same code across multiple repos.

**Comment by triblondon** [comment]
We'd welcome it.  You can find our contribution guidelines at http://cdn.polyfill.io/v1/docs/contributing
