### ISSUE TITLE
All array methods are "supported natively by IE6+" according to website

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#454]
Pretty sure there should be some blue boxes here. Unless I'm just very confused.

http://polyfill.webservices.ft.com/v1/docs/features/

![image](https://cloud.githubusercontent.com/assets/250617/9096451/193b67c6-3bb5-11e5-88b6-98f9bbffb5aa.png)

**Comment by callumlocke** [comment]
a few more features that are suspiciously all-green:
- Date.now
- Event.focusin
- Element
- Date.prototype.toISOString

**Comment by triblondon** [comment]
That does look wrong.  I'll regenerate the compat data.

**Comment by triblondon** [comment]
Fixed in https://github.com/Financial-Times/polyfill-service/commit/700c9007826797fb3591461d713330a9e28e55d1

**Comment by callumlocke** [comment]
Website still has the problem – is this fix still awaiting deployment, or did it get fixed and then regress?
