### ISSUE TITLE
Support Microsoft Edge

### ISSUE THREAD

**Issue by adgad** [polyfillpolyfill/polyfill-service#455]
User Agent's from Microsoft Edge are currently unrecognized:
https://cdn.polyfill.io/v1/polyfill.js?ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/42.0.2311.135%20Safari/537.36%20Edge/12.10240

Bit of background to their odd UA string: http://blogs.windows.com/msedgedev/2015/06/17/building-a-more-interoperable-web-with-microsoft-edge/

**Comment by triblondon** [comment]
OK, no problem.  I'm going to give Edge the browser name `ie`, meaning "I am Edge".

**Comment by triblondon** [comment]
Fixed in https://github.com/Financial-Times/polyfill-service/commit/9257d34b891bb4b1c579c8dc13c705696226f6e3
