### ISSUE TITLE
Raise baseline to exclude older IEs, iOS, Safari, Android

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#456]
Quite a number of our polyfills are intended for IE6 and 7, and they are generating issues like https://github.com/Financial-Times/polyfill-service/issues/452.  The FT doesn't support these browsers for its own products, but does not want to be irresponsible in not dealing with issues with polyfills intended for older browsers that may be causing significant problems like the one above.

Given the usage of these older browsers (tiny), and difficulties in running tests on them, I propose we increase the support baseline of the polyfill service to exclude the following browsers that we currently support:
- IE: 6, 7
- Safari: 3, 4, 5
- iOS Safari: 3, 4, 5, 6
- Android: 2, 3

Caniuse reports that global usage of the above browsers combined is less than 0.5% of total traffic.

The impact of this change would be that we would serve empty files to these browsers, rather than the requested polyfills, and we would also remove any polyfills intended only for those browsers.  By doing this we are not suggesting that users on these browsers should be unsupported, but that a technique like "Cuts the mustard" should be used so that more advanced JavaScript features are only accessed in newer user agents.

**Comment by triblondon** [comment]
@samgiles to check that we're OK to set up a log drain from Fastly to FT splunk so that we can analyse the usage stats from our actual data.  Also @olizh do you have an opinion?  Does FTC use the service, and if so are you adopting the cuts the mustard technique for IE < 9 or do you still run JS in older browsers?

**Comment by jonathantneal** [comment]
I’m okay with this. I only ask that its done upfront and with due diligence in the reasons. It takes a lot of effort to support older browsers, and maybe we don’t have the devpower to pull it off. That’s fair.

Let’s not be cavalier with percentages. How many people is .5% in real life? For instance, when Wikipedia describes 0.69% of users being on older Android devices, that is like 109 million people.

It’s easy to lose touch of the numbers and forget these are people. So, if the numbers justify the cut, then all I ask if that we identify which people/regions will be most impacted. Then, if no one can step up to support those users, we know it can’t be done. And again, I think that’s fair, and I’d hope it does not require significant research into your usage statistics. I can look into browser usage, if that helps.

</my-two-cents>

**Comment by triblondon** [comment]
@jonathantneal Just to emphasise that I agree the 0.5% should not be ignored.  My argument is that it's inappropriate to serve JavaScript to those users, and therefore pointless trying to polyfill JavaScript features.

**Comment by vvo** [comment]
As for IE6/7 I think we can forget them yes.

**Comment by olizh** [comment]
@triblondon In FTC we do use polyfill service. In our previous experience using other origami components, we found that all IE versions, not just 6/7, have issues. So our policy is to treat all IE versions as potentially problematic, and display a big bold warning message to urge users to open our site in Chrome or FireFox. 

My point is that if a user is still using any version of IE now, he/she probably doesn't care about user experience.

**Comment by Rob-pw** [comment]
Unfortunately we know of customers using Safari 5.0, at present it doesn't seem as though the polyfills are included unless we specify 'always'. If the plan is to exclude ancient browsers entirely, at least provide an option to still try and supply polyfills.

**Comment by triblondon** [comment]
@Rob-pw if others are happy to help maintain them then that's fine, but there doesn't seem to be much enthusiasm for that, and if it's just me, I would be fine to just not run any JavaScript in Safari 5.

**Comment by JakeChampion** [comment]
Have we come to a conclusion on this issue?

**Comment by triblondon** [comment]
I think we take the plunge in 3.4 and drop IE 6, Safari 3 and Android 2. Maybe add something to the docs about cuts the mustard.

**Comment by triblondon** [comment]
See #687
