### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#460]
A release candidate of 2.0 is now available in npm and on qa.polyfill.io.

Release notes: https://github.com/Financial-Times/polyfill-service/issues?utf8=%E2%9C%93&q=milestone%3A2.0+

Major changes:
- Node API now async, returns Promises (backwards incompatible change)
- Support for `libVersion` in HTTP API removed, to allow for more frequent releases (backwards incompatible change)
- Support for Microsoft Edge
- Picture element (picturefill)
- Fix for documentation bug: "Browsers and features" matrix is now correct.
- Refactor to load polyfill sources asynchronously for improved memory efficiency
- Implement a local UA lookup cache rather than using the one in the useragent module for better memory efficiency
- Better segmentation of graphite metrics
- Update to Node 0.12, drop Promise polyfill
- Allow polyfill config to include opt-out for CI testing (avoid Intl locales slowing down CI)

**Comment by triblondon** [comment]
Bit of a delay on this while we sort out a memory use issue.  Memory use is climbing due to support for `libVersion` and caching of UA lookups.  A refactor is solving this and a new RC will be made shortly.

**Comment by triblondon** [comment]
RC2 is now on qa.polyfill.io

**Comment by MikaelStenstrand** [comment]
After installing RC2 via npm, it doesn't seem to work as a library anymore. I get the following stack trace

```
/Users/mste/Documents/dev/digitransit-ui/node_modules/polyfill-service/lib/sources.js:31
  throw Error("No polyfill sources found.  Run `grunt buildsources` to build th
      ^
Error: No polyfill sources found.  Run `grunt buildsources` to build them
  at Error (native)
  at Object.<anonymous> (/Users/mste/Documents/dev/digitransit-ui/node_modules/polyfill-service/lib/sources.js:31:8)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/mste/Documents/dev/digitransit-ui/node_modules/polyfill-service/lib/index.js:5:18)
  at Module._compile (module.js:460:26)
```

**Comment by triblondon** [comment]
Prepublish task might be broken, thanks for that.

Also have just realised that the async refactor has changed the Node API, so we'll need to make this a 2.0 release.

**Comment by triblondon** [comment]
2.0.0-rc.1 released.  This issue updated with latest release notes.

**Comment by triblondon** [comment]
Pushed to prod.
