### ISSUE TITLE
getComputedStyle not included by default for IE8

### ISSUE THREAD

**Issue by thednp** [polyfillpolyfill/polyfill-service#468]
I am sure this changed recently because I really had no problem with my code. 

Was it intentionally done or somebody slipped it?

**Comment by triblondon** [comment]
this polyfill has never been in the default set.  It's easy enough to check:

https://github.com/Financial-Times/polyfill-service/commits/master/polyfills/getComputedStyle/config.json

It's a fairly large polyfill, which is why it's not there by default.

**Comment by callumlocke** [comment]
@thednp you need something like:

https://cdn.polyfill.io/v1/polyfill.min.js?features=default,getComputedStyle

**Comment by thednp** [comment]
Thank you, I found in the API doc.
Thanks again.
