### ISSUE TITLE
Array.from on Chrome 44

### ISSUE THREAD

**Issue by phaistonian** [polyfillpolyfill/polyfill-service#469]
Though it's not supported in this version, the polyfill does not include this in the bundle.

Thank you.

**Comment by triblondon** [comment]
Confirmed, it became native in 45. Thanks @phaistonian.

**Comment by triblondon** [comment]
It looks like we currently target Array.from to all versions of chrome.  But it's not included by default, which is probably why you aren't getting it.  Treating this bug as the failure to _suppress_ the polyfill on Chrome 45, which does support the feature natively.
