### ISSUE TITLE
unknown=polyfill not working

### ISSUE THREAD

**Issue by scottb** [polyfillpolyfill/polyfill-service#473]
I use cdn.polyfill.io to polyfill the Promise and fetch features in my application. Now that Windows 10 is out and runs Edge by default, I started seeing a problem. When I use the following URL on Edge:

http://cdn.polyfill.io/v1/polyfill.min.js?features=Promise,fetch

I get a mostly empty script that has the comment "Unsupported UA detected: edge/12.10136.0". Looking at the docs, I see the default behavior for unsupported UAs is to _not_ polyfill the features. Ok, I can (sort of) understand that -- it could do unexpected things for large feature sets.

I see there's an "unknown" option that lets me override that choice, which should be fine for my two little features, but:

http://cdn.polyfill.io/v1/polyfill.min.js?unknown=polyfill&features=Promise,fetch

Gives me the same response - Unsupported UA detected.

I grabbed the UA string, made everything explicit, and dropped the minification:

http://cdn.polyfill.io/v1/polyfill.js?unknown=polyfill&features=Promise,fetch&ua=Mozilla/5.0%20(Windows%20NT%2010.0)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/42.0.2311.135%20Safari/537.36%20Edge/12.10136

Same response. So either "unknown=polyfill" doesn't do what I think it's supposed to (that is, handle the "unsupported UA" case by including the polyfill), or it's broken.

Unfortunately, I don't really have the resources to track down which it is.

**Comment by scottb** [comment]
I cloned the project and ran the latest code in dev, and it appears to do the right thing, there -- I assume that the problem really has to do with getting the live service at cdn.polyfill.io updated with the latest code (or whatever version included the detection of Edge).

Any ideas as to what the schedule might be for that, or must I give up on the site and run my own copy?

**Comment by triblondon** [comment]
The version you need is currently a release candidate on the QA CDN:

http://qa.polyfill.io/v1/polyfill.js?unknown=polyfill&features=Promise,fetch&ua=Mozilla/5.0%20(Windows%20NT%2010.0)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/42.0.2311.135%20Safari/537.36%20Edge/12.10136

However, we are pushing a major async refactor into this to sort out a memory issue, so there'll be another RC before we can go live.

**Comment by scottb** [comment]
Ok -- so when should I expect the RC, and how long does it usually take before it goes live?

I get that you need to test, and that Edge support isn't the only thing going on, here, but having no support for a browser that Microsoft is aggressively pushing makes it difficult to actually use the polyfill service in production.

**Comment by triblondon** [comment]
See https://github.com/Financial-Times/polyfill-service/issues/460

**Comment by scottb** [comment]
Thanks.
