### ISSUE TITLE
Firefox for Android Intl Polyfill

### ISSUE THREAD

**Issue by alicoding** [polyfillpolyfill/polyfill-service#477]
I'm running Firefox for Android on all version (Stable, Beta and Nightly) and getting this error

```
ReferenceError: Intl is not defined
```

When I curl I get this:

```
$ curl -H "User-Agent:'Mozilla/5.0 (Android 5.1.1; Mobile; rv:43.0) Gecko/43.0 Firefox/43.0" https://cdn.polyfill.io/v1/polyfill.js\?features\=Intl.\~locale.fr,Intl.\~locale.pt-BR
/* For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 *
 * UA detected: firefox/43.0.0
 * Features requested: Intl.~locale.fr,Intl.~locale.pt-BR
 * Library version: latest
 *  */

(function(undefined) {

})
.call('object' === typeof window && window || 'object' === typeof self && self || 'object' === typeof global && global || {});%
```

That User-Agent I copied from my Firefox Nightly request header.

**Comment by triblondon** [comment]
This has been raised before in relation to FFOS here: https://github.com/Financial-Times/polyfill-service/issues/449.  There seems to be something weird going on. I have FF38 handy, so I typed `Intl` in the console and it is definitely defined:

![image](https://cloud.githubusercontent.com/assets/1735391/9743833/435c9816-5660-11e5-8e1f-3b4e68e08fc2.png)

The response from the polyfill service is totally expected because we believe that Firefox supports Intl from version 29:

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Intl/config.json

**Comment by alicoding** [comment]
@triblondon This is actually Firefox for Android that I'm seeing the error, and not Desktop version.

**Comment by alicoding** [comment]
Looking at MDN for browser compatibility it also mentioned there that Firefox for Android it currently does not support `Intl` https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Intl

**Comment by samgiles** [comment]
Blocked by: https://bugzilla.mozilla.org/show_bug.cgi?id=864843

**Comment by alicoding** [comment]
Hey @samgiles thanks for the update.. Can you suggest any workaround in the meanwhile?? We are launching a Mozilla campaign in a few weeks and Firefox for Android expects to receive very high in traffic and it really depends on this library atm.

**Comment by samgiles** [comment]
At the moment Firefox for mobile is aliased as  "firefox": 

https://github.com/Financial-Times/polyfill-service/blob/master/lib/UA.js#L45

Would the project maintainers be willing to expand the baseline browser support to include Firefox for Mobile as is done for Chrome on iOS?

I could send a PR? :)

**Comment by triblondon** [comment]
Please do :-)

**Comment by alicoding** [comment]
Any update on this issue? What can I do to make this possible? I would love to help make a PR if anyone can guide me as to what exactly needs to get done? :)

**Comment by samgiles** [comment]
So I've had a quick look at this - to avoid duplicating all the config for `firefox` and `firefox_mobile` it seems to make sense to be able to use both if the UA is parsed as `firefox_mobile`. Is that something that would work or would you rather duplicate config?

**Comment by triblondon** [comment]
Hm, so are you suggesting that we recognise `firefox_mobile` as a separate UA, but apply `firefox` polyfills to `firefox_mobile` UAs as well?

If so, I don't like it :-)  Seems very arbitrary, and makes it a lot harder for newcomers to understand the matching logic.

**Comment by samgiles** [comment]
Duplicate config it is then :).
