### ISSUE TITLE
IE9 - Object doesn't support property or method 'trim' 

### ISSUE THREAD

**Issue by alicoding** [polyfillpolyfill/polyfill-service#478]
I'm doing some testing for my website to see if it works on IE9 > and seeing this error:

```
SCRIPT438: Object doesn't support property or method 'trim' 
polyfill.min.js?features=Intl.~locale.fr,Intl.~locale.pt-BR,Intl.~locale.de,Intl.~locale.id,Intl.~locale.es,Intl.~locale.en-US, line 3 character 275
```

Not sure why IE9 throw this since I have tested with https://cdn.polyfill.io/test/tests?feature=String.prototype.trim and all tests are passing?

**Comment by alicoding** [comment]
Any update/insight for this bug? The URL that I try this IE9 is https://donate.mofostaging.net

![bs_win7_ie_9 0](https://cloud.githubusercontent.com/assets/4368149/9995847/26e750da-6052-11e5-874b-c4ae50098284.jpg)

**Comment by triblondon** [comment]
There's a decent amount of script on that page.  Can you reproduce in a JSBin with just the polyfill service and a couple of lines of code to invoke the error?

**Comment by alicoding** [comment]
It turns out to be a very stupid problem with React here. I have to include this meta tag here for backward compatibility  http://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills

```
  <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
```

Added this and it just work O_o
