### ISSUE TITLE
Intl undefined IE8

### ISSUE THREAD

**Issue by donnrri** [polyfillpolyfill/polyfill-service#484]
Hi 

I must be doing something wrong but
I add   <script src="https://cdn.polyfill.io/v1/polyfill.min.js?features=Intl.~locale.en"></script>

I run my app in virtual box using Windows XP + IE envrionment.

I get the error windows.Intl undefined 

I use the following script in the same 

<html>
<head>

</head>
<body>

<script src="../../customercare/app/ie8/es5-shim.js"> </script>

<script src="https://cdn.polyfill.io/v1/polyfill.min.js"></script>

<script>
(function(){
console.log('  log Intl ---->  ' + window.Intl);
})();
</script>

</body>
</html>

Chrome is OK , IE8 Intl again undefined.  Any advice very gratetfully recieved

**Comment by donnrri** [comment]
Great cannot add code here !

**Comment by donnrri** [comment]
Its just a simple HTML file with the script tage for polyfill service and a script tag to console.log(window.Intl)

**Comment by alicoding** [comment]
Just tried this on BrowserStack with IE8 on Windows XP and it works for me 

Tried on this page
https://cdn.polyfill.io/test/tests?feature=Intl

**Comment by donnrri** [comment]
Thanks for you're reply. Yes, must be something strange with my set up.  Thanks for taking time to check
