### ISSUE TITLE
IE8 Object.defineProperty exception

### ISSUE THREAD

**Issue by doodlemoonch** [polyfillpolyfill/polyfill-service#490]
Including default and Intl on IE8, es5 shim seems to have the same [issue](https://github.com/es-shims/es5-shim/issues/249)
![screen shot 2015-10-07 at 10 58 51](https://cloud.githubusercontent.com/assets/213453/10334936/aa70e3d6-6ce5-11e5-8212-535fe8c71fb4.png)

**Comment by radum** [comment]
Yep, I started to have the same issue now, it was working Ok before.

**Comment by tp** [comment]
Can anyone say which specific version worked for you? Seeing the same error in es5 shim and here as well. If it ever worked there must be a "defineProperty" polyfill somewhere...

**Comment by triblondon** [comment]
Thanks for this issue report.  I'm happy to investigate, but to help me reproduce, could you give me a reduced test case, ideally in a jsbin.com bin?  The bin should include the polyfill service script tag that you are using, and either no other code or the minimum amount of code needed to trigger the error.

**Comment by JakeChampion** [comment]
That's an intentional error being thrown. This feature is not fully implementable as a polyfill and as such we throw an error when the behaviour being requested is not possible. I would advise wrapping your code in a try/catch.

**Comment by triblondon** [comment]
Ah yes, looking at the screenshot, that's an error we're throwing on purpose.  Unfortunately IE8's devtools doesn't show you the text of the exception message!  I have added a note to our docs to warn people about this (#681).
