### ISSUE TITLE
Why events trigger so slow in IE8?

### ISSUE THREAD

**Issue by thednp** [polyfillpolyfill/polyfill-service#492]
I'm testing the both v1 and v2 versions of the polyfill service and want to report that IE8 is very slow on clicks and scrolls, I think they're all affected.

I also experienced this on virtual machine testing with actual IE8.

Anyone confirm that?

**Comment by triblondon** [comment]
@thednp sorry we didn't reply to this at the time.  To look into it we ideally need some test cases - can you post some example code, ideally just including the polyfill service with a single polyfill, and a couple of lines of code to trigger the problem you want to demonstrate.

**Comment by thednp** [comment]
@triblondon it's really hard to go back in time and find the ideal test case. The thing is I cooked my own polyfill I need for my needs and runs alot faster on IE8.

Basically I only remember `scroll` and `resize` events get slower when using this polyfill library compared to my own mini 5k polyfill lib called minifill.

I hope this helps.

**Comment by triblondon** [comment]
Ok, thanks, I appreciate it's hard to be more specific after so much time.  I think we would need to narrow this down to a specific polyfill to investigate further.
