### ISSUE TITLE
Polyfill source link broken

### ISSUE THREAD

**Issue by piuccio** [polyfillpolyfill/polyfill-service#495]
Hi, amazing project

On [this page](https://cdn.polyfill.io/v2/docs/features/) if you click on the burger icon, the last link, `polyfill source` links to https://github.com/Financial-Times/polyfill-service/tree/master/Users/andrew.betts/sandboxes/local/polyfill-service/polyfills/fetch

See that `Users/andrew.betts/...`, that seems wrong, and indeed when you click you get a 404

**Comment by triblondon** [comment]
Whoops, thanks for that.
