### ISSUE TITLE
Update fetch polyfill

### ISSUE THREAD

**Issue by piuccio** [polyfillpolyfill/polyfill-service#496]
Hi, amazing project again :grin: 

How do you guys keep polyfills up to date?
I'm including `fetch` but the version hosted here does not have `Response.ok` which is instead included in [github/fetch at this line](https://github.com/github/fetch/blob/11f0e9a7c3a8d3e1b8d90a083e43ef19d3de1f62/fetch.js#L278)

Is there some sort of automated process? Otherwise would it be possible to update it?

Thanks

**Comment by JakeChampion** [comment]
@piuccio There is a pull request that seems to be adding the functionality you are after - https://github.com/Financial-Times/polyfill-service/pull/494

**Comment by piuccio** [comment]
Thanks, I didn't notice that PR when I open this issue. Closing, I'll follow that PR.
