### ISSUE TITLE
Opera Mini support

### ISSUE THREAD

**Issue by kdzwinel** [polyfillpolyfill/polyfill-service#498]
Is Opera Mini supported? We use polyfill.io but I'm getting `localStorage` errors (which this browser does not support).

**Comment by triblondon** [comment]
Yes, we do identify opera mini as `op_mini`.  But I suspect the targeting of our polyfills is very incomplete.  Please do add the additional metadata that is needed to target the right polyfills at Opera Mini.

**Comment by triblondon** [comment]
Sent a quick note to Bruce Lawson.

**Comment by kdzwinel** [comment]
I'm not sure what metadata you are referring to, could you elaborate on that?

This is my minimal test: http://jsbin.com/rufasuc.

It fails (localStorage doesn't work) even thought polyfill.io script is included. Tested on Opera Mini Emulator (v8).

<img width="279" alt="opera mini localStorage" src="https://cloud.githubusercontent.com/assets/985504/10866149/61ce47ee-8023-11e5-9e23-3ccadabfb1b0.png">

**Comment by triblondon** [comment]
We only target localstorage at IE currently:

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/localStorage/config.json

I don't know if our LS polyfill is effective in Opera Mini, or what it would achieve. I would generally advocate not using JS at all in proxy browsers like Opera Mini.  But if the polyfill does work, feel free to do a PR to add opera mini targeting.

Contribution guidelines:
http://cdn.polyfill.io/v2/docs/contributing

**Comment by brucelawson** [comment]
Opera Mini doesn't support localStorage at the moment - because there is no "local"; everything is rendered on the server.

**Comment by kdzwinel** [comment]
Right, the question is if there is a way to pollyfil it on Opera Mini, e.g. using cookies. Or, maybe, load existing polyfill, so that a dummy localStorage object is created. It won't persist state, but it will prevent page from failing when some script tries accessing `localStorage`.

**Comment by brucelawson** [comment]
cc  @mathiasbynens

**Comment by mathiasbynens** [comment]
The polyfill seems to load just fine in Opera Mini and creates the global `localStorage` object correctly.

Let’s enable the polyfill in Opera Mini, as that prevents pages from failing in the case @kdzwinel mentioned. I’ll submit a PR.

**Comment by triblondon** [comment]
Closing this since we do support Opera Mini so that question seems well answered.
