### ISSUE TITLE
`closest` polyfill does not support SVGElementInstance

### ISSUE THREAD

**Issue by kdzwinel** [polyfillpolyfill/polyfill-service#499]
IE10 defines SVG nodes as SVGElementInstance. Unfortunately, `SVGElementInstance` does not extend `Element` and the `closest` polyfill (and probably others) attaches itself only to the `Element.prototype`.

**Comment by triblondon** [comment]
My reading of the spec suggests that `SVGElement` _should_ extend `Element` - is this a bug in IE or my misunderstanding of the spec?

**Comment by triblondon** [comment]
Closing on assumption that my read of the spec is correct and the polyfill is therefore spec-compliant where the IR behaviour is not.
