### ISSUE TITLE
Chrome 31 needs promise polyfill

### ISSUE THREAD

**Issue by jhiswin** [polyfillpolyfill/polyfill-service#501]
Chrome 31 doesn't support native Promise, and needs to be polyfilled.  It was added in Chrome 32.

*tested on BrowserStack and using 360safe browser in webkit mode (which is a clone of Chrome 31)

**Comment by jhiswin** [comment]
On an additional note, V8's native promise is known to be buggy:
https://code.google.com/p/v8/issues/detail?id=4162
And most recommend to just polyfill it regardless.  core-js, for example, always polyfills on Chrome.

**Comment by jhiswin** [comment]
After some more testing, it seems as if Chrome never gets polyfill Promise.  Really odd.

**Comment by triblondon** [comment]
Yes it does:
http://cdn.polyfill.io/v2/polyfill.js?ua=chrome/31&features=Promise

It's just not in the default set, because it's big.  See the docs to find out which polyfills are served by default.

**Comment by jhiswin** [comment]
@triblondon ah so it was deliberate because of size issues; I just kind of assumed Promise would be included by default
