### ISSUE TITLE
Move to browserstack

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#505]
We are finding sauce labs testing platform quite unreliable. Browserstack are keen for us to try their platform, so I'd like to create a task based on the tasks/saucelabs.js one that does the testing on browserstack.

The current Sauce task can be run with `grunt ci`

**Comment by triblondon** [comment]
An interesting example of running Browserstack on Travis here:

https://travis-ci.org/9ikhan/travis-browserstack-example

Looks like the tunnel is set up via shell commands, which is actually quite a nice separation of concerns, so potentially we could simplify the saucelabs.js task. I've not been able to find any docs that show how to use webdriver directly with browserstack though.

**Comment by JakeChampion** [comment]
We have moved CI to Circle CI and are no longer seeing SauceLab issues. Closing this issue, please re-open if you think there are other reasons to move to BrowserStack.
