### ISSUE TITLE
svg4everybody

### ISSUE THREAD

**Issue by jamesarosen** [polyfillpolyfill/polyfill-service#519]
I'd love to add support for [jonathantneal/svg4everybody](https://github.com/jonathantneal/svg4everybody) for SVG includes. If you're interested, I'm happy to work on a pull request.

The library does [its own user-agent checks](https://github.com/jonathantneal/svg4everybody/blob/243335bf6ad23e2a757ff2c49647523332682a3a/lib/svg4everybody.js#L56-L60) in code. But that means that I would need to ship the JS to every browser. I'd love to take advantage of polyfill-service's UA checking.

**Comment by triblondon** [comment]
Yes please.  @jonathan-fielding also mentioned that he was interested in working on this.

**Comment by jonathan-fielding** [comment]
Yes we need this, I was planning on looking at this but if you have already started let me know

**Comment by jonathan-fielding** [comment]
Ok got a lot of this done https://github.com/jonathan-fielding/polyfill-service/tree/feature/SVGExternalContent still working on the detect test though as the polyfill doesn't appear to have a feature test instead relies on user agent sniffing

**Comment by triblondon** [comment]
https://github.com/Financial-Times/polyfill-service/pull/531
