### ISSUE TITLE
IndexedDB

### ISSUE THREAD

**Issue by matthew-andrews** [polyfillpolyfill/polyfill-service#52]
Could I request that an IndexedDB polyfill be added (that uses WebSQL as an underlying storage tech if IDB is not available)?  [Perhaps - as it is quite big - one that is only added when it is explicitly requested, ie. http://polyfill.io/maybe/indexeddb ]

(The use case of the optional-ness of it would be just that such a polyfill is likely to be huge and [for most people] unwanted)

http://nparashuram.com/IndexedDBShim/

Also the [IndexedDB wrapper](https://github.com/jensarps/IDBWrapper) could be handy for 'smoothing over the differences' in IDB implementations across browsers.

**Comment by triblondon** [comment]
I don't think the FT needs this anymore.
