### ISSUE TITLE
Expose browser/feature support data as an API

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#532]
Polyfill service has inadvertently become arguably the most comprehensive and granular collection of browser feature support data on the web (caniuse, kangax’s compat tables, quirksmode and mdn all have annoying gaps in their knowledge). As it's a production level service it also has a strong built in incentive to maintain its comprehensiveness and accuracy

There’s also no good api for this information available anywhere else on the web AFAIK. How about exposing a new endpoint to make this data consumable as an API?

**Comment by triblondon** [comment]
I'd say we have just as many gaps if not more than datasets like caniuse.  I did have a brief email exchange with @fyrd last year but it didn't amount to any closer integration at the time.  I'll ping him again to see if he's interested in talking again.  I'm not convinced an API in the service makes sense, but using the data to enhance a more canonical dataset like caniuse definitely does.

**Comment by triblondon** [comment]
Sent Alexis an email but didn't get a reply.
