### ISSUE TITLE
Enable running of tests for a single polyfill

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#537]
It's an obstacle to contributing that one must run tests for the entire set of polyfills when most contributions will be for a single one. Would be really nice to be able to run `grunt test my-polyfill`

**Comment by JakeChampion** [comment]
I am currently looking into lowering the barrier to entry for adding polyfills to this service. This is a great feature request.

Would you expect the same sort of tasks as we currently have for testing? A quick task `grunt saucelabs:quick --polyfill my-polyfill`; A more comprehensive task `grunt saucelabs:ci --polyfill my-polyfill`; And a task to test against everything `grunt saucelabs:all --polyfill my-polyfill`

**Comment by JakeChampion** [comment]
In another pull-request (#538) I am trying to remove the need to add polyfills directly to this repository and instead have them be their own packages. What do you think to that idea? I'm thinking (hoping) it will make creating/submitting/updating polyfills easier for contributors.

**Comment by wheresrhys** [comment]
It would be great to have the ability to run the tests for a single polyfill in a local browser. That way a contributor can get very quick feedback on simple mistakes they've made (e.g. I had a syntax error). The simplest solution for this I can think of would be to write a wrapper around karma which would enable something like `grunt unit-test PageVisibility --browser Chrome`. This needn't be used at all as part of CI, but would be a handy dev tool

All your other suggestions above are also good for verifying a polyfill works cross browser, but having to run tests via saucelabs when developing a new polyfill from scratch slows down the time to find big mistakes in the code which would affect any browser.

Regarding the npm idea, I like that too. I think there's a case for polyfill service to have its own git organisation, with each polyfill it's own repo. That way infrastructure (the service) and content (the polyfills) can be separate.

**Comment by triblondon** [comment]
You can already run the tests for a single polyfill in a single local browser.  The thing I think you want to do is run a test on one polyfill using Sauce, right?

**Comment by wheresrhys** [comment]
Good. That's not documented though, is it?

**Comment by wheresrhys** [comment]
specifically, 'grunt dev' isn't mentioned in the contributing guide

**Comment by triblondon** [comment]
ok, I'll add it.  To run a test on a single polyfill, just load eg. `/test/test?feature=Promise&mode=targeted`
