### ISSUE TITLE
Intl is not defined for Firefox on Tablet

### ISSUE THREAD

**Issue by alicoding** [polyfillpolyfill/polyfill-service#540]
I got a report that Firefox on Tablet (Android) doesn't get polyfill for `Intl` similar issue that I reported while back for mobile version of Firefox.

```
Mozilla/5.0 (Android 6.0; Tablet; rv:42.0) Gecko/42.0 Firefox/42.0
```

This is the user-agent. The file is filed long ago on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1215247) but I don't think this will get done anytime soon anyway.

**Comment by JakeChampion** [comment]
@alicoding I can confirm the [polyfill does not load](https://cdn.polyfill.io/v2/polyfill.js?features=Intl&ua=Mozilla/5.0%20%28Android%206.0;%20Tablet;%20rv:42.0%29%20Gecko/42.0%20Firefox/42.0).

Here is how you can request the polyfill with that useragent explicitly set:
`https://cdn.polyfill.io/v2/polyfill.js?features=Intl&ua=Mozilla/5.0%20(Android%206.0;%20Tablet;%20rv:42.0)%20Gecko/42.0%20Firefox/42.0`

**Comment by JakeChampion** [comment]
It is being detected as Android 6.0.
The [polyfill table](https://cdn.polyfill.io/v2/docs/features/#Intl) does not show if it works on Android.
The [browsers the polyfill states it works with](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Intl/config.json#L2) does not include Android -- 

```
"ie": "<11",
"ie_mob": "10",
"firefox": "<29",
"opera": "<15",
"chrome": "<24",
"safari": "*",
"ios_saf": "*",
"firefox_mob": "*"
```

If Android was added to the list, it would work.

Until then, you can request to always returns the polyfill and have it behind a feature detection - this is achieved by adding `&flags=always,gated` to the request.

https://cdn.polyfill.io/v2/polyfill.js?features=Intl&ua=Mozilla/5.0%20(Android%206.0;%20Tablet;%20rv:42.0)%20Gecko/42.0%20Firefox/42.0&flags=always,gated

**Comment by alicoding** [comment]
@JakeChampion I'm wondering. If my `navigator.userAgent` is not equal to `Mozilla/5.0 (Android 6.0; Tablet; rv:42.0) Gecko/42.0 Firefox/42.0` should `Intl` be polyfill even if it exists in `this`?

**Comment by triblondon** [comment]
The issue here is misidentification of Firefox mobile as Android.  We use the [ua-parser](github.com/ua-parser/uap-core) module to identify browsers so this issue could be reported there.  Also Mozillians like @samgiles might be interested.

If this UA string were recognised as firefox mobile, we would serve the Intl polyfill to it.

**Comment by JakeChampion** [comment]
This has been fixed - https://cdn.polyfill.io/v2/polyfill.js?features=Intl&ua=Mozilla/5.0%20(Android%206.0;%20Tablet;%20rv:42.0)%20Gecko/42.0%20Firefox/42.0

**Comment by alicoding** [comment]
Thanks!
