### ISSUE TITLE
Window.requestAnimationFrame not served in default bundle to iOS6 Safari

### ISSUE THREAD

**Issue by laurieboyes** [polyfillpolyfill/polyfill-service#542]
Example user agent string: 

`Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25`

This is causing an issue in o-overlay on these devices: https://github.com/Financial-Times/o-overlay/issues/98

**Comment by matthew-andrews** [comment]
This line https://github.com/Financial-Times/o-overlay/blob/master/origami.json#L13 should mean that `o-overlay`'s demos work…  And consumers of any origami components should look at the polyfills they rely on and update their usage of the polyfill service

**Comment by laurieboyes** [comment]
This issue was due to the default webkit polyfill not being served to iOS Safari 6.0. This PR fixes the issue: https://github.com/Financial-Times/polyfill-service/pull/543
