### ISSUE TITLE
ES7 / ES2016 feature aliases

### ISSUE THREAD

**Issue by tracker1** [polyfillpolyfill/polyfill-service#545]
Would be nice to see `es7` as an alias for all es7 features that can be polyfilled.

Also, an `everything` or `kitchen-sink` option that includes all features that can be polyfilled (with pre-tests)... This would be more optimal for CDN usage as it could be more universally applied.

**Comment by JakeChampion** [comment]
Since the move from ES5/6/7 to ES5/2015/2016 I would imagine the alias being `ES2016`.

**Comment by triblondon** [comment]
There is already a kitchen sink alias, `all`.  I strongly recommend not using it - the bundle will be huge, including massive polyfills like `Intl` with every single language pack, and will also pick up all polyfills we add in future, even those for experimental features where standards are not yet stable.

Renaming to focus on the es7/es2016 alias - happy to have this, feel free to add it!

**Comment by JakeChampion** [comment]
I think this issue has been resolved and can be closed.

There were two additions to the spec with ES7/ES2016:
- [`Array.prototype.includes`](https://tc39.github.io/ecma262/2016/#sec-array.prototype.includes)
- [Exponentiation Operator](https://tc39.github.io/ecma262/2016/#sec-exp-operator)

We cannot polyfill the Exponentiation Operator and we have a polyfill for `Array.prototype.includes` which has the alias [`es7`](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array/prototype/includes/config.json#L3).
