### ISSUE TITLE
Fails in IE 8 and 9

### ISSUE THREAD

**Issue by netsi1964** [polyfillpolyfill/polyfill-service#546]
I made a simple test page http://www.netsi.dk/Test-cdn.polyfill.io.htm and when I opened it in IE 8 and IE 9 errors occurred.

**Comment by triblondon** [comment]
Page not found.  Feed free to reopen with:
- Working link or URL of polyfill service bundle that you are using
- Details of what errors you see (a screenshot of the console would also be helpful)
- Exactly which version numbers of IE8 and 9 that you are testing.

**Comment by netsi1964** [comment]
Sorry for the death link, I left out a "l" in the url.
Here is the working link: [http://www.netsi.dk/Test-cdn.polyfill.io.html](http://www.netsi.dk/Test-cdn.polyfill.io.html)
