### ISSUE TITLE
`grunt build` fails on master branch when using Windows

### ISSUE THREAD

**Issue by Ikkyu-os** [polyfillpolyfill/polyfill-service#547]
I failed to install polyfill-service locally using npm install.

Basically, the script will start grunt build (as the doc' specifies), but it seems that most the files that should be in __dist\latest directory are missing.

Extract of log here: 
Running "buildsources" task
Loading sources...
{ [Error: ENOENT, no such file or directory 'D:\git_clones\openSource\polyfill-service\polyfills__dist\latest\Array\from.json']
  errno: -4058,
  code: 'ENOENT',
  path: 'D:\git_clones\openSource\polyfill-service\polyfills\__dist\latest\Array\from.json',
  syscall: 'open' }

I attached the full result of a grunt build in the issue.

[build.txt](https://github.com/Financial-Times/polyfill-service/files/65252/build.txt)

Could it be due to the fact that master CI build is failing on travis ? 
https://travis-ci.org/Financial-Times/polyfill-service

**Comment by triblondon** [comment]
Travis is broken due to issues tunnelling to Sauce Labs, unfortunately.

**Comment by triblondon** [comment]
I'll look into the build problem that you're having though

**Comment by triblondon** [comment]
Hm, I've never tried building on Windows, so maybe there's a path issue that doesn't work with Windows' filesystem.  I just confirmed that a fresh checkout of master builds fine for me.

**Comment by triblondon** [comment]
Can anyone reproduce this problem?

**Comment by Ikkyu-os** [comment]
Is there any way to add more logs to grunt so I could perhaps investigate which steps is actually failing and fix it ? 

Basically, it seems that \polyfills__dist\latest  is almost empty on my local. where all __dist\v1.0.X\ directories are properly populated.
Which process create those directories ?

**Comment by triblondon** [comment]
Take a look at the gruntfile for the build process.  Your problem is probably somewhere in the installcollections task, or possibly in buildsources.  Adding logs is just a matter of dropping grunt.log.writeln wherever you want to log.

**Comment by Ikkyu-os** [comment]
So i was able to investigate the issue and here's my findings.

When buildsources task is executed, it seems that polyfill subdirectories for "latest" version is not created, generating an error.

Attaching some logs (sorry for the poor debug trace skills)

``` bash
Running "buildsources" task
Loading sources...
debug - version = latest
debug - destFolder to create : D:\git_clones\openSource\polyfill-service\polyfills\__dist\latest
debug - scanDir complete for  : D:\git_clones\openSource\polyfill-service\polyfills
debug - featureName: Array\from
debug - detect: D:\git_clones\openSource\polyfill-service\polyfills\Array\from\detect.js
debug - polyfillSourcePath: D:\git_clones\openSource\polyfill-service\polyfills\Array\from\polyfill.js
debug - minify done
debug - featurePath: D:\git_clones\openSource\polyfill-service\polyfills\__dist\latest\Array\from.json
Error - something went wrong with feature Array\from
Error: Error: ENOENT, no such file or directory 'D:\git_clones\openSource\polyfill-service\polyfills\__dist\latest\Array\from.json'
```

If I manually create the directory __dist/latest directory does exists, however, the task somehow fails to create a directory for nested polyfill.
If I manually create the "Array" directory and run "grunt buildsources", then this polyfill (Array.from) is properly built. 
Polyfill which are not "nested" in subdirectories like AudioContext are properly built too. 

I'll need to investigate deeper to understand which part of the process create the polyfill subdirectories, and check if writeFileSync from fs library shouldn't create sub-directories itself.

**Updated:**
After looking a bit, I might have a fix.
I'll create a new branch & PR for this. However, I'll need someone to test it on a linux platform, as I unfortunately don't have one available currently.

I'm also looking forward the code review, as I am a beginner in node.

The fix consist in using mkdir() on the feature directory prior to invoking writeFileSync().
I'm not sure why this issue only appears on windows, as [filesystem doc](https://nodejs.org/api/fs.html) doesn't detail this behavior.

**Comment by Ikkyu-os** [comment]
PR https://github.com/Financial-Times/polyfill-service/pull/565 pending for fix validation :)

**Comment by triblondon** [comment]
Thanks for this - well done on the diagnosis. We refactored the polyfills directory for the 3.0 release to remove all the old versions of the library - so can you test master and rebase your PR on that if it's still needed?

**Comment by Ikkyu-os** [comment]
I did rebase from master, for now travis is not happy due to SauceLabs it seems. 
Not sure I can help with that, or if it's an issue to finalize the PR.

Build log: https://travis-ci.org/Financial-Times/polyfill-service/builds/100766606

**Comment by Ikkyu-os** [comment]
PR #565 has been merged. I guess we can close this PR now.
