### ISSUE TITLE
Unsupported UA detected

### ISSUE THREAD

**Issue by borisyankov** [polyfillpolyfill/polyfill-service#556]
UserAgent is 
"Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75 (5308056416)"

Is it possible to more gracefully handle unknown UAs? I am thinking providing a full polyfill set?

**Comment by JakeChampion** [comment]
You can provide the full polyfill set by adding the `unknown` query parameter with the value `polyfill` to the url. 

I.E. `<script src="https://cdn.polyfill.io/v2/polyfill.min.js?unknown=polyfill"></script>`

**Comment by borisyankov** [comment]
Thanks. That worked like a charm.
