### ISSUE TITLE
config.esversion -> config.build.?????

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#558]
For consistency with minify, but what should the property be?  Do we just want to indicate that a source probably needs transpilation in some cases?  In that case this would do:

```
config.build.transpile = true
```

However it might be that Babel needs to know more about how a source is constructed and what standards have been used.  In that case maybe:

```
config.build.transpileFrom = 'es2015'
```

**Comment by JakeChampion** [comment]
I don't know of any polyfills that require compiling to older ES environments. Do you have any you could link to?

**Comment by triblondon** [comment]
https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Math/acosh/polyfill.js

It's more the principle that it will be increasingly common in future

**Comment by triblondon** [comment]
Thinking more about this - the need to transpile is a property of the target UA's syntax support, not the polyfill source's use of particular syntax.  In theory, when you get a request from a UA that supports no more than ES5, you pass all polyfills that you intend to serve to that browser through a 'make sure this works in ES5' transpilation.  So the behaviour varies on the UA, not on the polyfill.

However, currently, we do the opposite: Transpilation depends on the properties of the polyfill, not the UA.  This is for two reasons:
1. We currently make an assumption that all browsers support ES5 and none support any syntax more advanced than that, so essentially there's no variation to be had between UAs.
2. Transpiling the majority of polyfills is unnecessary as their syntax is compatible with ES5, so doing so would slow down the build unnecessarily.

Point 1 can be expected to change at some point in future. But point 2 is an optimisation that we should avoid losing.  So a better implementation is probably something like `willTranspile = polyfill.esVersion > ua.maxEsSyntaxSupport.  On that basis we should stick to the current naming and location of the`esVersion` property.

Another option, theoretically more ideal, would have us able to use granular data on specific syntax support (eg from Kangax tables) and transpile only the specific features not implemented in the browser.  But that's likely to be fiddly, error prone and not worth it.

So on balance I think we stick with `esVersion` as it is and review again when we want to add a polyfill that requires more advanced transpilation.
