### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#578]
The polyfill service now helps thousands of sites play their part in upgrading the experience of users on older browsers. Main contributors are me and a couple of other FT developers, and none of us have any design skills.

Can someone make us a nice logo!?

Ideas for brief:
- encompasses a single vector image which can easily be rendered in SVG (though happy to consider wider font/colour scheme changes)
- works reasonably well with our simple documentation colour scheme (or changes it)
- embodies ideas like "upgrading", "magic solution", "community", "speed"
- fun?

I had the idea of a shiny rocket duck-taped to the roof of an old car. No idea if that would work.

**Comment by triblondon** [comment]
There's no budget for this, incidentally, and the resulting logo would need to be contributed to the project under an MIT or compatible licence.

**Comment by triblondon** [comment]
Suggestion from @ComedyTomedy:

![image](https://cloud.githubusercontent.com/assets/1735391/12373453/9384dc46-bc71-11e5-93ad-568ffd8bd161.png)

**Comment by triblondon** [comment]
Suggestion from Ross Mackay:

![image](https://cloud.githubusercontent.com/assets/1735391/12393387/4b9ba20c-bded-11e5-8a2a-c04b5ddabaf5.png)

(sadly probably ruled out by copyright issues, plus possibly a bit unfair on IE)

**Comment by JakeChampion** [comment]
Attempt: We could add some text onto this. I.E. "Polyfill Service".
![Logo](https://cloud.githubusercontent.com/assets/1569131/12398018/daa1d686-be08-11e5-8dc2-4e80178a0096.png)

**Comment by alexwilson** [comment]
Suggestion from @didoo - https://twitter.com/areaweb/status/690331988935450624 
![](http://i.imgur.com/HFycvwg.jpg)

**Comment by triblondon** [comment]
More from @didoo:

![image](https://cloud.githubusercontent.com/assets/1735391/12614574/b2968348-c4f8-11e5-9bae-7b512b68af71.png)

**Comment by triblondon** [comment]
I really like 'the missing element' as a strapline, but Jake's ill-fitting triangle is still my fav.

**Comment by seanmtracey** [comment]
:+1: on Jake's triangle.

**Comment by GeorgeBogdis** [comment]
Hi guys, here's an idea based on the Origami 'O' icon, turned to a 'P'. Cheers, g.

![screen shot 2016-02-16 at 15 11 49](https://cloud.githubusercontent.com/assets/8426017/13080195/8d6b7a52-d4bf-11e5-8431-45bd0336ad0e.png)

**Comment by jonathantneal** [comment]
I like the second origami "p" and the "pf" guitar pick.

**Comment by triblondon** [comment]
Chatted with George and he is going to play around with colour options for the second Origami P.

**Comment by GeorgeBogdis** [comment]
Hi guys, I've had another idea I wanted to try out, below, let me know what you think. Thanks, g.

![screen shot 2016-02-17 at 10 15 25](https://cloud.githubusercontent.com/assets/8426017/13106203/f2b9afe2-d55e-11e5-9fbc-328b953334ec.png)

**Comment by alicebartlett** [comment]
@GeorgeBogdis I like this latest one, it will work at lots of sizes, and in black and white, isn't too fussy. My favourite so far.

**Comment by didoo** [comment]
Agree, my fav too. Very well done!

**Comment by triblondon** [comment]
New idea:
![image](https://cloud.githubusercontent.com/assets/1735391/13265834/79ff1d76-dab8-11e5-833d-5379a77b4f00.png)

**Comment by JakeChampion** [comment]
I like that one Andrew. It's got my vote.

**Comment by alicebartlett** [comment]
@triblondon I like this.
Not sure I understand why the oranges are a different colour. 
I'd also lose the black outlines of the orange boxes, they're going to lead to weird antialiasing effects when this logo is used at smaller sizes. If your intention with them was to make them the logo legible to colour blind users then maybe a pattern could work instead of colours.
Generally though I like the concept.

**Comment by triblondon** [comment]
OK, we're going with the last one.
