### ISSUE TITLE
iOS Home Screen Web apps aren't detected as iOS Safari

### ISSUE THREAD

**Issue by seanmtracey** [polyfillpolyfill/polyfill-service#579]
#### Issue

Web apps pinned to the home screen and made web-app-capable with 
`<meta name="apple-mobile-web-app-capable" content="yes">`
do not get detected as iOS Mobile Safari despite being almost identical. As such, no polyfills are delivered to the browser.

Mobile Safari's UA is reported as:
`Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1`

Whereas the home screen web app UA is:
`Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75`

The only ommissions are `Version/9.0` and `Safari/601.1`, otherwise the strings are identical
#### Steps to reproduce
1. Create a simple web page
2. Add `<meta name="apple-mobile-web-app-capable" content="yes">` into the <head> of the page
3. Load the web page in Mobile Safari
4. Pin the page to the homescreen with the Safari UI
5. Go to the home screen and open the web app you've just pinned
6. It will open fullscreen, but no polyfills will have been delievred
#### Proposed solution

I think an approach similar to the one used in #561 would suitably fix this issue.

**Comment by triblondon** [comment]
Ah, this is pretty easy, by the looks of it.  We identify it as `mobile safari uiwebview`, so we just need to alias that to `ios_saf`.

**Comment by bdmac** [comment]
@triblondon can you tell me if this is live on the polyfill.io service yet? We are still seeing this happen as of today. I can't tell when you guys release updates or how to tie that back to this repo.

**Comment by JakeChampion** [comment]
@bdmac This is live.
 The way to tie live back to the repo is to visit http://cdn.polyfill.io/__about and look at the appVersion key, the value of this key is linked to a milestone on Github.

**Comment by bdmac** [comment]
A curl request with homescreen iPhone UA indicated an unknown device and resulted in unknown=ignore being invoked. I had to override that to unknown=polyfill to get this working. I tried this at the time of my previous comment so unless this went live literally in the last like hour then it isn't working properly still.

**Comment by JakeChampion** [comment]
@bdmac This works for me

https://cdn.polyfill.io/v2/polyfill.js?features=Intl&ua=Mozilla/5.0%20(iPad;%20CPU%20OS%209_2%20like%20Mac%20OS%20X)%20AppleWebKit/601.1.46%20(KHTML,%20like%20Gecko)%20Mobile/13C75

**Comment by bdmac** [comment]
@JakeChampion this does not work for me:

```
curl 'https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en,Intl.~locale.es,Intl.~locale.de,Intl.~locale.fr,Intl.~locale.it,Intl.~locale.pt,Intl.~locale.ru' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en,en-US;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13D15' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' --compressed
```

That is an exact request with the UA string passed from our app saved to my iPhone's homescreen and the result from that cURL request indicates `UA detected: other/0.0.0` and goes on to say using policy `unknown=ignore` (the default).

**Comment by JakeChampion** [comment]
Hmm, that UA works when sent via a query parameter:
https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en,Intl.~locale.es,Intl.~locale.de,Intl.~locale.fr,Intl.~locale.it,Intl.~locale.pt,Intl.~locale.ru&ua=Mozilla/5.0%20(iPhone;%20CPU%20iPhone%20OS%209_2_1%20like%20Mac%20OS%20X)%20AppleWebKit/601.1.46%20(KHTML,%20like%20Gecko)%20Mobile/13D15

The curl command you sent also seems to work for me.

![screen shot 2016-02-24 at 20 10 03](https://cloud.githubusercontent.com/assets/1569131/13299339/a8c6a67c-db32-11e5-904e-6f600cb3952e.png)

**Comment by bdmac** [comment]
That's so odd. I wonder if it's something with fastly?

## 

Brian McManus
CheckMate Co-Founder
