### ISSUE TITLE
Always doesn't always polyfill

### ISSUE THREAD

**Issue by markrichardsft** [polyfillpolyfill/polyfill-service#581]
When using Midori (default browser on Raspbian), nothing was being polyfilled even though always was requested: 

```
curl -L -H "User-Agent: Mozilla/5.0 (X11; Linux) AppleWebKit/538.15+ Midori/0.5" "https://cdn.polyfill.io/v1/polyfill.min.js?features=~html5-elements,Element.prototype.matches,Object.assign,requestAnimationFrame,Function.prototype.bind,Event,CustomEvent|always"
/* Rerun without minification (remove `.min` from URL path) for verbose metadata */
```

Midori is good for testing Webkit browsers as it often replicates some of the errors seen on mobile devices that use WebKit.

**Comment by JakeChampion** [comment]
If you remove `.min` from the request you get this returned:

```
/* For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: midori/0.5.0 (unknown/unsupported; using policy `unknown=ignore`)
 * Features requested: CustomEvent,Element.prototype.matches,Event,Function.prototype.bind,Object.assign,requestAnimationFrame,~html5-elements
 *  */
```

This shows that Midori is not a supported UA for the service and is treated as an unknown. Unknown UAs are not returned polyfills by default. You can add `unknown=polyfill` to return all polyfills requested for any UA which is unknown to the service.

E.G. [Midori request with unknown UAs polyfilled](https://cdn.polyfill.io/v2/polyfill.js?features=~html5-elements%2CElement.prototype.matches%2CObject.assign%2CrequestAnimationFrame%2CFunction.prototype.bind%2CEvent%2CCustomEvent%7Calways&ua=Mozilla/5.0%20%28X11;%20Linux%29%20AppleWebKit/538.15+%20Midori/0.5&unknown=polyfill) `https://cdn.polyfill.io/v2/polyfill.js?features=~html5-elements%2CElement.prototype.matches%2CObject.assign%2CrequestAnimationFrame%2CFunction.prototype.bind%2CEvent%2CCustomEvent%7Calways&ua=Mozilla/5.0%20(X11;%20Linux)%20AppleWebKit/538.15+%20Midori/0.5&unknown=polyfill`

**Comment by markrichardsft** [comment]
@JakeChampion thanks: what's recommended in this instance? I guess unknown=polyfill is best regardless?

**Comment by JakeChampion** [comment]
I'd recommend making an issue/pull-request to [uap-core](https://github.com/ua-parser/uap-core) to let the useragent module detect Midori successfully. Once the issue has been resolved in that project, we can then look into what polyfills should be served to Midori. If it is a version of Webkit, we could alias it in a similar manner to what we do for [Yandex](https://github.com/Financial-Times/polyfill-service/blob/master/lib/UA.js#L80).

Whilst all this work is yet to be done, you can choose to use `unknown=polyfill` but be warned that the polyfill being served will be rather large as we cannot assume any features are supported natively.

**Comment by JakeChampion** [comment]
Looking at this issue again it does seem we do recognise Midori, we however do not support it.

```
 * UA detected: midori/0.5.0 (unknown/unsupported; using policy `unknown=ignore`)
```

To enable support for Midori we require it to be defined in a polyfills `config.json`.
