### ISSUE TITLE
setImmediate() polyfilled when requesting "fetch" on Chrome 48

### ISSUE THREAD

**Issue by ithinkihaveacat** [polyfillpolyfill/polyfill-service#587]
On Chrome 48, the setImmediate() polyfill (only) seems to be emitted when requesting the "fetch" feature on Chrome 48:

``` sh
$ curl -s -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36' 'https://cdn.polyfill.io/v2/polyfill.js?features=fetch'
/* For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: chrome/48.0.0
 * Features requested: fetch
 * 
 * - setImmediate, License: CC0 (required by "Promise", "fetch") */

(function(undefined) {

// setImmediate
(function (global, undefined) {
    "use strict";
…
```

This is unexpected since `fetch()` itself is not polyfilled.

**Comment by JakeChampion** [comment]
@ithinkihaveacat This is because the [config for setImmediate](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/setImmediate/config.json#L3) is set to be included on everything except Internet Explorer 9 and above.

Thanks for spotting this. I'll be submitting a patch to fix this shortly.

**Comment by JakeChampion** [comment]
Thinking about this a bit more, it seems that dependant polyfills should not be included in the response if the actual polyfill is not required. This will take a bit longer to fix. I will submit a patch to restrict setImmediate for the time being.

**Comment by JakeChampion** [comment]
Patch for this is in https://github.com/Financial-Times/polyfill-service/pull/588

**Comment by triblondon** [comment]
Fixed by https://github.com/Financial-Times/polyfill-service/pull/618
