### ISSUE TITLE
how to make sure polyfill was loaded?

### ISSUE THREAD

**Issue by siddo420** [polyfillpolyfill/polyfill-service#589]
Is it possible to make sure polyfill was loaded?

The use-case is on Phonegap apps when an attempt will be made to load a local copy if the connection is down and script cant be loaded from CDN.

**Comment by siddo420** [comment]
Does polyfill (when loaded) makes sure it is not overriding already existing functions/methods/objects?

**Comment by triblondon** [comment]
You can use the `callback` query param to fire a function call when the polyfill bundle is loaded, and you can use the `gated` flag to wrap every polyfill in a feature detect
