### ISSUE TITLE
IE window.Event.prototype.stopPropagation.bind is broken

### ISSUE THREAD

**Issue by RobbieTheWagner** [polyfillpolyfill/polyfill-service#593]
I have tried IE9 and IE10 and for some reason `window.Event.prototype.stopPropagation.bind` is broken on both. "Unable to get value of the property 'bind': object is null or undefined" 

Anyone else seeing this?

**Comment by jonathantneal** [comment]
Since IE9 and IE10 support `addEventListener`, there is not any polyfilling of `stopPropagation` going on that I know of. Would you please setup a test page so I can recreate this myself?

**Comment by RobbieTheWagner** [comment]
@jonathantneal I made a JSFiddle that just includes the polyfill script and attempts to `console.log(window.Event.prototype.stopPropagation)`. Please check it out in IE9 and notice the error https://jsfiddle.net/0yo7eejL/

**Comment by RobbieTheWagner** [comment]
@jonathantneal can you please confirm you see the error?

**Comment by jonathantneal** [comment]
There is no polyfill for `stopPropagation` in IE9 because IE9 already supports `stopPropagation`. IE does not expose `stopPropagation` to `Event.prototype`. This is not an error in polyfill.io, it’s just how IE implements `stopPropagation`. I’m not certain what you are asking for.

**Comment by RobbieTheWagner** [comment]
@jonathantneal this is definitely a polyfill error. Please look at the JSFiddle I posted. If you run it in IE9, and include the polyfill script the `console.log(window.Event.prototype.stopPropagation)` will be:

 `undefined`

Then, if you remove the polyfill and run again, `console.log(window.Event.prototype.stopPropagation)` returns this:

```
function stopPropagation() {
    [native code]
}
```

This tells me that the polyfill is incorrectly blowing away the native handler from IE. Do you see what I mean?

**Comment by RobbieTheWagner** [comment]
For simplicity of your testing, just open up IE9 and load https://jsfiddle.net/0yo7eejL/3/ to see `window.Event.prototype.stopPropagation` work correctly, and then open the original fiddle to see it blow up with the polyfill included. https://jsfiddle.net/0yo7eejL/

**Comment by RobbieTheWagner** [comment]
Any updates on this? I assume you were able to see the error?

**Comment by triblondon** [comment]
@jonathantneal only dips into the project intermittently so may not get to this for some time.  If you have a suggested fix I'm happy to review.

**Comment by RobbieTheWagner** [comment]
@triblondon and @jonathantneal any updates?

**Comment by triblondon** [comment]
sorry, Jake and I are not looking at this at the moment. Contributions always welcomed though.

**Comment by RobbieTheWagner** [comment]
@jonathantneal any plans of looking into this or is it a won't fix?

**Comment by RobbieTheWagner** [comment]
@jonathantneal @triblondon is there any intent to investigate this at all? Please respond. If there is no intent to fix it, let's close this issue as won't fix. Anyone who uses `window.Event.prototype.stopPropagation.bind` will just have to not use this service.

**Comment by triblondon** [comment]
@rwwagner90 I've updated this issue several times in response to your chasing, and reminded you each time that you are very welcome to work on this.  If you can't solve the problem yourself you might also consider paying for a qualified developer to investigate and solve the problem for you.  This is one of the great advantages of open source software - anyone can be involved.

Meanwhile, it seems none of the core team is able or willing to help with this.  Personally, I simply don't have enough knowledge of the way event propagation is supposed to work, and my team is not affected by this problem.

**Comment by RobbieTheWagner** [comment]
@triblondon I am not familiar with the repo at all or I would dig into it. I am certainly not going to pay a third party to do it.

Please do not misunderstand my intent, I am perfectly fine with you closing as a won't fix, although it is inconvenient, since the whole point of a polyfill service is to get older and problem browsers working.

What I am not okay with, is this sitting open for years, and eventually being closed way later as a won't fix.

I'm just looking for a straight answer, and if there is not the manpower to fix it, I'd just like to know that, so we can look for alternative polyfills.

**Comment by triblondon** [comment]
OK, good luck.
