### ISSUE TITLE
Call polyfill.io by library name, with only features the library uses

### ISSUE THREAD

**Issue by LeaVerou** [polyfillpolyfill/polyfill-service#594]
Hi there! Thanks for creating this awesome service!

At [bliss.js](http://blissfuljs.com), we suggest to people to use Bliss with your service, for maximum browser coverage. However, we were faced with this dilemma:
1. Either we had to give people a huge URL of features that might even change with every release
2. or tell them to use `?features=all` despite the file size because 1 is a maintenance nightmare.

As you might have guessed, we went with 2. However, this means people are downloading a lot of polyfills they don't actually need.

Wouldn't it be awesome if they could call polyfill.io with a query string like `?libs=bliss,foolib,barjs` and get polyfills for the union of features needed by these libraries and nothing more?
Sure, it would be good if the registry included versions and all, but that would probably be a mess to maintain. Even if it's only the polyfills of the latest version of the library, it would be a huge improvement over using `?features=all`.

Pretty please? :)

**Comment by jonathantneal** [comment]
@LeaVerou, every polyfill comes with tags that let you narrow down what you’re looking to polyfill. For example, if I wanted to polyfill es5 features, I could use `https://cdn.polyfill.io/v2/polyfill.js?features=es6`.

To that end, it would be possible to tag the features you want with `bliss` and then recommend something like `https://cdn.polyfill.io/v2/polyfill.js?features=bliss`. What do you think?

**Comment by LeaVerou** [comment]
So I can send a PR with a tag of `bliss` and it would be merged? Didn't realize I could do that, thought tags were more restricted.

**Comment by jonathantneal** [comment]
There’s a great use case for tagging things as `bliss` (or `jquery2`), given the adoption of these libraries. There are tags for `modernizr` and `caniuse` as well.

@triblondon, would you :+1:  me accepting a PR for this?

**Comment by triblondon** [comment]
We call this concept **aliases** rather than tags, since an alias may just be another name for a single polyfill, but as Jonathan says it's also a great way to group together polyfill collections like es5, es6 etc.

Yes @jonathantneal go ahead and accept if a PR just adds aliases to existing polyfills, provided that Lea is happy to keep that alias up to date.

**Comment by triblondon** [comment]
Also I'd slightly prefer an alias of `bliss.js` rather than just `bliss` since bliss is a dictionary word that might conflict with other naming.

**Comment by LeaVerou** [comment]
What about `blissfuljs` since that's the npm module too?

**Comment by triblondon** [comment]
:+1:

**Comment by LeaVerou** [comment]
I’m working on the PR. Quick question: There's no way to include an existing alias (like `es5`) in an alias, right?

**Comment by jonathantneal** [comment]
@triblondon, has a deploy happened since PR #596? I still don’t see any polyfills when I hit https://cdn.polyfill.io/v2/polyfill.js?features=blissfuljs

**Comment by triblondon** [comment]
Not yet.  You can see the active CDN version at https://cdn.polyfill.io/__about under the `appVersion` property.

**Comment by LeaVerou** [comment]
Any ETA on when 3.3 will be deployed?

**Comment by triblondon** [comment]
Will try for this week.  Currently a bit busy moving to Japan, bear with me.

**Comment by triblondon** [comment]
OK, sorry for delay, moving continents turns out to be hard.

3.3 is now in QA: qa.polyfill.io, and I'm tracking the release to live at https://github.com/Financial-Times/polyfill-service/issues/625

**Comment by JakeChampion** [comment]
3.3 is now live :-)

**Comment by LeaVerou** [comment]
Awesome, thanks guys!
We have updated [Bliss’ homepage to suggest using this alias](http://blissfuljs.com/#browser-support).

**Comment by velum** [comment]
The path suggested on the Bliss homepage (https://cdn.polyfill.io/v2/polyfill.min.js?features=blissfuljs) does not output any polyfills...

**Comment by JakeChampion** [comment]
If requested in a modern browser then none of the polyfill for blissfuljs
are required.

If requested using ie9 you will get polyfills -
https://cdn.polyfill.io/v2/polyfill.js?features=blissfuljs&ua=ie/9
