### ISSUE TITLE
validate functions

### ISSUE THREAD

**Issue by Webnewbies** [polyfillpolyfill/polyfill-service#597]
*_Each created function must be conditional *_on the existence in the browser.
For example:

> String.prototype.includes = String.prototype.includes || function (//code..

..with that we made sure not to modify an existing function.

This is important.

**Comment by triblondon** [comment]
We provide detects for almost all our polyfills.  See the `gated` option in the docs.

**Comment by Webnewbies** [comment]
But in the latest versions of browsers (Safari 9.01, Chrome 48, Firefox 42, Opera 35, all MAC OS X) display functions that already exist in the browser. Show Element.prototype.closest, Object.assign and String.prototype.includes.
