### ISSUE TITLE
Support Array.prototype.fill

### ISSUE THREAD

**Issue by maximilianschmitt** [polyfillpolyfill/polyfill-service#600]
Would be great if support for Array.prototype.fill was included.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/fill
https://www.npmjs.com/package/array.prototype.fill

**Comment by jonathantneal** [comment]
@maximilianschmitt, awesome. I did not know about this one.

**Comment by triblondon** [comment]
Moving to the PR...
