### ISSUE TITLE
grunt test fails on windows

### ISSUE THREAD

**Issue by Ikkyu-os** [polyfillpolyfill/polyfill-service#604]
Hello

Windows user back again.
When using `grunt test` on my windows computer, on latest master branch, all tests fail, with the same generic Error:
`TypeError: undefined is not a function`

Complete logs attached.
[gruntTest.txt](https://github.com/Financial-Times/polyfill-service/files/123819/gruntTest.txt)

I'll have to debug this one to figure out what is missing in windows + git bash context.

If you have any starting point for this, will be appreciated :)

When this one will be fixed, I'll be able to resume https://github.com/Financial-Times/polyfill-service/issues/522

**Comment by Ikkyu-os** [comment]
Ok, so after debugging / checking the code in aliases.js issue was due to my local installation :( 

I was using an old version of NodeJS, 0.12 (was testing an old library not compatible with later versions on another project), which doesn't contain ES2015 methods such a Object.assign()

After upgraded on 4.3 version, I still have some errors on master, but this seem to be related to the polyfills themselves.

@triblondon  I assume nobody uses anymore Node < 4.0 except me, but should the readme provide a minimal version just in case ?

**Comment by triblondon** [comment]
Hey, sorry we broke your setup again :-(

Yes, we do have an engine specified in the travis file but not in package.json, which is where it probably should be.  Feel free to add it, or I'll get round to it at some point.
