### ISSUE TITLE
Promise polyfill includes setImmediate even if Promise is not needed

### ISSUE THREAD

**Issue by tschaub** [polyfillpolyfill/polyfill-service#605]
In Chrome 48, I'm seeing the `setImmediate` polyfill included when I request the `Promise` polyfill, even though the `Promise` polyfill [is not needed](https://github.com/Financial-Times/polyfill-service/blob/63b7f3ecdf0ce7a2b184ff7c0175c494f95c98f7/polyfills/Promise/config.json#L10).

Here's an example of the Promise polyfill request for Chrome 48: http://cdn.polyfill.io/v2/polyfill.js?ua=chrome/48&features=Promise

And the current response which includes `setImmediate` (unexpected) but not `Promise` (expected):  https://gist.github.com/tschaub/245f1a4cff18ebfb45c6

**Comment by triblondon** [comment]
#587
