### ISSUE TITLE
Specify engine in package.json

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#606]
Raised in https://github.com/Financial-Times/polyfill-service/issues/604

**Comment by Ikkyu-os** [comment]
I checked the .travis.yml file and the version specified is 5.0.0.

Should package.json reflect the same or can have a lower requirement? From what I saw build is working fine with 4.3. If I'm not too lazy, I could reinstall a 4.0.0 to check with this one too.

**Comment by triblondon** [comment]
We run with 5.0.0 in production, so I'd probably prefer to specify that.

**Comment by Ikkyu-os** [comment]
Ok :+1:
