### ISSUE TITLE
Polyfill build doesn't work correctly on windows 7

### ISSUE THREAD

**Issue by Ikkyu-os** [polyfillpolyfill/polyfill-service#610]
As discussed in Issue https://github.com/Financial-Times/polyfill-service/issues/522

The directory __dist is not built correctly during grunt build when used in Windows 7.
Instead of generating files from polyfill like this:

```
Object.method.json
```

It generates a directory with files

```
Object/method.json
```

This cause the polyfill-service to not detect those polyfills, and it doesn't serve them.
It is similar to other issues I faced on windows where directory were not created correctly, whereas it was working fine on linux.

**Comment by netsgnut** [comment]
Hi @Ikkyu-os, I have written a PR (#638) on that. Would you mind having a look and checking if that works for you? Thanks!

**Comment by triblondon** [comment]
Fixed in #610, thanks again to @netsgnut and @Ikkyu-os
