### ISSUE TITLE
Streamline releases & ci for changes in polyfill config files

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#616]
There are frequent gaps in the service's delivery of polyfills to minority browsers, and the fix for these is normally a line change or two in a json file. It's frustrating that releasing these changes has the same workflow as adding/changing a polyfill. Often the changes pertain to a browser which _isn't even included in the cross-browser testing_, so running the entire test suite actually provides no guarantee of the validity of the code change anyway.

It would be excellent if updates to polyfill config could be easier to roll out. I have one or two fairly rubbish ideas for how this could work, but thought I'd raise this general issue first for discussion of whether this is a problem that should be tackled.

**Comment by wheresrhys** [comment]
spoke to Jake, and various plans already in the pipeline (notably, move to browser stack and smart polyfill config) will make this issue melt away into nothingness

**Comment by triblondon** [comment]
Yeah, also @wheresrhys I would disagree that these kinds of changes require less oversight.  We serve 360 million requests a month, so it's important that we don't suddenly break some of those users browsers.

**Comment by wheresrhys** [comment]
I was thinking about smarter oversight. Something like
- diff with master
- if diff is restricted to config.json check which browsers are affected
- if covered by saucelabs, run the tests in that browser, if not, pass with a warning.
