### ISSUE TITLE
Allow search engine indexing of polyfill bundles

### ISSUE THREAD

**Issue by andresmrm** [polyfillpolyfill/polyfill-service#621]
It seems `cdn.polyfill.io` is blocking Googlebot, at least this is what Google Fetch said to me.
And on my case that caused my website not to be indexed at all.

I found a way around this [detecting Googlebot on the client](http://stackoverflow.com/questions/20084513/detect-search-crawlers-via-javascript) and serving a local polyfill.js for it.

I agree that according to "progressive enhancement" my website should my minimally working even without the polyfills, but I thought it would be good to share the problem here.

**Comment by triblondon** [comment]
Thanks for raising this. I hadn't appreciated that this would cause a problem for sites using the service. Our intention was just to avoid pointlessly indexing polyfill bundles, but if you need them for the site to be read by Google, I think that trumps it.

**Comment by andresmrm** [comment]
Thanks for the attention. =)

Well, maybe I'm a rare case... Feel free to judge if it's worth or not to allow search engine indexing.
