### ISSUE TITLE
ES6 Reflect and Proxy

### ISSUE THREAD

**Issue by philippevk** [polyfillpolyfill/polyfill-service#623]
It seems the Reflect API is missing from the polyfills (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect)

There is a good implementation here:
https://github.com/tvcutsem/harmony-reflect

Would it be possible to include it?

**Comment by triblondon** [comment]
Hi @philippevk, thanks for raising this and for the suggestion.  We are adopting a policy of not keeping feature-request issues open for long periods of time, if no-one seems keen to implement them, so this issue will be closed now.  Of course we always welcome contributions and that includes a contribution that adds this feature.
