### ISSUE TITLE
Add Web Streams as an optional polyfill

### ISSUE THREAD

**Issue by creatorrr** [polyfillpolyfill/polyfill-service#634]
WHATG has finalized the Web Stream [spec](https://streams.spec.whatwg.org/) along with a [working implementation](https://github.com/whatwg/streams). They are going to be shipping in browsers soon.

Thoughts on including the polyfill as an optional?

**Comment by triblondon** [comment]
Yes, that would be a great idea.

**Comment by creatorrr** [comment]
How does the process of adding a polyfill work? I am happy to make a PR.

**Comment by triblondon** [comment]
yes, see http://cdn.polyfill.io/v2/docs/contributing

**Comment by triblondon** [comment]
Thanks for raising this and for the suggestion. We are adopting a policy of not keeping feature-request issues open for long periods of time, if no-one seems keen to implement them, so this issue will be closed now. Of course we always welcome contributions and that includes a contribution that adds this feature.
