### ISSUE TITLE
Safari 9 errors when requesting Array.prototype.find|always with Intl

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#635]
Browser tested:
Safari 9

Operating system/version:
OS X 10.11.3

Steps to reproduce:
- Visit https://cdn.polyfill.io/v2/polyfill.js?features=Array.prototype.find%7Calways,Intl
- Copy the response of the body into the console and execute the code
  >TypeError: Object must be an object (Object.defineProperty polyfill)

The issue seems to be the combination of Object.defineProperty, Array.prototype.find, and Intl. When it is only 2 of the 3 being applied together no errors occur.

**Comment by caridy** [comment]
It is very likely that this is now fixed in Intl, considering the detection adjustments that we did recently.
