### ISSUE TITLE
Add a click polyfill for DOM elements

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#636]
PhantomJS is rather old and doesn't have a `click` method on the `HTMLElement.prototype`.

I've not thought about it for long but I reckon this is a viable polyfill:

``` js
HTMLElement.prototype.click = function click () {
  var click = document.createEvent("MouseEvent");
  click.initMouseEvent("click", true, true, window,0, 0, 0, 0, 0, false, false, false, false, 0, null);
  this.dispatchEvent(click);
};
```

**Comment by triblondon** [comment]
Looks OK.  MDN docs are https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click, though for some reasonn they've called it `HTMLElement.click` not `HTMLElement.prototype.click` (they've done this with other things too, and when I asked about it on IRC I didn't really understand the answer :-(

Write some tests and we'll add it.

**Comment by triblondon** [comment]
I might write these tests on a flight tomorrow.

**Comment by triblondon** [comment]
Never got around to this.  @JakeChampion why is this one [FT] ?  Is it still wanted by us?

**Comment by JakeChampion** [comment]
@AlbertoElias Wanted it for polyfilling PhantomJS' lack of a `click` method on DOM elements. I think we are in the middle of updating PhantomJS from V1 to V2, we might not require this anymore.

**Comment by AlbertoElias** [comment]
Yup, not necessary anymore
