### ISSUE TITLE
Wrongly polyfilling Object.assign on Chrome 49

### ISSUE THREAD

**Issue by buzinas** [polyfillpolyfill/polyfill-service#642]
Chrome 49 already has Object.assign natively, but if I open https://cdn.polyfill.io/v2/polyfill.js - for some unexplicable reason - the library changes the Object.assign native method.

Why is this happening? Isn't this an unexpected/undesired behavior?

**Comment by triblondon** [comment]
It looks like this polyfill just needs a configuration update.

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/assign/config.json

This is a very easy PR, why not give it a try?

http://cdn.polyfill.io/v2/docs/contributing

**Comment by buzinas** [comment]
Opened https://github.com/Financial-Times/polyfill-service/pull/657!

**Comment by buzinas** [comment]
Although this issue was merged/fixed/closed 20 days ago, the problem persists when I try to use the polyfill service cdn. What should I do? @triblondon @JakeChampion

**Comment by triblondon** [comment]
Your PR was assigned to the 3.4 release.  You can track that release here:

https://github.com/Financial-Times/polyfill-service/issues/666

**Comment by buzinas** [comment]
@triblondon Thank you! :)
