### ISSUE TITLE
Use HSTS

### ISSUE THREAD

**Issue by DavidBruant** [polyfillpolyfill/polyfill-service#646]
[https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security) upgrades an HTTP connection to an HTTPS one and tells the browser to remember that this domain should only be accessed via HTTPS.
This increases security and only costs something at the very first request to the domain.

HSTS is easy to implement on an express website using [helmet](https://www.npmjs.com/package/helmet).

Happy to make the contrib if there is an interest.

**Comment by triblondon** [comment]
Go ahead, thanks :-)

Just be aware that we don't (yet) support HTTPS on the apex domain, only on cdn.polyfill.io subdomain, for Fastly-related reasons.

**Comment by DavidBruant** [comment]
> Just be aware that we don't (yet) support HTTPS on the apex domain

I'm not sure I understand this part (and the consequences for adding HSTS support). What does "the apex domain" mean? (or what is it?)

**Comment by triblondon** [comment]
ah, sorry: apex domain means polyfill.io, vs cdn.polyfill.io which is a
subdomain. If you load http://polyfill.io, you get redirected to
https://cdn.polyfill.io. I'm happy to have HSTS apply to the latter.

**Comment by DavidBruant** [comment]
To answer your concern, I need an answer. I'll try to phrase the question as accurately as possible:
Is code from the Financial-Times/polyfill-service repo deployed under the polyfill.io domain? (is it this code that triggers the redirect). If yes, I'm not sure it's a good idea to add HSTS in the current circumstances. If both domains are even on the same physical machine, but handled by different code, then I feel confident HSTS won't affect polyfill.io.

Asked differently, is the code that redirects polyfill.io to cdn.polyfill.io under the current repository?

**Comment by triblondon** [comment]
OK, I understand. polyfill.io's redirect is not handled by the code in the repo - the response comes directly from our DNS provider.  This repo's code is used only to serve cdn.polyfill.io.  Basically, all I'm saying is that `includeSubDomains` should not be set in the HSTS header.

**Comment by DavidBruant** [comment]
> This repo's code is used only to serve cdn.polyfill.io

ok

>  Basically, all I'm saying is that includeSubDomains should not be set in the HSTS header.

I was not planning on including it. In any case, this wouldn't be a worry, since `includeSubDomains` would only apply to subdomains of `cdn.polyfill.io`, not `polyfill.io` (so it would apply to something like `blabla.cdn.polyfill.io`). But anyway, I won't apply it.

**Comment by JakeChampion** [comment]
The work for this is in #673 - please test and review

**Comment by JakeChampion** [comment]
Should we also discuss the possibility of auto-enforcing HTTPS connections using https://github.com/aredo/express-enforces-ssl ?

**Comment by DavidBruant** [comment]
> Should we also discuss the possibility of auto-enforcing HTTPS connections using https://github.com/aredo/express-enforces-ssl ?

Certainly. The [spec suggests](https://tools.ietf.org/html/rfc6797#section-5) that the header is considered only when received via HTTPS, so, a bootstrap can only happen if there is at least one HTTPS connection (then the browser remembering the STS policy will always go HTTPS even if asked HTTP).

You can also consider being added to the [preload list](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security#Preloading_Strict_Transport_Security) (but that should probably be a different issue regarding cdn.polyfill.io specifically, not this repo)

**Comment by JakeChampion** [comment]
Closing as HSTS is now live. Will create a new issue for discussing redirecting to https and adding to preload list.

**Comment by JakeChampion** [comment]
New issue for HTTP -> HTTPS - https://github.com/Financial-Times/polyfill-service/issues/677
