### ISSUE TITLE
Android 4.3 browser running on android 4.4 phone

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#653]
I have a samsung Galaxy note II whose UA string reports android 4.4.2 but webkit 534.30, which is the version [expected on Android 4.3](http://jimbergman.net/webkit-version-in-android-version/). Hence a lot of things that are needed don't get polyfilled on the device.

Some potential solutions

a) coerce all values of 4.3 for android in configs to  `<5` 
b) For android at least, clobber the OS version reported by the UA string if the webkit version is lower than expected.

@JakeChampion

**Comment by triblondon** [comment]
Doing (b) is supported as long as the browser identifies itself as something other than generic android.  What's the UA?  Related to https://github.com/Financial-Times/polyfill-service/pull/652

**Comment by wheresrhys** [comment]
Didn't fancy typing it all in, but it was pretty generic, android 4.4.2 and
WebKit 534.30, being the salient properties. I can try to get the full
string later

On Friday, 18 March 2016, Andrew Betts notifications@github.com wrote:

> Doing (b) is supported as long as the browser identifies itself as
> something other than generic android. What's the UA? Related to #652
> https://github.com/Financial-Times/polyfill-service/pull/652
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Financial-Times/polyfill-service/issues/653#issuecomment-198207474

## 

---

_This email was sent by a company owned by Financial Times Group Limited 
("FT Group http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law._

**Comment by triblondon** [comment]
Need the full string to debug useragent normalisation

**Comment by wheresrhys** [comment]
Will get the string ASAP to verify, but my gut feeling is the UA sniffing is fine; the problem lies in polyfill.io only making a distinction based on android OS version and ignoring the rendering engine

**Comment by triblondon** [comment]
That's part of the UA normalisation.

**Comment by dac09** [comment]
Hello,

I've encoutered the same problem with these user agents:

> Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-N910F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36
> 
> Mozilla/5.0 (Linux; Android 5.0.1; SAMSUNG GT-I9505 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36

I'm trying to polyfill Intl, but it returns nothing.

Thanks,
Daniel

**Comment by triblondon** [comment]
Those UAs report as samsung browser.  See #671

**Comment by aflatter** [comment]
@triblondon I'm seeing this with the following UA string, which appears to be a Galaxy Tab.

`Mozilla/5.0 (Linux; U; Android 4.4.2; de-de; GT-P5210 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30`

**Comment by aflatter** [comment]
Another two examples:

`Mozilla/5.0 (Linux; U; Android 4.2.2; de-de; HTC_OneXplus Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`
`Mozilla/5.0 (Linux; U; Android 4.2.2; de-de; GT-I8200N Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

**Comment by triblondon** [comment]
If you need to extend targeting of a polyfill to a browser we do not currently target, see https://cdn.polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers
