### ISSUE TITLE
TOS?

### ISSUE THREAD

**Issue by kentcdodds** [polyfillpolyfill/polyfill-service#663]
Hi there!
This is amazing! Thank you for building and hosting this. I'm planning on making a series of video lessons on the JavaScript bundler [webpack](http://webpack.github.io/) and the latest beta version which I'll be using for my series requires a promise polyfill. I'm planning on teaching people to use this service, but I'd really like to know whether this service will stick around for the long term. Is there a terms of service or any kind of guarantee that I can give people when recommending this service to them?

Thanks again!

**Comment by triblondon** [comment]
Hi Kent,

There are no TOS for the CDN, I'm afraid.  It's an at-will collaboration between the FT and Fastly, and could be withdrawn at any time.  That said, we have no plans to do so and are very happy that we're serving an increasing amount of traffic, in fact we're approaching 1 million requests per hour.

Providing some kind of availability assurance would require buy in from Fastly on that, and I'm meeting Artur in a couple of weeks so I will mention it.  Is your project an official PayPal thing?

Andrew

**Comment by kentcdodds** [comment]
Hi @triblondon!

> could be withdrawn at any time

Definitely a scary statement for anyone building a serious application leveraging this service!

> we have no plans to do so and are very happy that we're serving an increasing amount of traffic

:+1: I expect that if it were withdrawn suddenly, that wouldn't do anything for the Financial-Times or Fastly's images. So if something were to happen, I expect that there'd be some sort of migration strategy or something....

> we're approaching 1 million requests per hour

:open_mouth: wow, that's awesome

>  I'm meeting Artur in a couple of weeks so I will mention it

Yes please do!

> Is your project an official PayPal thing?

Nope, but maybe it should be!

My project is actually a video series that I'll be creating on [egghead.io](https://egghead.io/) about [webpack](http://webpack.github.io/) which requires a Promise polyfill to work. I'm also going to use this for a workshop I'm giving at a conference or two and for [Frontend Masters](https://frontendmasters.com/). Many people actually used webpack to conditionally load a Promise polyfill in the past and are now looking for a good way to conditionally include a Promise polyfill. I've used this service before and when I saw that you have polyfills for a bunch of APIs (promises included) I thought this would be a great solution to the problem.

So, if I can get some kind of assurance that I wont be teaching people to add a dependency on an unstable service, then I'll go ahead and do it!

Thanks!

**Comment by triblondon** [comment]
The best I can offer you is that the service is an active dependency of FT's own web products. If it goes down, ft.com breaks, amongst many other FT sites. I don't imagine the FT or Fastly would ever provide a contractual SLA on a service we are offering to the community for free, and we've no plans to charge for pro support.

I think the solution for people who have concerns here is really just run it yourself :-)

**Comment by kentcdodds** [comment]
In case you're interested, here's the lesson I was working on. Just published today :-) https://egghead.io/lessons/tools-polyfill-promises-for-webpack-2

**Comment by triblondon** [comment]
That's really cool and very concise.  I often find videos drag on but you cover the material at a perfect speed; love the attention to detail in the editing.  I tweeted a link to it.
