### ISSUE TITLE
Promise polyfill should be a part of es6 set

### ISSUE THREAD

**Issue by okonet** [polyfillpolyfill/polyfill-service#667]
https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Promise/config.json#L2

It looks like at the moment it isn't a part of `es6` set. Is there a reason for that?

**Comment by JakeChampion** [comment]
No reason, feel free to submit a PR with the change and I'll see that it gets merged :-)

**Comment by JakeChampion** [comment]
@okonet I've added Promise to the es6 set in #672 - please test and review :-)
