### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#677]
We now have HSTS #673 - however this is is only considered when a user visits HTTPS which means HTTP can still be used if the user never visits HTTPS. I imagine we can do this in a variety of ways such as adding [express-enforces-ssl](https://github.com/aredo/express-enforces-ssl) to our application server or possibly by adding a redirect inside the VCL on Fastly.

**Comment by triblondon** [comment]
Redirecting in Fastly would be the best method. I'll submit a PR and also add an on-deploy task to publish the VCL to Fastly.

**Comment by triblondon** [comment]
https://github.com/Financial-Times/polyfill-service/pull/682
