### ISSUE TITLE
get-own-property-symbols broken on IE11 - Can not use default features

### ISSUE THREAD

**Issue by ro-savage** [polyfillpolyfill/polyfill-service#679]
It appears the current polyfill service is using a old version of get-own-property-symbol, before a bug in IE11 was fixed. See [issue #8 of original repo](https://github.com/WebReflection/get-own-property-symbols/issues/8).

This is causing IE11 to throw an `Out of stack space` error for:

`https://cdn.polyfill.io/v2/polyfill.js?features=default`

**Comment by JakeChampion** [comment]
The fix for that issue was [applied in the polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/polyfill.js#L154). Could you supply a test case?

**Comment by ro-savage** [comment]
@JakeChampion 

This is our site that is currently broken on IE11: 
http://macvad.ap-southeast-2.elasticbeanstalk.com

It appears to me that it is dying as soon as it tries to run the polyfills. 

However, maybe something in our code is calling the polyfill and that is causing the issue?

**Comment by ro-savage** [comment]
Haven't been able to make a simple test case. I will update once I have a simple test case that causes the error. Thanks.

**Comment by ro-savage** [comment]
`https://cdn.polyfill.io/v2/polyfill.min.js?features=default` is breaking
`https://cdn.polyfill.io/v2/polyfill.js?features=default` is working

Thought it wasn't before. Nor sure what happened. Maybe corrupt CDN or... no idea. Git log had no changes and now its working after 3hrs of being broken.

Closing the issue.
