### ISSUE TITLE
Make an Origami alias resolver

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#68]
Add an alias resolver that, faced with a feature list such as:

```
polyfills.min.js?features=ft-origami:o-grid^2.0.0
```

would do the following:
1. Look up the module reference using the [Origami build service metadata API](http://origami.ft.com/docs/developer-guide/build-service/#get-modulesmoduleversion)
2. Use the `browserFeatures` section of origami.json to get feature names
3. Return those features, for subsequent alias resolvers

**Comment by JakeChampion** [comment]
@Financial-Times/origami-core @Financial-Times/origami-collaborators 

Is this still wanted?

**Comment by triblondon** [comment]
I'm keen on this because it will encourage component authors to pay better attention to the browserFeatures declarations in origami.json

**Comment by matthew-andrews** [comment]
The integration already exists the other way around — OBT will add the features listed in `browserFeatures` polyfill service to the demos.  I think that's probably enough incentive to list out the features.  Maybe enough to achieve the encouragement you're looking for already?

**Comment by triblondon** [comment]
That's a much better idea. And we're already doing it. Right.
