### ISSUE TITLE
Symbol polyfill doesn't function well with babel when using ES6 classes

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#690]
See https://phabricator.babeljs.io/T7335. I believe the fix should be on babel's side, but raising this issue here to save others the trouble of investigating

**Comment by JakeChampion** [comment]
@wheresrhys Are you getting this error with the latest version of the polyfill-service?

**Comment by wheresrhys** [comment]
probably not. Not tested recently though
