### ISSUE TITLE
Failed to load fetch polyfill on IE11+

### ISSUE THREAD

**Issue by motss** [polyfillpolyfill/polyfill-service#691]
### Description

Inserting `<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>` failed to load `fetch` polyfill on IE11 and above. 

However, `<script src="https://cdn.polyfill.io/v2/polyfill.js?features=fetch,Promise"></script>` did sort out the problem.
### Expected outcome

`fetch` API should be usable after loading the `polyfill.min.js`.
### Actual outcome

`fetch is undefined` was thrown at the console.
### Browsers Affected

- [x] Edge
- [x] IE 11

**Comment by JakeChampion** [comment]
I'm not sure fetch is in the default set of polyfills. The features in
[this table](https://cdn.polyfill.io/v2/docs/features/) which have a star
next to them are in the default set of polyfills you receive when
requesting cdn.polyfill.io/v2/polyfill.js

**Comment by motss** [comment]
@JakeChampion It makes sense. I didn't notice the star next to them.

**Comment by triblondon** [comment]
Also note that if you want the default set PLUS fetch, you can do `features=default,fetch`.

**Comment by MartinMuzatko** [comment]
Ugh. I didn't know that fetch wasn't included by default. Thanks for clarifying that.
