### ISSUE TITLE
Add Array.prototype[@@iterator]

### ISSUE THREAD

**Issue by callumlocke** [polyfillpolyfill/polyfill-service#692]
AFAICT, it's not possible to use the polyfill service to ensure that arrays are 'iterable' as per ES2015.

For an example of why this matters, look at how Babel compiles the following code:

``` js
const arr = [1, 2, 3];

for (const num of arr) {
  console.log(num);
}
```

The [compiled output](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015&code=const%20arr%20%3D%20%5B1%2C%202%2C%203%5D%3B%0A%0Afor%20%28const%20num%20of%20arr%29%20%7B%0A%20%20console.log%28num%29%3B%0A%7D%0A) includes the expression `arr[Symbol.iterator]()` which is likely to fail in old browsers (even if you've polyfilled Symbol and Array using the polyfill service).

---

I think something like this is needed:

``` js
// feature detect:
typeof Array.prototype[Symbol.iterator] === 'function'

// polyfill:
Array.protoype[Symbol.iterator] = function () {
  return new ArrayIterator(this);
};
// ...where `ArrayIterator` is something like this:
// https://github.com/medikoo/es6-iterator/blob/master/array.js
```

Let me know if interested in a PR.

**Comment by triblondon** [comment]
I haven't checked but I thought the Symbol.iterator polyfill covered that
use case.

**Comment by JakeChampion** [comment]
It doesn't. It creates the `Symbol.iterator` symbol but does not add it to any Objects' prototypes as that would go against our polyfill authoring guidelines.

**Comment by triblondon** [comment]
Ah yes, sorry, I remember the conversation about this now.  Jake and I couldn't work out how to create a polyfill for this - whether it belongs in the Array polyfill or in the Symbol one or in a dedicated `Array.prototype[Symbol.iterator]` polyfill (which I think might be an invalid name on the filesystem).

Not a great reason not to polyfill this though, and if we can agree on where it goes, we'd love a PR.

**Comment by callumlocke** [comment]
The spec uses [`@@name`](http://www.ecma-international.org/ecma-262/6.0/#sec-well-known-symbols) notation for well-known symbols.

Can we put this new polyfill in `polyfills/Array/prototype/@@iterator`?

And another one (slightly different implementation) in `polyfills/String/prototype/@@iterator`?

**Comment by JakeChampion** [comment]
I do prefer your approach to naming @callumlocke. The name of the polyfill doesn't matter too much.

As we are now adding more and more ES6/2015 polyfills, many of these polyfills require `Symbol` in some form or another. I think the biggest issue here is deciding when we include the polyfill. As @callumlocke has pointed out, `Array` and `String` make use of `Symbol.iterator`, should we include polyfills for these in the default set thereby allowing developers to start using ES6/2015 features without requiring them to construct a custom polyfill.io url?

**Comment by callumlocke** [comment]
I'm not 100% sure but I would lean towards including `Array/prototype/@@iterator` and `String/prototype/@@iterator` in the default set, and making them each depend on `Symbol/iterator`, which effectively adds the whole Symbol polyfill to the default set. This would add around 2.5KB to the default bundle size for browsers that don't support Symbol natively. That includes IE (pre-Edge), Safari < 9, iOS Safari < 9, Android < 9.1. (All the _latest_ major browser versions support Symbol natively.)

Just thought, does `@@name` notation present any problem in URL query strings? If so maybe it's better to use the `~name` style instead?

**Comment by triblondon** [comment]
If all the latest browsers support it, I'm completely in favour of chucking it in the default set.  I think Jake's polyfill is also really good and more people should benefit from it :-)

@callumlocke can you land this soon so we can ship it in 3.7?

**Comment by callumlocke** [comment]
Ah forgot about this. I'm a bit snowed under and won't be able to do this till Wednesday. When are you hoping to ship?

**Comment by triblondon** [comment]
No date for 3.7, but Wednesday is fine with me :-)

**Comment by JakeChampion** [comment]
This is now in QA.
