### ISSUE TITLE
Fake LocalStorage for iOS privacy mode

### ISSUE THREAD

**Issue by matthew-andrews** [polyfillpolyfill/polyfill-service#70]
Right now the FT app fixes broken localStorage implementations (eg. on iOS private browsing mode).  with a library called 'superstore' - https://github.com/matthew-andrews/superstore

Could there a way to deal with this via Polyfill?

**Comment by triblondon** [comment]
This cannot fulfil the requirements to be part of the polyfill library I'm afraid.
