### ISSUE TITLE
Intl polyfil and Safari 9.1.1

### ISSUE THREAD

**Issue by ying80** [polyfillpolyfill/polyfill-service#701]
I am having issue using Intl polyfil with safari 9.1.1.
It doesn't seem to work. 
`console.log( Intl );` -> undefined. No error. 
`console.log( new Intl.NumberFormat('en', {style: 'currency', currency: 'USD'}).format(1234));` also doesn't produce anything or error.

Including it like this on a blank page:
`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>`

**Comment by triblondon** [comment]
Hi @ying22.  Thanks for raising the issue. Please load this URL in the affected browser and tell us what the comment at the top of the output says:

```
https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en
```

**Comment by ying80** [comment]
```
/* Polyfill service v3.5.0
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: safari/9.1.0
 * Features requested: Intl.~locale.en
 * 
 * - Intl, License: MIT (required by "Intl.~locale.en")
 * - Intl.~locale.en, License: MIT */
```

My Safari is 9.1.1 (11601.6.17)

**Comment by ying80** [comment]
My bad, it works fine. I was testing this in the browser console instead of code.
