### ISSUE TITLE
requestAnimationFrame not polyfilling in Android stock browser

### ISSUE THREAD

**Issue by mdmoreau** [polyfillpolyfill/polyfill-service#704]
I've been getting inconsistent results with requestAnimationFrame being detected and loading in certain versions of the Android stock browser as part of the default set.  Specifying the property with |always fixes the issue, but otherwise I get a `Uncaught ReferenceError: requestAnimationFrame is not defined`.

A client reported JS not working properly on two Galaxy S5 devices running versions of Android 5 and 6, but the only place I've had a chance to test the problem/fix is the Galaxy S3 Android 4.1 emulator on Browserstack.  Not sure how useful that information is, but it's all I have to go on at the moment.  I'll post an update if I get any more information - figured it was worth passing my findings along.

**Comment by triblondon** [comment]
Thanks for reporting.  It sounds like an issue with some potential niche UA strings not being correctly identified as `android`.  To investigate we really need to get the raw UA strings that are being sent by the devices you believe are being wrongly classified.

And yes of course you can drop in the `always` flag as a workaround.

**Comment by mdmoreau** [comment]
This is the UA string I'm getting from the S3 emulator on Browserstack:

`Mozilla/5.0 (Linux; U; Android 4.1.2; en-us; sdk Build/MASTER) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

Not sure how useful that is since it's an emulator, but I'm working on getting the UA strings and errors from the actual devices as well.  Thanks for looking into this, and let me know if there's any other information that would help.

**Comment by triblondon** [comment]
That UA is detected as `android/4.1.0`.  It actually looks like the main problem is that we are not targeting Android:

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/requestAnimationFrame/config.json

To fix:

https://cdn.polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by mdmoreau** [comment]
It looks like that might solve the problem with the S3 emulator, but after getting some more data from the client it appears their issue was a separate one with Object.assign not being polyfilled in the S5/6.

The UA strings just about match those referenced in #509, and it sounds like #671 won't be merged in.  Happy to close this if that's the decision for now.  Appreciate all of the work on the polyfill - it's really come in handy recently!

**Comment by triblondon** [comment]
I just updated #509 with a suggestion for a maintainable solution, so if you can contribute there you might get a fix.  Also consider adding target config for raf on Android stock browser!
