### ISSUE TITLE
Redirect from http to https broken in IE

### ISSUE THREAD

**Issue by AlbertoElias** [polyfillpolyfill/polyfill-service#707]
In IE (tested on Browserstack and IE9 VM), when requesting a polyfill set via the http protocol, on the redirect to https, it breaks.

It redirects to: [https://cdn.polyfill.io/v2/normalizeUa?ua=Mozilla%2F5.0%20%28Windows%20NT%206.1%3B%20WOW64%3B%20Trident%2F7.0%3B%20rv%3A11.0%29%20like%20Gecko](https://cdn.polyfill.io/v2/normalizeUa?ua=Mozilla%2F5.0%20%28Windows%20NT%206.1%3B%20WOW64%3B%20Trident%2F7.0%3B%20rv%3A11.0%29%20like%20Gecko)

Which doesn't return anything.

Temporary fixes would be to revert PR #682 or revert the fastly config change. Users can also change the request to use https which will avoid the issue completely

**Comment by richtier** [comment]
seeing this on safari on iphone too.

to workaround for us was to hard code the request to `https://`

**Comment by triblondon** [comment]
Ouch, this is a serious issue. I'll hotfix this in VCL in the next 30 mins.

**Comment by triblondon** [comment]
Deployed to Fastly.

**Comment by triblondon** [comment]
@richtier sorry about this and thanks for reporting the issue.
