### ISSUE TITLE
TypedArray methods

### ISSUE THREAD

**Issue by dy** [polyfillpolyfill/polyfill-service#714]
Safari for iOS does not support some TypedArray methods, like `fill`, `slice`.
For now typedArrays, like `Float32Array` seem to be unpolyfilled.

**Comment by triblondon** [comment]
Happy to have a polyfill.  Can you submit one?

**Comment by dy** [comment]
The polyfill itself is trivial, it is just the entry barrier for FT polyfills is a bit too troublesome for me.
Literally just

``` js
if (typeof Int8Array !== 'undefined') {
    if (!Int8Array.prototype.fill) Int8Array.prototype.fill = Array.prototype.fill;
    if (!Int8Array.prototype.slice) Int8Array.prototype.slice = Array.prototype.slice;
}
if (typeof Uint8Array !== 'undefined') {
    if (!Uint8Array.prototype.fill) Uint8Array.prototype.fill = Array.prototype.fill;
    if (!Uint8Array.prototype.slice) Uint8Array.prototype.slice = Array.prototype.slice;
}
if (typeof Uint8ClampedArray !== 'undefined') {
    if (!Uint8ClampedArray.prototype.fill) Uint8ClampedArray.prototype.fill = Array.prototype.fill;
    if (!Uint8ClampedArray.prototype.slice) Uint8ClampedArray.prototype.slice = Array.prototype.slice;
}
if (typeof Int16Array !== 'undefined') {
    if (!Int16Array.prototype.fill) Int16Array.prototype.fill = Array.prototype.fill;
    if (!Int16Array.prototype.slice) Int16Array.prototype.slice = Array.prototype.slice;
}
if (typeof Uint16Array !== 'undefined') {
    if (!Uint16Array.prototype.fill) Uint16Array.prototype.fill = Array.prototype.fill;
    if (!Uint16Array.prototype.slice) Uint16Array.prototype.slice = Array.prototype.slice;
}
if (typeof Int32Array !== 'undefined') {
    if (!Int32Array.prototype.fill) Int32Array.prototype.fill = Array.prototype.fill;
    if (!Int32Array.prototype.slice) Int32Array.prototype.slice = Array.prototype.slice;
}
if (typeof Uint32Array !== 'undefined') {
    if (!Uint32Array.prototype.fill) Uint32Array.prototype.fill = Array.prototype.fill;
    if (!Uint32Array.prototype.slice) Uint32Array.prototype.slice = Array.prototype.slice;
}
if (typeof Float32Array !== 'undefined') {
    if (!Float32Array.prototype.fill) Float32Array.prototype.fill = Array.prototype.fill;
    if (!Float32Array.prototype.slice) Float32Array.prototype.slice = Array.prototype.slice;
}
if (typeof Float64Array !== 'undefined') {
    if (!Float64Array.prototype.fill) Float64Array.prototype.fill = Array.prototype.fill;
    if (!Float64Array.prototype.slice) Float64Array.prototype.slice = Array.prototype.slice;
}
if (typeof TypedArray !== 'undefined') {
    if (!TypedArray.prototype.fill) TypedArray.prototype.fill = Array.prototype.fill;
    if (!TypedArray.prototype.slice) TypedArray.prototype.slice = Array.prototype.slice;
}
```

**Comment by JakeChampion** [comment]
@dfcreative What are the issues you are having with contribution? I'd love to help smooth those out and make the experience better for new committers to the project.

**Comment by dy** [comment]
Just for the record: [typedarray-methods](https://github.com/dfcreative/typedarray-methods)

**Comment by JakeChampion** [comment]
The tests for that repository are rather lacking. I also believe that not all those Array methods are implemented by all browsers meaning we will need to include polyfills for those as well. I think we would require those polyfills to be included first before being able to bring in your TypedArray polyfill set.

**Comment by dy** [comment]
@JakeChampion exactly, tests there are irrelevant to polyfill, just minimal use-cases. As for methods - I guess it is possible to walk by existing `Array` methods to avoid including extra polyfill dependencies.
BTW not every browser has _TypedArray_ at all, there is [typedarray](http://npmjs.org/package/typedarray) implementation for that as well.

**Comment by triblondon** [comment]
thanks for raising this and for the suggestion. We are adopting a policy of not keeping feature-request issues open for long periods of time, if no-one seems keen to implement them, so this issue will be closed now. Of course we always welcome contributions and that includes a contribution that adds this feature.  If you need any help, please feel free to open a new issue and we'll do our best to assist.  We're also happy to hear any suggestions that would make contributing to the project easier.

**Comment by dy** [comment]
Just wonder - since now polyfill-library does not necessarily host polyfill code and can refer to external repositories - if there's a sense to include that?

**Comment by JakeChampion** [comment]
We do that already for TypedArray -- https://github.com/Financial-Times/polyfill-library/blob/65a860cb2246f182acad92abb47aefdcbaafae54/polyfills/_TypedArray/config.toml#L1-L38
