### ISSUE TITLE
Polyfill DOM iterators

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#718]
- [x] 'NodeList'
- [x] 'DOMTokenList'
- [ ] 'MediaList'
- [ ] 'StyleSheetList'
- [ ] 'CSSRuleList' 

should all be iterable.

**Comment by kaelig** [comment]
👍

**Comment by wheresrhys** [comment]
I'm going to take on domTokenlist and nodelist as they are the most useful cases and the easiest to write tests for

**Comment by wheresrhys** [comment]
https://github.com/Financial-Times/polyfill-service/pull/798 tackles DOMTokenList and NodeList

**Comment by JakeChampion** [comment]
@wheresrhys Are these all still needed by FT?

**Comment by wheresrhys** [comment]
NodeList was the only one we needed

**Comment by JakeChampion** [comment]
I will close this issue then and we can add these other polyfills if and when they are required.
