### ISSUE TITLE
Document#prepend duplicate

### ISSUE THREAD

**Issue by Mouvedia** [polyfillpolyfill/polyfill-service#720]
I was reading [an article](http://labs.ft.com/2014/09/polyfills-as-a-service/) on your blog and apparently I am getting `Document.prototype.prepend` twice. Is it perhaps a typo and the first one should be `append` instead?

browser:
Chrome Canary
user agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2751.0 Safari/537.36

```
    Document.prototype.prepend = Element.prototype.append = function() {
        this.appendChild(_mutation(arguments))
    };
    Document.prototype.prepend = Element.prototype.prepend = function() {
        this.insertBefore(_mutation(arguments), this.firstChild)
    };
```

**Comment by JakeChampion** [comment]
Thanks for spotting this, I've created a PR for this work over at #721.

**Comment by Mouvedia** [comment]
You should review the rest of the polyfills: it's probably not the only duplicate.
