### ISSUE TITLE
Symbol and Symbol.* polyfills are not provided for ie_mob/11.0.0

### ISSUE THREAD

**Issue by hannesj** [polyfillpolyfill/polyfill-service#727]
It seems that none of the recently added polyfills have been configured with support for IE mobile, even though they are needed also for the desktop counterparts?

**Comment by triblondon** [comment]
Sorry about that. I don't have IE mobile available for testing.  If you do, can you try it and add the appropriate configuration?

https://cdn.polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by triblondon** [comment]
Also @nolanlawson may have devices / support data to hand?

**Comment by nolanlawson** [comment]
Hm yeah, I see SauceLabs [doesn't have any Windows Phone or Windows 10 Mobile](https://saucelabs.com/platforms/) devices; that's too bad.

In general I can say that you can typically match the mobile version to its desktop counterpart (e.g. IE11 mobile ~= IE11 desktop, Edge 12 mobile ~= Edge 12 desktop), but of course it's always better to test these things.

@triblondon If you can point me to a live site or something where I can just open a URL on the phone and then give you the result afterwards, then I'd be happy to grab a few phones and do that for you. :)

**Comment by JakeChampion** [comment]
Live Symbol tests:
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.iterator
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.search
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.toPrimitive
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.match
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.species
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.toStringTag
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.hasInstance
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.split
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.unscopables
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.isConcatSpreadable
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol.replace
https://cdn.polyfill.io/test/director?mode=all&feature=Symbol

You can also visit https://cdn.polyfill.io/v2/docs/features/ and click the "Live test" radio input that is on the Features list table. This will given you the results for every feature we have within the service.

**Comment by nolanlawson** [comment]
@JakeChampion Is there some way I can send you the data after running the tests? (E.g. a global JS object or something?) Looks like I'd need to screenshot the whole page, which could take awhile.

**Comment by JakeChampion** [comment]
Yes, `globalresults` is the global results object.

**Comment by triblondon** [comment]
Even better if you can run the director without a feature filter (to test all features) with `mode=all` and `mode=control`.  This gives us results for native implementations and results after polyfilling.

The work that then needs to happen is to diff the two resultsets, compare to the existing config.json files and PR the necessary changes.

**Comment by nolanlawson** [comment]
Unfortunately it’s difficult for me to grab the `globalresults` object from a phone (haven’t figured out remote debugging yet), also at my immediate disposal I only have Insider builds… ^_^;;

Luckily I got approval to send y’all some phones, so hopefully those will be useful for you. If there are any versions that are still missing or you need more help, please get back to me and I’ll see if I can find the phone you need.

**Comment by triblondon** [comment]
I suspect if that's the case we'd have similar problems to you trying to programmatically extract results from the phone.  But I certainly won't say no to test devices.  I'm in Tokyo and my colleagues are in London, but probably best to send them to London.  I'll send you the details by email.

Meanwhile if you know the rough support data for those devices feel free to just send us a PR.  Over-polyfilling is not normally a problem and helps people out quickly.
