### ISSUE TITLE
Include polyfill by default if no browser config specified

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#731]
A large proportion of the issues raised on this project are of the form 

> polyfill X is not delivered in browser Y

and the solution is, more often than not

> add browser Y to the config for polyfill X

To avoid bugs it would be better to include a polyfill unless explicitly configured not to. On the other hand, this could lead to bloated bundles, but perhaps a cleverer method to audit this could be developed. e.g. `?reportRedundancy=true` could ping an endpoint with a tiny report of which polyfills are redundant. Even if next were the only site to turn this on the information gathered would be valuable

The use case that inspired this is `NodeList.prototype.@@iterator` - none of the usual compat tables etc seem to have any information on what supports it. Even firefox, which does support it, neglects to mention it in its release notes as far as I can see

**Comment by JakeChampion** [comment]
Could you write up a strawman proposal for `reportRedundancy`, I'm quite intrigued with that idea.

I think for the first part of this issue, configs missing browsers, we could add another query param to turn that on, much like the `unknown=polyfill` query param.

**Comment by triblondon** [comment]
Beaconing real-would detection stats was discussed as part of https://github.com/Financial-Times/polyfill-service/issues/366, and I'd be in favour of trying it out, strictly as an opt-in.

**Comment by triblondon** [comment]
The current issue is https://github.com/Financial-Times/polyfill-service/issues/107

**Comment by triblondon** [comment]
You've reignited my interest here so I'm posting a proposal over at #107.  I think the title of that issue better captures the problem so I'll close this one.
