### ISSUE TITLE
Extra polyfills being served to Microsoft Edge

### ISSUE THREAD

**Issue by nolanlawson** [polyfillpolyfill/polyfill-service#736]
Howdy! 👋

I noticed that some of the supported features of Edge 13 (Promise, Symbol) and Edge 14 (fetch) are getting polyfilled when querying the API. E.g.:
- https://cdn.polyfill.io/v2/polyfill.js?features=Symbol,Promise,fetch

In Edge 14, that returns all three polyfills, whereas in Firefox 49 and Chrome 53 it returns nothing. In Edge 13, we get all three as well, even though Symbol and Promise are supported. 

This seems like it might be an issue with the IE/Edge divide, because features that debuted in IE11 are correctly being omitted in all versions of Edge (e.g. Intl).

If there's anything we on the Edge team could do to help out, please let me know. 🙂 I took a look at the code, but wasn't sure of the best place to start tackling it.

(This is polyfill-service v3.6.1 and it says: `UA detected: ie/14.14366.0`.)

**Comment by triblondon** [comment]
Hi Nolan - thanks for raising this. Mistargeting is a common problem, and easy to fix.  We've posted instructions here:

https://cdn.polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

Basically, edit the config files such as [this one for Promise](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Promise/config.json), to adjust the browser targeting.

I would love to see more contribution from browser vendors like MS to the polyfill service.  We're currently just concluding a successful effort with Google to add a polyfill for IntersectionObserver, we're serving around 500m polyfills a month from our CDN service, and obviously there are many other features we could be polyfilling but don't as yet. If you like the way the service works and what we are doing we'd be delighted to welcome contributions from the Edge team.

**Comment by nolanlawson** [comment]
Ah cool! I didn't realize it was so simple. 😃 My understanding from the docs was that there was some automated service (SauceLabs etc.) that was generating the browsers-to-features matrix, but if it's just a config file then it's easy to contribute.

`polyfill-service` seems like a great project; would be happy to provide contributions from the Edge team. If Edge users are being served extra bytes they don't need, then that's impetus for us to step up and fix stuff.

**Comment by triblondon** [comment]
Automatic configuration has come up before and I do intend to implement it soonish, initially just as a mechanism for highlighting potential errors in the configuration, but maybe at some point to do the configuration automatically.  More info in https://github.com/Financial-Times/polyfill-service/issues/107

**Comment by nolanlawson** [comment]
Ah OK, thanks!
