### ISSUE TITLE
Testing Link on Website is Wrong

### ISSUE THREAD

**Issue by jambonrose** [polyfillpolyfill/polyfill-service#739]
The `Contributing > Testing` link in the lefthand navigation menu links to `https://cdn.polyfill.io/v/docs/contributing/testing` when it should link to `https://cdn.polyfill.io/v2/docs/contributing/testing` .

If you point me at the website repo, I'm happy to open a PR.

**Comment by triblondon** [comment]
This is actually already fixed in master - https://github.com/Financial-Times/polyfill-service/commit/0cfd3269df5b19b556fdd1fda0711a96355cad8f#diff-9196b807a42aa88966f3ce475292b219.  Thanks for pointing it out and sorry this got through.  Will be released in 3.8.

**Comment by jambonrose** [comment]
Whoops! Sorry about the false alarm.
