### ISSUE TITLE
Throw a descriptive error if the querystring is malformed

### ISSUE THREAD

**Issue by rowanmanning** [polyfillpolyfill/polyfill-service#745]
We're seeing a few malformed requests on QA which are throwing a not-very-descriptive error. I don't think this is a huge issue – we're still sending an error – but maybe it could be a little more descriptive?

To reproduce visit this URL, which uses JS-style arrays: http://ft-polyfill-service-qa.herokuapp.com/v2/polyfill.js?features=%5B%27default%2CrequestAnimationFrame%27%5D&excludes=%5B%27Symbol%27%5D

This could be fixed by checking that `excludes` is an array in [`service/routes/api.js` line 59](https://github.com/Financial-Times/polyfill-service/blob/master/service/routes/api.js#L59).

(For anyone with Sentry access: https://app.getsentry.com/nextftcom/polyfill-service-dev/issues/137403821/)

**Comment by triblondon** [comment]
https://github.com/Financial-Times/polyfill-service/commit/471ddf842dc4d672dbf3b09702d91b850d04e4b9
