### ISSUE TITLE
Intl not served for Blackberry 10

### ISSUE THREAD

**Issue by aflatter** [polyfillpolyfill/polyfill-service#748]
The Intl polyfill is not served for Blackberry 10, but it's necessary according to [caniuse](http://caniuse.com/#search=intl).

```
$ curl -A "Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.2876 Mobile Safari/537.35+" "https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.de,Intl.~locale.en&unknown=polyfill"
/* Polyfill service v3.7.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 *
 * UA detected: bb/10.3.0
 * Features requested: Intl.~locale.de,Intl.~locale.en
 *  */
```

**Comment by triblondon** [comment]
No problem.  See https://cdn.polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers for how to fix this.

**Comment by triblondon** [comment]
We don't have anyone stepping up to test this, and FT devs are not supporting blackberry devices with script, so closing.  If anyone wants this, please see #945 and do the testing to complete this work.
