### ISSUE TITLE
iOS 9.3.2 on iPod touch not recognized

### ISSUE THREAD

**Issue by aflatter** [polyfillpolyfill/polyfill-service#749]
Looks like user-agent-parser does not extract the iOS version here.

```
$ curl -A "Mozilla/5.0 (iPod touch; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69" "https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.de,Intl.~locale.en&unknown=polyfill"
/* Polyfill service v3.7.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 *
 * UA detected: ios_saf/0.0.0 (unknown/unsupported; using policy `unknown=polyfill`)
 * Features requested: Intl.~locale.de,Intl.~locale.en
 *
 * Version range for polyfill support in this family is: >=4
 *  */
```

**Comment by triblondon** [comment]
I updated us to the latest version of the useragent library and it is still parsing this UA as ios_saf 0.0.0.  If you replace the `iPod touch` token with `iPhone` it parses correctly, so I think this requires a PR to the ua-parser project.  This is the file that needs to be updated:

https://github.com/ua-parser/uap-core/blob/master/regexes.yaml

It looks like `ipod touch` is not a recognised token.  Could you push a PR there and to the useragent module?  I'm happy to pull a new useragent release as soon as it's updated.
