### ISSUE TITLE
Automatically purge homepage and documentation pages on deploy

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#751]
### Problem:

Currently when we deploy the application we require manually purging the cache for the website pages to show the correct version number and feature-set available. 
### Solution:

Add a post-deployment step to our task-runner which will purge the required pages from the cache.

**Comment by triblondon** [comment]
Endpoints to purge:

/v2/
/v2/docs/
/v2/docs/features/
/v2/docs/api/
/v2/docs/examples/
/v2/docs/usage/
/v2/docs/contributing/
/v2/docs/contributing/authoring-polyfills/
/v2/docs/contributing/testing/
/v2/docs/contributing/common-scenarios/

**Comment by JakeChampion** [comment]
This is now in master
