### ISSUE TITLE
Contribution links under the left-hand nav go to a 404, pointing to an invalid API version

### ISSUE THREAD

**Issue by alexwilson** [polyfillpolyfill/polyfill-service#752]
@danielknell discovered that the contribution guide links all point to a 404 (e.g. `https://cdn.polyfill.io/v/docs/contributing/authoring-polyfills`).

It looks as though this bug stems from here: https://github.com/Financial-Times/polyfill-service/blob/master/docs/nav.html#L21-L30

**Comment by alexwilson** [comment]
Oops, looks like this is already fixed!

**Comment by triblondon** [comment]
No problem, thanks for raising an issue, Alex.
