### ISSUE TITLE
IntersectionObserver polyfill has been updated

### ISSUE THREAD

**Issue by philipwalton** [polyfillpolyfill/polyfill-service#761]
Not sure how best to report this or keep these in sync, but the `IntersectionObserver` polyfill code has been updated since polyfill.io added it. I believe [these commits](https://github.com/WICG/IntersectionObserver/compare/5c8ef4dfb25b0ca8c33e6b1d15648711e75f6cb9...9b1a3bfcf64fe3f82a8674e85d34af1bd9e898b1) represent all the changes. 

Also, now that it's been merged into the official WICG repo, it's been given a `package.json` file with versioning, so hopefully that'll help keep these two versions in sync.

**Comment by JakeChampion** [comment]
I've made a PR for this work - https://github.com/Financial-Times/polyfill-service/pull/762

**Comment by JakeChampion** [comment]
The latest version doesn't seem to work in IE 7 & 8 according to our CI results:

```
 - ie 8 (Sauce results: https://saucelabs.com/tests/e682c14868774352a3725e9ef3f8a4fd)
    -> IntersectionObserver
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=IntersectionObserver
 - ie 7 (Sauce results: https://saucelabs.com/tests/45d5251169e747388113f4d1b873b52a)
    -> IntersectionObserver
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=IntersectionObserver
```

**Comment by philipwalton** [comment]
Is it possible the polyfill isn't including `Array.prototype.indexOf`? The new code includes a new `indexOf` call, but that's the only change I can think of that would have any effect.

**Comment by triblondon** [comment]
Looks like @JakeChampion has added the indexOf dependency and it's now passing!  This is really superb work.  Thanks for letting us know about the update.  See #762 for the PR.

**Comment by triblondon** [comment]
PR merged.
