### ISSUE TITLE
Flaky IntersectionObserver tests

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#771]
I occasionally see the IntersectionObserver tests failing in CI for pull requests which haven't modified the IntersectionObserver polyfill. We should look into why they are not always passing and see if we can resolve this issue.

**Comment by JakeChampion** [comment]
What do we think about moving the tests back upstream to the original polyfill's repository?

**Comment by triblondon** [comment]
They were ported from there so our tests are essentially a fork of an older
version from the source repo.

**Comment by triblondon** [comment]
@JakeChampion does this still happen?

**Comment by JakeChampion** [comment]
Yes, still happens :-(
