### ISSUE TITLE
IE10 in IE7 compatibility mode

### ISSUE THREAD

**Issue by tavvy** [polyfillpolyfill/polyfill-service#772]
I am seeing a console error in the document.querySelector polyfill for IE10 in IE7 compatibility mode.

This is the request being made: (`min` has been removed for debugging)
`https://next-geebee.ft.com/polyfill/v2/polyfill.js?callback=ftNextPolyfillServiceCallback&rum=1&features=default,requestAnimationFrame,Promise,matchMedia,HTMLPictureElement,CustomEvent|always|gated,fetch|always|gated,Array.prototype.find|always|gated,Array.prototype.findIndex|always|gated,IntersectionObserver&excludes=Symbol,Symbol.iterator,Symbol.species,Map,Set`

The error from ie dev console:
`SCRIPT65535: Argument not optional`

The offending snippet:
https://github.com/Financial-Times/polyfill-service/blob/c347adb384b77b0844e9d09f25779bbe9ca13952/polyfills/document.querySelector/polyfill.js#L7

I have fixed the error locally by excluding the querySelector polyfill and using a local one which has the following difference/change: `generator = document.createElement('null')`

**Comment by JakeChampion** [comment]
May I ask why it is in IE7 compat mode? Can they move to a browser version the FT supports such as IE8 or higher?
