### ISSUE TITLE
IntersectionObserver polyfill triggering for display:none elements

### ISSUE THREAD

**Issue by adgad** [polyfillpolyfill/polyfill-service#776]
If I'm observing a `display: none` element, the observer callback is triggered with the polyfill (tested on Firefox and Edge) but not with the browser implementation on Chrome 51.

JSBin:
http://jsbin.com/kiyikazone/2/edit?html,console,output

**Comment by triblondon** [comment]
@philipwalton

**Comment by philipwalton** [comment]
Thanks, I reported this on the [WICG repo](https://github.com/WICG/IntersectionObserver/issues/145).

**Comment by JakeChampion** [comment]
There is an upstream PR for this -- https://github.com/WICG/IntersectionObserver/pull/155

**Comment by triblondon** [comment]
Posted [a reminder](https://github.com/WICG/IntersectionObserver/pull/155#issuecomment-272096107) in that issue

**Comment by allenhwkim** [comment]
Just to confirm, based on this, https://github.com/w3c/IntersectionObserver/pull/155/files#diff-d881855d8287e00bed364a1cee1dd6b6R357, observer is not triggered with `display:none`, right?

**Comment by philipwalton** [comment]
@allenhwkim not quite, that comment means that a target element that isn't displayed cannot intersect with its root element, but that doesn't mean the observer won't be triggered. For example, if an element that was previously intersecting is set to `display: none`, it should trigger the observer.
