### ISSUE TITLE
IE8 console error on minfication

### ISSUE THREAD

**Issue by ashleynolan** [polyfillpolyfill/polyfill-service#778]
Have recently found that our call to the Polyfill service is producing a console error on IE8.

The call we make to Polyfill.io is the following URL:

`//cdn.polyfill.io/v2/polyfill.min.js?features=default,console,Array.prototype.includes,fetch|always,promise|always&flags=gated`

And in IE8 we get a console error of:

`Expected identifier – polyfill.min.js?features=default,console,fetch|always,promise|always&flags=gated, line 13 character 3132`

When taking off the minification, the console error disappears, so this must come about as a result of the minified code(?).  I’ve also tried reducing the call down to just have the default feature set and it still returns the console error, so it doesn’t seem to be caused by one of the additional feature requests.

Any help on this would be appreciated.

**Comment by JakeChampion** [comment]
I think this is because it is not using array notation for the property `v.prototype.catch`, `catch` is a reserved word in IE8. I'll look into why this is happening now and didn't before.

**Comment by JakeChampion** [comment]
It seems uglify-js version 2.7.0 turned on `screw-ie8` by default. I'll be submitting a PR to polyfill-service shortly which explicitly turns it off.

**Comment by ashleynolan** [comment]
Great – thanks for looking into this 👍
