### ISSUE TITLE
Some polyfills are not provided for Android browser

### ISSUE THREAD

**Issue by falsandtru** [polyfillpolyfill/polyfill-service#793]
Android browsers that have a following user-agent need Map/Set/WeakMap/WeakSet polyfills, but this polyfill service provides only Map/Set polyfills. So I got an error `ReferenceError: WeakSet is not defined`.

```
"Mozilla/5.0 (Linux; Android 4.4.2; KYY24 Build/108.1.2110) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36"
```

**Comment by triblondon** [comment]
Hi there,

You can easily fix this by adding the appropriate browser configurations to our target files.  Instructions here:

https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by falsandtru** [comment]
Thanks. I think this is not a problem of details of user-agent. One of the problem is a failure of browser family detection. For example, my reported user-agent was detected as Chrome, but it should be detected as Android. This service misdetect a browser family with Android browser that user-agent has a string of "Chrome".

**Comment by JakeChampion** [comment]
If I use the useragent string you provided in the issue description and request WeakSet, it is [returned correctly](https://cdn.polyfill.io/v2/polyfill.js?features=WeakSet&ua=Mozilla/5.0%20%28Linux;%20Android%204.4.2;%20KYY24%20Build/108.1.2110%29%20AppleWebKit/537.36%20%28KHTML,%20like%20Gecko%29%20Version/4.0%20Chrome/30.0.0.0%20Mobile%20Safari/537.36).

We can also see in the comment block at the top of the response returned by the polyfill.io request that the browser being detected is chrome 30. Are you 100% sure that the browser being used is not chrome?

Edit: Here is a [polyfill.io request](https://cdn.polyfill.io/v2/polyfill.js?features=Map,Set,WeakMap,WeakSet&ua=Mozilla/5.0%20%28Linux;%20Android%204.4.2;%20KYY24%20Build/108.1.2110%29%20AppleWebKit/537.36%20%28KHTML,%20like%20Gecko%29%20Version/4.0%20Chrome/30.0.0.0%20Mobile%20Safari/537.36) which asks for Map, Set, WeakMap, WeakSet with the useragent string you posted, all the polyfills are returned successfully.

**Comment by falsandtru** [comment]
At least, I have a chrome browser version 51 as a different browser of default browser in my smartphone.

My repro is here
1. Set ua `Mozilla/5.0 (Linux; Android 4.4.2; KYY24 Build/108.1.2110) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36` with Chrome.
2. Open https://cdn.polyfill.io/v2/polyfill.js

```
/* Polyfill service v3.8.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: chrome/30.0.0
 * Features requested: default
 * 
 * - Array.from, License: CC0 (required by "default")
 * - Array.of, License: CC0 (required by "default")
 * - Array.prototype.fill, License: CC0 (required by "default")
 * - _mutation, License: CC0 (required by "Element.prototype.after", "Element.prototype.append", "Element.prototype.before", "Element.prototype.prepend", "Element.prototype.replaceWith", "default")
 * - Element.prototype.after, License: CC0 (required by "default")
 * - Element.prototype.append, License: CC0 (required by "default")
 * - Element.prototype.before, License: CC0 (required by "default")
 * - Element.prototype.matches, License: CC0 (required by "Element.prototype.closest", "default")
 * - Element.prototype.closest, License: CC0 (required by "default")
 * - Element.prototype.prepend, License: CC0 (required by "default")
 * - Element.prototype.replaceWith, License: CC0 (required by "default")
 * - Symbol, License: MIT (required by "Map", "Set", "Symbol.iterator", "Symbol.species", "default")
 * - Symbol.iterator, License: MIT (required by "Map", "Set", "default")
 * - Symbol.species, License: MIT (required by "Map", "Set", "default")
 * - Map, License: CC0 (required by "default")
 * - Object.assign, License: CC0 (required by "default")
 * - setImmediate, License: CC0 (required by "Promise", "default")
 * - Promise, License: MIT (required by "default")
 * - Set, License: CC0 (required by "default")
 * - String.prototype.endsWith, License: CC0 (required by "default")
 * - String.prototype.includes, License: CC0 (required by "default")
 * - String.prototype.startsWith, License: CC0 (required by "default")
 * - URL, License: CC0 (required by "default")
 * - document.visibilityState, License: CC0 (required by "default") */
```

In this case, ua should be `android/4.4.0`, and polyfills should have WeakMap and WeakSet by default because its features are not provided on Android 4.4.

http://kangax.github.io/compat-table/es6/

**Comment by falsandtru** [comment]
At least, I have a chrome browser version 51 as a different browser of default browser in my smartphone.

**Comment by falsandtru** [comment]
I think this problem needs to fix a feature of browser family detection.

**Comment by JakeChampion** [comment]
I see you open https://cdn.polyfill.io/v2/polyfill.js - this is the default set, which does not include `WeakMap` or `WeakSet`. Documentation over what features are in the default set can be found [here](https://cdn.polyfill.io/v2/docs/features/#default-sets).

**Comment by JakeChampion** [comment]
If you included `WeakSet` and `WeakMap` in the features being requested then it will work as expected. E.G. https://cdn.polyfill.io/v2/polyfill.js?features=default,WeakMap,WeakSet

**Comment by falsandtru** [comment]
Oh, I did not know it default restriction. Thanks a lot! However, when I request as Android 4.4 using `Mozilla/5.0 (Linux; Android 4.4.2; KYY24 Build/108.1.2110) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36` (`Chrome` was removed), its response does not have WeakMap and WeakSet. Is this a correct behavior?

```
/* Polyfill service v3.8.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: android/4.4.0
 * Features requested: WeakMap,WeakSet,default
 * 
 * - _mutation, License: CC0 (required by "Element.prototype.after", "Element.prototype.append", "Element.prototype.before", "Element.prototype.prepend", "Element.prototype.remove", "Element.prototype.replaceWith", "default")
 * - Element.prototype.after, License: CC0 (required by "default")
 * - Element.prototype.append, License: CC0 (required by "default")
 * - Element.prototype.before, License: CC0 (required by "default")
 * - Element.prototype.matches, License: CC0 (required by "Element.prototype.closest", "default")
 * - Element.prototype.closest, License: CC0 (required by "default")
 * - Element.prototype.prepend, License: CC0 (required by "default")
 * - Element.prototype.remove, License: CC0 (required by "default")
 * - Element.prototype.replaceWith, License: CC0 (required by "default")
 * - Number.isNaN, License: MIT (required by "Set", "default")
 * - Object.assign, License: CC0 (required by "default")
 * - setImmediate, License: CC0 (required by "Promise", "default")
 * - Promise, License: MIT (required by "default")
 * - Set, License: CC0 (required by "default")
 * - String.prototype.endsWith, License: CC0 (required by "default")
 * - String.prototype.includes, License: CC0 (required by "default")
 * - String.prototype.startsWith, License: CC0 (required by "default")
 * - URL, License: CC0 (required by "default")
 * - document.visibilityState, License: CC0 (required by "default") */
```

Another, how should we do about a browser family detection problem? I'm worried about `ReferenceError: WeakMap is not defined` on Android 4.x.

**Comment by JakeChampion** [comment]
The link Andrew posted in this issue about contributing a polyfill user
agent configuration change explains how to add Android to the weak map and
weak set polyfills. If you have time,  I recommend following that guide and
submitting a pull request otherwise it may get done by another contributer
but I can't be sure when.

**Comment by falsandtru** [comment]
Also, Map doesn't exist in https://github.com/Financial-Times/polyfill-service/issues/793#issuecomment-238112927.

**Comment by falsandtru** [comment]
I'm trying to fix these problems in #818. Please review it.

**Comment by falsandtru** [comment]
Add, Array.from and too many polyfills are not provided for Android browser.

**Comment by triblondon** [comment]
OK, we have a few issues here:
- Missing polyfills for some browsers: adjust the configs.  You have PRs for this, awesome.
- Incorrect identification of Android as Chrome.  You may need to raise this in the ua-parser project (example: https://github.com/ua-parser/uap-core/pull/155)
- Not serving non-default polyfills when not explicitly requested: You need to request them, which you're now doing.

I'm going to close this issue as I think we've gotten to the bottom of these points.

**Comment by falsandtru** [comment]
Thanks for the navigation.

**Comment by falsandtru** [comment]
Note: I found https://github.com/3rd-Eden/useragent/issues/46. We cannot distinguish Android browser and Chrome mobile. So we need to switch config by chrome version.
