### ISSUE TITLE
Next article preview in IE11 within Methode does not display images

### ISSUE THREAD

**Issue by debugwand** [polyfillpolyfill/polyfill-service#794]
https://jira.ft.com/browse/NFT-532
This ticket is raised on behalf of Mark Alderson's team who use Methode for article Previews of Next.
The preview for all articles shows blank images when previewed in IE11 (see attached 'Preview via Methode' image).

![preview via methode](https://cloud.githubusercontent.com/assets/996106/17323939/fc6eaaf4-589b-11e6-9552-1346b4554675.png)
![preview via external link](https://cloud.githubusercontent.com/assets/996106/17323942/ffd0d91a-589b-11e6-98f6-bd3610357410.png)

Methode preview is actually IE10 in compatibility mode. Unfortunately it is not possible to change the Methode preview settings. Apparently there is a newer shiner version of Methode which they would be happy to sell us which includes chrome as the preview. The FT do not want to do that. So I am afraid we are stuck with the preview as is.

After some digging, this turned out to be caused by the config for HTMLPictureElement polyfill supporting IE8+.  This meant that the src attribute was never getting created for IE10 in compatibility mode.  Changing this config to IE7+ fixes the issue.  Fork fix coming soon

**Comment by JakeChampion** [comment]
This work is in master and will be released in next release - `3.10`
