### ISSUE TITLE
Below baseline browser versions not subject to `unknown=polyfill` policy

### ISSUE THREAD

**Issue by klaemo** [polyfillpolyfill/polyfill-service#795]
I know some Samsung support is being tackled in `3.9.0`, but hear me out :D

With the following UA string
`Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-A500FU/A500FUXXU1BOL1 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36`
We currently get this response:

```
/* Polyfill service v3.8.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: other/0.0.0 (unknown/unsupported; using policy `unknown=ignore`)
 * Features requested: default
 *  */
```

which is okay, because with `unknown=polyfill` I can request the entire shebang and get it to work on those devices. With `3.9.0` (http://qa.polyfill.io/v2/polyfill.js) on the other hand, I get:

```
/* Polyfill service v3.9.0-rc3
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: samsung_mob/3.3.0 (unknown/unsupported; using policy `unknown=ignore`)
 * Features requested: default
 * 
 * Version range for polyfill support in this family is: >=4
 *  */
```

which I don't seem to be able to work around with `unknown=polyfill`:

```
/* Polyfill service v3.9.0-rc3
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: samsung_mob/3.3.0 (unknown/unsupported; using policy `unknown=polyfill`)
 * Features requested: default
 * 
 * Version range for polyfill support in this family is: >=4
 *  */
```

Is this a bug or am I doing something wrong?

Thank you for this great service :)

**Comment by wheresrhys** [comment]
The baseline version number for samsung is 4, https://github.com/Financial-Times/polyfill-service/blob/master/lib/UA.js#L35, so perhaps the behaviour of `unknown=polyfill` for browsers which are recognised, but below the baseline version, should be altered to treat them the same as unknown UAs. Although this risks delivering some polyfills which are known to be incompatible with the browser.

**Comment by JakeChampion** [comment]
Good catch Clemens, you are correct, this looks like it will break some
websites which currently work. Rhys, your idea makes sense, I would think a
more descriptive name for the configuration option would be unsupported
instead of unknown but that may cause more complexity with configurations.
I'm unsure what issues we may run into if we change what the unknown
configuration currently does.

**Comment by triblondon** [comment]
Agree with Rhys.  I think we should ship this change in 3.9 otherwise we'll have a problem with Samsung.

**Comment by JakeChampion** [comment]
This is now live on qa.polyfill.io and on npmjs under the `next` tag.

**Comment by JakeChampion** [comment]
Demo of this working -- http://qa.polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20(Linux;%20Android%205.0.2;%20SAMSUNG%20SM-A500FU/A500FUXXU1BOL1%20Build/LRX22G)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20SamsungBrowser/3.3%20Chrome/38.0.2125.102%20Mobile%20Safari/537.36&unknown=polyfill

**Comment by klaemo** [comment]
Awesome! Thank you so much :)
