### ISSUE TITLE
Internet Explorer 8 reserved keywords on minified request

### ISSUE THREAD

**Issue by gkurt** [polyfillpolyfill/polyfill-service#796]
In Internet Explorer 8 reserved keywords such as "try", "catch", "delete" cannot be used in a manner such as:

```
var a = {catch: 15};
a.delete=5;
```

And both lines will fail with an error "Expected identifier.". However they can be written as such:

```
var a = {'catch': 15};
a['delete']=5;
```

Looks like the minifier you are using doesn't regard this and uses the former. There doesn't seem to be such an error in the non-minified version.

**Comment by wheresrhys** [comment]
It should be configured correctly https://github.com/Financial-Times/polyfill-service/blob/master/tasks/buildsources.js#L98-L100. What's the polyfill.io url you're calling?

**Comment by JakeChampion** [comment]
It was an issue from uglifyjs' latest minor version release which turned on
`screw_ie8` by default. This is fixed in `master` and in the release
candidate currently on qa.polyfill.io and will be out to production on
Friday if no issues are found in the release prior to that day.

**Comment by gkurt** [comment]
Ok, it is my bad that this is actually a duplicate issue of #778.  
Btw, I was using [https://cdn.polyfill.io/v2/polyfill.min.js](url)

**Comment by JakeChampion** [comment]
That's okay, thank you very much for taking the time to create an issue
about this. Without users like you this bug could have been around for a
lot longer than it currently has.

Again, thank you for filing the issue and please feel free to file any
others you come across.
