### ISSUE TITLE
[FR/Question] any plans to support flexbox?

### ISSUE THREAD

**Issue by siddo420** [polyfillpolyfill/polyfill-service#810]
I found https://github.com/jonathantneal/flexibility that might be of some help

**Comment by siddo420** [comment]
Also found https://philipwalton.github.io/polyfill/ (with flex support)

**Comment by triblondon** [comment]
Can't see any flex support in Philip's project, it just provides hooks to your own flexbox polyfill.  Flexibility looks like it could work.  We'd accept a PR adding this feature.

We've recently updated our documentation on how to add a new feature, and haven't deployed it yet, so apologies for not offering a rendered version.

https://github.com/Financial-Times/polyfill-service/blob/master/docs/contributing/common-scenarios.html#L45-L66

**Comment by triblondon** [comment]
Older version of the docs: https://polyfill.io/v2/docs/contributing/common-scenarios
