### ISSUE TITLE
3.9.2 release

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#824]
We've pushed version 3.9.2 to [QA](http://qa.polyfill.io) and to npm.

This addresses #820 only.  As a patch we're just seeking verification from users who reported the issue (@brenoferreira @vojtech-dobes @nmaves), then will push to prod.

**Comment by triblondon** [comment]
Promoted to prod, caches cleared.

**Comment by nmaves** [comment]
Sorry guys just got in and I will test this ASAP

**Comment by nmaves** [comment]
I just tested the QA version and it looks solid.  Thanks for the super fast turn around on this.

**Comment by nmaves** [comment]
The production versions works as expected.
