### ISSUE TITLE
Element polyfill issue

### ISSUE THREAD

**Issue by fredj** [polyfillpolyfill/polyfill-service#827]
On Chrome (version 52.0.2743.82) loading the `Element.prototype.classList` polyfill raises and exception:
`Failed to execute 'appendChild' on 'Node': Only one element on document allowed.`
See https://fredj.io/polyfill.html

**Comment by triblondon** [comment]
Classlist is not required in chrome 52.  You are loading it with the `always` flag, but not the `gated` flag, which means you're trying to overwrite a native implementation with a polyfill.  In this case, the polyfill cannot overwrite the native implementation, but we don't consider this a problem.  Either include the gated flag, or remove the always one.
