### ISSUE TITLE
Use ESI to handle callbacks

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#842]
Just an idea based on this https://www.fastly.com/blog/using-esi-part-2-leveraging-vcl-and-esi-to-use-jsonp
https://gist.github.com/simonw/640331

**Comment by JakeChampion** [comment]
Could you explain the pros and cons of implementing callbacks this way?

**Comment by wheresrhys** [comment]
I was originally thinking about some other FT proxy services where we maintain a node backend that doesn't do much other than jsonp. Generating jsonp in the vcl would save money, and improve reliability and latency. For polyfill.io you'd get a higher cache hit rate, with all the benefits that brings.

Cons... people are always rather wary of ESIs, which I can never fully understand, but I believe it mainly revolves around divergence of prod and dev environments. For something as small as wrapping a request's body in a few bytes of text that have a very speciific non-scope-creepy purpose, and where writing unit tests for the CDN is very achievable, and where a separate service/endpoint to deliver the ESI doesn't need to exist (all done in vcl_error), then I think the cons are vanishingly small. The other con would be adding complexity to the VCL, which is always a risk.. but again, the CDN is unit-testable.

On balance, it may not be worth it, but as @triblondon is a VCL fan I thought I'd share

**Comment by triblondon** [comment]
Wow, this is like templating system in VCL.  You could do a lot with this, but I'm not sure it would achieve much in this particular use case because I don't think we suffer much cache fragmentation as a result  of the callback param

**Comment by triblondon** [comment]
@wheresrhys but feel free to offer us a PR for this if you like.
