### ISSUE TITLE
Event.DOMContentLoaded does not work when gated

### ISSUE THREAD

**Issue by andrepereiradasilva** [polyfillpolyfill/polyfill-service#843]
In https://cdn.polyfill.io/v2/polyfill.js?features=Event.DOMContentLoaded&flags=always,gated

Notice the:

``` js
if (!('addEventListener' in this)) {
// Event.DOMContentLoaded
// [code removed for brevity]
}
```

`addEventListener` is already added above (in `Event` dependency) so this will never run, correct?

If so, maybe replacing `'addEventListener' in this` in https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Event/DOMContentLoaded/detect.js for `'createEvent' in document` could work?

**Comment by triblondon** [comment]
@andrepereiradasilva Sounds feasible.  Can you do some tests and submit a PR?

**Comment by andrepereiradasilva** [comment]
See https://github.com/Financial-Times/polyfill-service/pull/862
