### ISSUE TITLE
Incorrectness of Array.from with iterators

### ISSUE THREAD

**Issue by falsandtru** [polyfillpolyfill/polyfill-service#844]
As a note, the following implementation is probably wrong because `parseIterable` detects an iterable response that has a `next` method, not an iterable objects that has a `[Symbol.iterator]` method. In the following code, it should detect an iterable object.

``` js
arrayFromIterable = parseIterable(arraylike);
```

https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array/from/polyfill.js#L72

This problem will be resolved by https://github.com/mathiasbynens/Array.from/pull/27.

**Comment by falsandtru** [comment]
Add: Array.from polyfill still broken with Map/Set polyfills because Array.from checks `value` prop in https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array/from/polyfill.js#L16 but Map/Set don't provide that prop in https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Map/polyfill.js#L27. It happened with my lib. So #817 is incomplete.

@JakeChampion Can I use the upstream polyfill with this service in a few week, or should I fix it on this repo?

**Comment by falsandtru** [comment]
@triblondon @JakeChampion Could you review #840? I reopened that pr to fix this bug.

**Comment by triblondon** [comment]
So now #840 is closed, what's the status of this problem now?

**Comment by falsandtru** [comment]
This will be fixed by #884. Thanks for your pointing.

**Comment by JakeChampion** [comment]
Just to update this issue, #884 was closed

**Comment by falsandtru** [comment]
Thanks, the problem I found on Android 4.4 is fixed.
