### ISSUE TITLE
Syntax Error: unexpected end of input with 3.10.0

### ISSUE THREAD

**Issue by ruiaraujo** [polyfillpolyfill/polyfill-service#845]
When using Chrome 52 with the new release with the following options, I get a Syntax Error: unexpected end of input.

https://cdn.polyfill.io/v2/polyfill.min.js?unknown=polyfill&features=default,es6,Intl.~locale.de|always,Object.assign|always|gated,requestAnimationFrame|always|gated,Array.prototype.fill|always|gated,Array.prototype.find|always|gated,Array.prototype.findIndex|always|gated,String.prototype.startsWith&excludes=Map,Set,Symbol,Symbol.iterator,Symbol.species

**Comment by ruiaraujo** [comment]
On IE 11, I am seeing and error related with this: 'Expected '}''

@JakeChampion you just made my day really exciting in a bad kind of way. 👿

**Comment by JakeChampion** [comment]
Will be fixed in 7 minutes :-)

**Comment by ruiaraujo** [comment]
Ok I have an hotfix ready to push to production which basically involves using the unminified version. I will wait 10 minutes then to see if the profecy is true.

Regardless, 👍 for the fast response time.

**Comment by JakeChampion** [comment]
Is it working for you?

**Comment by ruiaraujo** [comment]
Nope. Still same error.

**Comment by JakeChampion** [comment]
Can you do a hard refresh? I'm visiting the url you posted -- `https://cdn.polyfill.io/v2/polyfill.min.js?unknown=polyfill&features=default,es6,Intl.~locale.de%7Calways,Object.assign%7Calways%7Cgated,requestAnimationFrame%7Calways%7Cgated,Array.prototype.fill%7Calways%7Cgated,Array.prototype.find%7Calways%7Cgated,Array.prototype.findIndex%7Calways%7Cgated,String.prototype.startsWith&excludes=Map,Set,Symbol,Symbol.iterator,Symbol.species` and can see that the line `//# sourceMappingURL=Intl.min.js.map` is now on it's own line, which resolves the issue.

**Comment by ruiaraujo** [comment]
Funny it seems the missing url encoding on the | character shows different results.
With your url, it works but if I use an url with |s, it still shows the bad bundle.

**Comment by JakeChampion** [comment]
Okay, I purged the cache for that particular request, should be working now

**Comment by ruiaraujo** [comment]
not really, but I am going to update production with the | url encoded to make sure the cache is busted.

**Comment by JakeChampion** [comment]
Did you do a hard-reload, your browser cache might still have the bad response.

**Comment by ruiaraujo** [comment]
I even used other browsers to be sure and browserstack remote sessions. I am sure there is no caching on my side that has survived this. 😄

**Comment by ruiaraujo** [comment]
I have fixed it by using encodeURI which has the correct version cached, I have now pushed it to production and can go home.

The old link still reports the broken version.

Anyhow thanks @JakeChampion for fixing it quickly.
