### ISSUE TITLE
UC Browser support; general config question

### ISSUE THREAD

**Issue by zslabs** [polyfillpolyfill/polyfill-service#846]
Hi all! Bringing this up here to get a little clarification on support for [UC Browser](https://en.wikipedia.org/wiki/UC_Browser) since I'm not seeing other issues with that (keyword) mentioned. Has this been brought up before? Is there anything in the service that would allow us to pass through some default polyfills for browsers that are not recognized?

**Comment by mudcube** [comment]
I believe this is the appropriate documentation:
https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers
Adding UC Browser support would be a nice addition.

**Comment by zslabs** [comment]
Ah ok great! It looks like UC Browser is normally expressed in the UA agent as as `UCBrowser` according to https://www.whatismybrowser.com/developers/tools/user-agent-parser/browse/browser-name/uc-browser-user-agents 

@JakeChampion Since my tests for support with UC Browser seem to align somewhat close to IE11 (as far as `fetch` and `closest` support), how would we go about mimicking a browser to act as another? IE10 may even be the safer bet based on older versions of UC Browser, but I'm not 100% on coverage there. https://github.com/ua-parser/uap-core/blob/master/regexes.yaml#L110

**Comment by triblondon** [comment]
@zslabs try here:

https://github.com/Financial-Times/polyfill-service/blob/master/lib/UA.js#L46

**Comment by zslabs** [comment]
Submitted #853 - but it's failing and I'm a little unsure why. Have a minute to look? From my tests, IE10 is a close equivalent to UC Browser.
