### ISSUE TITLE
Googlebot doesn't get Object.assign polyfilled

### ISSUE THREAD

**Issue by MartijnHols** [polyfillpolyfill/polyfill-service#849]
I ran into this issue that my React app wasn't being rendered by Googlebot. By using [Fetch as Google](https://www.google.com/webmasters/tools/googlebot-fetch?utm_source=support.google.com/webmasters/&utm_medium=referral&utm_campaign=6155685), I tracked it down to `Object.assign` not being available in Googlebot, even though I'm using the following polyfill:

```
https://cdn.polyfill.io/v2/polyfill.min.js?features=default
```

I tested this with the following code:

```
<h1>At what point do you stop working, Google?</h1>

{Object.assign && 'We have object.assign! :)'}
{!Object.assign && 'No object.assign available! :('}
```

Which renders the following in [Fetch as Google](https://www.google.com/webmasters/tools/googlebot-fetch?utm_source=support.google.com/webmasters/&utm_medium=referral&utm_campaign=6155685):

![image](https://cloud.githubusercontent.com/assets/4565223/17928956/9a279cde-69fd-11e6-9927-8c23f6b5407e.png)

Note that the left says "No object.assign available! :(".

**Comment by MartijnHols** [comment]
I'm going to fix this for myself by polyfilling it in my own code, so it's not a critical issue for me but I'm sure others might encounter the same issue.

**Comment by JakeChampion** [comment]
This can be solved in a few ways:
- include `unknown=polyfill` in your querystring to polyfill.io

`unknown=polyfill` makes polyfill.io return all polyfills if it doesn't know what browser the client is. Here is the explanation from our documentation:

> What to do when the user agent is not recognised. Set to polyfill to return default polyfill variants of all qualifying features, ignore to return nothing. Use caution when setting this argument to 'polyfill' on large feature sets, since huge polyfill bundles may cause crashes or lockups in extremely old or underpowered user agents. Defaults to ignore.
- Wait on https://github.com/Financial-Times/polyfill-service/issues/107 to be completed.

**Comment by triblondon** [comment]
@MartijnHols we'd also be delighted if you would consider helping us to improve our browser targeting. We prepared a document to help people get started if they want to correct browser targeting configuration:

https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by triblondon** [comment]
Currently we don't support Googlebot as a browser family.  We still recommend using the `unknown=polyfill` config parameter if you want to polyfill for search crawlers.  We would welcome any efforts to either add and maintain a googlebot browser family, or create aliases to the appropriate versions of chrome or webkit. However, I'm aware that Google doesn't publicly disclose which browser engine version is used by Googlebot, so it is kinda hard to do that.

**Comment by hheexx** [comment]
We need intl support for googlebot. We receive javascript errors that it's missing.

@triblondon Can you estimate the effort needed to support bots? Just user agent regex?

**Comment by williamoliveira** [comment]
Googlebot uses Chrome 41
https://developers.google.com/search/docs/guides/rendering

**Comment by JakeChampion** [comment]
@williamoliveira We alias Googlebot to Chrome 41 :-) -- https://github.com/Financial-Times/polyfill-service/blob/8ae2f6fa5b1a169aab01cad3b88bd577d67f8294/packages/polyfill-library/lib/UA.js#L145
