### ISSUE TITLE
SamsungBrowser 2.1 polyfill is empty

### ISSUE THREAD

**Issue by msokk** [polyfillpolyfill/polyfill-service#850]
Hi,

requesting the polyfill with default parameters does not return any polyfills.
From the response it looks like it does not recognize samsung mobile:
`* UA detected: samsung_mob/2.1.0 (unknown/unsupported; using policy`unknown=ignore`)`

But wasn't samsung support added recently?

My code depends on Array.from:
https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Array/from/config.json

**Comment by msokk** [comment]
Ah, noticed that the support starts from v4, any reason for that?

**Comment by JakeChampion** [comment]
Hi @msokk, Samsung 4 and above is what the Samsung contributors are offering to support.

Quote from https://medium.com/samsung-internet-dev/samsung-and-the-polyfill-service-d6e70a9f1684#.t0j1ur5jw :

> The Samsung Developer Advocate team will continue to maintain the Samsung bits of the polyfill service so that Samsung Internet 4 and above will always be able to use latest language features not already available in the browser.

**Comment by msokk** [comment]
Ok thanks for the information, will pull the match polyfill into the main bundle to fix it then.
