### ISSUE TITLE
Google Adsbot Mobile UA doesn't receive Intl

### ISSUE THREAD

**Issue by jopdeklein** [polyfillpolyfill/polyfill-service#852]
I am not sure how relevant this is for others, but Sentry is reporting that the Google Adsbot for mobile (mimicking an iPhone running iOS 9.1) doesn't receive Intl, on which our app relies and apparently isn't provided by the AdsBot:

```
curl 'https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en-GB' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1 (compatible; AdsBot-Google-Mobile; +http://www.google.com/mobile/adsbot.html)' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' --compressed

/* Polyfill service v3.11.0
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: adsbot/0.0.0 (unknown/unsupported; using policy `unknown=ignore`)
 * Features requested: Intl.~locale.en-GB
 *  */
```

**Comment by triblondon** [comment]
we'd be delighted if you would consider helping us to improve our browser targeting. We prepared a document to help people get started if they want to correct browser targeting configuration:

https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by triblondon** [comment]
Currently we don't support Googlebot as a browser family. We still recommend using the unknown=polyfill config parameter if you want to polyfill for search crawlers. We would welcome any efforts to either add and maintain a googlebot browser family, or create aliases to the appropriate versions of chrome or webkit. However, I'm aware that Google doesn't publicly disclose which browser engine version is used by Googlebot, so it is kinda hard to do that.
