### ISSUE TITLE
IE 11 issue - .includes() is not supported

### ISSUE THREAD

**Issue by arthurvi** [polyfillpolyfill/polyfill-service#854]
### Bug

In IE11 I get the following error while I included the polyfill.

```
Object doesn't support property or method 'includes'
```

```
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
```

![image](https://cloud.githubusercontent.com/assets/3864426/18124145/4583f618-6f71-11e6-830d-7b894f2cd258.png)
### Cause

It goes wrong [here](https://github.com/airbnb/react-dates/blob/58930108f67e7ccbd820deecef75aafcf17cb4bd/src/components/SingleDatePicker.jsx#L82)

Is there any reason why `includes` isn't correctly replaced?

**Comment by JakeChampion** [comment]
[Array.prototype.includes](https://polyfill.io/v2/docs/features/#Array_prototype_includes) is not in the default set of polyfills. 

You can add it to your request as follows:
`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.includes"></script>`

**Comment by arthurvi** [comment]
@JakeChampion Thank you! That did it.
