### ISSUE TITLE
Doesn't polyfill Symbol for Android even with 'always' flag

### ISSUE THREAD

**Issue by tinovyatkin** [polyfillpolyfill/polyfill-service#855]
![screen shot 2016-08-31 at 09 42 49 am](https://cloud.githubusercontent.com/assets/5350898/18131068/717e2b2e-6f5f-11e6-8d90-8ff687bc86ec.png)

**Comment by JakeChampion** [comment]
Hi, can you post the polyfill.io url you are using to get your polyfill bundle please? The one in the image looks to not has a `?` for the querystring parameters

**Comment by tinovyatkin** [comment]
Well, that the only things it missed (`?` was eaten by Rollbar):
`https://cdn.polyfill.io/v2/polyfill.min.js?features=Promise,Symbol,Event,CustomEvent,URL,Symbol.iterator,Array.prototype.@@iterator,Event.hashchange,Node.prototype.contains,Element.prototype.classList,Object.create,Object.setPrototypeOf,IntersectionObserver&flags=gated,always&callback=window.onPolyfilLoaded`

then window.onPolyfillLoaded callback starts my code that uses Symbol and so on..

**Comment by JakeChampion** [comment]
The useragent string looks to be [facebook's in-app browser](https://polyfill.io/v2/polyfill.js?ua=Mozilla/5.0%20%28Linux;%20Android%204.4.2;%20GT-N7100%20Build/KOT49H%29%20AppleWebKit/537.36%20%28KHTML,%20like%20Gecko%29%20Version/4.0%20Chrome/30.0.0.0%20Mobile%20Safari/537.36%20[FB_IAB/FB4A;FBAV/91.0.0.17.68;]), which we have not got coverage for on Android as of yet.

**Comment by tinovyatkin** [comment]
So, 'always' is not overriding userAgent check or polyfill is not working in Facebook browser.. I didn't get you...

**Comment by tinovyatkin** [comment]
As API reference says:

> |always
> Polyfill should be included regardless of whether it is required by the user-agent making the request.

**Comment by JakeChampion** [comment]
Apologies for not explaining fully. The browser is unknown/unsupported by polyfill.io, which means we default to not serving polyfills to it. You can override this setting by passing the query parameter `unknown` with the value `polyfill`.

This is your polyfill url with the `unknown=polyfill` added on:
`https://cdn.polyfill.io/v2/polyfill.min.js?features=Promise,Symbol,Event,CustomEvent,URL,Symbol.iterator,Array.prototype.@@iterator,Event.hashchange,Node.prototype.contains,Element.prototype.classList,Object.create,Object.setPrototypeOf,IntersectionObserver&flags=gated,always&callback=window.onPolyfilLoaded&unknown=polyfill`.

Here is the documentation for `unknown` (taken from https://polyfill.io/v2/docs/api):

> What to do when the user agent is not recognised. Set to polyfill to return default polyfill variants of all qualifying features, ignore to return nothing. Use caution when setting this argument to 'polyfill' on large feature sets, since huge polyfill bundles may cause crashes or lockups in extremely old or underpowered user agents. Defaults to ignore.

**Comment by JakeChampion** [comment]
You can see the difference between the bundle responses here:

[Facebook Android in-app browser without `unknown=polyfill`](https://cdn.polyfill.io/v2/polyfill.min.js?features=Promise,Symbol,Event,CustomEvent,URL,Symbol.iterator,Array.prototype.@@iterator,Event.hashchange,Node.prototype.contains,Element.prototype.classList,Object.create,Object.setPrototypeOf,IntersectionObserver&flags=gated,always&callback=window.onPolyfilLoaded&ua=Mozilla/5.0 %28Linux; Android 4.4.2; GT-N7100 Build/KOT49H%29 AppleWebKit/537.36 %28KHTML, like Gecko%29 Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/91.0.0.17.68;])

[Facebook Android in-app browser with `unknown=polyfill`](https://cdn.polyfill.io/v2/polyfill.min.js?features=Promise,Symbol,Event,CustomEvent,URL,Symbol.iterator,Array.prototype.@@iterator,Event.hashchange,Node.prototype.contains,Element.prototype.classList,Object.create,Object.setPrototypeOf,IntersectionObserver&flags=gated,always&callback=window.onPolyfilLoaded&unknown=polyfill&ua=Mozilla/5.0 %28Linux; Android 4.4.2; GT-N7100 Build/KOT49H%29 AppleWebKit/537.36 %28KHTML, like Gecko%29 Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/91.0.0.17.68;])

**Comment by tinovyatkin** [comment]
@JakeChampion thank you, I've just added `unknown` flag to our code. However, it's still unclear for me why `unknown` overrides `always`. I was thinking that `always` flag should prevent userAgent sniffing on your side, is it not?

**Comment by triblondon** [comment]
@tinovyatkin the current behaviour is intentional, but we will be changing to make it more in line with your expectations in an upcoming release.
