### ISSUE TITLE
Map polyfill detect crashes Safari 8

### ISSUE THREAD

**Issue by hannesj** [polyfillpolyfill/polyfill-service#863]
With the error `Map constructor does not accept arguments`. Unfortunately already the detect breaks the site, as it tries to create a Map. Possibly a similar solution to https://github.com/google/traceur-compiler/pull/1940

![bs_macyos_safari_8 0](https://cloud.githubusercontent.com/assets/698100/18327192/0d4a7a2e-7552-11e6-899e-290a3763b2a3.jpg)

**Comment by triblondon** [comment]
Looks like we already have a reasonable detect that would catch this poor implementation and fail, but we don't target Saf 8.  And it looks like our compat matrix already acknowledges this issue:

![image](https://cloud.githubusercontent.com/assets/1735391/18373253/8cc51f6c-767d-11e6-938f-dec16eecf03b.png)

So feel free to extend Map to Saf 8.

**Comment by triblondon** [comment]
Does the polyfill work in Saf 8?  I don't have 8 handy, unfortunately.

**Comment by hannesj** [comment]
@triblondon The detect should probably be wrapped in a try/catch, as it throws an exception currently.

**Comment by JakeChampion** [comment]
@hannesj This is now live on http://qa.polyfill.io - would you be able to report back whether we have fixed your issue?
