### ISSUE TITLE
`gated` broke functionality on Safari

### ISSUE THREAD

**Issue by tinovyatkin** [polyfillpolyfill/polyfill-service#869]
iOS 9.3.5, Safari
That works:
`<script async crossorigin="anonymous" src="https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en-US&unknown=polyfill&callback=window.onPolyfilLoaded"></script>`

That doesn't:
`<script async crossorigin="anonymous" src="https://cdn.polyfill.io/v2/polyfill.js?features=Intl.~locale.en-US&flags=gated&unknown=polyfill&callback=window.onPolyfilLoaded"></script>`

Error: `ReferenceError: No locale data has been provided for this object yet.`

**Comment by triblondon** [comment]
I tested this using http://jsbin.com/suyafi/1/ in Safari on iOS 9.3.5, and there was no error.  I'm going to assume this is an error in your own code, but if you can adjust this JSBin to reproduce the error, feel free to reopen.
