### ISSUE TITLE
Cannot use 'in' operator to search for 'value' in Array Iterator

### ISSUE THREAD

**Issue by jswift** [polyfillpolyfill/polyfill-service#871]
As of today (3.12.0) the following options are resulting in a javascript error in Chrome and Safari

polyfill.js?features=es5|always|gated,Intl.~locale.en-CA|always|gated

> Uncaught TypeError: Cannot use 'in' operator to search for 'value' in Array Iterator  polyfill.js?features=es5|always|gated,Intl.~locale.en-CA|always|gated:54

Removing _always_ fixes the issue.

**Comment by triblondon** [comment]
Hmm, I don't really understand why this would be the case:

``` javascript
> var a = [1,2,3];
> var i = a.values();
> i
ArrayIterator {}
> 'value' in i
false
> 'value' in a
false
```

No errors thrown.  I was using Chrome 53 and polyfilling `values()`.  And [a jsbin](https://jsbin.com/pomefulowi/edit?html,output) has no errors.  Are you sure this is not an error in your code?  If not can you post a JSBin demo?

**Comment by dhaselhan** [comment]
Seeing a similar issue starting today.
Values has become iterable on the array prototype, I have had to exclude Array.prototype.values for now.

[JSBin](https://jsbin.com/yenejutewi/edit?html,js,console,output)

**Comment by triblondon** [comment]
Assuming this was an error in the application's code.
