### ISSUE TITLE
Array.prototype.values polyfill gets added to array when using $.extend

### ISSUE THREAD

**Issue by dhaselhan** [polyfillpolyfill/polyfill-service#880]
Saw this issue starting yesterday.
Values has become iterable on the array prototype, I have had to exclude Array.prototype.values for now.

[JSBin](https://jsbin.com/yenejutewi/edit?html,js,console,output)

**Comment by chapmanc** [comment]
Present for me as well. Please take a look.

**Comment by dhaselhan** [comment]
Looks like this is happening because Array.prototype.values is enumerable and should not be. 

Object.defineProperty(Array.prototype, "values", {enumerable: false}) is a work around for the issue.

**Comment by falsandtru** [comment]
The current implementation `Array.prototype.values = Array.prototype[Symbol.iterator];` makes an enumerable property.

```
> Object.getOwnPropertyDescriptor(Array.prototype, 'values')
Object {writable: true, enumerable: true, configurable: true}
> Object.getOwnPropertyDescriptor(Array.prototype, 'length')
Object {value: 0, writable: true, enumerable: false, configurable: false}
> for (var i in []) i
"values"
```

**Comment by triblondon** [comment]
Please review https://github.com/Financial-Times/polyfill-service/pull/894

**Comment by JakeChampion** [comment]
@dhaselhan This is now live on http://qa.polyfill.io - would you be able to report back whether we have fixed your issue?
