### ISSUE TITLE
Cannot modify non-writable property 'iterator'

### ISSUE THREAD

**Issue by bhandfast** [polyfillpolyfill/polyfill-service#881]
Recently we've seen lots of error reports from Edge. The error is reported to the console as
SCRIPT5079: Cannot modify non-writable property 'iterator': polyfill.min.js (3,3694)

We load polyfill as:
https://cdn.polyfill.io/v2/polyfill.min.js?features=modernizr:es5array,es6

I did a search in the issues list but I didn't find anything relevant, but I might have overlooked something.

**Comment by srolel** [comment]
I'm seeing this as well. `Symbol.iterator` is required by the `es6` polyfill, Edge does have it. The `Symbol` has `"ie": "< 13"` but `Symbol.iterator` has `"ie": "*"``, and I'm guessing that it is getting required as a dependency of`es6`directly, since`Symbol` isn't included in the Edge polyfill.

**Comment by srolel** [comment]
I submitted a pull request, under the assumption that i was correct in my assertion above. This currently breaks the polyfill and apps that use it for es6 on Edge.

**Comment by triblondon** [comment]
Thanks.  Should be released in 3.13.

**Comment by bhandfast** [comment]
Any ETA when 3.13 will be pushed to the CDN?

**Comment by JakeChampion** [comment]
It will head to qa.polyfill.io tomorrow and if no issues are reported for 7
days then it is promoted to production. If all goes smoothly it will hit
production next Friday.

**Comment by bhandfast** [comment]
Ok, thanks for the info!

**Comment by JakeChampion** [comment]
@bhandfast This is now released onto http://qa.polyfill.io, apologies it took longer than I expected.
