### ISSUE TITLE
Function.prototype.bind 

### ISSUE THREAD

**Issue by abozhilov** [polyfillpolyfill/polyfill-service#89]
Actually this is not a polyfill. When the returned function by bind is called as: `new (String.bind('test'));` then it's called the [[Construct]] method of the bound function. Since built-in constructors has overloaded behavior depends on its calling, your polyfill is not reliable. If you don't sure, try this: `new (String.bind('test')) === new (String.bind('test'))`

**Comment by triblondon** [comment]
Lots of issues reported with our bind implementation: ref #313 and #261
