### ISSUE TITLE
"Text" is a dep of Element.prototype.after but does not exist

### ISSUE THREAD

**Issue by triblondon** [polyfillpolyfill/polyfill-service#895]

**Comment by JakeChampion** [comment]
@triblondon Are you suggesting we remove it as a dep?

**Comment by triblondon** [comment]
Not sure, hadn't given it any thought at the time.  Looks like originally this polyfill was written by Jonathan, and I made this change to it in response to the lack of a `Text` constructor in IE 6/7:

https://github.com/Financial-Times/polyfill-service/commit/b80fbc6d83a14e68aad0d3cc2932c12d4204448b

In fact it looks like there is still a lack of support generally for this constructor:

https://developer.mozilla.org/en-US/docs/Web/API/Text#Browser_compatibility

I think the short term solution is remove the dependency - we should not be listing a dependency that we don't have.  These are the polyfills that list it:

```
polyfills/_mutation/config.json:20:     "Text"
polyfills/Element/prototype/after/config.json:26:       "Text",
polyfills/Element/prototype/before/config.json:26:      "Text",
polyfills/Element/prototype/remove/config.json:25:      "Text",
polyfills/Element/prototype/replaceWith/config.json:26:     "Text",
```

Happy to do that if you agree.

**Comment by JakeChampion** [comment]
I agree with your proposal 👍
