### ISSUE TITLE
Minify feature detects

### ISSUE THREAD

**Issue by wheresrhys** [polyfillpolyfill/polyfill-service#896]
I notice feature detects are not being minified. Not sure if it's a regression, but (particularly when the detect contains comments) adds a not insignificant amount to the bundle)

**Comment by triblondon** [comment]
Rhys, can you quantify 'not insignificant'?  Average length of a detect is about 50 bytes.  There are longer ones, I concede, but it will be slightly annoying to minify these and I am not sure it is worth the bother.

**Comment by wheresrhys** [comment]
Probably not worth the bother if it's difficult - thought it may have been an oversight/regression that'd be easy to fix.
