### ISSUE TITLE
Opera Mini - Map and Array.from polyfills missing.

### ISSUE THREAD

**Issue by kdzwinel** [polyfillpolyfill/polyfill-service#897]
Hey! Default bundle for Opera Mini doesn't seem to include `Map` and `Array.from` polyfills. My test case: http://jsbin.com/gosifujexo . When everything is OK, the page should be empty. When `Array.from` or `Map` are not available errors will be shown - like so (Opera Mini emulator):

<img width="303" alt="jsbin" src="https://cloud.githubusercontent.com/assets/985504/18993480/c27793cc-8723-11e6-8f3f-57f9e8e8b715.png">

We load polyfill.io from CDN without any params (`<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>`) and we observed issues on wide range of Opera Mini browsers:

<img width="395" alt="errors" src="https://cloud.githubusercontent.com/assets/985504/18993602/43cb3668-8724-11e6-80d5-6da9684df62f.png">

**Comment by triblondon** [comment]
Does it work if you append `flags=always,gated` to your polyfill url?  If so, we can update the browser targeting for those polyfills to target Opera Mini.

**Comment by kdzwinel** [comment]
Hey Andrew! Just tested and it does work when polyfills are forced as you suggested.

**Comment by triblondon** [comment]
@kdzwinel would you consider doing a PR adding all the Opmini targets that we need to resolve this issue and #927 as well?

**Comment by kdzwinel** [comment]
@triblondon sure, I can take care of that.
