### ISSUE TITLE
Polyfills missing

### ISSUE THREAD

**Issue by PascalAOMS** [polyfillpolyfill/polyfill-service#900]
Arrow functions and Template strings are not being polyfilled.
Using these in IE11 breaks the script.

Is there a way to handle these?

Thanks.

**Comment by JakeChampion** [comment]
There is not anything we can do for arrow functions or template strings as
they are syntactic changes in the specification, they are impossible to
polyfill. You will need to precompile your code to es5 using something like
babel.
