### ISSUE TITLE
IE Mobile 9 lacks support for console.info (and is not being polyfilled)

### ISSUE THREAD

**Issue by rubencodes** [polyfillpolyfill/polyfill-service#910]
I wasn't able to find any official reference on which versions of IE Mobile support the console APIs, but I have found that a device with user agent `Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; LG; LG-C900)` does not have support for the `console.info` function. When requesting it explicitly on Polyfill.io I got back the following:

```
/* Polyfill service v3.12.1
 * For detailed credits and licence information see http://github.com/financial-times/polyfill-service.
 * 
 * UA detected: ie_mob/9.0.0
 * Features requested: console.info
 *  */
```

I'm assuming `console.error` and most other console functions also don't work on this platform, but I have not yet been able to test this.

**Comment by triblondon** [comment]
@rubencodes you need to add a browser target to https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/console/info/config.json.

See https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by rubencodes** [comment]
PR for this here: https://github.com/Financial-Times/polyfill-service/pull/914
