### ISSUE TITLE
Remove console log.

### ISSUE THREAD

**Issue by DylanPiercey** [polyfillpolyfill/polyfill-service#915]
Currently every time I start my app using this module I get the following printed to the console.
(from https://github.com/Financial-Times/polyfill-service/blob/4efb6aaf02ce7a94b87abf716c2d3f50efb2e724/lib/sources.js#L23)

``` console
Found 871 polyfills
```

It would be nice if this was hidden behind `NODE_ENV=debug` or better yet if you used the [debug](https://www.npmjs.com/package/debug) module. I don't think the log is very helpful anyways so it might be best to remove it.

**Comment by triblondon** [comment]
Fair point.  Currently we are using console for logging throughout the app, where needed.  That is probably the only one that gets executed if you use the polyfill service as a node library.  I have no objection to removing it.

**Comment by DylanPiercey** [comment]
Thanks for the quick response and resolution! 👍
