### ISSUE TITLE
Automatically parse for polyfills.

### ISSUE THREAD

**Issue by DylanPiercey** [polyfillpolyfill/polyfill-service#920]
I came across https://github.com/azproduction/autopolyfiller today and noticed that is no longer getting updated. It would be awesome if this module supported some form of 'auto polyfilling' a file.

It may be out of scope but I figured I'd mention it.

**Comment by triblondon** [comment]
There have been on and off discussions about using a parser/tokeniser to figure out what APIs are used by a string of JavaScript and then generating an appropriate polyfill.io URL. See https://github.com/Financial-Times/polyfill-service/issues/163 and the linked issue on autopolyfiller.
