### ISSUE TITLE
Polyfilling any console APIs removes support for all other console APIs

### ISSUE THREAD

**Issue by rubencodes** [polyfillpolyfill/polyfill-service#922]
I'm not sure if this is intended behavior. What I'm observing is when polyfilling any console API (like, say `console.info`), all of the other are removed from the browser's console object (e.g. I can no longer use `console.warn`). Below I've attached a screenshot of my console object before and after running the polyfill.io script for `console.info` and `console.error`.

<img width="566" alt="screen shot 2016-10-05 at 11 11 26 am" src="https://cloud.githubusercontent.com/assets/1036549/19125676/da3dadf8-8aec-11e6-9a63-f8d44dcbc246.png">
To reproduce, [run the script here](https://cdn.polyfill.io/v2/polyfill.js?features=console.info|always).

As you can see, everything but the polyfilled properties and `console.log` are gone. This makes sense from the implementation, but I'm wondering if this is done on purpose or is an accident. 
Moreover, after running this polyfill, `console.log` no longer outputs to the console. If I'm polyfilling `console.info`, I would expect `console.log` to remain functioning as it was before the polyfill (and preferably for both of them to output to the console).

**Comment by falsandtru** [comment]
It should be `this.console = this.console || {}`. Can you make a pr?
