### ISSUE TITLE
iOS 8.3.2 throws an error

### ISSUE THREAD

**Issue by VladDubrovskis** [polyfillpolyfill/polyfill-service#923]
Next proxy URL seems to throw following an error on iOS:

![screen shot 2016-10-07 at 14 34 51](https://cloud.githubusercontent.com/assets/15323495/19192869/abd2d100-8c9f-11e6-9e0b-1740a2d68dc2.png)

https://next-geebee.ft.com/polyfill/v2/polyfill.min.js?features=default,requestAnimationFrame,Promise,matchMedia,HTMLPictureElement,fetch,Array.prototype.find,Array.prototype.findIndex,IntersectionObserver,Map%7Calways%7Cgated,Array.from%7Calways%7Cgated&flags=gated&unknown=polyfill&callback=ftNextPolyfillServiceCallback&next-variant=enhanced

**Comment by JakeChampion** [comment]
This seems to be a replicate of https://github.com/Financial-Times/polyfill-service/issues/863 and will be fixed in the next release of the service - 3.13.0

**Comment by JakeChampion** [comment]
@VladDubrovskis This is now live on http://qa.polyfill.io - would you be able to report back whether we have fixed your issue?
