### ISSUE TITLE
NodeList.prototype.@@iterator doesn't load in IE 11

### ISSUE THREAD

**Issue by simono** [polyfillpolyfill/polyfill-service#931]
IE 11 needs a polyfill for NodeList.prototype.@@iterator. But when I try to load the polyfill IE 11 is detected but the polyfill isn't loaded:
https://cdn.polyfill.io/v2/polyfill.js?features=NodeList.prototype.%40%40iterator&ua=Mozilla%2F5.0%20(Windows%20NT%206.3%3B%20Trident%2F7.0%3B%20rv%3A11.0)%20like%20Gecko

When specifying 'always' it works:
https://cdn.polyfill.io/v2/polyfill.js?features=NodeList.prototype.%40%40iterator|always&ua=Mozilla%2F5.0%20(Windows%20NT%206.3%3B%20Trident%2F7.0%3B%20rv%3A11.0)%20like%20Gecko

Any idea what I'm doing wrong? Thanks.

**Comment by triblondon** [comment]
Thanks for raising - there's a syntax error in the semver expression for targeting IE.  I've proposed a fix.

**Comment by simono** [comment]
Thanks. I just saw #932
