### ISSUE TITLE
IE9 (and probably below) issue with Certificate expired

### ISSUE THREAD

**Issue by nayaabkhan** [polyfillpolyfill/polyfill-service#933]
Hey guys, I was testing out on IE9 with default polyfill set. It seems that it is not loading the polyfill. When I try to open the site, I get "Certificate Expired" screen and I think it has something to do with it.

When I turn off the "Check for publisher's revocation" and "Check for server certificate revocation." settings from options, all works okay. Refer: https://help.yahoo.com/kb/SLN5178.html.

Can you guys please check out the issue? Let me know if any more details needed.

**Comment by JakeChampion** [comment]
Hi @nayaabkhan Would you be able to post the URL you were using to replicate this bug?

I've opened https://cdn.polyfill.io/v2 in IE9 and I saw no certificate issues. Is there a step I am missing?

![bs_win7_ie_9 0](https://cloud.githubusercontent.com/assets/1569131/19347788/810c488c-9142-11e6-8a1c-bdc1b3590331.jpg)

**Comment by nayaabkhan** [comment]
Hey @JakeChampion I am trying to access https://polyfill.io/v2/docs/examples. I see this:

<img width="1100" alt="screenshot 2016-10-13 17 16 02" src="https://cloud.githubusercontent.com/assets/234889/19347976/3af213aa-9169-11e6-872e-1c23ee3487f1.png">

**Comment by JakeChampion** [comment]
I have replicated the issue now, no idea why IE9 is seeing our certificate as being revoked. According to [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=polyfill.io) our certificate has not been revoked.

**Comment by JakeChampion** [comment]
This is an issue with Fastly, they have issued an incident report -- https://status.fastly.com/incidents/2tf2hvkj2z50

**Comment by nayaabkhan** [comment]
Alright, I am going to keep a tab on that Fastly incident. Closing this issue then. Thanks for the help! :)
