### ISSUE TITLE
SauceLabs microsoftedge 12 is not available

### ISSUE THREAD

**Issue by JakeChampion** [polyfillpolyfill/polyfill-service#934]
We are seeing this is all CI builds at the moment. It looks like SauceLabs has removed this environment for the time being.

```
Error: [init({"name":"grunt-test:Thu, 13 Oct 2016 12:59:18 GMT","record-video":true,"record-screenshots":true,"tunnel-identifier":"SauceTunnel:Thu, 13 Oct 2016 12:59:18 GMT","browserName":"microsoftedge","version":"20.10240","platform":"Windows 10"})] The environment you requested was unavailable.
```

**Comment by triblondon** [comment]
ah, they do that. It's annoying, I don't know why they remove browsers, especially IE/Edge variants

https://saucelabs.com/platforms#windows8-10

We will need to remove that browser, and add the new Edge version.

**Comment by JakeChampion** [comment]
@triblondon Is there a contact at SauceLabs we can speak to about this?

**Comment by triblondon** [comment]
I haven't been in touch with them for some time.  I'd suggest just going through the support ticket system.
