### ISSUE TITLE
Always serve URL to Edge

### ISSUE THREAD

**Issue by fredj** [polyfillpolyfill/polyfill-service#941]
From e54f901 Microsoft Edge no longer receives URL but the [searchParams property](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) is not implemented in this browser.

Would it be possible to revert e54f901?

Tested with (in the debugger console):

```
> u = new URL('https://github.com/Financial-Times/polyfill-service?foo=bar');
url.searchParams === undefined
```

**Comment by JakeChampion** [comment]
@fredj PR for this - #946

**Comment by fredj** [comment]
thanks !
