### ISSUE TITLE
Support for Function.name

### ISSUE THREAD

**Issue by Regaddi** [polyfillpolyfill/polyfill-service#943]
Haven't seen this on the feature list and no issue or pull-request either.

I'd like to see [Function.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) supported by Polyfill.io.

**Comment by triblondon** [comment]
No problem, go for it!  Here's a guide:

https://polyfill.io/v2/docs/contributing/common-scenarios#new-polyfill

**Comment by falsandtru** [comment]
Which level polyfill will we provide? We cannot provide compatibility with es6 in some case.

``` js
var f = function () {};
console.log(f.name); // "f"
```

**Comment by JamesMGreene** [comment]
@falsandtru: Right, the only reasonable level of support would be the very minimal subset of ES6's `Function.name` spec that covers named function definitions (both named function declarations and named function expressions). All other scenarios are either impossible or highly impractical to support.

**Comment by JamesMGreene** [comment]
I can submit my polyfill for this soon, hopefully tonight.

**Comment by falsandtru** [comment]
I see, now I think developers should accept this difference because some legacy browsers possibly have an incomplete partial implementation. So we can provide the partial implementation like those legacy browsers.

**Comment by JamesMGreene** [comment]
PR submitted: #951
