### ISSUE TITLE
Support for HTML5 `document.currentScript`

### ISSUE THREAD

**Issue by JamesMGreene** [polyfillpolyfill/polyfill-service#952]
Can add guaranteed support for HTML's [`document.currentScript`](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) in IE `8-10` (but _**NOT**_ IE 11 😭) by using the techniques from [JamesMGreene/document.currentScript](https://github.com/JamesMGreene/document.currentScript).

If it weren't for the lack of defining getters _**on DOM interfaces**_ in IE `<8`, this can actually be supported all the way down to IE `6`.

I can submit a PR for this soon-ish.

**Comment by JamesMGreene** [comment]
> If it weren't for the lack of define getters in IE <9, this can actually be supported all the way down to IE 6.

Although, now that I've said that, I am struggling to remember why this didn't work in IE 8 since we are adding the accessor to a DOM object (`Document`/`HTMLDocument`)... I will investigate that before submitting: JamesMGreene/document.currentScript#17

**Comment by JamesMGreene** [comment]
@triblondon et al:
`Object.defineProperty` exists but only works on DOM interfaces (not other JS objects).  However, for the PR related to this issue, I can still support IE8 by utilizing `Object.defineProperty` as I will be adding a getter to a DOM interface.

How would I handle declaring my dependencies on `Object.defineProperty` for this feature, given that I also want to enable its use In IE8?

**Comment by JakeChampion** [comment]
@JamesMGreene Here is an example of adding another polyfill as a dependency -- https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Element/prototype/placeholder/config.json#L10

**Comment by JamesMGreene** [comment]
@JakeChampion: Thanks, I understand that bit already (just recently made use of the same thing in my PR #951). However, my question is a bit more complex than that.

The difference here is that the version of `Object.defineProperty` that I need/want to utilize (only needs to work for DOM interfaces) is available in IE8, whereas the full-featured version of `Object.defineProperty` did not hit the scene until IE9.

If you look at [`polyfills/Object/defineProperty/detect.js`](https://github.com/Financial-Times/polyfill-service/blob/251f807e840725712b4ca8ba8eb1aab2de2d9086/polyfills/Object/defineProperty/detect.js), for example, you will see that the feature test is done specifically on a plain JS object (which is the right thing to do). However, that also means that, if I mark "Object.defineProperty" as a dependency, Polyfill will always include the [`polyfills/Object/defineProperty/polyfill.js`](https://github.com/Financial-Times/polyfill-service/blob/251f807e840725712b4ca8ba8eb1aab2de2d9086/polyfills/Object/defineProperty/polyfill.js) file for IE8 despite the fact that it isn't actually needed to support this.  The polyfill will work fine due to [`polyfills/Object/defineProperty/polyfill.js#L9-L12`](https://github.com/Financial-Times/polyfill-service/blob/251f807e840725712b4ca8ba8eb1aab2de2d9086/polyfills/Object/defineProperty/polyfill.js#L9-L12), so that isn't a concern so much as potentially wasting download/execution time with it unnecessarily.

The issue is also exacerbated for this particular polyfill as it can **ONLY** be correctly polyfilled for IE8-10 ([and _**not**_ IE11](https://github.com/JamesMGreene/document.currentScript#public-service-announcement-psa)  😭), so the polyfill's browser inclusion pattern will have already limited it to those IE versions which have the means available already.

Can polyfills be forcibly included even if they don't match the compatible browser versions?
- If so, it is probably best to still mark the `Object.defineProperty` polyfill as a dependency to ensure that appropriate pre-conditions are being verified and suffer the unnecessary hit for IE8.
- If not, then we'd achieve the best performance by omitting the `Object.defineProperty` dependency indication and just adding descriptive comments instead.

**Comment by JamesMGreene** [comment]
@JakeChampion @triblondon: Any further clarification on what you'd recommend here?

**Comment by triblondon** [comment]
Hi James. Sorry for the delay on this. It's a tricky one: it is indeed possible to force-include a polyfill in all browsers (and many people do this) using the `always` flag. This is not normally recommended but it makes sense in some cases.

So in this case you want to ship a polyfill that depends on defineProperty, but only works in browsers that already have it. if there are any cases where including defineProperty would actually offer any value (e.g. In cases where your polyfill is being force loaded in inappropriate browsers) then I'd agree that on the safe side you should list it as a dependency. However if it makes no difference (your polyfill still fails, and no more or less gracefully) then there'a no benefit to drawing the relationship between the two.

**Comment by JamesMGreene** [comment]
Thanks for fielding that one, Andrew.  I'll proceed to create a corresponding PR when I find the time.
