### ISSUE TITLE
onhashchange detection evaluates to false in browsers that supports it.

### ISSUE THREAD

**Issue by wessberg** [polyfillpolyfill/polyfill-service#953]
Let's continue the dialog from https://github.com/Financial-Times/polyfill-service/commit/a79ea032d03ef0d22b0da5fbeb94cdf40aa34f88 in this issue as suggested.

`window.onhashchange` will always be strictly equal to null in most browsers unless it is explicitely set. 

May I suggest the following instead:
`'onhashchange' in this && this.docmode == null || this.docmode > 7;` like seen in this gist: https://gist.github.com/Integralist/1599740.

@falsandtru suggested `'onhashchange' in this && (this.onhashchange == null || typeof this.onhashchange === 'function')` which is probably fine too, but I haven't tested IE8 in IE7 compatiblity mode.

**Comment by JakeChampion** [comment]
PR for this -- https://github.com/Financial-Times/polyfill-service/pull/947

**Comment by JakeChampion** [comment]
This is live now, please open a new issue if the problem still occurs
