### ISSUE TITLE
Polyfills for ParentNode properties

### ISSUE THREAD

**Issue by tuespetre** [polyfillpolyfill/polyfill-service#957]
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode

In particular, these are the properties:
- `children`
- `childElementCount`
- `firstElementChild`
- `lastElementChild`

What I wonder is how (or even if) these should be split up? 

We can't test for `ParentNode` because it's an abstract interface not present to the UA. It wouldn't make sense (IMO) to serve out a polyfill for, say `Document` but not `DocumentFragment` or vice versa. IE6 through IE8 have a quirk in their implementation for `Element` that includes Comment nodes in the results, adding complexity to the feature detection test. Virtually all browsers otherwise support the properties on `Element` already, so maybe just polyfill `Document` and `DocumentFragment`? If that were the case a simple test for `'children' in Document.prototype && 'children' in DocumentFragment.prototype` may suffice.

**Comment by tuespetre** [comment]
Update... as I have been working on https://github.com/tuespetre/shadow-dom, I found some additional weirdness around these APIs in Internet Explorer -- they are implemented on `HTMLElement` rather than `Element`, so even when you polyfill `Element` you have to `delete` the originals from `HTMLElement`.

**Comment by JakeChampion** [comment]
We would be very happy to accept a PR which adds these polyfills @tuespetre :-)

**Comment by triblondon** [comment]
More info: https://polyfill.io/v2/docs/contributing/common-scenarios#new-polyfill

**Comment by triblondon** [comment]
Hi, thanks for raising this.  We love to see people wanting to extend the polyfill service to accommodate new features.  We don't keep feature request issues open without a PR, but we do provide feedback on how enthusiastic we are to adopt the suggested idea.  In this case, the feature you've suggested is very appealing to the core team, and we would be happy to receive a PR for it, and help you with reviews and testing, or with how to get started if you are a new contributor.

You can find out more about common contribution scenarios and how to make the perfect PR here:
https://polyfill.io/v2/docs/contributing/common-scenarios

If you need any further help before you submit your PR, feel free to reopen this issue!
