### ISSUE TITLE
Symbol polyfill breaking native implementation

### ISSUE THREAD

**Issue by jacobgunnarsson** [polyfillpolyfill/polyfill-service#959]
Recently I was trying to replace core-js as my ES6 polyfill in an Angular 2 project with polyfill.io using the `es6` set. It was working fine and dandy up until I tried the project in the iOS Simulator running iOS 9 and encountered the following error:

```
Error: Error in ./NavigationMenuComponent class NavigationMenuComponent - inline template:27:49 caused by: a[getSymbolIterator()] is not a function. (In 'a[getSymbolIterator()]()', 'a[getSymbolIterator()]' is undefined)
```

It seems like the Symbol polyfill is resolved as a dependency for several other unsupported ES6 features in Safari 9 and therefore overwriting the native implementation and somehow breaking it. I reproduced the issue in a Plunkr here: https://plnkr.co/edit/6D7YcSJPmHhFlemBOPoc, and it can just as well be reproduced in an actual device running iOS 9, without using the forced `ua` param.

Am I misunderstanding something?

Love the service otherwise! Thanks!

**Comment by JakeChampion** [comment]
We need to update out Symbol configuration for ios_saf to not include ios_saf 9 or higher -- https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Symbol/config.json#L11

**Comment by JakeChampion** [comment]
Didn't mean to close that, apologies.

**Comment by jacobgunnarsson** [comment]
No problems! That makes sense as to why it was included in the first place.

Do you know the reason why the native implementation is overwritten at all? And why the polyfill seems to break the array iterator?

If included I would expect it to not overwrite the native implementation, and even if it did, that it would work as before it was overwritten.

**Comment by JakeChampion** [comment]
it is overridden because the polyfill is requested without being wrapped in a feature detect. You can wrap it in a feature detect by adding `|gated` to the feature. 

```
https://cdn.polyfill.io/v2/polyfill.js?features=es6|gated
```

I'm not sure why it doesn't work in ios 9, that is something we could investigate however, as ios 9 supports it natively this would not be a high priority. The higher priority is changing our config to not serve this polyfill to ios 9 browsers.

**Comment by jacobgunnarsson** [comment]
Ah, that's great, thanks!

Def. agree on the priorities. Just a heads up though; I can replicate the breaking in Chrome 53, Safari 10 and Firefox 49.0.2, so it is probably a more general problem than just Safari iOS 9.

**Comment by JakeChampion** [comment]
Thanks, we will fix all of these in the next release :-) The reason we have not spotted these issues is because our CI does yet run those browsers, it will once #954 is merged.

**Comment by triblondon** [comment]
@JakeChampion can we close this one?

**Comment by JakeChampion** [comment]
Yep :-)
