### ISSUE TITLE
Incorect feature-detect (`gated` flag) for multiple identical features with different sub-features

### ISSUE THREAD

**Issue by merkuriy** [polyfillpolyfill/polyfill-service#960]
Identical feature-detect (when using the `gated` flag) blocks wraped repeatedly for sub-features after block parent feature . It is necessary to combine it into a single feature-detect block for identical features with different sub-features.

Example URL: https://cdn.polyfill.io/v2/polyfill.js?flags=always,gated&features=Intl.~locale.en,Intl.~locale.en-GB,Intl.~locale.ru-RU,Intl.~locale.ru

Feature-detect `if (!('Intl' in this)) { … }` multiple wraped for `Intl`, `locale.en`, `locale.en-GB`, `locale.ru-RU` and `locale.ru`.

![Example image](http://i.imgur.com/OMth6IF.png)

**Comment by jacobgunnarsson** [comment]
Just stumbled upon this myself, this prevents all subsequent Intl locale polyfills to load, effectively making `flags=gated` unusable. Using `|gated` individually for each feature except for `Intl` works in the meantine.

**Comment by triblondon** [comment]
Thanks for this.  I think our options here are, in order of preference:
1. (best) find a way of detecting that a locale is available, and use that instead of the current detect.js for locale directories
2. Remove the detect files from the locales, so they are not subject to feature detection

**Comment by triblondon** [comment]
This is the update task for Intl, by the way, where the change would be needed:
https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Intl/update.task.js

**Comment by JakeChampion** [comment]
PR for this -- https://github.com/Financial-Times/polyfill-service/pull/1027
