### ISSUE TITLE
Request: Smooth scroll polyfill

### ISSUE THREAD

**Issue by arvigeus** [polyfillpolyfill/polyfill-service#963]
Chrome and some other browsers are having issues with window.scroll, window.scrollToView, etc... Can you include a polyfill for this? Example: https://www.npmjs.com/package/smoothscroll-polyfill

Thank you!

**Comment by triblondon** [comment]
If the behaviour is a web standard, sure!

https://polyfill.io/v2/docs/contributing/common-scenarios#new-polyfill

**Comment by triblondon** [comment]
Hi, thanks for raising this. We love to see people wanting to extend the polyfill service to accommodate new features. We don't keep feature request issues open without a PR, but we do provide feedback on how enthusiastic we are to adopt the suggested idea. In this case, the feature you've suggested is moderately appealing to the core team, and we would be happy to receive a PR for it, and help you with reviews and testing, or with how to get started if you are a new contributor.  We would need to ensure that the polyfill is filling for a standard feature of the web platform, which we're not sure is the case here.

You can find out more about common contribution scenarios and how to make the perfect PR here:
https://polyfill.io/v2/docs/contributing/common-scenarios

If you need any further help before you submit your PR, feel free to reopen this issue!

**Comment by zgreen** [comment]
I'm happy to submit a PR for this, if one is not currently in progress.

**Comment by JakeChampion** [comment]
Hi @zgreen, feel free to submit a PR for this, one is not in progress :-)
