### ISSUE TITLE
notes toggles (the (i) icons) in the feature list in docs don't toggle in Firefox

### ISSUE THREAD

**Issue by dbaron** [polyfillpolyfill/polyfill-service#966]
In https://polyfill.io/v2/docs/features/ there are a few features listed that have an (i) icon next to them.  In Chrome, clicking on the (i) toggles the display of the information, but this doesn't work in Firefox.

The code that's supposed to make this work is [in docs/assets/ui.js](https://github.com/Financial-Times/polyfill-service/blob/65c7eed9551ae44cd03e66936c30c8d309452451/docs/assets/js/ui.js#L187).

From some brief debugging, I suspect the problem in Firefox might be one of either:
- the elements matching '.notes-toggle' don't yet exist at the time of DOMContentLoaded (which doesn't seem incredibly surprising to me given that they're dynamically generated), or
- the script that adds the DOMContentLoaded event listener gets executed after DOMContentLoaded (which also seems possible, since the script appears to be loaded by a script loader).

I make this claim because, if I manually run the contents of the DOMContentLoaded handler in Firefox by entering the code in the console, then the toggles start working.

This code was added in 625d4cce59d09b83c77b22045ff18162540e5f41.

**Comment by triblondon** [comment]
Ugh, that UI code is dreadful, sorry about that. I'll fix

**Comment by triblondon** [comment]
Hmm.  I can't see anything to suggest that the notes elements are not present on page load. We do render them on the server.  But you're probably spot on with the second observation.
