### ISSUE TITLE
Functionalize console methods

### ISSUE THREAD

**Issue by falsandtru** [polyfillpolyfill/polyfill-service#967]
Some legacy browsers throw an error at the following code because of missing context. We can add interop for that code.

``` js
(0, console.log)();
```

**Comment by JakeChampion** [comment]
I can't remember when the change was made to `console` methods to make them autobound.

I tried to find a spec which mentioned it but failed to. Do you have a link to a spec for this? The reason I ask is because I'm not sure if all `console` methods are now autobound to `console` or if it was a subset of them.

**Comment by falsandtru** [comment]
Sorry, I also can't remember it. I'll try to find a spec later.

**Comment by falsandtru** [comment]
Found: https://github.com/whatwg/console/issues/3

Now `console` is a namespace, has not an interface.

**Comment by triblondon** [comment]
I don't have good enough knowledge of the language semantics to recognise what's going on here - @JakeChampion can you explain it?

**Comment by JakeChampion** [comment]
Yes, if you wanted to use a console method as a separate function you needed to bind it to the console object like so - `console.log.bind(console)`, console methods are now autobound meaning you can use a console method as a separate function like so - `console.log`.

To implement this change isn't a lot of work I believe, would mean adding `Function.prototype.bind` as a dep to every `console` polyfill and binding the methods to the console object.

**Comment by JakeChampion** [comment]
Our console polyfills are not tied to the console object, they do not need to be bound to be called directly.
