### ISSUE TITLE
Fetch polyfill not served to Safari 9.1 and 9 mobile

### ISSUE THREAD

**Issue by qwelias** [polyfillpolyfill/polyfill-service#974]

**Comment by triblondon** [comment]
@qwemaze https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

**Comment by fatso83** [comment]
Add Safari 10 to that list.

@triblondon, the weird thing is that the test page says it should be polyfilled, but it is not!

``` shell
 curl 'https://cdn.polyfill.io/v2/polyfill.js' -XGET -H 'Referer: http://meny.local/Testsider/fleksibel-kampanjeside/' -H 'Accept: */*' -H 'Cache-Control: max-age=0' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14'  | grep fetch
```

Returns nothing.

As the test shows, it should have been served. 
![fetch safari](https://www.dropbox.com/s/8vrcnz51qpvlzs6/fetch.safari.polyfill.png?dl=1)

**Comment by JakeChampion** [comment]
Safari 10 is there --
https://cdn.polyfill.io/v2/polyfill.js?features=fetch&ua=safari/10 --
https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/fetch/config.json

**Comment by fatso83** [comment]
@JakeChampion : thank you for that. I obviously missed the distinction between the set of _default_ features and the other features (which fetch is part of) that you need to specify separately.

You are indeed right in that fetch is being served for all Safari versions. 
https://cdn.polyfill.io/v2/polyfill.js?features=fetch&ua=safari/8 works as well.

@qwemaze : you should close this issue; it's working fine.

**Comment by JakeChampion** [comment]
Apologies if my previous reply seemed abrupt, I was using my mobile phone to reply.

I will close this issue, thanks for taking the time to confirm it is all working.

I also think we should add `fetch` to the default set as it seems many people are expecting it to be there.

**Comment by qwelias** [comment]
@JakeChampion oh, so there's a distinction on *default* and *selected* features, my bad. Thought it just upgrades everything.
