### ISSUE TITLE
Question: how to include all locale in Intl polyfill?

### ISSUE THREAD

**Issue by chiefjester** [polyfillpolyfill/polyfill-service#978]
Hi,
What's the correct flag to use if I want to include all locales?

something like this?
https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.all|always

**Comment by JakeChampion** [comment]
There is no flag for this unfortunately, if you only want Intl polyfills you will need to place them all in manually.

**Comment by triblondon** [comment]
@thisguychris also bear in mind that even if you did that, you would get a polyfill bundle in the 10s of megabytes.  Since there's basically no situation in which that's a good idea, we don't enable that use.

**Comment by chiefjester** [comment]
@triblondon not really, I tried the bower package, which basically just mirrors what they have in github, its 214kb gzipped.

http://take.ms/LOfa3

You can check it for your self, I added this:

``` html
<script src="bower_components/intl/dist/Intl.min.js"></script>
<script src="bower_components/intl/locale-data/complete.js"></script>
```
