### ISSUE TITLE
Issue with certificate

### ISSUE THREAD

**Issue by enyo** [polyfillpolyfill/polyfill-service#979]
When I got to polyfill.io I get:

"Your connection is not private"

![screen shot 2016-11-04 at 17 45 46](https://cloud.githubusercontent.com/assets/133277/20014257/9056e8da-a2b6-11e6-898e-284628d71ab7.png)

**Comment by JakeChampion** [comment]
I can not replicate the issue on any devices. Can you click the red triangle in the address bar and paste a screenshot into this issue please?

**Comment by JakeChampion** [comment]
@enyo Are you still seeing this issue?

**Comment by enyo** [comment]
Hey yes, and strangely only at work, so it is probably related to my IP?

![image](https://cloud.githubusercontent.com/assets/133277/20059669/bb8f5c9c-a4f7-11e6-93da-661fe5cdf3c4.png)

![image](https://cloud.githubusercontent.com/assets/133277/20059674/c18231ce-a4f7-11e6-9464-b3ba20bac7ca.png)

When I click on "View certificate" I get a huge white popup 

![image](https://cloud.githubusercontent.com/assets/133277/20059726/f3aa3a16-a4f7-11e6-8120-e77a9c2b7495.png)

**Comment by JakeChampion** [comment]
@enyo Do you use the same machine at work and out of work? If not, it could be that your work machine has a bad cache of either our certificate or the certificate revocation list. Would you be able to empty the cache on the machine?

**Comment by enyo** [comment]
Hey, the problem disappeared today (I guess the cache got invalidated by itself).
Thank you for your support!
