### ISSUE TITLE
Number.parseInt/parseFloat not supported in older browsers.

### ISSUE THREAD

**Issue by ttsvetko** [polyfillpolyfill/polyfill-service#980]
Number.parseInt/parseFloat have the same functionality as the global parseInt/parseFloat and are part of ECMAScript 2015. Number.parseInt/float are not supported in IE and Safari based on the info from MDN:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseFloat

Would be great if the polyfill have something like:
if (!Number.parseInt) {
Number.parseInt = window.parseInt
}

Same for parseFloat:
if (!Number.parseFloat) {
Number.parseFloat = window.parseFloat;
}

**Comment by triblondon** [comment]
Sounds easy, let's do it! Can you do a PR?

https://polyfill.io/v2/docs/contributing/common-scenarios#new-polyfill
