### ISSUE TITLE
IE 11 - cdn -  Array.prototype.findIndex missing in minified js

### ISSUE THREAD

**Issue by detrash08** [polyfillpolyfill/polyfill-service#982]
I need to polyfill  Array.prototype.findIndex in IE11 but when ask for in the minified version the function is not included. 
example:
https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.find,Array.prototype.findIndex&excludes=Object.assign,Promise&flags=gated&unknown=polyfill&callback=init

The same url without ".min" extension works great
https://cdn.polyfill.io/v2/polyfill.js?features=default,Array.prototype.find,Array.prototype.findIndex&excludes=Object.assign,Promise&flags=gated&unknown=polyfill&callback=init

am I missing something?

**Comment by JakeChampion** [comment]
I see it in the first url when I add `ua=ie/11` to mimic ie11 for the polyfill-service.

Here is a polyfill.io requests for only findIndex to help show it is being served to ie11 in minified form -- https://cdn.polyfill.io/v2/polyfill.min.js?features=Array.prototype.findIndex&flags=gated&unknown=polyfill&callback=init&ua=ie/11

**Comment by detrash08** [comment]
I've tried my first url on Chrome adding "&ua=ie/11" and seems to work. 
On IE instead seems that passing both "Array.prototype.find" and  "Array.prototype.findIndex" to "features" parameter generates the issue.

@JakeChampion try this on IE11
https://cdn.polyfill.io/v2/polyfill.min.js?features=Array.prototype.find,Array.prototype.findIndex&flags=gated&unknown=polyfill&callback=init&ua=ie/11

**Comment by triblondon** [comment]
I also can't reproduce. That last URL does include the findIndex polyfill... can you attach the full output that you're getting?

**Comment by detrash08** [comment]
this is the minified response that I get from the url in my previous post.
http://pastebin.com/m9WuesUY

the following paste contains the response calling the same url without ".min"
http://pastebin.com/kvspfW7N

Both calls performed on IE11

**Comment by triblondon** [comment]
Looks like you're getting a truncated response.  That first one is not complete.  Maybe take a look at the response headers?  I'd be looking for the declared content length, gzip, and which CDN node served it.  Try clearing any local caches too.

**Comment by detrash08** [comment]
I've tried to clean local cache and seems to work. Do you have changed something? Perhaps IE11 is getting older.
