### ISSUE TITLE
Facebook in-app browser (on both iOS and Android) not working

### ISSUE THREAD

**Issue by andyburke** [polyfillpolyfill/polyfill-service#990]
We are seeing issues with the polyfill not appropriately filling inside the Facebook in-app browser.

This seems like it may be a regression on #561

Reproduction:

https://m.facebook.com/story.php?story_fbid=10154490930306508&id=739196507

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>FB Browser Window setImmediate repro</title>

    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,setImmediate"></script>
</head>

<body>
    <script type="text/javascript">
        setImmediate( function() {
            alert( 'setImmediate worked' );
        } );
    </script>
<body>
```

**Comment by jacklee0223** [comment]
Same thing happens to Object.assign

**Comment by JakeChampion** [comment]
@andyburke @jacklee0223 do you happen to know of a way to do automated testing against facebook's in-app browser? When we fix this I want to ensure we are unlikely to regress again in the future.

**Comment by andyburke** [comment]
@JakeChampion I'm not aware of a way, other than theoretically faking their UA?

Is there any progress on this? Do you have any idea what could be causing it? We're willing to contribute, but would probably need at least a little guidance on how to proceed.

**Comment by triblondon** [comment]
@andyburke I suggest you first find out how we are classifying that browser by sending the browser directly to the polyfill URL (without `.min`), or if FB refuses to directly load and display a script file, by downloading the polyfill.io resource using `fetch` and adding the raw source to the document body, eg something like:

```
<script>
fetch("https://polyfill.io/v2/polyfill.js")
  .then(resp => resp.text())
  .then(text => document.body.innerText = text)
;
</script>
```

It seems likely that we are not recognising the browser, which might be a change we've made to our UA module, but more likely either a change in the useragent module we depend on, or in the actual string Facebook uses as their UA header.

**Comment by andyburke** [comment]
@triblondon I've updated the test url: https://hellofloat.com/fb_browser_polyfill_test/

It results in this (tested on an Android device in FB app):

![screenshot_2017-01-12-20-21-23](https://cloud.githubusercontent.com/assets/273857/21918322/06eac500-d905-11e6-9ffa-d372415eee88.png)

**Comment by triblondon** [comment]
OK, I think the solution to this is to remove the Facebook-added `[FB_IAB/FB4A;FBAV/35.0.0.48.273;]` token from the UA string before parsing.  This will then cause the UA to be recognised as Chrome on Android, and Safari on iOS.  I'd like to do this after https://github.com/Financial-Times/polyfill-service/pull/1050 is merged.

**Comment by TheUltDev** [comment]
For anyone that this is a critical issue for you can add `?flags=gated` (feature detection) to fix this.

It adds a bit of bloat but it's worth it.

More detailed and duplicate issue here: https://github.com/Financial-Times/polyfill-service/issues/799

EDIT: this is fixed and live on the CDN

**Comment by triblondon** [comment]
@Cavitt We haven't yet released a change to the CDN that I'm aware of.  #799 describes a slightly different issue with `defineProperty`.
