### ISSUE TITLE
Object.keys has es5 behavior. is there an es6 variant?

### ISSUE THREAD

**Issue by gnoff** [polyfillpolyfill/polyfill-service#991]
in es5 `Object.keys("boo")` throws
in es2015 it coerces the arg to an object in this case returns `["0", "1", "2"]`

the current polyfill only implements the es5 behavior. are there plans for hosting polyfills for variants of native behaviors that have changed in recent versions of Ecmascript?

**Comment by JakeChampion** [comment]
I've been thinking about this for the past year, it's something I've been meaning to post an issue about. The question I've had is "should the polyfill-service stick with the latest ecmascript 262 specification version or should it have a separate polyfill implementation for each version?". My current thinking is that we aim to always have our polyfills adhere to the latest specification as that is what browsers will eventually have.

With regards to `Object.keys`, we have an ES5 polyfill as you already know, if you [add a failing test to this file](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/keys/tests.js), I'm sure we can get it passing and configured for the correct browsers :-)

**Comment by gnoff** [comment]
PR here: #993 

there are some issues with the fact that while IE9+ support Object.keys, they do so in an es5 compliant way. The tests don't target these browsers because of this and I'm not sure how you might want to distribute a polyfill for browsers that support the older spec.

**Comment by JakeChampion** [comment]
This was added in https://github.com/Financial-Times/polyfill-service/pull/1033
