### ISSUE TITLE
Feature request: Add EventSource polyfill

### ISSUE THREAD

**Issue by CheloXL** [polyfillpolyfill/polyfill-service#996]
Either https://github.com/Yaffle/EventSource or https://github.com/amvtek/EventSource.
It's needed in old Androids and all IEs/Edge.

**Comment by triblondon** [comment]
That would be great.  Here's how to do that: https://polyfill.io/v2/docs/contributing/common-scenarios#new-polyfill

**Comment by triblondon** [comment]
Hi, thanks for raising this. We love to see people wanting to extend the polyfill service to accommodate new features. We don't keep feature request issues open without a PR, but we do provide feedback on how enthusiastic we are to adopt the suggested idea. In this case, the feature you've suggested is very appealing to the core team, and we would be happy to receive a PR for it, and help you with reviews and testing, or with how to get started if you are a new contributor.

You can find out more about common contribution scenarios and how to make the perfect PR here:
https://polyfill.io/v2/docs/contributing/common-scenarios

If you need any further help before you submit your PR, feel free to reopen this issue!
